### PR TITLE
i#3839: Do not block SIGSEGV and SIGBUS at exit time

### LINKED ISSUE #3839: Regression: safe read failing during client exit events
Dr. Memory's leak scan during the exit event is failing to handle safe_reads: it crashes instead, or on Mac64 it hangs.  This is a regression.

I tracked it down to edb2eed6b74646dcf92718675ad2ec9a3fe2b674: for #2921, PR #3364 blocks all signals, not just asynchronous ones, *before* running exit code.  This means that DR won't catch and report crashes, and more importantly clients can't use safe_read and other features in their exit events.

### PR DESCRIPTION
**Pull request by derekbruening**
Fixes a regression from edb2eed where all signals, including SIGSEGV and
SIGBUS, were blocked while running exit code.  This meant that DR wouldn't
catch and report crashes, and more importantly clients couldn't use safe_read
and other features in their exit events.  Now we avoid blocking those two
key signals.

Tested: Dr. Memory's safe_read uses during exit no longer crash or hang.

Fixes #3839

### CODE REVIEW

File: core/unix/signal.c [hunk 1]
```diff
@@ -359,6 +359,11 @@ block_all_signals_except(kernel_sigset_t *oset, int num_signals,
         kernel_sigdelset(&set, va_arg(ap, int));
     }
     va_end(ap);
+    /* We never block SIGSEGV or SIGBUS: we need them for various safe reads and to
+     * properly report crashes.
+     */
+    kernel_sigdelset(&set, SIGSEGV);
```
Comment (hgreving2304) [inline core/unix/signal.c]: Why did you not add the signals to the call of block_all_signals_except() and instead baked them into the function? Ok, if you had a good reason for it, otherwise I would add it to the except list of the function call, since that's what it was meant for.

Comment (derekbruening) [reply core/unix/signal.c]: I'm looking at this function as blocking all signals that can *safely* be blocked.  This way we avoid shooting ourselves in the foot the next time this function is used if we forget to add these two.  They should really *never* be blocked for us.  If you look at this function as doing whatever the caller says, then I agree the caller should add them: but I believe that every single caller should add these 2, so we'll have duplication with the risk of messing up somewhere where we forget.  Maybe rename the function?

Comment (derekbruening) [reply core/unix/signal.c]: I'm thinking s/block_all_signals_except/block_all_noncrash_signals_except/.

Comment (derekbruening) [reply core/unix/signal.c]: My interpretation is influenced by this being exported out of the signal module to all of unix/: that makes it seem like not a low-level utility for the signal module to manipulate signals irrespective of DR, but a DR-centric operation.

**Comment by derekbruening** [comment]
AArch64 failures are #3025 and #3406.
