### PR TITLE
i#7773: Raise error on invalid inputs on drmemtrace replay

### LINKED ISSUE #7773: drmemtrace replay with wrong input order can hang instead of raising error
When replaying a recorded drmemtrace schedule, the inputs need to be
in the same order as when recorded. If they're not, it's possible to
hang when an input hits EOF but the record file says it has more
data. I hit such a hang and was very confused. It would be nice to have
an explicit error.

### PR DESCRIPTION
**Pull request by derekbruening**
When replaying a recorded drmemtrace schedule, the inputs need to be in the same order as when recorded. If they're not, it's possible to hang when an input hits EOF but the record file says it has more data. This is turned into an explicit error to avoid that hang.

Adds a unit test that hangs without the fix and passes with the fix.

Also fixes a schedule_stats assert when run on a replayed file, where it did not expect a wait record, hit while debugging this issue.

Fixes #7773

### CODE REVIEW

File: clients/drcachesim/scheduler/scheduler_replay.cpp [hunk 1]
```diff
@@ -367,6 +367,15 @@ scheduler_replay_tmpl_t<RecordType, ReaderType>::pick_next_input_for_mode(
              (outputs_[output].record[record_index].type != schedule_record_t::SKIP &&
               // Don't wait if we're at the end and just need the end record.
               segment.type != schedule_record_t::SYNTHETIC_END))) {
+            // If the input is at eof it's an error: maybe the inputs are not identical
```
Comment (abhinav92003) [inline clients/drcachesim/scheduler/scheduler_replay.cpp:370]: > If they're not, it's possible to hang when an input hits EOF but the record file says it has more data

But the issue is bigger than just a hang right? It would be an incorrect replay.

Comment (abhinav92003) [inline clients/drcachesim/scheduler/scheduler_replay.cpp:370]: Would be nicer to somehow include something about the input order in the record file.

Comment (derekbruening) [reply clients/drcachesim/scheduler/scheduler_replay.cpp:370]: Right, but our documented design decision is that it's up the user to preserve the inputs as it's hard to detect that they are the same.

Added:

                          (our documented design requires that the
            // user pass in the same inputs; but we'd rather not hang).

Comment (derekbruening) [reply clients/drcachesim/scheduler/scheduler_replay.cpp:370]: Our documented design decision is that it's up the user to preserve the inputs as it's hard to detect that they are the same. I think we were worried about contents changing, which is very hard to detect; plus, for interfaces taking in a reader pointer and not a file, it is even harder to detect.

Maybe recording the tid value would be a compromise. Added a XXX comment:

            // XXX: Though it's hard to detect that inputs are precisely the same,
            // maybe recording and checking the tid is a good compromise sanity check?
