### PR TITLE
i#3926: Do not clone label callbacks.

### LINKED ISSUE #3926: Crash, may or may not be expansion sequence related
I can deterministically reproduce a crash by expanding scatter/gather in a loop many times (only a few times does not reproduce a crash).

```
diff --git a/suite/tests/client-interface/drx-scattergather.c b/suite/tests/client-interface/drx-scattergather.c
index 4c62be56..d4fcb04d 100644
--- a/suite/tests/client-interface/drx-scattergather.c
+++ b/suite/tests/client-interface/drx-scattergather.c
@@ -173,18 +173,20 @@ test_avx512_gather(void (*test_func)(uint32_t *, uint32_t *, uint32_t *),
                    uint32_t *ref_sparse_test_buf, uint32_t *ref_xmm_ymm_zmm,
                    uint32_t *test_idx_vec, uint32_t *output_xmm_ymm_zmm OUT)
 {
-    memset(output_xmm_ymm_zmm, 0, CONCAT_XMM_YMM_ZMM_U32 * sizeof(uint32_t));
-    test_func(ref_sparse_test_buf, test_idx_vec, output_xmm_ymm_zmm);
-    if (memcmp(output_xmm_ymm_zmm, ref_xmm_ymm_zmm,
-               CONCAT_XMM_YMM_ZMM_U32 * sizeof(uint32_t)) != 0) {
-        print("ERROR: gather result does not match\n");
-        return false;
-    }
-    if (!test_avx512_mask_all_zero()) {
-        print("ERROR: mask is not zero\n");
-        return false;
+    for (int i = 0; i < 50; ++i) {
+        memset(output_xmm_ymm_zmm, 0, CONCAT_XMM_YMM_ZMM_U32 * sizeof(uint32_t));
+        test_func(ref_sparse_test_buf, test_idx_vec, output_xmm_ymm_zmm);
+        if (memcmp(output_xmm_ymm_zmm, ref_xmm_ymm_zmm,
+                   CONCAT_XMM_YMM_ZMM_U32 * sizeof(uint32_t)) != 0) {
+            print("ERROR: gather result does not match\n");
+            return false;
+        }
+        if (!test_avx512_mask_all_zero()) {
+            print("ERROR: mask is not zero\n");
+            return false;
+        }
+        print("AVX-512 gather ok\n");
     }
-    print("AVX-512 gather ok\n");
     return true;
 }
```

Leads to a SIGSEGV of the test under DynamoRIO

```
build/bin64/drrun -debug -code_api -c build/suite/tests/bin/libclient.drx-scattergather.dll.so -- build/suite/tests/bin/client.drx-scattergather
```

```
(gdb) bt
#0  0x00007fb39f379952 in common_heap_free (tu=0x7fb2db233958, p_void=0xcdcdcdcdcdcdcdcd, size=3280, which=ACCT_IR) at /usr/local/google/home/hgreving/dynamorio/src/core/heap.c:4455                                                                                                    
#1  0x00007fb39f37a7db in heap_free (dcontext=0x7fb2db232d80, p=0xcdcdcdcdcdcdcdcd, size=3280, which=ACCT_IR) at /usr/local/google/home/hgreving/dynamorio/src/core/heap.c:4588                                                                                                          
#2  0x00007fb39f4246a0 in instr_free (dcontext=0x7fb2db232d80, instr=0x7fb2db2849a0) at /usr/local/google/home/hgreving/dynamorio/src/core/arch/instr_shared.c:185                                                                                                                       
#3  0x00007fb39f4243b2 in instr_destroy (dcontext=0x7fb2db232d80, instr=0x7fb2db2849a0) at /usr/local/google/home/hgreving/dynamorio/src/core/arch/instr_shared.c:103                                                                                                                    
#4  0x00007fb35b26b4d3 in free_einstr (drcontext=0x7fb2db232d80, label=0x7fb2db287e40) at /usr/local/google/home/hgreving/dynamorio/src/ext/drmgr/drmgr.c:2701                                                                                                                           
#5  0x00007fb39f424647 in instr_free (dcontext=0x7fb2db232d80, instr=0x7fb2db287e40) at /usr/local/google/home/hgreving/dynamorio/src/core/arch/instr_shared.c:171                                                                                                                       
#6  0x00007fb39f4243b2 in instr_destroy (dcontext=0x7fb2db232d80, instr=0x7fb2db287e40) at /usr/local/google/home/hgreving/dynamorio/src/core/arch/instr_shared.c:103                                                                                                                    
#7  0x00007fb39f434702 in instrlist_clear (dcontext=0x7fb2db232d80, ilist=0x7fb2db285e28) at /usr/local/google/home/hgreving/dynamorio/src/core/arch/instrlist.c:101                                                                                                                     
#8  0x00007fb39f3843e8 in end_and_emit_trace (dcontext=0x7fb2db232d80, cur_f=0x7fb2db3053d0) at /usr/local/google/home/hgreving/dynamorio/src/core/monitor.c:1590                                                                                                                        
#9  0x00007fb39f38665a in monitor_cache_enter (dcontext=0x7fb2db232d80, f=0x7fb2db3053d0) at /usr/local/google/home/hgreving/dynamorio/src/core/monitor.c:2093                                                                                                                           
#10 0x00007fb39f2c2117 in d_r_dispatch (dcontext=0x7fb2db232d80) at /usr/local/google/home/hgreving/dynamorio/src/core/dispatch.c:197
#11 0x00007fb35b20617f in ?? ()
#12 0x0000000000000000 in ?? ()
```

The crash is also noticeably absent with -disable_traces

### PR DESCRIPTION
**Pull request by hgreving2304**
Label callbacks are called every time an instruction is destroyed if the instruction is
a label instruction and the field is valid. When cloning an instruction, we can't blindly
copy the label callback field causing it to be called when the cloned instruction is
destroyed. We are adding a note to the docs of instr_clone() and prevent the field from
being copied.

Fixes #3926
Issue: #3962

### CODE REVIEW

File: core/arch/instr.h [hunk 1]
```diff
@@ -886,7 +886,8 @@ DR_API
 /**
  * Returns a copy of \p orig with separately allocated memory for
  * operands and raw bytes if they were present in \p orig.
- * Only a shallow copy of the \p note field is made.
+ * Only a shallow copy of the \p note field is made. The \p label_cb
+ * field will not be copied at all if \p orig is a label instruction.
  */
 instr_t *
```
Comment (derekbruening) [inline core/arch/instr.h]: instr_set_label_callback needs documentation about this, to parallel the cloning note in instr_get_label_data_area

File: core/arch/instr_shared.c [hunk 2]
```diff
@@ -126,6 +126,11 @@ instr_clone(dcontext_t *dcontext, instr_t *orig)
         instr->bytes =
             (byte *)heap_reachable_alloc(dcontext, instr->length HEAPACCT(ACCT_IR));
         memcpy((void *)instr->bytes, (void *)orig->bytes, instr->length);
+    } else if (instr_is_label(orig)) {
+        /* We don't know what this callback does, we can't copy this. The caller that
+         * makes the clone needs to take care of this, xref i#3926.
```
Comment (derekbruening) [inline core/arch/instr_shared.c]: There seem to be deeper issues: drmgr_is_emulation_start will still return true for a cloned instrlist, and if the original is freed, then drmgr_get_emulated_instr_data on the clone will point to freed memory.  Is there something we can do to prevent use-after-frees.  Adding on-clone callbacks (starting to get overkill?  would want C++ or sthg at that point); zeroing label data instead of shallow-copying it and thus committing to clones being second-class copies?

nit: More comma issues.

Comment (hgreving2304) [reply core/arch/instr_shared.c]: This is kind of documented already by saying that instr_clone() only makes a shallow copy, I would say. So again the caller needs to consider this.

File: core/arch/instr.h (hunk 1 above)
Comment (hgreving2304) [reply core/arch/instr.h]: Done.

File: core/arch/instr_shared.c (hunk 2 above)
Comment (hgreving2304) [reply core/arch/instr_shared.c]: Sorry, missed the second part of the question. I would say usually a shallow copy _does_ make a shallow copy, w/o zeroing. The reason for the zeroing in this PR is that it causes an automatic callback on destroy. So I would consider this a special case.

Comment (derekbruening) [reply core/arch/instr_shared.c]: > The caller that makes the clone needs to take care of this

I'm afraid that this is not something the caller can do, is it?  The caller doesn't know what data might be stored in labels in the instrlist.

I'm also worried about DR's current uses: I don't remember the details, but trace building involves cloning an instrlist in some cases.  Does it later pass that to the client?  So the client might then see the emulation markers and be likely to commit a use-after-free?  Does that mean that whole model either needs to change and not use a clone, or we do have to add on-clone callbacks?

I don't have a magic solution but would like to better understand the current status.

Comment (hgreving2304) [reply core/arch/instr_shared.c]: I agree. This is a deeper problem and I don't have the whole picture, i.e. I am not sure how this is being used later, e.g. for traces, do we pass down the cloned instruction to the client or the original one etc... or both...? My thinking was that cloning the callback pointer in instr_clone() is definitely not right and whether the caller should make a deep copy, no copy or transfer the pointer is up to the higher semantics of the caller. I saw this as a small fix but more than just a band-aid, because I looked at this as definitely wrong. I would suggest to add a describing FIXME comment to the emulation instruction API.

Comment (derekbruening) [reply core/arch/instr_shared.c]: Maybe you could file a new issue, add pointers to it in this PR, and then submit this PR to fix the immediate problem?

Comment (hgreving2304) [reply core/arch/instr_shared.c]: xref https://github.com/DynamoRIO/dynamorio/issues/3962

Comment (derekbruening) [reply core/arch/instr_shared.c]: Please add comments to the emulation API pointing to it.

Comment (hgreving2304) [reply core/arch/instr_shared.c]: doxygen or internal only?

Comment (derekbruening) [reply core/arch/instr_shared.c]: I don't know, maybe both

Comment (hgreving2304) [reply core/arch/instr_shared.c]: Done. Please note that the bug affects rather the label callback in general and less the emulation API directly. The label_data is cloned and copied. It's the label callback that may or may not be used by an emulation client.

**Comment by hgreving2304** [comment]
PTAL.

File: core/arch/instr_shared.c (hunk 2 above)
Comment (derekbruening) [reply core/arch/instr_shared.c]: But the label_data contains a pointer to an instr_t whose copy is what leads to the use-after-free so they are both involved.

**Comment by hgreving2304** [comment]
run arm tests
