### PR TITLE
i#7572: Fix mid-block-detach drmemtrace bug

### LINKED ISSUE #7572: drmemtrace mid-block detach keeps never-executed instrs with no data addrs
We observed on an app with long basic blocks that a detach mid-block with offline tracing results in the rest of the block's instructions being added to the final trace but without any data addresses, violating invariants for load/store instrs.

The proposal is to store a record showing the detach point in the block for raw2trace to consume.

Maybe the same record could be used for #5790.

### PR DESCRIPTION
**Pull request by derekbruening**
Adds a new test drcacheoff.longblock which reproduces a bug where a detach mid-block results in an incorrectly-complete post-processed block missing load/store records in the tail of the block.  The test fails with an invariant error on missing read records in HEAD.

Fixes the test by adding a new trace record
TRACE_MARKER_TYPE_MIDBLOCK_END_PC just before the footer in each thread. This holds the thread's final PC value.  This marker is used by raw2trace to identify a block interruption point, just like a kernel event marker would, and the same
TRACE_MARKER_TYPE_UNCOMPLETED_INSTRUCTION is emitted as well (it doesn't really help analyzers/simulators for detach, but it will help for DR mid-block relocation: #5790).  The marker is removed and not visible in the final trace.

This same marker can be used to solve block truncation for DR mid-block relocation (#5790) once DR provides a relocation event.

Updates DR detach to set each thread's mcontext for retrieval by clients in the thread exit event.  Documents that the pc field is in fact set for the thread exit event (and verified it is set for regular exit: points to exit syscall post-pc so the uncompleted marker does not get added there which seems good).

Fixes #7572

### CODE REVIEW

File: clients/drcachesim/tests/burst_longblock.cpp [hunk 1]
```diff
@@ -0,0 +1,323 @@
...
+    // but tracing has already ended.
+    if (!my_setenv("DYNAMORIO_OPTIONS",
+                   "-stderr_mask 0xc -client_lib ';;-offline -no_align_endpoints"))
+        std::cerr << "failed to set env var!\n";
+    std::cerr << "pre-DR init\n" << std::flush;
+    dr_app_setup_and_start();
+    assert(dr_app_running_under_dynamorio());
+    if (do_some_work() < 0)
+        std::cerr << "error in computation\n";
+    // TODO i#6490: This app produces incorrect output when run under DR if we do
```
Comment (abhinav92003) [inline clients/drcachesim/tests/burst_longblock.cpp]: Sigh. I thought we fixed this.

File: clients/drcachesim/tests/burst_longblock.cpp [hunk 2]
```diff
@@ -0,0 +1,323 @@
...
+int
+test_main(int argc, const char *argv[])
+{
+    // Start up a thread that spends most of its time in a long block.
+    thread_t thread = create_thread(thread_func, nullptr);
+    // Now gather a trace where the detach should often split the block.
+    gather_trace();
+    child_should_exit.store(true, std::memory_order_release);
+    join_thread(thread);
+    // The test harness will post-process the trace and run invariant_checker
```
Comment (abhinav92003) [inline clients/drcachesim/tests/burst_longblock.cpp:316]: So ideally cmake should run this test Nx and ensure there isn't a single failure? (Assuming the odds of hitting the mid-block-detach are very high 1/N).

File: clients/drcachesim/tracer/output.cpp [hunk 3]
```diff
@@ -1426,6 +1426,21 @@ exit_thread_io(void *drcontext)
...
     if (has_prior_window_data || is_not_empty) {
+        if (op_offline.get_value()) {
+            // Provide the PC in case detach exited mid-block.
+            dr_mcontext_t mc;
+            mc.size = sizeof(mc);
+            mc.flags = DR_MC_CONTROL;
+            if (dr_get_mcontext(drcontext, &mc)) {
+                NOTIFY(2, "Thread " TIDFMT "%d end pc=%p\n", dr_get_thread_id(drcontext),
+                       mc.pc);
+                // XXX i#5790: This same marker can be used to solve block truncation for
```
Comment (abhinav92003) [inline clients/drcachesim/tracer/output.cpp:1439]: Surprised that mid-block-detach wasn't seen before. Am I missing something that made it less likely before and we're seeing it only now for some reason? Maybe our drbbdup stops traces only at bb ends? But what about before we used drbbdup?

File: clients/drcachesim/tracer/output.cpp [hunk 4]
```diff
@@ -1426,6 +1426,21 @@ exit_thread_io(void *drcontext)
...
+                // DR mid-block relocation once DR provides a relocation event.
```
Comment (abhinav92003) [inline clients/drcachesim/tracer/output.cpp]: Re the asynchronous thread relocation event: is that specific to only languages where the runtime supports it, like Rust? Do we expect it in C++? Is there a high level issue filed for Rust support?

File: clients/drcachesim/tracer/raw2trace.cpp [hunk 5]
```diff
@@ -475,6 +475,10 @@ raw2trace_t::process_marker(raw2trace_thread_data_t *tdata,
                             trace_marker_type_t marker_type, uintptr_t marker_val,
                             byte *&buf, DR_PARAM_OUT bool *flush_decode_cache)
 {
+    if (marker_type == TRACE_MARKER_TYPE_MIDBLOCK_END_PC) {
+        // Consumed by raw2trace and not made visible in final trace.
```
Comment (abhinav92003) [inline clients/drcachesim/tracer/raw2trace.cpp:479]: Document cases where this may happen, as to a first time reader it seems to violate the basic principle of basic blocks: that it can be relied on to execute till the bb end (though we did have the kernel_event case from before too). Also worth a similar comment by offline_entry_t.pc.instr_count.

File: clients/drcachesim/tracer/raw2trace.cpp [hunk 6]
```diff
@@ -1757,13 +1764,16 @@ raw2trace_t::append_bb_entries(raw2trace_thread_data_t *tdata,
...
         // The trace is recording instruction retirement, premmpted instructions
-        // and the corresponding memrefs, and instructions casuing a fault are
+        // and the corresponding memrefs, and instructions causing a fault are
         // removed.
         const bool interrupted = interrupted_by_kernel_event(tdata, cur_pc, cur_offs);
         if (interrupted) {
             // Insert the TRACE_MARKER_TYPE_UNCOMPLETED_INSTRUCTION marker to
             // indicate an instruction is removed from the trace because it was
             // interrupted by an asynchronous signal or caused a fault.
+            // We emit the marker for a midblock exit (detach or DR transfer)
```
Comment (abhinav92003) [inline clients/drcachesim/tracer/raw2trace.cpp]: "DR transfer" seems a new phrase to me. I understand it means async thread transfer from this PR's context, but it may not be clear to a future reader looking at this code. More explanation would be nice. FWIW I wasn't aware that something like the async thread transfer mechanism exists.

File: core/lib/dr_ir_utils.h [hunk 7]
```diff
@@ -804,8 +804,9 @@ DR_API
  *
  * Even when #DR_MC_CONTROL is specified, does NOT copy the pc field,
  * except for system call events, when it will point at the
- * post-syscall address, and kernel transfer events, when it will point to the
- * target pc.
+ * post-syscall address; for kernel transfer events, when it will point to the
+ * target pc; and thread exit events, when it will point to the thread's final
+ * (or detach-time) pc.
```
Comment (abhinav92003) [inline core/lib/dr_ir_utils.h]: So it did execute that pc?

File: clients/drcachesim/tracer/output.cpp [hunk 8]
```diff
@@ -1426,6 +1426,21 @@ exit_thread_io(void *drcontext)
...
+                BUF_PTR(data->seg_base) += instru->append_marker(
+                    BUF_PTR(data->seg_base), TRACE_MARKER_TYPE_MIDBLOCK_END_PC,
+                    reinterpret_cast<uintptr_t>(mc.pc));
```
Comment (abhinav92003) [inline clients/drcachesim/tracer/output.cpp:1444]: From the dr_get_mcontext comment: So this pc was indeed executed and will be included in the trace?

File: clients/drcachesim/common/trace_entry.h [hunk 9]
```diff
@@ -735,6 +735,14 @@ typedef enum {
      */
     TRACE_MARKER_TYPE_UNCOMPLETED_INSTRUCTION,
 
+    /**
+     * This marker is used in raw offline traces to indicate the endpoint of the
+     * final block in a thread at detach, or the interruption point of a block by a
+     * relocation performed by DR.  This marker is not visible in a final trace: it
+     * is consumed during post-processing.  The marker value is the PC in the block.
```
Comment (abhinav92003) [inline clients/drcachesim/common/trace_entry.h]: Clarify if this pc is included in the trace or not.

File: clients/drcachesim/tracer/raw2trace.cpp [hunk 10]
```diff
@@ -1539,14 +1543,17 @@ raw2trace_t::interrupted_by_kernel_event(raw2trace_thread_data_t *tdata, uint64_
...
                 if (!get_marker_value(tdata, &next_entry, &marker_val)) {
                     return false;
                 }
                 // Check the stored PC against cur_offs or cur_pc based on version.
                 int version = get_version(tdata);
-                if (version < OFFLINE_FILE_VERSION_KERNEL_INT_PC) {
+                if (is_kernel && version < OFFLINE_FILE_VERSION_KERNEL_INT_PC) {
                     // We have only the offs, so we can't handle differing modules for
                     // the source and target for legacy traces.
                     if (marker_val == cur_offs)
```
Comment (abhinav92003) [inline clients/drcachesim/tracer/raw2trace.cpp:1562]: Comment for L1562: Xref other comments for clarification on this. My current understanding is the kernel_event holds the next pc and that pc is not included in the trace, whereas the midblock_end_pc holds the last pc executed which is indeed included in the trace. So should the L1562 condition look different for the two kinds of markers handled in the outer if-block?

**Review by abhinav92003 — APPROVED** [review]

File: clients/drcachesim/tracer/output.cpp (hunk 3 above)
Comment (derekbruening) [reply clients/drcachesim/tracer/output.cpp:1439]: I found that -align_endpoints made it much less likely on this test: I think that is the reason. (I have a comment about that where I disable the option for this test.) Probably most threads enter a new block and go to nop mode before they get the detach signal, and so it doesn't matter if they detach mid-block (I observed on this test it was definitely detaching mid block but was already in nop mode).

Comment (derekbruening) [reply clients/drcachesim/tracer/output.cpp:1439]: I updated the bug to make this clear.

Re: before we used drbbdup: I suspect we didn't have the invariant check for read and write records, so we had errors but didn't know it.

File: clients/drcachesim/tests/burst_longblock.cpp (hunk 1 above)
Comment (derekbruening) [reply clients/drcachesim/tests/burst_longblock.cpp]: Oh, I didn't observe this: I admit I copy-pasted parts of this from another test. The comment is also in burst_gencode and burst_syscall_inject. So presumably these can all be removed: removing from longblock here; will send a separate PR to remove from the others.

File: clients/drcachesim/tracer/output.cpp (hunk 4 above)
Comment (derekbruening) [reply clients/drcachesim/tracer/output.cpp]: Oh no, that's when DR relocates a thread (can happen for several reasons: see #5790).

File: clients/drcachesim/tests/burst_longblock.cpp (hunk 2 above)
Comment (derekbruening) [reply clients/drcachesim/tests/burst_longblock.cpp:316]: Actually this test hits the problem every single time: 50 out of 50 when I tested it. So one run is enough. It's because fpatan is a very slow instruction :)

I added here:

    // As noted, the test hits a mid-block detach reliably every time,
    // so we just need the one trace.

I added up above:

    // (it happens in 50 out of 50 runs this way and almost never with
    // -align_endpoints enabled).

File: clients/drcachesim/tracer/output.cpp (hunk 3 above)
Comment (derekbruening) [reply clients/drcachesim/tracer/output.cpp:1439]: Resolving.

File: clients/drcachesim/tracer/output.cpp (hunk 4 above)
Comment (derekbruening) [reply clients/drcachesim/tracer/output.cpp]: I added parentheses here: "DR mid-block relocation (happens on synchronous flushes and resets)".

File: clients/drcachesim/tests/burst_longblock.cpp (hunk 1 above)
Comment (derekbruening) [reply clients/drcachesim/tests/burst_longblock.cpp]: I removed here and the test does pass 10 times in a row.

Comment (derekbruening) [reply clients/drcachesim/tests/burst_longblock.cpp]: To clarify, I removed both the comment and all the "std::flush" calls.

File: clients/drcachesim/tracer/raw2trace.cpp (hunk 5 above)
Comment (derekbruening) [reply clients/drcachesim/tracer/raw2trace.cpp:479]: Added this in the code where it looks for this marker interrupting a block:

            // Check for interruption of the basic block in the middle by either
            // a kernel event (e.g., a signal) or DR not finishing the block
            // (e.g., on detach or some thread relocation like a synchronous flush).

Added this by instr_count field:

            // This is the count of instructions in the block.
            // However, they may not all have exited if interrupted mid-block
            // by a kernel event (e.g., a signal) or DR not finishing the block
            // (e.g., on detach or some thread relocation like a synchronous flush);
            // in those cases the trace has markers indicating where the block ended.

File: clients/drcachesim/tracer/raw2trace.cpp (hunk 6 above)
Comment (derekbruening) [reply clients/drcachesim/tracer/raw2trace.cpp]: Reworded to "detach or DR transfer such as synchronous flush".

File: core/lib/dr_ir_utils.h (hunk 7 above)
Comment (derekbruening) [reply core/lib/dr_ir_utils.h]: No. Added " (which is the next pc to execute: it was not itself executed under DR)"

File: clients/drcachesim/tracer/output.cpp (hunk 8 above)
Comment (derekbruening) [reply clients/drcachesim/tracer/output.cpp:1444]: No. Added:

            // This PC was not executed; raw2trace will end the block before this PC
            // (and add an uncompleted marker).

File: clients/drcachesim/common/trace_entry.h (hunk 9 above)
Comment (derekbruening) [reply clients/drcachesim/common/trace_entry.h]: Now it says:

     * is consumed during post-processing.  The marker value is the PC in the block
     * where execution stopped (i.e., this PC itself was not executed; raw2trace will
     * end the block before this PC and add an uncompleted marker).

File: clients/drcachesim/tracer/raw2trace.cpp (hunk 10 above)
Comment (derekbruening) [reply clients/drcachesim/tracer/raw2trace.cpp:1562]: See other comments: the mid-block is also not included and was not executed.
