### PR TITLE
i#3069 DRCachesim: Fix sim_refs regression

### LINKED ISSUE #3069: regression from warmup_fraction feature causes no-warmup sim_refs to be ignored
Commit 93c1d01389ae81d539161aa256633adff257075d for #2755 (PR #2758) broke
sim_refs: without any warmup specified, sim_refs is completely ignored.

It looks like there is not a good regression test for sim_refs, which is
why this was not noticed.  Adding one to the unit tests is appealing but
will require #3068.

### PR DESCRIPTION
**Pull request by snehasish**
Make sure we respect the sim_refs knob when warmup_refs and
warmup_fraction are set to defaults. Add a unit test to check.

Fixes #3069

### CODE REVIEW

File: clients/drcachesim/simulator/cache_simulator.cpp [hunk 1]
```diff
@@ -286,6 +286,11 @@ cache_simulator_t::~cache_simulator_t()
     }
 }
 
+uint64_t
+cache_simulator_t::knobs_sim_refs() const {
```
Comment (derekbruening) [inline clients/drcachesim/simulator/cache_simulator.cpp]: style: { on own line

File: clients/drcachesim/simulator/cache_simulator.h [hunk 2]
```diff
@@ -61,6 +61,7 @@ class cache_simulator_t : public simulator_t
 
     // Exposed to make it easy to test
     bool check_warmed_up();
+    uint64_t knobs_sim_refs() const;
```
Comment (derekbruening) [inline clients/drcachesim/simulator/cache_simulator.h]: From the name, I would expect this to return the original option value I passed in, not the *remaining* refs to simulate.   Seems better renamed: s/knobs_/remaining_/ or sthg.

**Comment by snehasish** [comment]
PTAL. Thanks!
