### PR TITLE
i#3662: Fix mask source operand's size in decode table.

### LINKED ISSUE #3662: AVX-512: Fix 1-bit mask opcodes and possibly introduce 1-bit mask size type.
Some AVX-512 instructions read only 1 mask bit (e.g. vmovss etc.) To better describe them, we may need a sub-1-byte type to describe a bit. Currently, we're using KEb to describe them.

The opcodes vaddss, vsubss, vmulss are wrong and need to be the new type, or KEb. Thanks @JivanH  for finding.

### PR DESCRIPTION
**Pull request by hgreving2304**
Fixes the evex masks' size for all ss* and sd* vector opcodes to reflect 1 bit.

Fixes #3662
Issue: #1312

### CODE REVIEW

File: core/arch/x86/decode_table.c [hunk 1]
```diff
@@ -1534,6 +1534,7 @@ const instr_info_t * const op_instr[] =
 #define KVw TYPE_K_VEX, OPSZ_2
```
Comment (derekbruening) [inline core/arch/x86/decode_table.c]: > Fixes the evex masks's size for all ss* and sd* vector opcodes to reflect 1 bit.

Grammar: masks'

Comment (hgreving2304) [reply core/arch/x86/decode_table.c]: Fixed.
