### PR TITLE
i#5426: Mark instrs in AArch64 mangling epilogue and emulate them.

### LINKED ISSUE #5426: [AArch64][jdk8] Incorrect handling synchro signal in case mangling epilogue pc
We've got synchro signal on thread.
```
main_signal_handler: thread=1588266, sig=12, xsp=0x0000fff923c94da0, retaddr=0x000000000000000c
siginfo: sig = 12, pid = 1587929, status = 0, errno = 0, si_code = -6
        x0     = 0x0000000000000000
        x1     = 0x0000fff923c6e000
        x2     = 0x000000000000000c
        x3     = 0x0000000000000030
        x4     = 0x000000000000005c
        x5     = 0x0000000000003c05
        x6     = 0x0000fff09015a9b8
        x7     = 0xfefeff6f6071735e
        x8     = 0x7f7f7f7f7f7f7f7f
        x9     = 0x0000000000000000
        x10    = 0x0101010101010101
        x11    = 0x0000000000000028
        x12    = 0x0000a701409d1276
        x13    = 0x0000000000000040
        x14    = 0x000000000000003f
        x15    = 0x0000000000000000
        x16    = 0x0000ffffa651dc00
        x17    = 0x0000ffffa6bc4080
        x18    = 0x0000000000000000
        x19    = 0x0000000000000030
        x20    = 0x0000fff090484208
        x21    = 0x0000fff0901b94f8
        x22    = 0x0000ffffa6600340
        x23    = 0x0000000000000001
        x24    = 0x0000000000000021
        x25    = 0x0000fff09045a8f8
        x26    = 0x0000000000000021
        x27    = 0x0000000000000108
        x28    = 0x0000fff923c6e000
        x29    = 0x0000fff106572880
        x30    = 0x0000ffffa635068c
        sp     = 0x0000fff106572880
        pc     = 0x0000ffff238c68c8
        pstate = 0x0000000020000000
```
pc is `0x0000ffff238c68c8`

code cache for the bb looks like
```
(gdb) x /16i (0x0000ffff238c68c8-48)
   0xffff238c6898:      ldr     x0, [x25, #8]
   0xffff238c689c:      str     x0, [x28]
   0xffff238c68a0:      mov     x0, x28
   0xffff238c68a4:      ldr     x28, [x28, #48]
   0xffff238c68a8:      lsl     x27, x28, #3
   0xffff238c68ac:      mov     x28, x0
   0xffff238c68b0:      ldr     x0, [x28]
   0xffff238c68b4:      str     x1, [x28, #8]
   0xffff238c68b8:      mov     x1, x28
   0xffff238c68bc:      ldr     x28, [x28, #48]
   0xffff238c68c0:      ldr     x0, [x0, x28, lsl #3]
   0xffff238c68c4:      mov     x28, x1
==>   0xffff238c68c8:      ldr     x1, [x28, #8]   <==
   0xffff238c68cc:      cmp     x20, x0
   0xffff238c68d0:      b.eq    0xffff238c6de8  // b.none
   0xffff238c68d4:      b       0xffff238c6a68
```

clear bb and bb after mangling
```
interp: start_pc = 0x0000ffffa6350424
check_thread_vm_area: pc = 0x0000ffffa6350424
check_thread_vm_area: check_stop = 0x0000ffffa6b02888
  0x0000ffffa6350424  f9400720   ldr    +0x08(%x25)[8byte] -> %x0
  0x0000ffffa6350428  d37df39b   ubfm   %x28 $0x3d $0x3c -> %x27
  0x0000ffffa635042c  f87c7800   ldr    (%x0,%x28,lsl #3)[8byte] -> %x0
  0x0000ffffa6350430  eb00029f   subs   %x20 %x0 lsl $0x00 -> %xzr
  0x0000ffffa6350434  54000340   b.eq   $0x0000ffffa635049c
end_pc = 0x0000ffffa6350438
```
```
bb ilist after mangling:
TAG  0x0000ffffa6350424
 +0    L3 @0x0000fff923eafda0  f9400720   ldr    +0x08(%x25)[8byte] -> %x0
 +4    m4 @0x0000fff923eb1110  f9000380   str    %x0 -> (%x28)[8byte]
 +8    m4 @0x0000fff923eb1df0  aa1c03e0   orr    %xzr %x28 lsl $0x0000000000000000 -> %x0
 +12   m4 @0x0000fff923eb1358  f9401b9c   ldr    +0x30(%x28)[8byte] -> %x28
 +16   L3 @0x0000fff923eb0430  d37df39b   ubfm   %x28 $0x3d $0x3c -> %x27
 +20   m4 @0x0000fff923eb1090  aa0003fc   orr    %xzr %x0 lsl $0x0000000000000000 -> %x28
 +24   m4 @0x0000fff923eae950  f9400380   ldr    (%x28)[8byte] -> %x0
 +28   m4 @0x0000fff923eaf438  f9000781   str    %x1 -> +0x08(%x28)[8byte]
 +32   m4 @0x0000fff923eae9d0  aa1c03e1   orr    %xzr %x28 lsl $0x0000000000000000 -> %x1
 +36   m4 @0x0000fff923eaeb18  f9401b9c   ldr    +0x30(%x28)[8byte] -> %x28
 +40   L3 @0x0000fff923eaf0a8  f87c7800   ldr    (%x0,%x28,lsl #3)[8byte] -> %x0
 +44   m4 @0x0000fff923eafd20  aa0103fc   orr    %xzr %x1 lsl $0x0000000000000000 -> %x28
==> +48   m4 @0x0000fff923eb00e8  f9400781   ldr    +0x08(%x28)[8byte] -> %x1     <==
 +52   L3 @0x0000fff923eb12d8  eb00029f   subs   %x20 %x0 lsl $0x00 -> %xzr
 +56   L3 @0x0000fff923eb20b8  54000340   b.eq   $0x0000ffffa635049c
 +60   L4 @0x0000fff923eb1e70  14000000   b      $0x0000ffffa6350438
END 0x0000ffffa6350424
```
So, pc `0x0000ffff238c68c8` is mangling m4 instruction `ldr    +0x08(%x28)[8byte] -> %x1`

When the thread was awake, dispatcher set target `0x0000ffffa635042c`
```
handle_suspend_signal: awake now
        main_signal_handler 12 returning now to 0x0000ffff22d11454
Exit due to proactive reset

d_r_dispatch: target = 0x0000ffffa635042c
```
Building new bb
```
interp: start_pc = 0x0000ffffa635042c
check_thread_vm_area: pc = 0x0000ffffa635042c
check_thread_vm_area: check_stop = 0x0000ffffa6b02888
==>  0x0000ffffa635042c  f87c7800   ldr    (%x0,%x28,lsl #3)[8byte] -> %x0 <==
  0x0000ffffa6350430  eb00029f   subs   %x20 %x0 lsl $0x00 -> %xzr
  0x0000ffffa6350434  54000340   b.eq   $0x0000ffffa635049c
end_pc = 0x0000ffffa6350438
```
```
bb ilist after mangling:
TAG  0x0000ffffa635042c
 +0    m4 @0x0000fff923eb1110  f9000781   str    %x1 -> +0x08(%x28)[8byte]
 +4    m4 @0x0000fff923eb12d8  aa1c03e1   orr    %xzr %x28 lsl $0x0000000000000000 -> %x1
 +8    m4 @0x0000fff923eb1df0  f9401b9c   ldr    +0x30(%x28)[8byte] -> %x28
==> +12   L3 @0x0000fff923eaf0a8  f87c7800   ldr    (%x0,%x28,lsl #3)[8byte] -> %x0 <==
 +16   m4 @0x0000fff923eb1358  aa0103fc   orr    %xzr %x1 lsl $0x0000000000000000 -> %x28
*** +20   m4 @0x0000fff923eb0430  f9400781   ldr    +0x08(%x28)[8byte] -> %x1 ***
 +24   L3 @0x0000fff923eafd20  eb00029f   subs   %x20 %x0 lsl $0x00 -> %xzr
 +28   L3 @0x0000fff923eb00e8  54000340   b.eq   $0x0000ffffa635049c
 +32   L4 @0x0000fff923eafda0  14000000   b      $0x0000ffffa6350438
END 0x0000ffffa635042c
```

Looks like we back to 1st original instruction `ldr    (%x0,%x28,lsl #3)[8byte] -> %x0` before our mangle `ldr    +0x08(%x28)[8byte] -> %x1`
but probably register context was not restored and x0 register has incorrect value

crash signal context
```
main_signal_handler: thread=1588266, sig=11, xsp=0x0000fff923c94da0, retaddr=0x000000000000000b
siginfo: sig = 11, pid = 264, status = 0, errno = 0, si_code = 1
          x0     = 0x0000000000000000
          x1     = 0x0000fff923c6e000
          x2     = 0x000000000000000c
          x3     = 0x0000000000000030
          x4     = 0x000000000000005c
          x5     = 0x0000000000003c05
          x6     = 0x0000fff09015a9b8
          x7     = 0xfefeff6f6071735e
          x8     = 0x7f7f7f7f7f7f7f7f
          x9     = 0x0000000000000000
          x10    = 0x0101010101010101
          x11    = 0x0000000000000028
          x12    = 0x0000a701409d1276
          x13    = 0x0000000000000040
          x14    = 0x000000000000003f
          x15    = 0x0000000000000000
          x16    = 0x0000ffffa651dc00
          x17    = 0x0000ffffa6bc4080
          x18    = 0x0000000000000000
          x19    = 0x0000000000000030
          x20    = 0x0000fff090484208
          x21    = 0x0000fff0901b94f8
          x22    = 0x0000ffffa6600340
          x23    = 0x0000000000000001
          x24    = 0x0000000000000021
          x25    = 0x0000fff09045a8f8
          x26    = 0x0000000000000021
          x27    = 0x0000000000000108
          x28    = 0x0000000000000021
          x29    = 0x0000fff106572880
          x30    = 0x0000ffffa635068c
          sp     = 0x0000fff106572880
          pc     = 0x0000ffff2417046c
          pstate = 0x0000000020000000
```

```
computing memory target for 0x0000ffff2417046c causing SIGSEGV, kernel claims it is 0x0000000000000108
compute_memory_target: falling back to racy protection checks
opnd_compute_address for: (%x0,%x28,lsl #3)
          base => 0x0000000000000000
          index,scale => 0x0000000000000108
          disp => 0x0000000000000108
For SIGSEGV at cache pc 0x0000ffff2417046c, computed target read 0x0000000000000108
          faulting instr: ldr    (%x0,%x28,lsl #3)[8byte] -> %x0
** Received SIGSEGV at cache pc 0x0000ffff2417046c in thread 1588266
record_pending_signal(11) from cache pc 0x0000ffff2417046c
          not certain can delay so handling now
          action is not SIG_IGN


(gdb) x /9i (0x0000ffff2417046c-12)
   0xffff24170460:      str     x1, [x28, #8]
   0xffff24170464:      mov     x1, x28
   0xffff24170468:      ldr     x28, [x28, #48]
   0xffff2417046c:      ldr     x0, [x0, x28, lsl #3]
   0xffff24170470:      mov     x28, x1
   0xffff24170474:      ldr     x1, [x28, #8]
   0xffff24170478:      cmp     x20, x0
   0xffff2417047c:      b.eq    0xffff24170484  // b.none
   0xffff24170480:      b       0xffff238c6a68
```

Looks like the following case:
  - before synchro signal we executed `ldr     x0, [x0, x28, lsl #3]` and change x0
  - after the signal, we back from `ldr     x1, [x28, #8]` to `ldr     x0, [x0, x28, lsl #3]` but don't restore context
  - we execute  `ldr     x0, [x0, x28, lsl #3]` the 2nd time but with incorrect register context

Derek comment is "You would expect this to be marked as a mangling epilogue. Translation in a mangling epilogue is supposed to target the next instruction and "emulate" the rest of the epilogue, as it is sometimes impossible to undo the app instr and thus returning the being-mangled instr PC for restart is not feasible. This makes it look like that is not done correctly for stolen register mangling on AArch64."

### PR DESCRIPTION
**Pull request by egrimley-arm**
In mangling instrs that use the stolen register, mark the instrs that restore the register state as mangling epilogue.

In recreate_app_state_from_ilist emulate those instructions to advance the app state to after the app instr.

This fixes #5426, for which a test is added, but there are probably other translation failures on AArch64, and similar failures on other architectures.

The test uses a new function in tools.c, adaptive_retry, which is abstracted from signal_pre_syscall.c.

Issue: #3307, #3329, #5426.
Fixes #5426

### CODE REVIEW

File: core/arch/aarchxx/mangle.c [hunk 1]
```diff
@@ -2234,8 +2238,12 @@ mangle_stolen_reg(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
     /* restore tls_base back to dr_reg_stolen */
     restore_tls_base_to_stolen_reg(dcontext, ilist, instr, next_instr, tmp, slot);
     /* restore tmp if necessary */
-    if (should_restore)
-        PRE(ilist, next_instr, instr_create_restore_from_tls(dcontext, tmp, slot));
+    if (should_restore) {
+        instr_t *restore = instr_create_restore_from_tls(dcontext, tmp, slot);
+        instr_set_our_mangling(restore, true);
```
Comment (derekbruening) [inline core/arch/aarchxx/mangle.c]: Isn't this already set by instrlist_set_our_mangling() at the top of d_r_mangle()?
Add an assert instead?

File: core/arch/aarchxx/mangle.c
Comment (derekbruening) [inline core/arch/aarchxx/mangle.c]: spelling: "writback"

File: core/arch/aarchxx/mangle.c [hunk 2]
```diff
@@ -2149,12 +2149,14 @@ restore_tls_base_to_stolen_reg(dcontext_t *dcontext, instrlist_t *ilist, instr_t
...
-                               opnd_create_base_disp(reg, REG_NULL, 0,
-                                                     os_tls_offset(TLS_REG_STOLEN_SLOT),
-                                                     OPSZ_PTR),
-                               opnd_create_reg(dr_reg_stolen)));
+        instr_t *store = XINST_CREATE_store(
+            dcontext,
+            opnd_create_base_disp(reg, REG_NULL, 0, os_tls_offset(TLS_REG_STOLEN_SLOT),
+                                  OPSZ_PTR),
+            opnd_create_reg(dr_reg_stolen));
+        instr_set_our_mangling(store, true);
```
Comment (derekbruening) [inline core/arch/aarchxx/mangle.c]: This is only used by routines inside d_r_mangle() so this should already be set. How about adding an assert on instrlist_get_our_mangling instead and commenting in the function comment that this is only callable inside d_r_mangle().

File: core/arch/aarchxx/mangle.c [hunk 3]
```diff
@@ -2164,9 +2166,11 @@ restore_tls_base_to_stolen_reg(dcontext_t *dcontext, instrlist_t *ilist, instr_t
     }
     /* restore stolen reg from spill reg */
     /* This precise opcode (OP_orr) is checked for in instr_is_stolen_reg_move(). */
-    PRE(ilist, next_instr,
-        XINST_CREATE_move(dcontext, opnd_create_reg(dr_reg_stolen),
-                          opnd_create_reg(reg)));
+    instr_t *move =
+        XINST_CREATE_move(dcontext, opnd_create_reg(dr_reg_stolen), opnd_create_reg(reg));
+    instr_set_our_mangling(move, true);
```
Comment (derekbruening) [inline core/arch/aarchxx/mangle.c]: This is only used by routines inside d_r_mangle() so this should already be set. How about adding an assert on instrlist_get_our_mangling instead and commenting in the function comment that this is only callable inside d_r_mangle().

File: core/arch/aarchxx/mangle.c [hunk 4]
```diff
@@ -2149,12 +2149,14 @@ restore_tls_base_to_stolen_reg(dcontext_t *dcontext, instrlist_t *ilist, instr_t
...
-                                                     os_tls_offset(TLS_REG_STOLEN_SLOT),
-                                                     OPSZ_PTR),
-                               opnd_create_reg(dr_reg_stolen)));
+        instr_t *store = XINST_CREATE_store(
+            dcontext,
+            opnd_create_base_disp(reg, REG_NULL, 0, os_tls_offset(TLS_REG_STOLEN_SLOT),
+                                  OPSZ_PTR),
+            opnd_create_reg(dr_reg_stolen));
+        instr_set_our_mangling(store, true);
+        instr_set_our_mangling_epilogue(store, true);
```
Comment (derekbruening) [inline core/arch/aarchxx/mangle.c]: A translation needs to be set as well: it's assumed by the epilogue handling code.
instrlist_set_translation_target() is typically already set: should point to the app instr.
Yet don't we want it to be the post-app-instr for the epilogue?
Use instr_set_translation_mangling_epilogue()?

File: core/arch/aarchxx/mangle.c [hunk 5]
```diff
@@ -2164,9 +2166,11 @@ restore_tls_base_to_stolen_reg(dcontext_t *dcontext, instrlist_t *ilist, instr_t
     }
     /* restore stolen reg from spill reg */
     /* This precise opcode (OP_orr) is checked for in instr_is_stolen_reg_move(). */
-    PRE(ilist, next_instr,
-        XINST_CREATE_move(dcontext, opnd_create_reg(dr_reg_stolen),
-                          opnd_create_reg(reg)));
+    instr_t *move =
+        XINST_CREATE_move(dcontext, opnd_create_reg(dr_reg_stolen), opnd_create_reg(reg));
+    instr_set_our_mangling(move, true);
+    instr_set_our_mangling_epilogue(move, true);
```
Comment (derekbruening) [inline core/arch/aarchxx/mangle.c]: A translation needs to be set as well: it's assumed by the epilogue handling code.
instrlist_set_translation_target() is typically already set: should point to the app instr.
Yet don't we want it to be the post-app-instr for the epilogue?
Use instr_set_translation_mangling_epilogue()?

File: core/arch/aarchxx/mangle.c [hunk 6]
```diff
@@ -2234,8 +2238,12 @@ mangle_stolen_reg(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
     /* restore tls_base back to dr_reg_stolen */
     restore_tls_base_to_stolen_reg(dcontext, ilist, instr, next_instr, tmp, slot);
     /* restore tmp if necessary */
-    if (should_restore)
-        PRE(ilist, next_instr, instr_create_restore_from_tls(dcontext, tmp, slot));
+    if (should_restore) {
+        instr_t *restore = instr_create_restore_from_tls(dcontext, tmp, slot);
+        instr_set_our_mangling(restore, true);
+        instr_set_our_mangling_epilogue(restore, true);
```
Comment (derekbruening) [inline core/arch/aarchxx/mangle.c]: A translation needs to be set as well: it's assumed by the epilogue handling code.
instrlist_set_translation_target() is typically already set: should point to the app instr.
Yet don't we want it to be the post-app-instr for the epilogue?
Use instr_set_translation_mangling_epilogue()?

File: core/translate.c [hunk 7]
```diff
@@ -930,6 +928,68 @@ recreate_app_state_from_info(dcontext_t *tdcontext, const translation_info_t *in
     return res;
 }
 
+#ifdef AARCH64 /* XXX: Add other non-x86 architectures here? */
+/* Emulate instructions in mangling epilogue. */
+static void
+emulate_epilogue(priv_mcontext_t *mc, instr_t *first_inst)
+{
+    app_pc translation = first_inst->translation;
```
Comment (derekbruening) [inline core/translate.c]: Nicer to use the accessors instr_get_translation(), as the existing code does.

File: core/translate.c [hunk 8]
```diff
@@ -1127,6 +1187,14 @@ recreate_app_state_from_ilist(dcontext_t *tdcontext, instrlist_t *ilist, byte *s
                     }
                 }
             }
+#ifdef AARCH64 /* XXX: Add other non-x86 architectures here? */
+            if (instr_is_our_mangling_epilogue(inst)) {
```
Comment (derekbruening) [inline core/translate.c]: Better to call this inside translate_walk_restore?

File: core/translate.c [hunk 9]
```diff
@@ -930,6 +928,68 @@ recreate_app_state_from_info(dcontext_t *tdcontext, const translation_info_t *in
...
+        case OP_ldr: {
+            ASSERT(instr_num_dsts(inst) == 1 && instr_num_srcs(inst) == 1);
+            opnd_t dst = instr_get_dst(inst, 0);
+            opnd_t src = instr_get_src(inst, 0);
+            ASSERT(opnd_is_reg(dst) && opnd_is_base_disp(src));
+            reg_t rd = opnd_get_reg(dst);
+            ASSERT(DR_REG_X0 <= rd && rd <= DR_REG_X30);
+            reg_t value;
+            memcpy(&value, opnd_compute_address_priv(src, mc), sizeof(value));
+            reg_set_value_priv(rd, mc, value);
```
Comment (derekbruening) [inline core/translate.c]: How does this differ from what x86 does? Why does this need special emulation when x86 does not seem to have such code?

File: core/arch/aarchxx/mangle.c (hunk 1 above)
Comment (egrimley-arm) [reply core/arch/aarchxx/mangle.c]: It gets set by `d_r_mangle()`, but later, so I can't use an assert here, and I don't want to leave the instruction temporarily in a weird state (`mangling_epilogue` but not `mangling`).

We're talking here about 3 locations in this file.

File: core/arch/aarchxx/mangle.c (hunk 2 above)
Comment (egrimley-arm) [reply core/arch/aarchxx/mangle.c]: See above.

File: core/arch/aarchxx/mangle.c (hunk 3 above)
Comment (egrimley-arm) [reply core/arch/aarchxx/mangle.c]: See above.

File: core/arch/aarchxx/mangle.c
Comment (egrimley-arm) [reply core/arch/aarchxx/mangle.c]: Done.

File: core/translate.c (hunk 7 above)
Comment (egrimley-arm) [reply core/translate.c]: Done.

File: core/arch/aarchxx/mangle.c (hunk 1 above)
Comment (egrimley-arm) [reply core/arch/aarchxx/mangle.c]: It seems that the `PRE` magically copies certain attributes from the `instrlist` to the `instr`. I can't see where that's documented or where it happens, but it seems to work if I put an `ASSERT` after the `PRE`, so I'll do that.

File: core/arch/aarchxx/mangle.c (hunk 4 above)
Comment (egrimley-arm) [reply core/arch/aarchxx/mangle.c]: See similar comment at later location in source file.

File: core/arch/aarchxx/mangle.c (hunk 5 above)
Comment (egrimley-arm) [reply core/arch/aarchxx/mangle.c]: See similar comment at later location in source file.

File: core/arch/aarchxx/mangle.c (hunk 6 above)
Comment (egrimley-arm) [reply core/arch/aarchxx/mangle.c]: I think the translation gets set later by `d_r_mangle()`, and it's set to the current instr rather than the following one, which I think is probably what developers would expect in the absence of a clear statement to the contrary.

File: core/translate.c (hunk 8 above)
Comment (egrimley-arm) [reply core/translate.c]: Done.

File: core/translate.c (hunk 9 above)
Comment (egrimley-arm) [reply core/translate.c]: I think it's because of the stolen register. Probably we can update `translate_walk` to handle the stolen register but there might be some unforeseen difficulty so for now I'm inserting this comment near the call to `emulate_epilogue`:
```
    /* TODO: Either add other non-x86 architectures to emulate_epilogue or
     * improve the translate_walk_t mechanism so that it can handle the stolen
     * register and other aspects of non-x86 mangling (i#7675).
     */
```

File: core/arch/aarchxx/mangle.c (hunk 6 above)
Comment (derekbruening) [reply core/arch/aarchxx/mangle.c]: The current instr is incorrect for post-instr mangling: the translation PC is the PC to be re-started. It can't be a retired instr as it is incorrect to re-execute it.

File: core/arch/aarchxx/mangle.c (hunk 1 above)
Comment (derekbruening) [reply core/arch/aarchxx/mangle.c]: >  I can't see where that's documented or where it happens

Like I said, it's instrlist_set_our_mangling() at the top of d_r_mangle().

File: core/translate.c [hunk 10]
```diff
@@ -606,10 +604,82 @@ translate_walk_good_state(dcontext_t *tdcontext, translate_walk_t *walk,
...
+    }
+}
+#endif /* AARCH64 */
+
+static app_pc
 translate_walk_restore(dcontext_t *tdcontext, translate_walk_t *walk, instr_t *inst,
                        app_pc translate_pc)
 {
+#ifdef AARCH64
+    /* TODO: Either add other non-x86 architectures to emulate_epilogue or
```
Comment (derekbruening) [inline core/translate.c]: style: Put the issue number covering this after the TODO: see https://dynamorio.org/page_code_style.html#autotoc_md127

File: core/translate.c [hunk 11]
```diff
@@ -606,10 +604,82 @@ translate_walk_good_state(dcontext_t *tdcontext, translate_walk_t *walk,
             (walk->in_mangle_region && translate_pc != walk->translation));
 }
 
+#ifdef AARCH64
+/* Emulate instructions in mangling epilogue. */
```
Comment (derekbruening) [inline core/translate.c]: How does this relate to d_r_emulate() which is the existing emulation code?
Maybe this should be moved to d_r_emulate().

Comment (derekbruening) [inline core/translate.c]: Still not entirely happy with this single-arch code that does not match the existing approach.

Please put a TODO here too about this not matching the existing approach and maybe going away in favor of integration with existing code.

File: suite/tests/linux/signal_translate.c [hunk 12]
```diff
@@ -0,0 +1,154 @@
+/* **********************************************************
```
Comment (derekbruening) [inline suite/tests/linux/signal_translate.c:1]: signal_translate.c seems a clearer filename, or at least sigtranslate.c.  "trans" could mean transparency or other things.

File: suite/tests/linux/sigtrans.c [hunk 13]
```diff
@@ -0,0 +1,154 @@
...
+}
+
+void
+fail(const char *s)
+{
+    perror(s);
+    exit(1);
+}
+
+/* XXX: These initial values must be large enough to avoid i#7675, but
```
Comment (derekbruening) [inline suite/tests/linux/sigtrans.c]: style: `XXX i#7675: `

File: suite/tests/linux/sigtrans.c [hunk 14]
```diff
@@ -0,0 +1,154 @@
...
+ * should probably be reduced when that bug is fixed.
+ */
+int iters = 1000;
+unsigned long init_param = 10000;
+
+bool
+test_code(int *adjust)
+{
+    unsigned long count = 0;
+    for (int i = 0; i < iters * 2; i++) {
```
Comment (derekbruening) [inline suite/tests/linux/sigtrans.c]: Clearer to set iters to 2000 and use plain iters here. This is the main use, so you expect the var to be the actual iter count.

File: suite/tests/linux/sigtrans.c [hunk 15]
```diff
@@ -0,0 +1,154 @@
...
+
+    return hit;
+}
+
+int
+main()
+{
+    /* This test relies on SIGPIPE, delivered by a timer, being
+     * treated as a synchronous signal, like a fault and may become
+     * useless if that ceases to be true.
```
Comment (derekbruening) [inline suite/tests/linux/sigtrans.c]: Point at the issue about identifying when asynch.

Comment (egrimley-arm) [reply suite/tests/linux/sigtrans.c]: Done.

File: suite/tests/linux/sigtrans.c (hunk 14 above)
Comment (egrimley-arm) [reply suite/tests/linux/sigtrans.c]: That's not just aesthetics, either, because I wasn't checking for overflow when doubling `iters` there!

Done.

File: suite/tests/linux/sigtrans.c (hunk 13 above)
Comment (egrimley-arm) [reply suite/tests/linux/sigtrans.c]: Done.

File: suite/tests/linux/signal_translate.c (hunk 12 above)
Comment (egrimley-arm) [reply suite/tests/linux/signal_translate.c:1]: Done.

File: core/translate.c (hunk 10 above)
Comment (egrimley-arm) [reply core/translate.c]: Done.

File: core/translate.c (hunk 11 above)
Comment (egrimley-arm) [reply core/translate.c]: Done.

File: core/arch/aarchxx/mangle.c (hunk 6 above)
Comment (egrimley-arm) [reply core/arch/aarchxx/mangle.c]: Done.

File: core/translate.c (hunk 11 above)
Comment (egrimley-arm) [reply core/translate.c]: Since `interp.c` is not concerned with "epilogues" perhaps I should get `interp.c` to export a version of `d_r_emulate()` that emulates an `instr_t` rather than a PC value and get `emulate_epilogue()` in `translate.c` to use that function. Any instructions that are added in `interp.c` could be labelled as probably only required by `emulate_epilogue()` and therefore `XXX i#7707: Could perhaps be removed ...`. Does that sound about right?

Comment (derekbruening) [reply core/translate.c]: Yes, sounds good to me.

Comment (egrimley-arm) [reply core/translate.c]: Done.

**Comment by derekbruening** [comment]
Sorry for the delay, I was out all last week.
