### PR TITLE
i#5982: Fix memory leak in invariant checker

### LINKED ISSUE #5982: Memory leak detected in invariant_checker
```
=================================================================
==2259==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1888 byte(s) in 59 object(s) allocated from:
    #0 0x55efe0391eee in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
    #1 0x55efe04f1f5b in instr_set_num_opnds core/ir/instr_shared.c:579:37
    #2 0x55efe05576f1 in decode_common core/ir/x86/decode.c:2617:5
    #3 0x55efe03de70f in invariant_checker_t::parallel_shard_memref(void*, _memref_t const&) clients/drcachesim/tools/invariant_checker.cpp:356:30
    ...

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x55efe0391eee in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
    #1 0x55efe04f1f97 in instr_set_num_opnds core/ir/instr_shared.c:592:41
    #2 0x55efe05576f1 in decode_common core/ir/x86/decode.c:2617:5
    #3 0x55efe03de70f in invariant_checker_t::parallel_shard_memref(void*, _memref_t const&) clients/drcachesim/tools/invariant_checker.cpp:356:30
    ...

SUMMARY: AddressSanitizer: 1904 byte(s) leaked in 60 allocation(s).
```
This was caused by PR #5935

### PR DESCRIPTION
**Pull request by bete0**
Adds instr_autoclean_t to ensure the instance of instr_t is cleaned up when it is out of scope.

Fixes #5982

### CODE REVIEW

File: clients/drcachesim/tools/invariant_checker.cpp [hunk 1]
```diff
@@ -109,6 +109,9 @@ invariant_checker_t::parallel_shard_init(int shard_index, void *worker_data)
 bool
 invariant_checker_t::parallel_shard_exit(void *shard_data)
 {
+    per_shard_t *shard = reinterpret_cast<per_shard_t *>(shard_data);
```
Comment (abhinav92003) [inline clients/drcachesim/tools/invariant_checker.cpp:112]: As discussed offline, a better fix would be to use instr_autoclean_t (similar to instrlist_autoclean_t used elsewhere in our codebase) so that unique_ptr itself can do this cleanup.

**Review by abhinav92003 — CHANGES_REQUESTED** [review]

**Comment by bete0** [comment]
> Seeing this unrelated failure on some of the tests while the CI jobs try to create the build environment:
> 
> ```
> Err:28 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libboost-wave1.71.0 amd64 1.71.0-6ubuntu6
>   Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.252.75.106 80]
> Err:29 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 qemu-user amd64 1:4.2-3ubuntu6.25
>   Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.252.75.[106](https://github.com/DynamoRIO/dynamorio/actions/runs/4738157170/jobs/8415829145#step:5:107) 80]
> Err:30 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 qemu-user-binfmt amd64 1:4.2-3ubuntu6.25
>   Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.252.75.106 80]
> Err:31 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 vera++ amd64 1.2.1-2build8
>   Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.252.75.106 80]
> Err:24 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libstdc++-9-dev-armhf-cross all 9.4.0-1ubuntu1~20.04.1cross2
>   Could not connect to azure.archive.ubuntu.com:80 (52.252.75.106), connection timed out [IP: 52.252.75.106 80]
> Err:25 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 g++-9-arm-linux-gnueabihf amd64 9.4.0-1ubuntu1~20.04.1cross2
>   Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.252.75.106 80]
> Fetched 40.2 MB in 12min 46s (52.5 kB/s)
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/cross-toolchain-base/libc6-dev-armhf-cross_2.31-0ubuntu9.9cross1_all.deb  Connection failed [IP: 52.252.75.106 80]
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gcc-9-cross/libstdc++-9-dev-armhf-cross_9.4.0-1ubuntu1~20.04.1cross2_all.deb  Could not connect to azure.archive.ubuntu.com:80 (52.252.75.106), connection timed out [IP: 52.252.75.106 80]
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gcc-9-cross/g++-9-arm-linux-gnueabihf_9.4.0-1ubuntu1~20.04.1cross2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.252.75.106 80]
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/gcc-arm-linux-gnueabihf_9.3.0-1ubuntu2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.252.75.106 80]
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/g++-arm-linux-gnueabihf_9.3.0-1ubuntu2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.252.75.106 80]
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/b/boost1.71/libboost-wave1.71.0_1.71.0-6ubuntu6_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.252.75.106 80]
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/q/qemu/qemu-user_4.2-3ubuntu6.25_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.252.75.106 80]
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/q/qemu/qemu-user-binfmt_4.2-3ubuntu6.25_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.252.75.106 80]
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/v/vera++/vera++_1.2.1-2build8_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.252.75.106 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> Error: Process completed with exit code 100.
> ```

Also happening on PR #5965 so not something specific to this PR.

File: clients/drcachesim/tools/invariant_checker.cpp (hunk 1 above)
Comment (bete0) [reply clients/drcachesim/tools/invariant_checker.cpp]: Done. Added `instr_autoclean_t` struct. not sure if we should move it outside the invariant checker and make it available to be used elsewhere.

File: clients/drcachesim/tools/invariant_checker.cpp [hunk 2]
```diff
@@ -378,15 +378,16 @@ invariant_checker_t::parallel_shard_memref(void *shard_data, const memref_t &mem
         memref.instr.type == TRACE_TYPE_PREFETCH_INSTR ||
         memref.instr.type == TRACE_TYPE_INSTR_NO_FETCH) {
         bool expect_encoding = TESTANY(OFFLINE_FILE_TYPE_ENCODINGS, shard->file_type_);
-        std::unique_ptr<instr_t> cur_instr_decoded = nullptr;
+        std::unique_ptr<instr_autoclean_t> cur_instr_decoded(
+            new instr_autoclean_t(GLOBAL_DCONTEXT, nullptr));
```
Comment (abhinav92003) [inline clients/drcachesim/tools/invariant_checker.cpp:382]: This can remain nullptr like before, and assign a new instr_autoclean_t when needed.

File: clients/drcachesim/tools/invariant_checker.cpp [hunk 3]
```diff
@@ -378,15 +378,16 @@ invariant_checker_t::parallel_shard_memref(void *shard_data, const memref_t &mem
...
-                GLOBAL_DCONTEXT, const_cast<app_pc>(memref.instr.encoding),
-                reinterpret_cast<app_pc>(memref.instr.addr), cur_instr_decoded.get());
+            cur_instr_decoded.get()->data = instr_create(GLOBAL_DCONTEXT);
+            app_pc next_pc = decode_from_copy(GLOBAL_DCONTEXT,
+                                              const_cast<app_pc>(memref.instr.encoding),
+                                              reinterpret_cast<app_pc>(memref.instr.addr),
+                                              cur_instr_decoded.get()->data);
             if (next_pc == nullptr) {
-                instr_free(GLOBAL_DCONTEXT, cur_instr_decoded.get());
+                instr_free(GLOBAL_DCONTEXT, cur_instr_decoded.get()->data);
```
Comment (abhinav92003) [inline clients/drcachesim/tools/invariant_checker.cpp:390]: We shouldn't need to do an instr_free at all. The destructor of instr_autoclean_t should handle it automatically (which is the reason why we're adding instr_autoclean_t here).

File: clients/drcachesim/tools/invariant_checker.cpp [hunk 4]
```diff
@@ -478,7 +479,8 @@ invariant_checker_t::parallel_shard_memref(void *shard_data, const memref_t &mem
         shard->prev_instr_ = memref;
         if (shard->prev_instr_decoded_ != nullptr)
             instr_free(GLOBAL_DCONTEXT, shard->prev_instr_decoded_.get());
```
Comment (abhinav92003) [inline clients/drcachesim/tools/invariant_checker.cpp:481]: We are still missing an instr_free at the end for prev_instr_decoded_, which is what the leak was. Does this PR pass the asan check? I suspect it might not.

To fix this, we should make the prev_instr_decoded_ also a unique_ptr<instr_autoclean_t> so that prev_instr_decoded_ is cleaned-up automatically.

File: clients/drcachesim/tools/invariant_checker.cpp [hunk 5]
```diff
@@ -378,15 +378,16 @@ invariant_checker_t::parallel_shard_memref(void *shard_data, const memref_t &mem
...
-            cur_instr_decoded.reset(new instr_t);
-            instr_init(GLOBAL_DCONTEXT, cur_instr_decoded.get());
-            app_pc next_pc = decode_from_copy(
-                GLOBAL_DCONTEXT, const_cast<app_pc>(memref.instr.encoding),
-                reinterpret_cast<app_pc>(memref.instr.addr), cur_instr_decoded.get());
+            cur_instr_decoded.get()->data = instr_create(GLOBAL_DCONTEXT);
+            app_pc next_pc = decode_from_copy(GLOBAL_DCONTEXT,
+                                              const_cast<app_pc>(memref.instr.encoding),
+                                              reinterpret_cast<app_pc>(memref.instr.addr),
+                                              cur_instr_decoded.get()->data);
```
Comment (abhinav92003) [inline clients/drcachesim/tools/invariant_checker.cpp:388]: The .get() can be dropped if we're sure that the unique_ptr object is not nullptr (https://en.cppreference.com/w/cpp/memory/unique_ptr/operator*).

**Review by abhinav92003 — CHANGES_REQUESTED** [review]

File: clients/drcachesim/tools/invariant_checker.cpp (hunk 2 above)
Comment (bete0) [reply clients/drcachesim/tools/invariant_checker.cpp]: Done.

File: clients/drcachesim/tools/invariant_checker.cpp (hunk 3 above)
Comment (bete0) [reply clients/drcachesim/tools/invariant_checker.cpp]: Done.

File: clients/drcachesim/tools/invariant_checker.h [hunk 6]
```diff
@@ -38,13 +38,41 @@
...
+            exit(1);
+        }
+#endif
+        if (data != nullptr) {
+            instr_destroy(drcontext, data);
+            data = nullptr;
+        }
+    }
+    void *drcontext = nullptr;
+    instr_t *data = nullptr;
```
[the remark this answers is not in the document]
Comment (bete0) [reply clients/drcachesim/tools/invariant_checker.h:73]: Done. Moved instr_create in the constructor.

File: clients/drcachesim/tools/invariant_checker.cpp (hunk 4 above)
Comment (bete0) [reply clients/drcachesim/tools/invariant_checker.cpp]: Done.

File: clients/drcachesim/tools/invariant_checker.cpp (hunk 5 above)
Comment (bete0) [reply clients/drcachesim/tools/invariant_checker.cpp]: Done.

**Comment by bete0** [comment]
run arm tests

File: clients/drcachesim/tools/invariant_checker.cpp [hunk 7]
```diff
@@ -735,9 +732,9 @@ invariant_checker_t::check_for_pc_discontinuity(
                 }
             } else if (cur_instr_decoded != nullptr &&
                        shard->prev_instr_decoded_ != nullptr &&
-                       instr_is_syscall(cur_instr_decoded.get()) &&
+                       instr_is_syscall(cur_instr_decoded.get()->data) &&
```
Comment (abhinav92003) [inline clients/drcachesim/tools/invariant_checker.cpp:735]: The .get() can be dropped.

File: clients/drcachesim/tools/invariant_checker.h [hunk 8]
```diff
@@ -38,13 +38,41 @@
...
+struct instr_autoclean_t {
+public:
+    instr_autoclean_t(void *drcontext)
+        : drcontext(drcontext)
+    {
+        data = instr_create(drcontext);
+    }
+    ~instr_autoclean_t()
+    {
+#ifdef DEBUG
```
Comment (abhinav92003) [inline clients/drcachesim/tools/invariant_checker.h:61]: This doesn't need to be a debug-only check. Also it'll be more useful in the constructor rather than here.

File: clients/drcachesim/tools/invariant_checker.cpp [hunk 9]
```diff
@@ -378,15 +378,13 @@ invariant_checker_t::parallel_shard_memref(void *shard_data, const memref_t &mem
         memref.instr.type == TRACE_TYPE_PREFETCH_INSTR ||
```
Comment (abhinav92003) [inline clients/drcachesim/tools/invariant_checker.cpp:378]: Before submitting, please confirm that asan passes with these changes.

**Review by abhinav92003 — APPROVED** [review]

File: clients/drcachesim/tools/invariant_checker.h (hunk 8 above)
Comment (bete0) [reply clients/drcachesim/tools/invariant_checker.h]: Done.

File: clients/drcachesim/tools/invariant_checker.cpp (hunk 9 above)
Comment (bete0) [reply clients/drcachesim/tools/invariant_checker.cpp:378]: Yes, I have confirmed that asan passes with these changes.

**Comment by bete0** [comment]
run arm tests
