### PR TITLE
i#6529: Check end of section headers mapped

### LINKED ISSUE #6529: CRASH drwrap-test: rseq_process_module incorrectly thinks section headers are mapped in
On my workstation there may have been a recent compiler update or other change which caused client.drwrap-test to start failing.  It crashes during rseq processing:

```
$ bin64/drrun -c suite/tests/bin/libclient.drwrap-test.dll.so "--" suite/tests/bin/client.drwrap-test dr/git/build_x64_dbg_tests/suite/tests/bin/libclient.drwrap-test.appdll.so

(gdb) bt
#0  0x00007ffff7c19e93 in d_r_strcmp (left=0x7ffff83636c3 <error: Cannot access memory at address 0x7ffff83636c3>, right=0x7ffff7dcf96e "__rseq_cs_ptr_array")
    at dr/git/src/core/string.c:212
#1  0x00007ffff7d2e647 in rseq_process_elf_sections (ma=0x7ffdb3aea320, at_map=true, sec_hdr_start=0x7ffff7f88ad0, strtab=0x7ffff7f836c0 "", load_offs=140737353621504)
    at dr/git/src/core/unix/rseq_linux.c:499
#2  0x00007ffff7d2edfb in rseq_process_module (ma=0x7ffdb3aea320, at_map=true, saw_glibc_rseq_reg=false) at dr/git/src/core/unix/rseq_linux.c:626
#3  0x00007ffff7d2f991 in rseq_module_init (ma=0x7ffdb3aea320, at_map=true) at dr/git/src/core/unix/rseq_linux.c:837
#4  0x00007ffff7d12a3a in os_module_area_init (ma=0x7ffdb3aea320, base=0x7ffff7f82000 "\177ELF\002\001\001", view_size=28672, at_map=true, 
    filepath=0x7ffdb3a3cef0 "dr/git/build_x64_dbg_tests/suite/tests/bin/libclient.drwrap-test.appdll.so", inode=26215504, which=ACCT_VMAREAS)
    at dr/git/src/core/unix/module.c:203
#5  0x00007ffff7bceaf2 in module_area_create (base=0x7ffff7f82000 "\177ELF\002\001\001", view_size=28672, at_map=true, 
    filepath=0x7ffdb3a3cef0 "dr/git/build_x64_dbg_tests/suite/tests/bin/libclient.drwrap-test.appdll.so", inode=26215504)
    at dr/git/src/core/module_list.c:126
(gdb) p/x *sec_hdr
$3 = {
  sh_name = 0x3e0003,
  sh_type = 0x1,
  sh_flags = 0x1a360,
  sh_addr = 0x40,
  sh_offset = 0x331e8,
  sh_size = 0x38004000000000,
  sh_link = 0x400009,
  sh_info = 0x150016,
  sh_addralign = 0x400000001,
  sh_entsize = 0x0
}
(gdb) p/x *elf_hdr
$8 = {
  e_ident = {0x7f, 0x45, 0x4c, 0x46, 0x2, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
  e_type = 0x3,
  e_machine = 0x3e,
  e_version = 0x1,
  e_entry = 0x0,
  e_phoff = 0x40,
  e_shoff = 0x6ad0,
  e_flags = 0x0,
  e_ehsize = 0x40,
  e_phentsize = 0x38,
  e_phnum = 0x9,
  e_shentsize = 0x40,
  e_shnum = 0x1e,
  e_shstrndx = 0x1d
}
```

Looks like the section headers at +0x6ad0 are not mapped in:
```
$ readelf -l dr/git/build_x64_dbg_tests/suite/tests/bin/libclient.drwrap-test.appdll.so

Elf file type is DYN (Shared object file)
Entry point 0x0
There are 9 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000000011d0 0x00000000000011d0  R      0x1000
  LOAD           0x0000000000002000 0x0000000000002000 0x0000000000002000
                 0x0000000000001bd1 0x0000000000001bd1  R E    0x1000
  LOAD           0x0000000000004000 0x0000000000004000 0x0000000000004000
                 0x0000000000000dc8 0x0000000000000dc8  R      0x1000
  LOAD           0x0000000000005db0 0x0000000000005db0 0x0000000000005db0
                 0x00000000000003b0 0x00000000000004b0  RW     0x1000
  DYNAMIC        0x0000000000005dc8 0x0000000000005dc8 0x0000000000005dc8
                 0x00000000000001e0 0x00000000000001e0  RW     0x8
  NOTE           0x0000000000000238 0x0000000000000238 0x0000000000000238
                 0x0000000000000024 0x0000000000000024  R      0x4
  GNU_EH_FRAME   0x0000000000004434 0x0000000000004434 0x0000000000004434
                 0x00000000000001ec 0x00000000000001ec  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x0000000000005db0 0x0000000000005db0 0x0000000000005db0
                 0x0000000000000250 0x0000000000000250  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00     .note.gnu.build-id .hash .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt 
   01     .init .plt .plt.got .text .fini 
   02     .rodata .eh_frame_hdr .eh_frame 
   03     .init_array .fini_array .dynamic .got .got.plt .data .bss 
   04     .dynamic 
   05     .note.gnu.build-id 
   06     .eh_frame_hdr 
   07     
   08     .init_array .fini_array .dynamic .got 
```

But we think they are b/c 0x6ad0 is under the mem size:
```
(gdb) p/x ma->end - ( elf_hdr->e_shoff + ma->start)
$10 = 0x530
(gdb) p/x 0x5db0+0x3b0
$11 = 0x6160
(gdb) p/x ma->end - ma->start
$12 = 0x7000
#+end_example
But the 64 section headers don't fit there:
#+begin_example
(gdb) p/x elf_hdr->e_shoff + ma->start + elf_hdr->e_shnum*64
$14 = 0x7ffff7f89250
(gdb) p/x ma->end - ( elf_hdr->e_shoff + ma->start + elf_hdr->e_shnum*64)
$15 = 0xfffffffffffffdb0
```

Still doesn't seem the best check b/c there could be room due to page
aligning and they still may not be mapped in.  We really should walk the
segments.  But a quick simple fix for this case and probably most cases is
to ensure the endpoint of the section headers fits.

### PR DESCRIPTION
**Pull request by derekbruening**
Updates the rseq_process_module() check for the section headers being in the mapped region to check the endpoint instead of the start point.

Tested locally: now client.drwrap-test passes when it failed with the toolchain on my local machine.

Fixes #6529

### CODE REVIEW

**Comment by derekbruening** [comment]
Failure is the new client.detach_test which seems to be flaky.  I filed #6536.

File: core/unix/rseq_linux.c [hunk 1]
```diff
@@ -581,7 +581,8 @@ rseq_process_module(module_area_t *ma, bool at_map, bool saw_glibc_rseq_reg)
     ELF_SECTION_HEADER_TYPE *sec_hdr = NULL;
     char *strtab;
     ssize_t load_offs = ma->start - ma->os_data.base_address;
-    if (at_map && elf_hdr->e_shoff + ma->start < ma->end) {
+    if (at_map &&
+        elf_hdr->e_shoff + elf_hdr->e_shnum * sizeof(*sec_hdr) + ma->start < ma->end) {
```
Comment (abhinav92003) [inline core/unix/rseq_linux.c:585]: Use e_shentsize instead of sizeof?

**Review by abhinav92003 — APPROVED** [review]

File: core/unix/rseq_linux.c (hunk 1 above)
Comment (abhinav92003) [reply core/unix/rseq_linux.c:585]: From docx:

```
The product of e_shentsize and e_shnum gives the section header table's size in bytes
```

Comment (derekbruening) [reply core/unix/rseq_linux.c:585]: Yes that seems better (note that the assert above would fire if the two were different).  Done.

**Comment by derekbruening** [comment]
x64 failure is attach_test flake #6452
