### PR TITLE
i#4237: Align redirected malloc to double-ptr-sized

### LINKED ISSUE #4237: DynamoRIO wrapped malloc should guarantee 16-byte heap alignment
MOVDQA requires 16-byte memory alignment. DynamoRIO malloc does not align by 16 bytes. Unaligned memory access causes a crash. More information can be found in [Google Groups](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/dynamorio-users/BlPaJytSH4o).

### PR DESCRIPTION
**Pull request by derekbruening**
Provides a guaranteed double-pointer-sized alignment for redirected
malloc, to match system allocators and avoid breaking private library
assumptions.

Adds a test to client.alloc.

Fixes #4237

### CODE REVIEW

File: core/loader_shared.c [hunk 1]
```diff
@@ -926,27 +926,56 @@ loader_allow_unsafe_static_behavior(void)
...
  * is also not guaranteed-reachable.
  */
 void *
 redirect_malloc(size_t size)
 {
     void *mem;
-    ASSERT(sizeof(size_t) >= HEAP_ALIGNMENT);
-    size += sizeof(size_t);
-    mem = global_heap_alloc(size HEAPACCT(ACCT_LIBDUP));
+    size_t alloc_size = size + sizeof(size_t) + STANDARD_HEAP_ALIGNMENT - HEAP_ALIGNMENT;
```
Comment (johnfxgalea) [inline core/loader_shared.c:950]: It is worth point out that alloc_size directly acts as the header here

File: core/win32/drwinapi/ntdll_redir.c [hunk 2]
```diff
@@ -299,26 +299,26 @@ RtlAllocateHeap(HANDLE heap, ULONG flags, SIZE_T size);
 void *
 wrapped_dr_alloc(ULONG flags, SIZE_T size)
 {
-    byte *mem;
-    ASSERT(sizeof(size_t) >= HEAP_ALIGNMENT);
-    size += sizeof(size_t);
-    mem = global_heap_alloc(size HEAPACCT(ACCT_LIBDUP));
+    /* HeapAlloc returns 16-byte-aligned for 64-bit and 8-byte-aligned for 32-bit.
```
Comment (johnfxgalea) [inline core/win32/drwinapi/ntdll_redir.c:302]: Just for my understanding, why wasn't redirect_malloc called prior?

Comment (derekbruening) [reply core/win32/drwinapi/ntdll_redir.c:302]: Prior to this PR redirect_malloc was only used on UNIX, and a parallel implementation of adding a size field was used here on Windows, just for historical reasons.  Somehow we never saw any problems from the smaller alignment.  Now that it's more complex to add a layer around DR's allocator I made them share the same impl in redirect_malloc.

Comment (derekbruening) [reply core/win32/drwinapi/ntdll_redir.c:302]: "just for historical reasons": I think they each evolved separately and just nobody ever took a step to share the code (it was pretty simple code before).

**Comment by derekbruening** [comment]
The unit_tests failure: have to add a function to return the requested size for Windows size queries.
