### PR TITLE
i#731,i#3271: Keep IR cti+copied bits valid and re-relativized

### LINKED ISSUE #731: auto-re-relativize level 1-3 ctis when encoding
_From [rnk@google.com](https://code.google.com/u/rnk@google.com/) on April 12, 2012 13:50:34_

This came up on our users mailing list (titled "enabling fixups of relatives jmps "), but we didn't file a bug about it: https://groups.google.com/forum/#!topic/dynamorio-users/lGQralbJg_U Our response:
"""
Force a re-encode: instr_set_raw_bits_valid(instr, false).

Note that when not in standalone mode all branches are mangled and thus this is never an issue.
"""

We need to at least document this somewhere.  The better solution is to add a check in our encoder for if the instruction takes a relative offset and assume that those bits are invalid.  99&#37; of the time users will want to re-encode decoded instructions to a different pc, so we can't use the current offset.

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=731_

### LINKED ISSUE #3271: decode_from_copy should keep its raw bits valid (for non-ctis at least)
Today, decode_from_copy always marks the raw bits invalid, with a comment saying it's avoiding an invalid relative target.  But that's mostly a stale worry b/c today encode properly re-relativizes rip-rel and cti-short instrs.  It's true that a general cti is not re-relativized there but we could rule that out inside decode_from_copy, or go and implement #731.

### LINKED ISSUE #4017: drcachesim offline trace has wrong size for 2-byte nop
We recently hit a case where the x86 nop `0x66 0x90` is recorded into an offline trace and the post-processing stores 1 as its instruction fetch size, instead of 2.  I tracked it down to #3271: raw2trace uses decode_from_copy() and decodes `0x66 0x90` into an OP_nop instruction, but because of the re-relativization worries decode_from_copy() marks the raw bits as invalid.  Thus, raw2trace's call to instr_length() does a re-encode which simply encodes an OP_nop, resulting in 0x90 and a length of 1.  Xref #3339 and other issues: another case of an encoding feature the IR does not store.

Rather than splitting the opcode or storing sthg about a prefix (we do have a requires-prefix feature -- but it's at the opcode level) I'm thinking we should just fix #3271, and #731 while we're at it.  That then leaves any other issues of keeping the `0x66` as something much lower priority along the lines of #3339.

### PR DESCRIPTION
**Pull request by derekbruening**
Adds rip-relative information tracking at IR levels 1-3 for
instruction references on x86, extending the existing tracking for
data references.

Adds decode_sizeof_ex() and instr_get_rel_data_or_instr_target() to
support rip-relative displacement and target handling.

Changes decode_from_copy() to preserve raw bits for all instructions,
eliminating problems where untracked encoding features are lost such
as in #4017.

Documents the changes and describes how to avoid the new behavior.
Does just that for intra-sequence cti's in the rseq native code copy.

Adds test cases to api.ir.

Implementing the same thing for AArchXX is left unimplemented, tracked
by i#4016.

Issue: #731, #3271, #3339, #4016, #4017
Fixes #731
Fixes #3271
Fixes #4017

### CODE REVIEW

**Comment by derekbruening** [comment]
(Making sure the CI is green before requesting review since this has potential to break things.)

**Comment by derekbruening** [comment]
All issues resolved.  PTAL.  See https://github.com/DynamoRIO/dynamorio/issues/4017#issuecomment-574782637 for logic behind tackling the full #731.

File: core/arch/x86/decode.c [hunk 1]
```diff
@@ -2654,27 +2657,19 @@ decode_common(dcontext_t *dcontext, byte *pc, byte *orig_pc, instr_t *instr)
...
-            instr_set_rip_rel_pos(instr, (int)(di.disp_abs - di.start_pc));
-        }
-#endif
+    /* We set raw bits AFTER setting all srcs and dsts b/c setting
+     * a src or dst marks instr as having invalid raw bits.
+     */
+    IF_X64(ASSERT(CHECK_TRUNCATE_TYPE_uint(next_pc - pc)));
+    instr_set_raw_bits(instr, pc, (uint)(next_pc - pc));
+    if (di.disp_abs > di.start_pc) {
+        CLIENT_ASSERT(di.disp_abs > di.start_pc, "decode: internal rip-rel error");
```
Comment (Carrotman42) [inline core/arch/x86/decode.c]: The expression inside the 'if' is the same as this assert, so the assert will never be false afaict. Either take out the assert, or perhaps you meant for the 'if' to be different?

File: core/arch/x86/encode.c [hunk 2]
```diff
@@ -2722,14 +2717,20 @@ copy_and_re_relativize_raw_instr(dcontext_t *dcontext, instr_t *instr, byte *dst
...
-            /* suffix byte */
-            memcpy(dst_pc + 4, instr->bytes + rip_rel_pos + 4,
-                   instr->length - (rip_rel_pos + 4));
+        /* We only support non-4-byte rip-rel disps for 1-byte instr-final (jcc_short). */
+        if (rip_rel_pos + 1 == instr->length) {
+            ASSERT(CHECK_TRUNCATE_TYPE_sbyte(new_offs));
+            *((char *)dst_pc) = (char)new_offs;
+        } else {
+            ASSERT(rip_rel_pos + 4 <= instr->length);
+            *((int *)dst_pc) = (int)new_offs;
```
Comment (Carrotman42) [inline core/arch/x86/encode.c]: Should we assert that this truncates to a singed int? I imagine 'int' is not always pointer sized, but I don't know for sure.

File: suite/tests/api/ir_x86.c [hunk 3]
```diff
@@ -2168,6 +2168,97 @@ test_reg_exact_reads(void *dc)
     instr_destroy(dc, instr);
 }
 
+static void
+test_re_relativization_disp32_opc16(void *dcontext, byte opc1, byte opc2)
+{
+    byte buf_dec_enc[] = { opc1, opc2,
+                           /* disp32 of 0 which targets the next PC. */
+                           0x00, 0x00, 0x00, 0x00,
+                           /* We encode here. */ 0x90, 0x90, 0x90, 0x90, 0x90, 0x90 };
```
Comment (Carrotman42) [inline suite/tests/api/ir_x86.c]: I'm guessing this line-joining is due to clang-format? Consider adding whitespace after the "We encode here." comment so that clang-format decides to wrap like the previous line is wrapped.

(alternatively we could use a line-comment, but that's against the existing style)

File: core/arch/x86/decode.c (hunk 1 above)
Comment (derekbruening) [reply core/arch/x86/decode.c]: Removed.

File: suite/tests/api/ir_x86.c (hunk 3 above)
Comment (derekbruening) [reply suite/tests/api/ir_x86.c]: Newline successfully added and preserved by clang-format.

File: core/arch/x86/encode.c (hunk 2 above)
Comment (derekbruening) [reply core/arch/x86/encode.c]: Assert added.  int is not pointer-sized for 64-bit gcc/clang/cl.

**Comment by derekbruening** [comment]
PTAL.  Sorry, I pre-emptively merged in upstream to deal w/ a conflict, so the "changes since last review" button may not be a good view: but selecting just the final commit from the commit selection dropdown on the diff page will show the review changes.
