### PR TITLE
i#7293 print crash: Increase privload tcb size to fix crashes

### LINKED ISSUE #7293: CRASH calling glibc fprintf from a client on Ubuntu22
For #7270 we're getting all our tests to pass on Ubuntu22.
Some tests hit:

```
203: <Application /home/derek/dr/git/build_x64_dbg_tests/suite/tests/bin/client.file_io (108384).  Tool internal crash at PC 0x000079973b6909ff.  Please report this at your tool's issue tracker.  Program aborted.
203: Received SIGSEGV at pc 0x000079973b6909ff in thread 108384
203: Base: 0x000079973be00000
203: Registers:eax=0x0000000000000000 ebx=0xf49998db0aa753ff ecx=0x00007994f7aa3700 edx=0x0000000000000180
203: 	esi=0x00000000000000c2 edi=0x00007fff9d5798f0 esp=0x00007fff9d579518 ebp=0x00007fff9d5798f0
203: 	r8 =0x0000000000000004 r9 =0x0000000000000001 r10=0x0000000000000180 r11=0x0000000000000246
203: 	r12=0x00000000000000c2 r13=0x00007fff9d5798f0 r14=0x000079973b7dcc00 r15=0x0000000010e36f3b
203: 	eflags=0x0000000000010246
```

More details:
```
$ bin64/drrun -c api/bin/libmemtrace_simple_test.so -log_to_stderr -- suite/tests/bin/allasm_repstr

(gdb) bt
#0  0x00007ffdf70909ff in __GI___pthread_enable_asynccancel () at ./nptl/cancellation.c:34
#1  0x00007ffdf71148a7 in __GI___libc_write (nbytes=61, buf=0x72005140, fd=2) at ../sysdeps/unix/sysv/linux/write.c:26
#2  __GI___libc_write (fd=2, buf=0x72005140, nbytes=61) at ../sysdeps/unix/sysv/linux/write.c:24
#3  0x00007ffdf708aeed in _IO_new_file_write (f=0x7ffdf721b6a0, data=0x72005140, n=61) at ./libio/fileops.c:1180
#4  0x00007ffdf708b7d0 in new_do_write (to_do=<optimized out>, data=0x72005140 "Format: <data address>: <data size>, <(r)ead/(w)rite/opcode>\n", fp=0x7ffdf721b6a0)
    at ./libio/libioP.h:947
#5  _IO_new_file_xsputn (n=61, data=<optimized out>, f=<optimized out>) at ./libio/fileops.c:1254
#6  _IO_new_file_xsputn (f=0x7ffdf721b6a0, data=<optimized out>, n=61) at ./libio/fileops.c:1196
#7  0x00007ffdf707ffd7 in __GI__IO_fwrite (buf=0x72005140, size=1, count=61, fp=0x7ffdf721b6a0) at ./libio/libioP.h:947
#8  0x0000000073009ab6 in drmgr_thread_init_event (drcontext=0x7ffdf7899080) at /home/derek/dr/git/src/ext/drmgr/drmgr.c:2639
#9  0x00007ffff7c00f02 in instrument_thread_init (dcontext=0x7ffdf7899080, client_thread=false, valid_mc=false) at /home/derek/dr/git/src/core/lib/instrument.c:1506
#10 0x00007ffff7bff5ca in instrument_init () at /home/derek/dr/git/src/core/lib/instrument.c:818
#11 0x00007ffff7a6135d in dynamorio_app_init_part_two_finalize () at /home/derek/dr/git/src/core/dynamo.c:716
#12 0x00007ffff7d24f3f in privload_early_inject (sp=0x7fffffffe360, old_libdr_base=0x0, old_libdr_size=1) at /home/derek/dr/git/src/core/unix/loader.c:2379
(gdb) disas
Dump of assembler code for function __GI___pthread_enable_asynccancel:
   0x00007ffdf70909f0 <+0>:	endbr64
   0x00007ffdf70909f4 <+4>:	mov    %fs:0x10,%rcx
   0x00007ffdf70909fd <+13>:	xor    %eax,%eax
=> 0x00007ffdf70909ff <+15>:	mov    %fs:0x972,%al
   0x00007ffdf7090a07 <+23>:	movzbl %al,%eax
   0x00007ffdf7090a0a <+26>:	movb   $0x1,%fs:0x972
   0x00007ffdf7090a13 <+35>:	mov    %fs:0x308,%edx
(gdb) p $_siginfo
$4 = {si_signo = 11, si_errno = 0, si_code = 2, _sifields = {_pad = {-141934478, 32765, 0 <repeats 26 times>}, _kill = {si_pid = -141934478, si_uid = 32765}, _timer = {
      si_tid = -141934478, si_overrun = 32765, si_sigval = {sival_int = 0, sival_ptr = 0x0}}, _rt = {si_pid = -141934478, si_uid = 32765, si_sigval = {sival_int = 0,
        sival_ptr = 0x0}}, _sigchld = {si_pid = -141934478, si_uid = 32765, si_status = 0, si_utime = 0, si_stime = 0}, _sigfault = {si_addr = 0x7ffdf78a4072, _addr_lsb = 0,
      _addr_bnd = {_lower = 0x0, _upper = 0x0}}, _sigpoll = {si_band = 140728756486258, si_fd = 0}, _sigsys = {_call_addr = 0x7ffdf78a4072, _syscall = 0, _arch = 0}}}

7ffdf78a2000-7ffdf78a4000 rw-p 00000000 00:00 0
7ffdf78a4000-7ffdf78a6000 ---p 00000000 00:00 0
```

There's a frame missing: whose thread init is it?
5 thread init events: drx, drmgr, drreg, drx_scatter_gather, memtrace_simple.
It's the fprintf line to data->logf which is stderr in memtrace_simple's thread init event.
Crashes without -log_to_stderr too.

Private TLS too small?  fs:0x972 is 0x72 off end of page.
tcb_size was 0x900.  Raising to 0x1000 fixes it!

This fixes the following tests which failed on Ubuntu 22:
+ client.destructor
+ client.file_io
+ code_api,satisfy_w_xor_x|client.file_io
+ sample.memtrace_simple_repstr
+ sample.memtrace_simple_repstr
+ sample.memtrace_simple
+ sample.memval_simple
+ sample.memval_simple_scattergather
+ sample.instrace_simple
+ sample.callstack
+ sample.memtrace_x86_text
+ sample.instrace_x86_text
+ tool.drcachesim.phys_SUDO
+ tool.drcacheoff.phys_SUDO
+ tool.drcacheoff.phys_nopriv

This fixes a crash in this test, but it still fails due to the
internal isa mode error hit in other Ubuntu22 tests (not yet filed
separately: currently under #7270):
+ tool.drcachesim.phys-threads_SUDO

### PR DESCRIPTION
**Pull request by derekbruening**
Increases the private TLS "tcb_size" from 0x970 to 0x1000, which fixes crashes in glibc code like this with an offset larger than 0x970 on a call to fprintf by a client on Ubuntu 22:

```
(gdb) bt
    at ./libio/libioP.h:947
<fprintf from client here>

=> 0x00007ffdf70909ff <+15>:	mov    %fs:0x972,%al

_sigfault = {si_addr = 0x7ffdf78a4072

7ffdf78a2000-7ffdf78a4000 rw-p 00000000 00:00 0
7ffdf78a4000-7ffdf78a6000 ---p 00000000 00:00 0
```

This fixes the following tests which failed on Ubuntu 22:
+ client.destructor
+ client.file_io
+ code_api,satisfy_w_xor_x|client.file_io
+ sample.memtrace_simple_repstr
+ sample.memtrace_simple_repstr
+ sample.memtrace_simple
+ sample.memval_simple
+ sample.memval_simple_scattergather
+ sample.instrace_simple
+ sample.callstack
+ sample.memtrace_x86_text
+ sample.instrace_x86_text
+ tool.drcachesim.phys_SUDO
+ tool.drcacheoff.phys_SUDO
+ tool.drcacheoff.phys_nopriv

This fixes a crash in this test, but it still fails due to the internal isa mode error hit in other Ubuntu22 tests (not yet filed separately: currently under #7270):
+ tool.drcachesim.phys-threads_SUDO

Issue: #7270, #7293
Fixes #7293

### CODE REVIEW

File: core/unix/loader_linux.c [hunk 1]
```diff
@@ -133,9 +133,11 @@ static size_t client_tls_size = 2 * 4096;
  * The "lea -0x900(%rax,%rbx,1),%rbx" instruction computes the thread pointer to
  * install.  The allocator used by the loader has no headers, so we don't have a
  * good way to guess how big this allocation was.  Instead we use this estimate.
+ * For Ubuntu22 glibc 2.38, the size is 0x9c0; we use 0x1000 to cover future
+ * expansion.
  */
 /* On A32, the pthread is put before tcbhead instead tcbhead being part of pthread */
-static size_t tcb_size = IF_X64_ELSE(0x900, 0x490);
+static size_t tcb_size = IF_X64_ELSE(0x1000, 0x490);
```
Comment (abhinav92003) [inline core/unix/loader_linux.c:140]: nit: s/tcb_size/tcb_size_maybe/

**Review by abhinav92003 — APPROVED** [review]

File: core/unix/loader_linux.c (hunk 1 above)
Comment (derekbruening) [reply core/unix/loader_linux.c:140]: Went with tcb_size_estimate.
