### PR TITLE
i#2681: AArch64 encoder: Consult check_reachable argument.

### LINKED ISSUE #2681: ASSERT: aarch64 instr_encode_arch() fails to honor check_reachable param
This was raised here: https://groups.google.com/forum/#!topic/DynamoRIO-Users/lqxQpY6GllM

Pasting from there:

This looks like a bug in the aarch64 encoder when encoding solely to print, based on looking at your log file.  That's why it's debug-only.  I think the bug is that the aarch64 encoder ignores the parameter "check_reachable" which is set to false for disassembly.  Branch reachability is supposed to be ignored since this is not a real encoding but just a disassembly.

It's not clear why A) it thinks it needs to encode at all, since it's an L3 instr; and B) why this doesn't happen on the prior 2 prints: presumably b/c they realize they don't need to encode.  Probably the final branch is tweaked before the "before mangling" print or sthg and it shows up as needing encoding despite printing L3.

Details from the log:

```
before instrumentation:
TAG  0x0000007f9bd10fc0
 +0    L3                      910003e0   add    %sp $0x0000 lsl $0x00 -> %x0
 +4    L3                      94000cac   bl     $0x0000007f9bd14274
END 0x0000007f9bd10fc0

CLEANCALL: insert clean call to 0x000000000003b690

after instrumentation:
TAG  0x0000007f9bd10fc0
... 
 +436  L3                      910003e0   add    %sp $0x0000 lsl $0x00 -> %x0
 +440  L3                      94000cac   bl     $0x0000007f9bd14274
END 0x0000007f9bd10fc0

bb ilist before mangling:
TAG  0x0000007f9bd10fc0
 ...
 +436  L3                      910003e0   add    %sp $0x0000 lsl $0x00 -> %x0
 +440  L3                      94000cac   bl     $0x0000007f9bd14274
SYSLOG_ERROR: Application ... (15543).  Internal Error: DynamoRIO debug check failure: Not implemented @.../core/arch/aarch64/codec.c:2603 (0)
```

### PR DESCRIPTION
**Pull request by egrimley**
A check_reachable member is added to the previously unused
decode_info_t struct and the encoder functions acquire an extra
argument which is a pointer to this struct. The functions that
encode branches, ADR and ADRP refer to this and accept unreachable
targets when check_reachable is false, setting the offset to zero
in this case. Targets are still required to be aligned.

Fixes #2681

Change-Id: I4575a396bf13ee9fd27e395b10957eed294342ce

### CODE REVIEW

File: core/arch/aarch64/codec.c [hunk 1]
```diff
@@ -190,10 +191,16 @@ encode_pc_off(OUT uint *poff, int bits, byte *pc, instr_t *instr, opnd_t opnd)
...
-    if (TEST(~((range - 1) << 2), off + (range << 1)))
-        return false;
-    *poff = off >> 2 & (range - 1);
-    return true;
+    if (!TEST(~((range - 1) << 2), off + (range << 1))) {
+        *poff = off >> 2 & (range - 1);
+        return true;
+    }
+    /* If !di->check_reachable we still require correct alignment. */
+    if (!di->check_reachable && !TEST(3, off)) {
```
Comment (derekbruening) [inline core/arch/aarch64/codec.c]: Use the ALIGNED() macro to test alignment

File: core/arch/aarch64/codec.c [hunk 2]
```diff
@@ -445,10 +452,16 @@ encode_opnd_adr_page(int scale, byte *pc, opnd_t opnd, OUT uint *enc_out,
...
-    if (!try_encode_int(&bits, 21, scale, offset))
-        return false;
-    *enc_out = (bits & 3) << 29 | (bits & 0x1ffffc) << 3;
-    return true;
+    if (try_encode_int(&bits, 21, scale, offset)) {
+        *enc_out = (bits & 3) << 29 | (bits & 0x1ffffc) << 3;
+        return true;
+    }
+    /* If !di->check_reachable we still require correct alignment. */
+    if (!di->check_reachable && !TEST((1ULL << scale) - 1, offset)) {
```
Comment (derekbruening) [inline core/arch/aarch64/codec.c]: Use the ALIGNED() macro to test alignment

**Comment by derekbruening** [comment]
Mac failure is client.timer #2003
