### PR TITLE
i#6713: Remove same-input-same-start cpu_schedule entries

### LINKED ISSUE #6713: Replaying a drmemtrace as-traced hits problems with same-start schedule entries
Running record_filter in as-traced mode after fixing #6712 still fails on an app based on threadsig:
```
[scheduler] Output #4 is as-traced CPU #2
<...>
[scheduler] [scheduler] next_record[6]: from 22 @1710811037678343: WARNING: next_record[4]: input 8 wants instr #0 but it is already at #86
[scheduler] [scheduler] next_record[4]: advancing to input 8 instr #0
next_record[4]: replay segment in=8 (@86) type=0 start=0 end=86
next_record[4]: from 8 @1710811037656128: [scheduler] type=22 size=0 addr=0x13bf3b
next_record[4]: from 8 @1710811037679753: type=24 size=0 addr=0x13ae00
next_record[4]: from 8 @1710811037680005: type=47 size=7 addr=0xc749
next_record[4]: waiting for input 9 instr #8931425
[scheduler] next_record[4]: replay segment in=8 (@86) type=0 start=0 end=86
[scheduler] next_record[4]: waiting for input 9 instr #8931425
next_record[4]: replay segment in=8 (@86) type=0 start=0 end=86
<...>
[scheduler] [scheduler] next_record[4]: replay segment in=8 (@86) type=0 start=0 end=86
[scheduler] next_record[4]: waiting for input 9 instr #8931425
[scheduler] [scheduler] next_record[4]: replay segment in=8 (@86) type=0 start=0 end=86
[scheduler] [scheduler] next_record[4]: advancing to input 9 instr #8931425
[scheduler] next_record[4]: replay segment in=9 (@8931425) type=0 start=8931425 end=8937416
[scheduler] next_record[4]: from 9 @1710811038148801: type=22 size=0 addr=0x13ae00
[scheduler] next_record[4]: from 9 @1710811038201658: type=24 size=0 addr=0x13ae00
[scheduler] [scheduler] [scheduler] next_record[11]: from 15 @1710811038201729: next_record[4]: from 9 @1710811038201740: type=10 size=4 addr=0x563642d82627
[scheduler] next_record[11]: from 15 @1710811038201830: Encoding size 7 != instr size 4 for PC 0x563642d82627
```

The warning is b/c of what looks like bad entries in the file?
```
[scheduler] Read 16 as-traced records for output #4
[scheduler] as-read segment #0: input=0 start=0 stop=76 time=13344214879969223
[scheduler] segment #0: input=0 start=0 stop=76 time=13344214879969223
[scheduler] as-read segment #1: input=8 start=0 stop=86 time=13344214879969223
[scheduler] segment #1: input=8 start=0 stop=86 time=13344214879969223
[scheduler] as-read segment #2: input=4 start=71 stop=-1 time=13344214879980090
[scheduler] segment #2: input=4 start=71 stop=-1 time=13344214879980090
[scheduler] as-read segment #3: input=0 start=76 stop=-1 time=13344214879994183
[scheduler] segment #3: input=0 start=76 stop=-1 time=13344214879994183
[scheduler] as-read segment #4: input=5 start=89 stop=-1 time=13344214880036735
[scheduler] segment #4: input=5 start=89 stop=-1 time=13344214880036735
[scheduler] as-read segment #5: input=9 start=8924326 stop=8928206 time=13344214880102306
[scheduler] segment #5: input=9 start=8924326 stop=8928206 time=13344214880102306
[scheduler] as-read segment #6: input=8 start=0 stop=86 time=13344214880209404
[scheduler] segment #6: input=8 start=0 stop=86 time=13344214880209404
[scheduler] as-read segment #7: input=9 start=8931425 stop=8937416 time=13344214880216519
[scheduler] segment #7: input=9 start=8931425 stop=8937416 time=13344214880216519
<...>
$ unzip -p cpu_schedule.zip 2 | od -t x8 -Ax -w32
000000 000000000013bf1e 002f687e23ba1fc7 0000000000000002 0000000000000000
000020 000000000013bf3b 002f687e23ba1fc7 0000000000000002 0000000000000000
000040 000000000013bf1d 002f687e23ba4a3a 0000000000000002 0000000000000047
000060 000000000013bf1e 002f687e23ba8147 0000000000000002 000000000000004c
000080 000000000013bf1f 002f687e23bb277f 0000000000000002 0000000000000059
0000a0 000000000013ae00 002f687e23bc27a2 0000000000000002 0000000000882ca6
0000c0 000000000013bf3b 002f687e23bdc9fc 0000000000000002 0000000000000000
0000e0 000000000013ae00 002f687e23bde5c7 0000000000000002 0000000000884861
<...>
```

Could this be #6107 where the counter resets every chunk?
But that was fixed in June'23 so shouldn't be in this trace.

Looking at thread 13bf3b:
```
           1           0:     1294139 <marker: version 6>
           2           0:     1294139 <marker: filetype 0xe40>
           3           0:     1294139 <marker: cache line size 64>
           4           0:     1294139 <marker: chunk instruction count 10000000>
           5           0:     1294139 <marker: page size 4096>
           6           0:     1294139 <marker: timestamp 13344214879969223>
           7           0:     1294139 <marker: tid 1294139 on core 2>
           8           0:     1294139 <marker: function==syscall #202>
           9           0:     1294139 <marker: function return value 0xffffffffffffff92>
          10           0:     1294139 <marker: system call failed: 110>
          11           0:     1294139 <marker: timestamp 13344214880209404>
          12           0:     1294139 <marker: tid 1294139 on core 2>
          13           1:     1294139 ifetch       3 byte(s) @ 0x0000563642cc5e75 8d 50 0b             lea    0x0b(%rax) -> %edx
<...>
         140          86:     1294139 ifetch       2 byte(s) @ 0x0000563642cc8a3e eb 06                jmp    $0x0000563642cc8a46
         141          86:     1294139 <marker: kernel xfer from 0x563642cc8a46 to handler>
         142          86:     1294139 <marker: timestamp 13344214880248428>
         143          86:     1294139 <marker: tid 1294139 on core 0>
         144          87:     1294139 ifetch       3 byte(s) @ 0x000056363ed3a4e0 83 ff 1a             cmp    %edi $0x0000001a
```

read_traced_schedule() collapses consecutive same-input zero-instr records, but
these are not consecutive: we have stuff in between.

read_traced_schedule() puts all the start points in a set: so has 0 and 86.

Should we collapse as zero-instr and just let the 1st one go straight to instr
number 86?  That seems fine.  Or better to remove the first and use the later timestamp.

Should we also try to not write into cpu_schedule.zip in the first place?
Maybe ok to keep: it is a segment, just not useful with instr ords.

Now succeeds:
```
[scheduler] Dropping same-input=8 same-start=0 entry 
[scheduler] Dropping same-input=13 same-start=23415 entry             
<...>
```

### PR DESCRIPTION
**Pull request by derekbruening**
Removes same-input-same-start cpu_schedule entries when reading the schedule file in the scheduler.  The scheduler cannot emulate a switch with no instructions in between in replay mode, and these same-start entries cause problems.

Adds a scheduler unit test.

Tested on a larger app in as-traced mode where there are many of these same-start entries and without this fix the scheduler advances too early, causing problems.

Fixes #6713

### CODE REVIEW

File: clients/drcachesim/tests/scheduler_unit_tests.cpp [hunk 1]
```diff
@@ -3260,6 +3260,156 @@ test_replay_as_traced_i6107_workaround()
...
+        }
+        inputs[input_idx].push_back(make_exit(tid));
+    }
+
+    // Synthesize a cpu-schedule file with duplicate starts.
+    std::string cpu_fname = "tmp_test_cpu_i6712.zip";
+    {
+        zipfile_ostream_t outfile(cpu_fname);
+        {
+            // Simple dup start: non-consecutive but in same output.
```
Comment (abhinav92003) [inline clients/drcachesim/tests/scheduler_unit_tests.cpp:3300]: This comment applies to L3302 and L3304 right? Please move it to L3304. I wasn't initially aware what a "dup-start" was.

File: clients/drcachesim/tests/scheduler_unit_tests.cpp [hunk 2]
```diff
@@ -3260,6 +3260,156 @@ test_replay_as_traced_i6107_workaround()
...
+            std::ostringstream cpu_string;
+            cpu_string << CPU_0;
+            std::string err = outfile.open_new_component(cpu_string.str());
+            assert(err.empty());
+            if (!outfile.write(reinterpret_cast<char *>(sched.data()),
+                               sched.size() * sizeof(sched[0])))
+                assert(false);
+        }
+        {
+            // More complex dup start across outputs.
```
Comment (abhinav92003) [inline clients/drcachesim/tests/scheduler_unit_tests.cpp:3315]: Move this comment to be directly above the TID_B dup start entry.

File: clients/drcachesim/scheduler/scheduler.h [hunk 3]
```diff
@@ -1331,6 +1331,39 @@ template <typename RecordType, typename ReaderType> class scheduler_tmpl_t {
...
+        schedule_output_tracker_t(bool valid, input_ordinal_t input,
+                                  uint64_t start_instruction, uint64_t timestamp)
+            : valid(valid)
+            , input(input)
+            , start_instruction(start_instruction)
+            , stop_instruction(0)
+            , timestamp(timestamp)
+        {
+        }
+        bool valid;
```
Comment (abhinav92003) [inline clients/drcachesim/scheduler/scheduler.h:1345]: Document when an entry wouldn't be "valid".

File: clients/drcachesim/scheduler/scheduler.cpp [hunk 4]
```diff
@@ -1212,12 +1211,64 @@ scheduler_tmpl_t<RecordType, ReaderType>::read_traced_schedule()
...
 
+template <typename RecordType, typename ReaderType>
+typename scheduler_tmpl_t<RecordType, ReaderType>::scheduler_status_t
+scheduler_tmpl_t<RecordType, ReaderType>::remove_zero_instruction_segments(
+    std::vector<std::vector<schedule_input_tracker_t>> &input_sched,
+    std::vector<std::vector<schedule_output_tracker_t>> &all_sched)
+
+{
+    // For a cpuid pair with no instructions in between, our
+    // instruction-ordinal-based control points cannot model both sides.
```
Comment (abhinav92003) [inline clients/drcachesim/scheduler/scheduler.cpp:1222]: Can you remind me why our control points are not record-ordinal-based?

File: clients/drcachesim/scheduler/scheduler.cpp [hunk 5]
```diff
@@ -1212,12 +1211,64 @@ scheduler_tmpl_t<RecordType, ReaderType>::read_traced_schedule()
...
+            assert(start >= prev_start);
+            if (i > 0 && start == prev_start) {
+                // Keep the newer one.
+                VPRINT(this, 1, "Dropping same-input=%d same-start=%" PRIu64 " entry\n",
+                       input_idx, start);
+                all_sched[input_sched[input_idx][i - 1].output]
+                         [static_cast<size_t>(
+                              input_sched[input_idx][i - 1].output_array_idx)]
+                             .valid = false;
+                input_sched[input_idx].erase(input_sched[input_idx].begin() + i - 1);
```
Comment (abhinav92003) [inline clients/drcachesim/scheduler/scheduler.cpp:1256]: Comment why we really need to erase. It's a vector so the operation can be linear time therefore not trivial.

**Review by abhinav92003 — APPROVED** [review]

File: clients/drcachesim/tests/scheduler_unit_tests.cpp (hunk 1 above)
Comment (derekbruening) [reply clients/drcachesim/tests/scheduler_unit_tests.cpp:3300]: Done.

File: clients/drcachesim/scheduler/scheduler.h (hunk 3 above)
Comment (derekbruening) [reply clients/drcachesim/scheduler/scheduler.h:1345]: Done.

File: clients/drcachesim/scheduler/scheduler.cpp (hunk 4 above)
Comment (derekbruening) [reply clients/drcachesim/scheduler/scheduler.cpp:1222]: The skip and region-of-interest features were designed thinking more about instructions, the more natural unit for microarchitectural simulators.  It seemed like that was much more usable for a user, and translated to other venues like PMU counts.  The scheduler replay features were also designed that way.  But, that makes the infrastructure messy as the underlying records are not built that way.  Xref #6716 on an instruction-based iterator.

I added this as a comment in the code.

File: clients/drcachesim/scheduler/scheduler.cpp (hunk 5 above)
Comment (derekbruening) [reply clients/drcachesim/scheduler/scheduler.cpp:1256]: Actually nobody uses input_sched after this so it looks like we don't have to erase.  I removed the erase (and --i) with a comment.
