### PR TITLE
i#4527: Set ISA mode for drcachesim flush redirect PC

### LINKED ISSUE #4527: APP CRASH: drcachesim delayed tracing broken on 32-bit ARM
Commit 72275ad4c52ef9d04bc4194e637c4f1516685b3d for #4496 via PR #4507 broke ARM delayed tracing:

```
$ bin32/drrun -t drcachesim -trace_after_instrs 20000 -- suite/tests/bin/simple_app
...
Hit delay threshold: enabling tracing.
<Application tried to execute from unreadable memory 0xb71db0a2.
This may be a result of an unsuccessful attack or a potential application vulnerability.>
<Application /home/derek/dr/git/build_dbg_tests/suite/tests/bin/simple_app (1075).  Application exception at PC 0xb71db0a2.  
Signal 11 delivered to application as default action.
Callstack:
	0xb71db0a2  
	0x0001e916  
	0x00000000  
>
```

It's due to an incorrect ISA mode on the dr_redirect_execution from the new synchall flush.

### PR DESCRIPTION
**Pull request by derekbruening**
Fixes drcachesim delayed tracing which was broken by commit 72275ad
for #4496 via PR #4507.  The fix is to decorate the target PC to
indicate the ISA mode.

Adds a reminder to the dr_flush_region_ex() documentation where it
talks about using dr_redirect_execution() to set the ISA mode.

Tested on ARM:
$ bin32/drrun -t drcachesim -trace_after_instrs 20000 -- suite/tests/bin/simple_app

Fixes #4527

### CODE REVIEW

File: core/lib/instrument_api.h [hunk 1]
```diff
@@ -6219,6 +6219,8 @@ DR_API
  * have been flushed. The context to use can be obtained via
  * dr_get_mcontext() with the exception of the pc to continue at which must be passed as
  * an argument to the callout (see instr_get_app_pc()) or otherwise determined.
+ * For 32-bit ARM, be sure to use dr_app_pc_as_jump_target() to properly set the ISA
```
Comment (abhinav92003) [inline core/lib/instrument_api.h:6222]: This comment should probably be at `dr_redirect_execution` too, as the continuation pc is passed to that method.

I see other example usages where this is not done currently. Eg https://github.com/DynamoRIO/dynamorio/blob/c1be309c8f21f9eabd05b759378ee097e1af83b0/api/samples/cbr.c#L261

**Review by abhinav92003 — APPROVED** [review]
Thanks for the fix!

File: core/lib/instrument_api.h (hunk 1 above)
Comment (derekbruening) [reply core/lib/instrument_api.h:6222]: dr_redirect_execution already has a comment about this, but perhaps it could be reworded.

Comment (derekbruening) [reply core/lib/instrument_api.h:6222]: Moved the doc to dr_redirect_execution, merged with what was already there, and raised it up rather than being a lower-down note.

Updated a sample, bbdup, and several tests.

**Comment by derekbruening** [comment]
Appveyor is alloc-noreset again -- seems to be getting more common: #4436.
