### PR TITLE
i#7630: Redirect __memcpy_chk etc. in private loader

### LINKED ISSUE #7630: Some tests fail with <ERROR: using undefined symbol!>
On Ubuntu 22.04 AArch64 with non-DEBUG build:
```
$ ctest -V -R drbbdup-test
...
171: <ERROR: using undefined symbol!>
1/1 Test #171: code_api|client.drbbdup-test .....***Failed  Required regular expression not found. Regex=[^case 2
...
```

No problem with DEBUG build.

### PR DESCRIPTION
**Pull request by egrimley-arm**
Various tests, including drbbdup-test, were failing with some toolchain versions.

The names without the __ prefix (memcpy_chk etc.) were already being redirected.

Fixes #7630

### CODE REVIEW

File: core/unix/loader.c [hunk 1]
```diff
@@ -1694,10 +1694,10 @@ static const redirect_import_t redirect_imports[] = {
     { "strstr", (app_pc)strstr },
     { "strcasecmp", (app_pc)strcasecmp },
     /* Also redirect the _chk versions (i#1747, i#46) */
-    { "memcpy_chk", (app_pc)memcpy },
-    { "memset_chk", (app_pc)memset },
-    { "memmove_chk", (app_pc)memmove },
-    { "strncpy_chk", (app_pc)strncpy },
+    { "__memcpy_chk", (app_pc)memcpy },
```
Comment (derekbruening) [inline core/unix/loader.c:1701]: This seems likely to break other toolchains (or else it wouldn't have been added without underscores). The __ variants should be new entries.

Comment (egrimley-arm) [reply core/unix/loader.c:1701]: > The __ variants should be new entries.

I'll do that. (No tests failed, but the CI tests can't cover all existing toolchains.)

File: core/unix/loader.c [hunk 2]
```diff
@@ -1698,6 +1698,10 @@ static const redirect_import_t redirect_imports[] = {
     { "memset_chk", (app_pc)memset },
```
Comment (derekbruening) [inline core/unix/loader.c:1698]: I would suggest changing to title to "i#7630: Redirect __memcpy_chk etc. in private loader".  (The current title sounds like symbol names are being changed and has no mention of redirection or the loader which is the key here.)

Comment (egrimley-arm) [reply core/unix/loader.c:1698]: Yes, definitely. Done.
