### PR TITLE
i#4893: Delay function tracing with address tracing

### LINKED ISSUE #4893: drmemtrace gathers function trace data before hitting -trace_after_instrs trigger
The -trace_after_instrs delayed tracing feature fails to delay function tracing, which gathers and stores data the whole time.  I hit this when running with a -trace_after_instrs threshold that was never reached, yet a whole bunch of trace data was stored.

### PR DESCRIPTION
**Pull request by derekbruening**
In drcachesim, the -trace_after_instrs delayed-tracing feature fails
to delay function tracing.  We fix that here by leaving the function
wrapping in place from the start and simply ignoring i/o until the
trigger point.

Delaying the function wrapping is complicated by being unable to hold
locks during the whole module load event.  Locks are needed to delay
that event, as we need to enable it and then iterate existing modules.
This is why we instead opt to not delay function wrapping.

Adds documentation to drwrap_wrap* that event-blocking locks cannot be
held.

Adds a new test that delays all tracing and ensures there are zero
function markers.

Fixes #4893

### CODE REVIEW

**Review by sapostolakis — APPROVED** [review]

File: clients/drcachesim/tracer/tracer.cpp [hunk 1]
```diff
@@ -1436,7 +1443,7 @@ enable_tracing_instrumentation()
             event_bb_instru2instru, &memtrace_pri))
         DR_ASSERT(false);
     dr_register_filter_syscall_event(event_filter_syscall);
-    tracing_enabled = true;
+    dr_atomic_add32_return_sum(&tracing_enabled, 1);
```
Comment (abhinav92003) [inline clients/drcachesim/tracer/tracer.cpp:1446]: Is there any benefit to using `dr_atomic_store32` instead of `dr_atomic_add32_return_sum`? Former may be less expensive I guess.

Comment (abhinav92003) [reply clients/drcachesim/tracer/tracer.cpp:1446]: As `tracing_enabled` is just a boolean that makes a one-way transition to `true`, may be better to use former.

Comment (derekbruening) [reply clients/drcachesim/tracer/tracer.cpp:1446]: Switched to store.
