### PR TITLE
i#7626: Fix drmemtrace input count with only_thread

### LINKED ISSUE #7626: CRASH drmemtrace analyzer with -only_thread
While creating a test for #7572 I had a trace with 2 threads in it and I tried to view the 2nd one and it crashed:

```
$ clients/bin64/drmemtrace_launcher -tool view -indir drmemtrace.tool*.dir -only_thread 3071248 -skip_instrs 22288400
Segmentation fault (core dumped)

$ gdb --args clients/bin64/drmemtrace_launcher -tool view -indir drmemtrace.tool*.dir -only_thread 3071248 -skip_instrs 22288400

Program received signal SIGSEGV, Segmentation fault.
std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_Reuse_or_alloc_node::_Reuse_or_alloc_node (this=0x7fffffffb020, __t=...)
    at /usr/include/c++/14/bits/stl_tree.h:446
446                   _M_root->_M_parent = 0;
(gdb) bt
#0  std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_Reuse_or_alloc_node::_Reuse_or_alloc_node (this=0x7fffffffb020, __t=...)
    at /usr/include/c++/14/bits/stl_tree.h:446
#1  0x00005555555e9dd2 in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::operator= (this=0x5555559f2a28, __x=...)
    at /usr/include/c++/14/bits/stl_tree.h:1796
#2  0x00005555555e7b6b in std::set<int, std::less<int>, std::allocator<int> >::operator= (this=0x5555559f2a28) at /usr/include/c++/14/bits/stl_set.h:300
#3  0x00005555555c9fd3 in dynamorio::drmemtrace::scheduler_impl_tmpl_t<dynamorio::drmemtrace::_memref_t, dynamorio::drmemtrace::reader_t>::init (this=0x555555a03770,
    workload_inputs=std::vector of length 1, capacity 1 = {...}, output_count=1, options=...)
    at dr/git/src/clients/drcachesim/scheduler/scheduler_impl.cpp:959
#4  0x00005555555b83c7 in dynamorio::drmemtrace::scheduler_tmpl_t<dynamorio::drmemtrace::_memref_t, dynamorio::drmemtrace::reader_t>::init (this=0x555555a03450,
    workload_inputs=std::vector of length 1, capacity 1 = {...}, output_count=1, options=...)
    at dr/git/src/clients/drcachesim/scheduler/scheduler.cpp:69
#5  0x000055555564f027 in dynamorio::drmemtrace::analyzer_tmpl_t<dynamorio::drmemtrace::_memref_t, dynamorio::drmemtrace::reader_t>::init_scheduler_common (
    this=0x555555a03440, workloads=std::vector of length 1, capacity 1 = {...}, options=...) at dr/git/src/clients/drcachesim/analyzer.cpp:367
#6  0x000055555564e88b in dynamorio::drmemtrace::analyzer_tmpl_t<dynamorio::drmemtrace::_memref_t, dynamorio::drmemtrace::reader_t>::init_scheduler (this=0x555555a03440,
    trace_paths=std::vector of length 1, capacity 1 = {...}, only_threads=std::set with 1 element = {...}, only_shards=std::set with 0 elements, output_limit=0, verbosity=0,
    options=...) at dr/git/src/clients/drcachesim/analyzer.cpp:268
#7  0x0000555555682f22 in dynamorio::drmemtrace::analyzer_multi_tmpl_t<dynamorio::drmemtrace::_memref_t, dynamorio::drmemtrace::reader_t>::analyzer_multi_tmpl_t (
    this=0x555555a03440) at dr/git/src/clients/drcachesim/analyzer_multi.cpp:616
#8  0x00005555555b5bde in main (argc=9, targv=0x7fffffffd708) at dr/git/src/clients/drcachesim/launcher.cpp:335
```

Looking more closely:
```
(gdb) p inputs_.size()
$1 = 1
(gdb) p index
$2 = 1
(gdb) p reader_info.first_input_ordinal
$3 = 0
(gdb) p local_index
$4 = 1
(gdb) p inputs_
$5 = std::vector of length 1, capacity 1 = {{
    index = 0,
    reader = std::unique_ptr<dynamorio::drmemtrace::reader_t> = {
      get() = 0x555555a136b0
    },
    reader_end = std::unique_ptr<dynamorio::drmemtrace::reader_t> = {
      get() = 0x555555a279f0
    },
    lock = std::unique_ptr<dynamorio::drmemtrace::mutex_dbg_owned> = {
      get() = 0x555555a0a910
    },
    workload = 0,
    tid = 3071248,
<...>
(gdb) p tid2input_
$6 = std::unordered_map with 1 element = {
  [{
    workload = 0,
    tid = 3071248
  }] = 0
}
```

So inputs_ has just the one thread: yet the index is 1 so we have an overflow.

Looks like open_reader() increments reader_info.input_count *before* throwing out un-selected inputs.

### PR DESCRIPTION
**Pull request by derekbruening**
Fixes a drmemtrace bug where the input count included threads excluded with -only_thread while the input_ array did not, leading to an array overflow.

Adds reader_info_t.unfiltered_input_count to fix a problem with the only_shards validity check.

Documents that input_thread_info_t.shards modifiers apply after only_* have filtered out inputs.

Adds a check on an invalid modifier index.

Avoids an empty binder set copy.

Adds "-skip_instrs 10" to the only_thread test, which reproduces the crash (now an invalid input error) without the fix and passes with the fix. The only_shards test exercises the unfiltered_input_count change as it fails without that change.

Fixes #7626

### CODE REVIEW

File: clients/drcachesim/scheduler/scheduler.h [hunk 1]
```diff
@@ -263,6 +263,10 @@ template <typename RecordType, typename ReaderType> class scheduler_tmpl_t {
          * #dynamorio::drmemtrace::scheduler_tmpl_t::input_workload_t.
          * If multiple entries list the same shard ordinal, only the last one is
          * honored.
+         *
+         * If #dynamorio::drmemtrace::scheduler_tmpl_t::input_workload_t.only_shards
+         * is also set, the indices here apply to the input list *after* only those
+         * matching only_shards are removed.
```
Comment (abhinav92003) [inline clients/drcachesim/scheduler/scheduler.h:269]: > matching only_shards are removed

matching only_shards are s/removed/retained/?

This  makes it potentially complicated for a user to specify the shard ordinals, right? They would  need to duplicate the filtering logic on their side.

If a user wants to filter, can't we just ask them to specify only the inputs they really want? IIUC the only_shards is for cases like the analyzer where the list of inputs includes all files/shards without the user doing anything, therefore requires a way for the user to "filter out" the ones they don't want.

If this is better, then we can just drop the support for only_shards in non-analyzer cases.

File: clients/drcachesim/scheduler/scheduler_impl.cpp [hunk 2]
```diff
@@ -849,7 +850,8 @@ scheduler_impl_tmpl_t<RecordType, ReaderType>::init(
         if (workload.path.empty()) {
             if (workload.readers.empty())
                 return sched_type_t::STATUS_ERROR_INVALID_PARAMETER;
-            reader_info.input_count = workload.readers.size();
+            reader_info.unfiltered_input_count = workload.readers.size();
```
Comment (abhinav92003) [inline clients/drcachesim/scheduler/scheduler_impl.cpp:853]: At first look: check_valid_input_limits is called after open_readers which already sets unfiltered_input_count and input_count.

But then I see that init calls open_readers only when !workload_path.empty() which is not true for this control path.

Maybe add an assert here to show that unfiltered_input_count and input_count are indeed not set yet?

File: suite/tests/CMakeLists.txt [hunk 3]
```diff
@@ -4101,7 +4101,8 @@ if (BUILD_CLIENTS)
         set(tool.reuse_time_offline_rawtemp ON) # no preprocessor
 
         torunonly_simtool(counts_only_thread ${ci_shared_app}
-          "-indir ${thread_trace_dir} -tool basic_counts -only_thread 872906"
+          # We add -skip_instrs to test i#7626.
+          "-indir ${thread_trace_dir} -tool basic_counts -only_thread 872906 -skip_instrs 10"
```
Comment (abhinav92003) [inline suite/tests/CMakeLists.txt:4105]: > Adds "-skip_instrs 10" to the only_thread test, which reproduces the crash (now an assert) 

Where is the assert that the PR description mentions?

File: clients/drcachesim/scheduler/scheduler.h (hunk 1 above)
Comment (derekbruening) [reply clients/drcachesim/scheduler/scheduler.h:269]: Yes it does make it complicated but I'm not sure we can solve that without adding a lot of overhead to our internal use cases.  You're saying better to not support at all if it's complicated?  I figured it was better to leave it in case someone wants to use it so they have an option and it's not impossible even if it's complex.

> If a user wants to filter, can't we just ask them to specify only the inputs they really want?

Not sure what you mean: please elaborate on "filter" (you mean limiting inputs as is done with only_ I assume) and "specify": isn't the current only_ already "specify only the inputs they really want"?

File: clients/drcachesim/scheduler/scheduler_impl.cpp (hunk 2 above)
Comment (derekbruening) [reply clients/drcachesim/scheduler/scheduler_impl.cpp:853]: There are two paths in init(): one for file paths which goes through open_readers, and one with direct reader_t pointers which is the code here. So both ways to specify inputs set unfiltered_input_count.
If you zoom out a few lines it is pretty clear IMHO that one path sets unfiltered_input_count directly and the other calls open_readers.

File: suite/tests/CMakeLists.txt (hunk 3 above)
Comment (derekbruening) [reply suite/tests/CMakeLists.txt:4105]: Ah, it was an assert but I changed it to a fatal error. Updated the description.

File: clients/drcachesim/scheduler/scheduler_impl.cpp (hunk 2 above)
Comment (abhinav92003) [reply clients/drcachesim/scheduler/scheduler_impl.cpp:853]: I understand. I just thought the assert would be useful.

File: clients/drcachesim/scheduler/scheduler.h (hunk 1 above)
Comment (abhinav92003) [reply clients/drcachesim/scheduler/scheduler.h:269]: There are two ways to construct an input_workload_t:
1. using a trace dir, which adds an input for every shard, and then the user needs to use only_shards to filter
2. using a std::vector<input_reader_t> readers. 

What I meant was: if the user is doing (2), it doesn't make sense to additionally specify only_shards. Because they can specify a vector entry only for the inputs they want in the first place.

I thought (1) is used only in the analyzer mode, and in the analyzer mode, there's no option where the user must specify the shard_ordinal_after_filtering. (I may be wrong in this assumption; let me know).

Comment (derekbruening) [reply clients/drcachesim/scheduler/scheduler.h:269]: 1) Is used by scheduler_launcher and quite possibly by some external simulators. So it is not only used in analyzer mode.

> What I meant was: if the user is doing (2), it doesn't make sense to additionally specify only_shards. Because they can specify a vector entry only for the inputs they want in the first place.

I think it might not be uncommon to either have two different components picking these two (someone has set up input_thread_info_t modifiers like bindings or ROI for each of the inputs, and someone else decides to only run 3 of the 5 inputs) or have one person set up bindings/ROI but then for debugging or other purposes wants to run just a subset. It could be the only_shards is a command line param but now they're forced to go make code changes b/c the ordinals are shifted. Not ideal. I'm not going to try to solve it, but I don't think it's something nobody would ever hit.

File: clients/drcachesim/scheduler/scheduler_impl.cpp (hunk 2 above)
Comment (derekbruening) [reply clients/drcachesim/scheduler/scheduler_impl.cpp:853]: > But then I see that init calls open_readers only when !workload_path.empty() which is not true for this control path.
> Maybe add an assert here to show that unfiltered_input_count and input_count are indeed not set yet?

But the "only when !workload_path.empty()" is this same control path: I thought this request was based on thinking whether to call open_readers was decided in some far away code.

> I just thought the assert would be useful.

It seems on the same level as all the other state that is initialized in a different way in those two paths, the direct-reader_t and the open_readers paths. If an assert is added on one path that some state is not set yet, I would think we would then want asserts on all the other state on both paths: which seems overkill IMHO.

File: clients/drcachesim/scheduler/scheduler.h (hunk 1 above)
Comment (abhinav92003) [reply clients/drcachesim/scheduler/scheduler.h:269]: Ok. Maybe add it to the comment here?

File: clients/drcachesim/scheduler/scheduler_impl.cpp (hunk 2 above)
Comment (abhinav92003) [reply clients/drcachesim/scheduler/scheduler_impl.cpp:853]: Oh wait I think I misread something here. I thought L853 was in check_valid_input_limits (I mentioned that in the first comment) which did seem faraway and for that it made sense to assert.

Ack, assert would be overkill.

File: clients/drcachesim/scheduler/scheduler.h (hunk 1 above)
Comment (derekbruening) [reply clients/drcachesim/scheduler/scheduler.h:269]: Added a (non-doxygen) comment about this being non-ideal but we have no good solution so we live with it.
