### PR TITLE
i#5304: Ignore reachability for instr_is_encoding_possible()

### LINKED ISSUE #5304: instr_is_encoding_possible fails on unreachable pc-relative operands but takes no target
While adding a test for #5302 on arm, I hit this:
```
ASSERT FAILURE: /home/derek/dr/git/src/suite/tests/api/ir_arm.c:80: instr_is_encoding_possible(instr)
```

This is for the instruction in test_pcrel() in ir_arm.c.

The problem is that  instr_is_encoding_possible() does not take in a target location for encoding, so it can't know whether pc-relative operands will reach.  It has to relax those reachability checks.

### PR DESCRIPTION
**Pull request by derekbruening**
On ARM, instr_is_encoding_possible() was checking reachabilty, yet it
took no target encode address, causing it to fail for any but very
small addresses.  We remove the reachability checks to solve this.

The test for #5302 in a forthcoming PR adds a regression test for
this.

Fixes #5304

### CODE REVIEW

**Review by abhinav92003 — APPROVED** [review]

File: core/ir/encode_shared.c [hunk 1]
```diff
@@ -99,6 +99,7 @@ get_encoding_info(instr_t *instr)
     const instr_info_t *info = instr_get_instr_info(instr);
     decode_info_t di;
     decode_info_init_for_instr(&di, instr);
+    IF_AARCHXX(di.check_reachable = false;)
```
Comment (abhinav92003) [inline core/ir/encode_shared.c:102]: From the PR description it looks like this PR is only for ARM, but here it's changing for AArch64 too.

Comment (abhinav92003) [reply core/ir/encode_shared.c:102]: Commenting as a review comment to make it visible on front PR page.

**Review by abhinav92003 — APPROVED** [review]

File: core/ir/encode_shared.c (hunk 1 above)
Comment (derekbruening) [reply core/ir/encode_shared.c:102]: Changing the description in the final merge.
