### PR TITLE
i#4291: append to LD_PRELOAD when using -late

### LINKED ISSUE #4291: drrun overwrites LD_PRELOAD when using -late
**Describe the bug**
When using `drrun`'s `-late` mode of injection, `LD_PRELOAD` is employed to load the DR support libraries. In the process of doing so, DR overwrites the existing value of `LD_PRELOAD`, rather than appending to the existing value.

**To Reproduce**
```
$ cd <DR_ROOT>/bin64
$ LD_PRELOAD=libtest.so ./drrun -late -c ../samples/bin64/libbbcount.so -- env
```
Note that the output does not include `libtest.so`.

**Expected behavior**
`LD_PRELOAD`'s value should be preserved through invocations of `drrun`.

**Versions**
Occurs on 7.1 and 8.0 releases on Linux on both 32/64 bit builds.

**Additional context**
PR coming shortly. Issue migrated from [Google Groups discussion](https://groups.google.com/forum/#!topic/DynamoRIO-Users/kGOpz9WASQ8).

### PR DESCRIPTION
**Pull request by mattgreen**
When using -late, append to LD_PRELOAD rather than overwrite it.

Fixes #4291

### CODE REVIEW

**Comment by derekbruening** [comment]
run arm tests

**Comment by derekbruening** [comment]
Travis is misbehaving: their Mac bots are dying or sthg midway through our build.  Will try one more rerun.

**Comment by derekbruening** [comment]
So it is in fact a build failure on Mac.  It is not presented very well which is #4223.
```
/Users/travis/build/DynamoRIO/dynamorio/core/unix/injector.c:221:17: error: unused variable 'ld_preload' [-Werror,-Wunused-variable]
    const char *ld_preload = NULL;
                ^
Users/travis/build/DynamoRIO/dynamorio/core/unix/injector.c:223:17: error: unused variable 'cur_preload' [-Werror,-Wunused-variable]
    const char *cur_preload = getenv("LD_PRELOAD");
                ^
/Users/travis/build/DynamoRIO/dynamorio/core/unix/injector.c:222:17: error: unused variable 'dr_ld_preload_libs' [-Werror,-Wunused-variable]
    const char *dr_ld_preload_libs = "libdynamorio.so libdrpreload.so";
                ^
/Users/travis/build/DynamoRIO/dynamorio/core/unix/injector.c:216:10: error: unused variable 'ld_preload_libs' [-Werror,-Wunused-variable]
    char ld_preload_libs[MAX_OPTIONS_STRING];
```

@mattgreen, If you could fix the build failure.

File: core/unix/injector.c [hunk 1]
```diff
@@ -213,16 +213,18 @@ report_dynamorio_problem(dcontext_t *dcontext, uint dumpcore_flag, app_pc except
...
 pre_execve_ld_preload(const char *dr_path)
 {
-    char ld_preload_libs[MAX_OPTIONS_STRING];
     char ld_lib_path[MAX_OPTIONS_STRING];
     const char *last_slash = NULL;
     const char *mode_slash = NULL;
     const char *lib_slash = NULL;
+    const char *cur_path = getenv("LD_LIBRARY_PATH");
+    const char *cur = dr_path;
+#ifdef LINUX
```
Comment (derekbruening) [inline core/unix/injector.c:222]: Hmm, so Mac is still overwriting instead of appending, so we have split behavior now.  Maybe worth addressing -- or maybe just a XXX comment.  I think it will let me edit this with a comment.

Comment (mattgreen) [reply core/unix/injector.c:222]: Good catch. I dev on a Mac, so I can fix this there as well if you'd like.

Comment (derekbruening) [reply core/unix/injector.c:222]: That would be awesome, thanks.

**Comment by mattgreen** [comment]
Hmm, Windows build failed. I'm surprised by that considering the source file isn't in the build. Is there a way to re-run it?

File: core/unix/injector.c [hunk 2]
```diff
@@ -259,16 +272,11 @@ pre_execve_ld_preload(const char *dr_path)
...
 
-    if (cur_preload != NULL) {
-        snprintf(ld_preload_libs, BUFFER_SIZE_ELEMENTS(ld_preload_libs), "%s %s",
-                 cur_preload, dr_ld_preload_libs);
-        NULL_TERMINATE_BUFFER(ld_preload_libs);
-        ld_preload = ld_preload_libs;
-    } else {
-        ld_preload = dr_ld_preload_libs;
-    }
+    snprintf(ld_lib_path, BUFFER_SIZE_ELEMENTS(ld_lib_path), "%s%s", preload_prefix,
```
Comment (derekbruening) [inline core/unix/injector.c:275]: I think you've omitted the %c preload_delimiter.

A test would presumably catch this.  Though with -late not used much it seems ok to not put in the effort for it: would have to make some other lib to be preloaded and check it got in there too with a -late injection.

Comment (derekbruening) [reply core/unix/injector.c:275]: Ah my bad: it's in the preload_prefix which is shared.

**Comment by derekbruening** [comment]
> Hmm, Windows build failed. I'm surprised by that considering the source file isn't in the build. Is there a way to re-run it?

Looks like drwrap-test 32-bit: #4231.  Yes it can be re-run individually but I'll update the branch which is another way to re-run.

**Comment by derekbruening** [comment]
run arm tests

**Comment by derekbruening** [comment]
Just documenting that we're going to live without a test for the new code.

**Comment by mattgreen** [comment]
Thanks for the feedback and accepting it!
