### PR TITLE
i#7516: Try in a loop if fd_priv_dup() fails

### LINKED ISSUE #7516: fd_priv_dup can fail in fd-limited environments
We observed internal applications failing in some environments with
-satisfy_w_xor_x with ENOMEM returned by the first two DUPFD attempts
in fd_priv_dup().  fd_priv_dup() only retries once and that value is
still to high in our failure cases.  Trying a 3rd time (/2 each time)
succeeds.  Probably we should generalize into a loop that retries, to make
things more robust for cases where fds are limited.

The failure manifests as this output and exit up front:

```
<ran out of stolen fd space>
<Application xxx (NNN). Failed to satisfy W^X policies.>
```

### PR DESCRIPTION
**Pull request by derekbruening**
We observed internal applications failing in some environments with -satisfy_w_xor_x with ENOMEM returned by the first two DUPFD attempts in fd_priv_dup().  fd_priv_dup() only retries once and that value is still too high in our failure cases.  Trying a 3rd time (/2 each time) succeeds. Here we generalize for a loop that retries, to make things more robust for cases where fds are limited.

Tested: Ran internal tests that were failing ~20% of the time and now there are zero failures.

Fixes #7516

### CODE REVIEW

File: core/unix/os.c [hunk 1]
```diff
@@ -4454,17 +4454,29 @@ fd_priv_dup(file_t curfd)
...
              */
-            SYSLOG_INTERNAL_WARNING_ONCE("ran out of stolen fd space");
+            SYSLOG_INTERNAL_WARNING_ONCE("ran out of stolen fd space with error %d",
+                                         newfd);
             /* Try again but this time in the app space, somewhere high up
              * to avoid issues like tcsh assuming it can own fds 3-5 for
              * piping std{in,out,err} (xref the old -open_tcsh_fds option).
              */
-            newfd = fcntl_syscall(curfd, F_DUPFD, min_dr_fd / 2);
+            newfd = fcntl_syscall(curfd, F_DUPFD, try_fd);
```
Comment (abhinav92003) [inline core/unix/os.c:4474]: > with ENOMEM returned by the first two DUPFD attempts in fd_priv_dup()

The man page for fcntl doesn't mention ENOMEM at all though: https://man7.org/linux/man-pages/man2/fcntl.2.html.

File: core/unix/os.c [hunk 2]
```diff
@@ -4454,17 +4454,29 @@ fd_priv_dup(file_t curfd)
...
+            /* Drop by half if we're up > 1M; else try linear values. */
+            if (try_fd > 1024 * 1024)
```
Comment (abhinav92003) [inline core/unix/os.c:4476]: > and that value is still to high in our failure cases

nit: s/to/too/

File: core/unix/os.c [hunk 3]
```diff
@@ -4454,17 +4454,29 @@ fd_priv_dup(file_t curfd)
          * so how do we tell if the flag is supported?  try calling once at init?
          */
         newfd = fcntl_syscall(curfd, F_DUPFD, min_dr_fd);
-        if (newfd < 0) {
+        int try_fd = min_dr_fd / 2;
```
Comment (abhinav92003) [inline core/unix/os.c:4461]: Maybe remind the reader that F_DUPFD returns the lowest numbered descriptor available >= try_fd, and we want to keep DR's file descriptors towards the top to minimize possibility for transparency issues.

**Review by abhinav92003 — APPROVED** [review]

File: core/unix/os.c (hunk 3 above)
Comment (derekbruening) [reply core/unix/os.c:4461]: There are comments to that effect already (tcsh wanting 3-5; "F_DUPFD starts at given value") but they may not be clear. Added:
```
        /* F_DUPFD will fail if it can't allocate a descriptor >= the 3rd paramter.
         * If it fails, try again with something smaller, but keep trying to stay
         * out of typical app descriptor ranges even if we can't fully isolate.
         */
```

File: core/unix/os.c (hunk 2 above)
Comment (derekbruening) [reply core/unix/os.c:4476]: Done.

File: core/unix/os.c (hunk 1 above)
Comment (derekbruening) [reply core/unix/os.c:4474]: The code here printed out 12 for the return value is all I know. Certainly man pages are not alway 100% accurate for every kernel.  Not sure what you're asking for here: yes it was definitely 12, which is ENOMEM.  It is a slightly custom kernel but it would not be surprising if even mainline kernels had behavior not in the man page regarding errors.

Comment (derekbruening) [reply core/unix/os.c:4474]: Going to resolve.  The PR description saying ENOMEM does say "internal environments" if this is unique to our internal kernel.  It doesn't hurt other kernels to have some retries before failure even if others wouldn't fail in this way where a retry would succeed.
