### PR TITLE
i#4237: Fix realloc over-read

### LINKED ISSUE #4237: DynamoRIO wrapped malloc should guarantee 16-byte heap alignment
MOVDQA requires 16-byte memory alignment. DynamoRIO malloc does not align by 16 bytes. Unaligned memory access causes a crash. More information can be found in [Google Groups](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/dynamorio-users/BlPaJytSH4o).

### PR DESCRIPTION
**Pull request by derekbruening**
Fixes a bug from 228933d #4237 where redirect_realloc() was not
updated to read the new malloc header, resulting in a memcpy that
reads beyond the end of the original allocation, which can crash if
it's at the end of a heap block with a subsequent guard page.

Adds at least some sanity checks of realloc to the alignment test.  I
tried to construct a regression test to reproduce the crash in the
bug, but it is not possible in a straightforward way just using the
public interface as it requires knowing what is beyond an allocation
or how two allocations are arranged and what headers or other bytes
are in between.

Fixes #4237

### CODE REVIEW

**Comment by derekbruening** [comment]
Should be #4250: will adjust on merge.

File: core/loader_shared.c [hunk 1]
```diff
@@ -991,11 +1006,18 @@ redirect_realloc(void *mem, size_t size)
...
+         * should be on slowpaths in any case.
+         */
         buf = redirect_malloc(size);
         if (buf != NULL && mem != NULL) {
-            size_t old_size = *((size_t *)((byte *)mem - sizeof(size_t)));
+            void *old_start;
+            size_t old_size = redirect_malloc_size_and_start(mem, &old_start);
             size_t min_size = MIN(old_size, size);
-            memcpy(buf, mem, min_size);
+            memcpy(buf, old_start, min_size);
```
Comment (johnfxgalea) [inline core/loader_shared.c:1020]: Why copy from old_start instead of mem? Didn't understand that part.

Comment (derekbruening) [reply core/loader_shared.c:1020]: Thank you, that is an error.  old_start is the DR alloc start, not the privlib start.  Wow, apparently I should not be the one writing this code: keep making errors.  At least my new test caught this one on Travis (passed locally somehow...b/c my 0xcd is DR's free pattern??  Confirmed: changing to 0x77 and it fails locally).

Comment (johnfxgalea) [reply core/loader_shared.c]: This also applies to the size as well. AFAIK redirect_malloc_size_and_start() returns the alloc size no?

Comment (derekbruening) [reply core/loader_shared.c]: Yes, should be redirect_malloc_requested_size().  Adding more to the test to catch that too.

**Comment by derekbruening** [comment]
Flaky test on appveyor: drwrap-test-detach #4058
