### PR TITLE
i#3906: Fix DR_NUM_SIMD_VECTOR_REGS to reflect the architectural number of registers.

### LINKED ISSUE #3906: Fix bad placement of DR_NUM_SIMD_VECTOR_REGS
When adding the DR_NUM_SIMD_VECTOR_REGS alias, it slipped my mind to also include it for the Intel architecture.

This issue concerns fixing the bad placement.

### PR DESCRIPTION
**Pull request by hgreving2304**
Change DR_NUM_SIMD_VECTOR_REGS to reflect the actual architectural number of registers
instead of the preserved number of registers as given by MCXT_NUM_SIMD_SLOTS, as it
was intended by beb2ded8ac9e83a02fe418.

Fix the upper bound of number of simd registers of xmm, ymm, and zmm in x86 reflected
by DR_REG_STOP_XMM, DR_REG_STOP_YMM, and DR_REG_STOP_ZMM in 32-bit mode.

Fixes #3906

### CODE REVIEW

**Comment by hgreving2304** [comment]
PTAL.

File: core/arch/opnd.h [hunk 1]
```diff
@@ -842,6 +842,11 @@ enum {
 #    endif
 
     DR_NUM_GPR_REGS = DR_REG_STOP_GPR - DR_REG_START_GPR + 1,
+#    ifdef AARCH64
+    DR_NUM_SIMD_VECTOR_REGS = DR_REG_Z31 - DR_REG_Z0 + 1,
+#    else
+    DR_NUM_SIMD_VECTOR_REGS = 0,
```
Comment (derekbruening) [inline core/arch/opnd.h]: Wait, is this else path for 32-bit ARM?  It has SIMD registers.  This doesn't seem right.

File: core/arch/opnd.h [hunk 2]
```diff
@@ -915,6 +917,8 @@ extern const reg_id_t dr_reg_fixer[];
 #    endif
 /** Number of general registers */
 #    define DR_NUM_GPR_REGS (DR_REG_STOP_GPR - DR_REG_START_GPR + 1)
+/** Number of SIMD vector registers */
```
Comment (derekbruening) [inline core/arch/opnd.h]: nit: end punctuation; good to have "The" too perhaps, for more professional user-facing doxygen comment.

Hmm, I guess none of the ones below have end punctuation either: I would say go ahead and add a `.` to the new ones but maybe not worth touching the old in this CL.

File: core/arch/opnd.h [hunk 3]
```diff
@@ -842,6 +842,11 @@ enum {
 #    endif
 
     DR_NUM_GPR_REGS = DR_REG_STOP_GPR - DR_REG_START_GPR + 1,
+#    ifdef AARCH64
+    DR_NUM_SIMD_VECTOR_REGS = DR_REG_Z31 - DR_REG_Z0 + 1,
```
Comment (derekbruening) [inline core/arch/opnd.h]: (Should we have START_SIMD and STOP_SIMD too?  Maybe not worth it.)

File: core/arch/opnd.h (hunk 1 above)
Comment (hgreving2304) [reply core/arch/opnd.h]: But only 64-bit right? Not what's commonly called "vector simd" like NEON. Can we add a FIXME comment here instead and leave it to the ARM guys?

File: core/arch/opnd.h (hunk 2 above)
Comment (hgreving2304) [reply core/arch/opnd.h]: Done.

File: core/arch/opnd.h (hunk 1 above)
Comment (hgreving2304) [reply core/arch/opnd.h]: And re-open #3906 to address this?

Comment (derekbruening) [reply core/arch/opnd.h]: No, 128-bit.  We consider NEON part of the 32-bit ARM ISA in our decoder.  It has 128-bit SIMD registers.

Comment (derekbruening) [reply core/arch/opnd.h]: In this same file we define these SIMD registers: DR_REG_Q0...

Comment (derekbruening) [reply core/arch/opnd.h]: I think the proper number should just be put here now.  No reason to have someone else add a simple expression.

File: core/arch/opnd.h (hunk 3 above)
Comment (hgreving2304) [reply core/arch/opnd.h]: I'd leave this to the ARM guys, not part of this cl/ for sure.

File: core/arch/opnd.h (hunk 1 above)
Comment (hgreving2304) [reply core/arch/opnd.h]: Done, re-open if necessary/

Comment (hgreving2304) [reply core/arch/opnd.h]: Ok, done.

File: core/arch/opnd.h [hunk 4]
```diff
@@ -845,7 +845,7 @@ enum {
 #    ifdef AARCH64
     DR_NUM_SIMD_VECTOR_REGS = DR_REG_Z31 - DR_REG_Z0 + 1,
 #    else
-    DR_NUM_SIMD_VECTOR_REGS = 0,
+    DR_NUM_SIMD_VECTOR_REGS = DR_REG_Q31 - DR_REG_Q0 + 1,
```
Comment (derekbruening) [inline core/arch/opnd.h]: Q15 not Q31.  (This is where a STOP would be useful.)  There are 16 128-bit SIMD regs on ARM.  See the comment next to DR_REG_Q16.

Comment (hgreving2304) [reply core/arch/opnd.h]: Ok, I see. This is very arbitrary for ARM. We chose the SVE registers for ARMv8. What about NEON etc.? I wonder if we should not define for ARM at all and there should be more distinct names specific to ARM/AArch64? I've added a comment.

Comment (derekbruening) [reply core/arch/opnd.h]: This *is* NEON, as explained.  This is not arbitrary, as discussed offline.  The only question is whether a user would also want the number of 64-bit D or 32-bit S registers, which is 32 instead of 16.  Adding or distinguishing those could be in a comment for the future.
