### PR TITLE
i#4856: Add Doxygen links for instr_t and fix formatting

### LINKED ISSUE #4856: Add Doxygen links to instr_t references in interface headers
There are many instances of INSTR_CREATE macro documentation saying things like this:
```
* \param dc  The void * dcontext used to allocate memory for the instr_t.
```

That should have a `#` to link up the `instr_t` type.

### PR DESCRIPTION
**Pull request by AnandRaj2224**
This PR adds explicit `#` Doxygen links for `instr_t` in various header files, as discussed in issue #4856.

Fixes #4856

### CODE REVIEW

File: core/lib/dr_events.h [hunk 1]
```diff
@@ -226,7 +226,7 @@ DR_API
  * basic block, usually global heap (#dr_global_alloc()) is a better
```
Comment (derekbruening) [inline core/lib/dr_events.h:226]: > Fix #4856: Add Doxygen links for instr_t references in core/lib headers

style: See https://dynamorio.org/page_code_reviews.html#sec_commit_messages where we use "i#4856: " in the title.

Comment (derekbruening) [inline core/lib/dr_events.h:226]: > Fixes #4856 

nit: We generally put all magic syntax lines at the bottom of the message

File: core/lib/globals_api.h [hunk 2]
```diff
@@ -371,7 +371,7 @@ typedef struct {
 } opnd_t;
 
 /**
- * Internal structure of instr_t is below abstraction layer, but we
+ * Internal structure of #instr_t is below abstraction layer, but we
```
Comment (derekbruening) [inline core/lib/globals_api.h:374]: There are more instances in core/ir/x86/instr_create_api.h and similar headers: include those in this PR?

**Comment by AnandRaj2224** [comment]
@derekbruening ,I'm having trouble resolving the CI formatting failures on this PR.
I've tried running clang-format on the changed files, but the checks are still failing.

Could you please point me to the exact formatting command or script the project uses? I seem to be missing a step and would appreciate your guidance.

Thanks for your help!

**Comment by derekbruening** [comment]
> @derekbruening ,I'm having trouble resolving the CI formatting failures on this PR. I've tried running clang-format on the changed files, but the checks are still failing.
> 
> Could you please point me to the exact formatting command or script the project uses? I seem to be missing a step and would appreciate your guidance.

https://dynamorio.org/page_code_style.html#autotoc_md123

https://github.com/DynamoRIO/dynamorio/blob/master/.github/workflows/ci-clang-format.yml#L82

**Comment by AnandRaj2224** [comment]
@derekbruening all the formatting checks (ci-clang-format, etc.) are passing now after rebasing onto the latest master and ensuring the correct clang-format-14 version was used for the header files. Thanks for the guidance!

However, there's one remaining failure in the ci-x86 / test (ubuntu-22.04, x86_64, RelWithDebInfo) job (ID: 53988260379).

Looking at the logs for that job, the errors seem related to the build environment itself:

Cross-compiler aarch64-linux-gnu-gcc not found,Cross-compiler riscv64-linux-gnu-gcc not found

Since my changes in this PR were only focused on fixing Doxygen @ref links for instr_t within comment blocks in .h files, these cross-compilation and build tool errors seem unlikely to be caused by my code changes.
I tried re-running the failed job, but the result was the same.
Could this be a temporary issue with the CI runner setup, or is there something specific I need to address in the configuration related to these cross-compilers?

Could someone please take a look or advise on how to proceed?
Thanks!

**Comment by derekbruening** [comment]
> @derekbruening all the formatting checks (ci-clang-format, etc.) are passing now after rebasing onto the latest master and ensuring the correct clang-format-14 version was used for the header files. Thanks for the guidance!
> 
> However, there's one remaining failure in the ci-x86 / test (ubuntu-22.04, x86_64, RelWithDebInfo) job (ID: 53988260379).
> 
> Looking at the logs for that job, the errors seem related to the build environment itself:
> 
> Cross-compiler aarch64-linux-gnu-gcc not found,Cross-compiler riscv64-linux-gnu-gcc not found
> 
> Since my changes in this PR were only focused on fixing Doxygen @ref links for instr_t within comment blocks in .h files, these cross-compilation and build tool errors seem unlikely to be caused by my code changes. I tried re-running the failed job, but the result was the same. Could this be a temporary issue with the CI runner setup, or is there something specific I need to address in the configuration related to these cross-compilers?
> 
> Could someone please take a look or advise on how to proceed? Thanks!

The cross compiler is not an issue: that is just how the scripts operate, attempting various configs. The errors are the test failures at the very bottom:

```
2025-10-29T15:34:41.8631268Z ====> FAILURE in debug-internal-64 <====
2025-10-29T15:34:41.8631963Z debug-internal-64: 558 tests passed, **** 7 tests failed, of which 1 were flaky, but ignoring 2 for i#2941: ****
2025-10-29T15:34:41.8633205Z 	code_api|client.drx-scattergather 
2025-10-29T15:34:41.8633598Z 	code_api|client.drx-scattergather-bbdup 
2025-10-29T15:34:41.8634303Z 	code_api|sample.memval_simple_scattergather 
2025-10-29T15:34:41.8634651Z 	code_api|tool.drcachesim.scattergather-x86 
```

That is #7678 which is a regression that appeared recently and shows up occasionally but no one has been able to reproduce locally or root cause it, unfortunately. I tried a re-run of that job.

**Comment by derekbruening** [comment]
Please reply to all comments and mark resolved, per https://dynamorio.org/page_code_reviews.html#autotoc_md118, and then click the arrows to re-request a review.

**Comment by derekbruening** [comment]
> @[AnandRaj2224](https://github.com/AnandRaj2224) AnandRaj2224 [force-pushed](https://github.com/DynamoRIO/dynamorio/compare/9267dd35ee6f573fdf3ded2c497f5be3a90df8df..2e247fcb4c5d844894b2bac85a8d1eece90838df) the fix-doxygen-links-4856 branch 2 times, most recently from [9267dd3](https://github.com/DynamoRIO/dynamorio/commit/9267dd35ee6f573fdf3ded2c497f5be3a90df8df) to [2e247fc](https://github.com/DynamoRIO/dynamorio/commit/2e247fcb4c5d844894b2bac85a8d1eece90838df) 
[2 days ago](https://github.com/DynamoRIO/dynamorio/pull/7700#event-20544079462)

Please do not force-push to a shared branch: it breaks the history and makes it hard to review. Seeing changes since the last review becomes impossible; comments lose their anchors in the code. Not doing force-pushes is documented in multiple places: https://dynamorio.org/page_code_reviews.html#sec_code_review_non_member, https://dynamorio.org/page_code_reviews.html#autotoc_md118.

The final merge squashes all the commits and the description comes from the PR text box: so there is no upside to a force-push and many significant downsides.

File: clients/drcachesim/tracer/raw2trace_shared.h [hunk 3]
```diff
@@ -69,7 +69,9 @@ namespace drmemtrace {
 #endif
 #define OUTFILE_SUBDIR "raw"
 #define WINDOW_SUBDIR_PREFIX "window"
-#define WINDOW_SUBDIR_FORMAT "window.%04zd" /* ptr_int_t is the window number type. */
+#define WINDOW_SUBDIR_FORMAT                               \
+    "window.%04zd" /* ptr_int_t is the window number type. \
```
Comment (derekbruening) [inline clients/drcachesim/tracer/raw2trace_shared.h]: This reformat doesn't look right.

I tried it and I don't see this change:
```
$ clang-format-14 < clients/drcachesim/tracer/raw2trace_shared.h | grep -1 SUBDIR_FO
#define WINDOW_SUBDIR_PREFIX "window"
#define WINDOW_SUBDIR_FORMAT "window.%04zd" /* ptr_int_t is the window number type. */
#define WINDOW_SUBDIR_FIRST "window.0000"
```

The tests are green: but we've seen clang-format-diff do different things from clang-format, including buggy behavior.

Did your clang-format produce this, or did you tweak this to match clang-format-diff v14? If the latter: maybe we should upgrade the GA CI -- 15 should be easily available.

There are a number of similar changes: in instr_create_api.h:500, opnd_api.h:269, opcode_api.h:1711, instr_api.h:2536.

File: core/ir/opnd_api.h [hunk 4]
```diff
@@ -265,16 +265,26 @@ enum {
 #define OPSZ_sidt OPSZ_6x10      /**< Operand size for sidt memory reference. */
 #define OPSZ_bound OPSZ_8_short4 /**< Operand size for bound memory reference. */
 #define OPSZ_maskmovq OPSZ_8     /**< Operand size for maskmovq memory reference. */
-#define OPSZ_maskmovdqu OPSZ_16  /**< Operand size for maskmovdqu memory reference. */
-#define OPSZ_fldenv OPSZ_28_short14  /**< Operand size for fldenv memory reference. */
+#define OPSZ_maskmovdqu                                        \
+    OPSZ_16 /**< Operand size for maskmovdqu memory reference. \
+             */
```
Comment (derekbruening) [inline core/ir/opnd_api.h]: More

File: core/lib/dr_events.h (hunk 1 above)
Comment (derekbruening) [reply core/lib/dr_events.h:226]: The title looks unchanged. This is the PR title: that's what becomes the final commit message.

Comment (derekbruening) [reply core/lib/dr_events.h:226]: This also looks unchanged in the PR first description box, which is what becomes the final merge commit's message.

**Comment by AnandRaj2224** [comment]
@derekbruening,Thanks again for the review and clarifying the formatting issues. I really appreciate your guidance and patience as I learn the contribution process.

Regarding the specific formatting changes you pointed out (like the multi-line split for WINDOW_SUBDIR_FORMAT): You were absolutely right. My previous attempts at formatting were incorrect. To fix this properly, I followed the CI setup precisely:
Used Docker with an ubuntu:22.04 image.

Installed clang-format-14 using the exact repository source specified in the ci-clang-format.yml workflow.

Ran clang-format-14 -i on all the files I had modified.

This process did fix the incorrect multi-line splits you identified.

However, I observed that this correct run of clang-format-14 also removed all the # symbols I had manually added before instr_t in the Doxygen comments (which was the original purpose of this PR, addressing #4856).

Before I push the new commit containing these formatting changes (which does pass the CI checks but removes the # symbols), I wanted to ask for guidance:

what's the recommended way to handle the conflict with clang-format-14 ,Please let me know how you'd prefer to proceed.

File: clients/drcachesim/tracer/raw2trace_shared.h (hunk 3 above)
Comment (derekbruening) [reply clients/drcachesim/tracer/raw2trace_shared.h]: Please reply to the specific comment thread: the top level comments have no threading or resolution marking and get messy and hard to follow. Quoting the top level comment here:

> Regarding the specific formatting changes you pointed out (like the multi-line split for WINDOW_SUBDIR_FORMAT): You were absolutely right. My previous attempts at formatting were incorrect. To fix this properly, I followed the CI setup precisely: Used Docker with an ubuntu:22.04 image.
> 
> Installed clang-format-14 using the exact repository source specified in the ci-clang-format.yml workflow.
> 
> Ran clang-format-14 -i on all the files I had modified.
> 
> This process did fix the incorrect multi-line splits you identified.
> 
> However, I observed that this correct run of clang-format-14 also removed all the # symbols I had manually added before instr_t in the Doxygen comments (which was the original purpose of this PR, addressing #4856).

clang-format will not change anything but whitespace (or backslashes at ends of lines) so some other step must have removed the #.  Start over with the github version and just run clang-format.

File: core/lib/dr_events.h (hunk 1 above)
Comment (AnandRaj2224) [reply core/lib/dr_events.h:226]: done

Comment (AnandRaj2224) [reply core/lib/dr_events.h:226]: done

File: clients/drcachesim/tracer/raw2trace_shared.h (hunk 3 above)
Comment (AnandRaj2224) [reply clients/drcachesim/tracer/raw2trace_shared.h]: done

**Comment by AnandRaj2224** [comment]
@derekbruening, I've pushed the final fixes for the formatting and the missing newline. All CI checks are passing now. Thanks again for all your help

File: core/ir/opnd_api.h [hunk 5]
```diff
@@ -1697,11 +1697,17 @@ typedef enum {
 #endif /* X86 */
 
 #ifdef X86 /* We don't need these for ARM which uses clear numbering */
-#    define DR_REG_START_GPR DR_REG_XAX /**< Start of general register enum values */
+#    define DR_REG_START_GPR                                  \
```
Comment (derekbruening) [inline core/ir/opnd_api.h]: This file still has surprising changes: could you double check that this is what clang-format produces?

Comment (AnandRaj2224) [reply core/ir/opnd_api.h]: @derekbruening ,my apologies i missed the other broken macros,dont know what caused the multi-line splits and clang-format is not fixing them so i manually fixed the bad multi-line splits in all the files

**Comment by AnandRaj2224** [comment]
i have merged master to sync the branch. The new CI run is complete, and it looks like all the style errors are now fixed
The only remaining failures appear to be the known tests  that you mentioned.

Thanks again for all your help and patience

**Review by derekbruening — APPROVED** [review]
LGTM. Thanks again for contributing!
