### PR TITLE
i#7533: Pass the tracing window number in self-nudge to create a memdump.

### LINKED ISSUE #7553: Tracer may use an incorrect window directory to store memory dump files.
#7509 introduced a race condition affecting tracing_window access. 

This occurs when hit_instr_count_threshold() sends a self-nudge. Before event_nudge() can read tracing_window, a new window might open, incrementing its value. This leads to memory dump files being written to the incorrect (next) window's directory, or failing to write if that directory hasn't yet been created.

### PR DESCRIPTION
**Pull request by ivankyluk**
https://github.com/DynamoRIO/dynamorio/pull/7509 introduced a race condition affecting tracing_window access.

This occurs when hit_instr_count_threshold() sends a self-nudge. Before event_nudge() can read tracing_window, a new window might open, incrementing its value. This leads to memory dump files being written to the incorrect (next) window's directory, or failing to write if that directory hasn't yet been created.

Manual test:

Ran "drrun -t drmemtrace -offline -trace_instr_intervals_file %{TRACE_FILE} -memdump_on_window" to capture multiple traces and memory dumps with and without the change. 

There were missing memory dump files without the change. And all memory dump files were captured with the change.

Fixes #7553

### CODE REVIEW

File: clients/drcachesim/tracer/tracer.h [hunk 1]
```diff
@@ -181,6 +181,12 @@ enum {
     BBDUP_MODE_L0_FILTER = 4, /* Address tracing with L0_filter. */
 };
 
+/* dr_nudge_client takes a 64 bits argument. We use the most significant 8 bits as the
```
Comment (derekbruening) [inline clients/drcachesim/tracer/tracer.h]: nit: s/64 bits/bit/

Comment (ivankyluk) [reply clients/drcachesim/tracer/tracer.h]: Done.
