### PR TITLE
i#6953: Fix sigcontext test AVX error

### LINKED ISSUE #6953: linux.sigcontext test fails when compiled for AVX due to VZEROUPPER
When compiled for AVX, the linux.sigcontext test has a VZEROUPPER inserted after it fills all the YMM registers and just before its call to kill() to send the signal.  The signal handler then sees all the zero YMMH values and fails the test.

### PR DESCRIPTION
**Pull request by derekbruening**
Replaces a kill() with an inlined system call in the linux.sigcontext test to avoid failure when compiled for AVX only, as the compiler inserts VZEROUPPER there (VZEROUPPER is recommended by Intel to avoid a performance penalty when switching between upper-zeroing VEX-encoded XMM operations and legacy upper-preserving SSE* operations: so doing it at transitions to code you don't control makes sense).

Tested on a toolchain targeting AVX.

Fixes #6953

### CODE REVIEW

**Comment by derekbruening** [comment]
These arm runs seem to have a failing test every single PR now.  This one is the drstatecmp-fuzz timeout #6944.

File: suite/tests/linux/sigcontext.c [hunk 1]
```diff
@@ -323,8 +325,21 @@ main(int argc, char *argv[])
         MOVE_TO_YMM(buf, 15)
 #        endif
 #    endif
-        /* now make sure they show up in signal context */
-        kill(getpid(), SIGUSR2);
+        /* Now make sure they show up in the signal context.
+         * But, it's not safe to make a regular call, as the compiler will
+         * insert VZEROUPPER for some configurations.
```
Comment (abhinav92003) [inline suite/tests/linux/sigcontext.c:330]: Do we know why the compiler does that?

Comment (derekbruening) [reply suite/tests/linux/sigcontext.c:330]: Yes, it is recommended by Intel to avoid a performance penalty when switching between upper-zeroing VEX-encoded XMM operations and legacy upper-preserving SSE* operations: so doing it at transitions to code you don't control makes sense.

**Review by edeiana — APPROVED** [review]
