### PR TITLE
i#3369: relax sigstack assertion in signal handler if thread is at late-exit

### LINKED ISSUE #3369: client.annotation-concurrency.prof-pcs.thread-private failing on Travis
edb2eed6b74646dcf927 has introduced flakiness to test:

```
<Application /home/travis/build/DynamoRIO/dynamorio/build_debug-internal-64/suite/tests/bin/client.annotation-concurrency (23003).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/unix/signal.c:5248 dcontext == NULL || dcontext == GLOBAL_DCONTEXT || frame->uc.uc_stack.ss_sp == ((thread_sig_info_t *)dcontext->signal_field)->sigstack.ss_sp
(Error occurred @3403 frags)
```

Seems to be related to the new TLS magic check.

### PR DESCRIPTION
**Pull request by hgreving2304**
Fix a regression introduced in edb2eed6b74646dcf92718675ad2ec9a3fe2b674. If a thread is on its way to exit, the app's sigstack may be restored already. Relax the master_signal_handler assertion accordingly.

Fixes #3369

### CODE REVIEW

File: core/unix/signal.c [hunk 1]
```diff
@@ -5242,8 +5242,11 @@ master_signal_handler_C(byte *xsp)
 
     /* Ensure we didn't get the app's sigstack into our frame.  On Mac, the kernel
      * doesn't use the frame's uc_stack, so we limit this to Linux.
+     * The pointers may be different if a thread is on its way to exit, and the app's
+     * sigstack was already restored (i#3369).
      */
-    IF_LINUX(ASSERT(dcontext == NULL || dcontext == GLOBAL_DCONTEXT ||
+    IF_LINUX(ASSERT(dcontext == NULL || dcontext->is_exiting ||
+                    dcontext == GLOBAL_DCONTEXT ||
```
Comment (derekbruening) [inline core/unix/signal.c]: These need to be in the other order to avoid crashing when dcontext == GLOBAL_DCONTEXT (==-1)

Comment (hgreving2304) [reply core/unix/signal.c]: Thanks!
