### PR TITLE
i#3549 static inlining: set NOINLINE on DR stopping points.

### LINKED ISSUE #3549: Aggressive inlining breaks static detach
For static detach, we decide when to stop interpretting and start running code natively based on whether the App PC the next basic block to run is in a static set of PCs:

https://github.com/DynamoRIO/dynamorio/blob/ff837d4f64c0dfb0fab73d65d8884941dc9f4bae/core/dispatch.c#L249-L276

Unfortunately, when DR is compiled statically and link-time-optimizations are enabled, the application is not guaranteed to  actually run that code at that location: internally we call dr_app_stop_and_cleanup_with_stats in a helper function, and in some cases it is inlined into our helper function, causing our helper to be the one who calls directly into detach_on_permanent_stack. This ends up causing self-interp and crashes when we hit a TLS action while using drcachesim.

My first thought is to disable inlining for all of the relevant stopping points.

### PR DESCRIPTION
**Pull request by Carrotman42**
Optimizers could still ignore this information, and in particular
post-link optimizers will not even see this attribute in their input
binary in the first place. Those scenarios would need their own
optimizer-specific solution.

Fixes #3549

### CODE REVIEW

File: core/dynamo.c [hunk 1]
```diff
@@ -2763,21 +2765,24 @@ dr_app_start_helper(priv_mcontext_t *mc)
 }
 
 /* dummy routine that returns control to the app if it is currently
```
Comment (derekbruening) [inline core/dynamo.c]: style: s/dummy/Dummy/.  I guess ignore if you do not want to change anything.

File: core/dynamo.c [hunk 2]
```diff
@@ -1169,7 +1169,8 @@ dynamo_shared_exit(thread_record_t *toexit /* must ==cur thread for Linux */
     return SUCCESS;
```
Comment (derekbruening) [inline core/dynamo.c]: > Those scenarios would need their own optimizer-specific solution.

Not for this PR but a future one -- We should add that to the docs: though we never made particular docs for static-library DR so we need to do that first.  Maybe we should file an issue on doing that.

Comment (Carrotman42) [reply core/dynamo.c]: I have it in my to-do list to write the start of the doc, I'll make a note to add this caveat.

File: core/dynamo.c (hunk 1 above)
Comment (Carrotman42) [reply core/dynamo.c]: I figured I would leave the comment like this since that's how it was before this change but I'm happy to clean up.

Comment (derekbruening) [reply core/dynamo.c]: The style guide requires capitalization only for multi-sentence comments, so your change of adding another sentence is what makes the original need to be modified.
