### PR TITLE
i#2431: Fix decoding of crc32w

### LINKED ISSUE #2431: x86 decoder bug: data prefix on crc32 mis-parsed into illegal instr
First reported under Dr. Memory: https://github.com/DynamoRIO/drmemory/issues/1921

```
(gdb) set {unsigned char[400]}0x04311a0d = { 66, f2, f, 38, f1, c8, 90, 90, 90, 90 }
(gdb) x/3i 0x04311a0d
   0x4311a0d:	crc32w %ax,%ecx
   0x4311a13:	nop
```

```
  0x00000000004016f8  f2 0f 38 f1 c8       crc32  %eax %ecx -> %ecx
  0x00000000004016fd  66 f2 0f 38 f1 c8...??  <INVALID>
interp: invalid instr at 0x00000000004016fd
```

read_prefix_ext() tries to do the right thing wrt a data prefix as a
modifier vs an opcode specifier (the Intel docs are vague in some cases
there) there, but its initial index is constructed in what looks like the
wrong order where it should consider repne_prefix before data_prefix:

```
    int idx = (di->rep_prefix?1 :(di->data_prefix?2 :(di->repne_prefix?3 :0)));
```

It ends up thinking this is OP_movbe which has to take a memory dst and
that's why it calls it invalid.

### PR DESCRIPTION
**Pull request by derekbruening**
Updates the prefix order to properly decode crc32w.

Fixes the destination size codes for OP_crc32: the destination can
never shrink to 16 bits.  Resolves an old comment expressing confusion
about this where the Intel manual had a separate entry for a data
prefix, resulting in different codes than we need in our table.

Enables all the crc32w test cases in the binutils decenc tests.
Updates the expected test patterns.

Fixes #2431

### CODE REVIEW

File: core/arch/x86/decode_table.c [hunk 1]
```diff
@@ -5092,7 +5092,7 @@ const instr_info_t prefix_extensions[][12] = {
     {INVALID,  0xf338f018, "(bad)",   xx, xx, xx, xx, xx, no, x, NA},
     /* really this is regular data-size prefix */
     {OP_movbe, 0x6638f018, "movbe", Gw, xx, Mw, xx, xx, mrm, x, tpe[139][2]},
-    {OP_crc32, 0xf238f018, "crc32", Gv, xx, Eb, Gv, xx, mrm, x, END_LIST},
+    {OP_crc32, 0xf238f018, "crc32", Gd_q, xx, Eb, Gd_q, xx, mrm, x, END_LIST},
```
Comment (hgreving2304) [inline core/arch/x86/decode_table.c]: Looking at the manual, yes for the destination. But the source seems to be always 1-byte for the F0 version, and 2/4/8 bytes for the F1. Why Gd_q for the source?

File: core/arch/x86/decode_table.c [hunk 2]
```diff
@@ -5106,7 +5106,10 @@ const instr_info_t prefix_extensions[][12] = {
     {INVALID,  0xf338f118, "(bad)",   xx, xx, xx, xx, xx, no, x, NA},
     /* really this is regular data-size prefix */
     {OP_movbe, 0x6638f118, "movbe", Mw, xx, Gw, xx, xx, mrm, x, END_LIST},
-    {OP_crc32, 0xf238f118, "crc32", Gv, xx, Ev, Gv, xx, mrm, x, tpe[138][3]},
+    /* The Intel table separates out a data-size prefix into Ey and Ew: ours are combined,
+     * and thus we want Ev.
+     */
+    {OP_crc32, 0xf238f118, "crc32", Gd_q, xx, Ev, Gd_q, xx, mrm, x, tpe[138][3]},
```
Comment (hgreving2304) [inline core/arch/x86/decode_table.c]: See above.

File: core/arch/x86/decode_table.c (hunk 1 above)
Comment (derekbruening) [reply core/arch/x86/decode_table.c]: I think you're mixing up the separate source Eb from the destination-is-also-a-source.

Comment (hgreving2304) [reply core/arch/x86/decode_table.c]: I was! Ok, looks good.
