### PR TITLE
i#3911: Support NULL sigmask parameter passed to pselect, ppoll, epoll_pwait.

### LINKED ISSUE #3911: pselect6 with NULL {sigmask*,masksize} struct for 6th + 7th args does not work?
This program does not seem to run correctly under DynamioRIO:
```
#include <sys/select.h>
#include <sys/syscall.h>
#include <unistd.h>

int main()
{
  fd_set fds;
  struct timespec ts;

  FD_ZERO(&fds);
  ts.tv_sec = 2;
  ts.tv_nsec = 0;
  return syscall(SYS_pselect6, 0, 0, 0, &fds, &ts, 0);
}
```

I think it's because the pselect6 code in `pre_system_call` does not check for the sigmask parameter being NULL.

### PR DESCRIPTION
**Pull request by hgreving2304**
While the glibc wrapper seems to always pass a valid pointer to the kernel, the latter
does accept NULL pointers. This patch adds support to handle pselect6, ppoll, and
epoll_pwait system calls with NULL sigmask parameter.

Adds tests for above.

Fixes #3911

### CODE REVIEW

File: suite/tests/linux/syscall_pwait.cpp [hunk 1]
```diff
@@ -415,6 +415,40 @@ main(int argc, char *argv[])
 
     execute_subtest(main_thread, &test_set, psyscall_ppoll, true);
 
+    auto psyscall_raw_epoll_pwait = [test_set](bool nullsigmask) -> int {
+        int epoll_fd = epoll_create1(EPOLL_CLOEXEC);
+        struct epoll_event events;
+        return syscall(SYS_epoll_pwait, epoll_fd, &events, 24, 60000, 0);
+    };
+
+    auto psyscall_raw_pselect = [test_set](bool nullsigmask) -> int {
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.cpp]: This isn't really a NULL *sigmask*: it's a NULL *struct* holding the 6th and 7th args.  Best to test both.

File: core/unix/os.c [hunk 2]
```diff
@@ -7245,16 +7245,18 @@ pre_system_call(dcontext_t *dcontext)
...
         /* Refer to comments in SYS_ppoll above. Taking extra steps here due to struct
          * argument in pselect6.
          */
-        if (!d_r_safe_read(data_param, sizeof(data), &data)) {
-            LOG(THREAD, LOG_SYSCALLS, 2, "\treturning EFAULT to app for pselect6\n");
-            set_failure_return_val(dcontext, EFAULT);
-            DODEBUG({ dcontext->expect_last_syscall_to_fail = true; });
-            execute_syscall = false;
-            break;
+        if (data_param != NULL) {
```
Comment (derekbruening) [inline core/unix/os.c]: Hmm, I would have done what seems simpler and easier to read logic to me:
```C
if (data_param == NULL) {
    /* The kernel does not consider a NULL 6th+7th-args struct to be an error but just a NULL sigmask. */
    dcontext->sys_param4 = NULL;
    break;
}
```
WDYT?  Then no lifetime worries for code below, no worries about zero being the right value for missing fields in data_t, etc.

Comment (hgreving2304) [reply core/unix/os.c]: Ok, done.

File: suite/tests/linux/syscall_pwait.cpp (hunk 1 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.cpp]: Added, done.

**Comment by derekbruening** [comment]
You may want to update the commit description to clarify the glibc stuff: our bug was not as bad as this description makes it sound like since we do handle a null sigmask, and in fact we "handle" a null struct too: we just made the syscall fail, which doesn't match what the kernel does.  It's not like we crashed on a null value or sthg.
