### PR TITLE
i#7499: Update to Windows 2022 GA runners and fix build + run errors

### LINKED ISSUE #7499: Github Actions windows-2019 runner image dropping on 2025-06-30
Xref https://github.com/actions/runner-images/issues/12045

Our vs2019-64 and vs2019-32 CI workflows (https://github.com/DynamoRIO/dynamorio/blob/master/.github/workflows/ci-windows.yml) use windows-2019. They need to be updated to atleast the next one which is windows-2022.

There are brown-outs every Tuesday in June.

```
June 3 13:00 - 21:00 UTC
June 10 13:00-21:00 UTC
June 17 13:00-21:00 UTC
June 24 13:00-21:00 UTC
```

### LINKED ISSUE #7528: CRASH in drmemtrace, drcpusim, others with VS2022 toolchain due to CRT VirtualProtect before vmareas setup
Pasting from https://github.com/DynamoRIO/dynamorio/issues/7499#issuecomment-3049445825

tmate debug of silent exit of drmemtrace -- focusing on drmemtrace.dll entry crash:

```
privload_call_entry for drmemtrace.dll: reason=1
SYSLOG_INFORMATION: privload_call_entry for drmemtrace.dll: reason=1
Initialized 8 bytes @0x000002a3f8afc7b8 for TLS idx=4 in drmemtrace.dll
ASYNCH intercepted exception in thread 6148 at pc 0x0000000015100c57
SYSLOG_WARNING: ignoring failure of private library drmemtrace.dll entry (call reason=1)
privload_call_entry for drmemtrace.dll: reason=2
SYSLOG_INFORMATION: privload_call_entry for drmemtrace.dll: reason=2
SYSLOG_WARNING: ignoring failure of private library drmemtrace.dll entry (call reason=2)

get_dll_short_name(base_addr=0x00007ff647a30000) exports=1202798352 dll_name=drmemtrace.dll
get_dll_short_name(base_addr=0x00007ff647a30000) exports=1202798352 dll_name=drmemtrace.dll
get_dll_short_name(base_addr=0x00007ff647b40000) exports=1203560288 dll_name=drsyms.dll
get_dll_short_name(base_addr=0x00007ff647b40000) exports=1203560288 dll_name=drsyms.dll
get_dll_short_name(base_addr=0x00007ff647e20000) exports=1206046448 dll_name=drwrap.dll
get_dll_short_name(base_addr=0x00007ff647e20000) exports=1206046448 dll_name=drwrap.dll
get_dll_short_name(base_addr=0x00007ff647e40000) exports=1206174928 dll_name=drmgr.dll
get_dll_short_name(base_addr=0x00007ff647e40000) exports=1206174928 dll_name=drmgr.dll
get_dll_short_name(base_addr=0x00007ff647e60000) exports=1206273872 dll_name=drutil.dll
get_dll_short_name(base_addr=0x00007ff647e60000) exports=1206273872 dll_name=drutil.dll
get_dll_short_name(base_addr=0x00007ff647e70000) exports=1206335136 dll_name=drstatecmp.dll
get_dll_short_name(base_addr=0x00007ff647e70000) exports=1206335136 dll_name=drstatecmp.dll
get_dll_short_name(base_addr=0x00007ff647e80000) exports=1206419344 dll_name=drcovlib.dll
get_dll_short_name(base_addr=0x00007ff647e80000) exports=1206419344 dll_name=drcovlib.dll
get_dll_short_name(base_addr=0x00007ff647e90000) exports=1206538512 dll_name=drx.dll
get_dll_short_name(base_addr=0x00007ff647e90000) exports=1206538512 dll_name=drx.dll
get_dll_short_name(base_addr=0x00007ff647eb0000) exports=1206631584 dll_name=drreg.dll
get_dll_short_name(base_addr=0x00007ff647eb0000) exports=1206631584 dll_name=drreg.dll
get_dll_short_name(base_addr=0x00007ff647ec0000) exports=1206701888 dll_name=drbbdup.dll
get_dll_short_name(base_addr=0x00007ff647ec0000) exports=1206701888 dll_name=drbbdup.dll
get_dll_short_name(base_addr=0x00007ff826280000) exports=643356432 dll_name=KERNELBASE.dll
get_dll_short_name(base_addr=0x00007ff826280000) exports=643356432 dll_name=KERNELBASE.dll
get_dll_short_name(base_addr=0x00007ff828660000) exports=678394928 dll_name=KERNEL32.dll
get_dll_short_name(base_addr=0x00007ff828660000) exports=678394928 dll_name=KERNEL32.dll
get_dll_short_name(base_addr=0x00007ff828ce0000) exports=686005568 dll_name=ntdll.dll
get_dll_short_name(base_addr=0x00007ff828ce0000) exports=686005568 dll_name=ntdll.dll
add_process_lock: 0 lock 0x000002a3f8b26a60: name=HTLOCK_RANK(readwrite)@D:\a\dynamorio\dynamorio\core\hashtablex.h:539
rank=49 owner=6148 owning_dc=0x000002a3f8a9f080                 0x0 prev=0x0000000000000000
lock count_times_acquired=       1                              0                               0                              0                               0+2 HTLOCK_RANK(readwrite)@D:\a\dynamorio\dynamorio\core\hashtablex.h:539
get_allocation_size_ex pc=0x00007ff647a30000 base=0x00007ff647a30000 region=0x00007ff647a30000 size=0x1000
get_allocation_size_ex pc=0x00007ff647a30000 base=0x00007ff647a30000 region=0x00007ff647a30000 size=0x1000
ASYNCH intercepted exception in thread 6148 at pc 0x00007ff828cf9daa
        exception code = 0x000002a3c0000005, ExceptionFlags=0x0000000000000000
        record=0x0000000000000000, params=2
        PC 0x00007ff828cf9daa tried to write address 0x0000000000000024
```

```
runneradmin@fv-az844-677 MINGW64 /d/a/dynamorio/dynamorio/build_debug-internal-64
# '/c/Program Files (x86)/Windows Kits/10/Debuggers/x64/cdb.exe' clients/bin64/drmemtrace_launcher.exe "-dr" "D:\a\dynamorio\dynamorio\build_debug-internal-64" "-dr_ops" "" "-tracer" "D:\a\dynamorio\dynamorio\build_debug-internal-64/clients/lib64/debug/drmemtrace.dll" "-tracer_alt" "" "-dr_debug" "-offline" "--" "suite/tests/bin/simple_app"

.childdbg 1

g

$><d:\a\dynamorio\dynamorio\tools\windbg-scripts\load_syms64

.sympath d:\a\dynamorio\dynamorio\build_debug-internal-64\lib64\debug
.reload /f /i dynamorio.dll=15000000

1:004> kn
 # Child-SP          RetAddr               Call Site
00 00000004`f4afe230 00000000`15101e56     dynamorio!atomic_aligned_read_int+0x57
01 00000004`f4afe270 00000000`15102267     dynamorio!mutex_testlock+0x16
02 00000004`f4afe2b0 00000000`151f0181     dynamorio!d_r_read_lock+0x107
03 00000004`f4afe2f0 00000000`151f299a     dynamorio!pretend_writable_vm_area_overlap+0x21
04 00000004`f4afe330 00000000`151d0016     dynamorio!app_memory_protection_change_internal+0x127a
05 00000004`f4afe600 00000000`15428ef2     dynamorio!app_memory_protection_change+0x56
+*** WARNING: Unable to verify checksum for drmemtrace.dll
06 00000004`f4afe650 00007ff6`47ab3f89     dynamorio!redirect_VirtualProtect+0x92
07 00000004`f4afe6c0 00007ff6`47ac7aeb     drmemtrace!__acrt_initialize_winapi_thunks+0x29
08 00000004`f4afe700 00007ff6`47aab690     drmemtrace!__acrt_execute_initializers+0x6b
09 00000004`f4afe750 00007ff6`47a79601     drmemtrace!__acrt_initialize+0x20
0a 00000004`f4afe780 00007ff6`47a79d25     drmemtrace!__scrt_initialize_crt+0x31
0b 00000004`f4afe7b0 00007ff6`47a79cc7     drmemtrace!dllmain_crt_process_attach+0x15
0c 00000004`f4afe800 00007ff6`47a79f65     drmemtrace!dllmain_crt_dispatch+0x47
0d 00000004`f4afe840 00007ff6`47a7a0c2     drmemtrace!dllmain_dispatch+0x75
0e 00000004`f4afe890 00000000`1541b733     drmemtrace!_DllMainCRTStartup+0x32
0f 00000004`f4afe8c0 00000000`1523827e     dynamorio!privload_call_entry+0xd53
10 00000004`f4afeb10 00000000`15238023     dynamorio!privload_call_entry_if_not_yet+0x9e
11 00000004`f4afeb50 00000000`15235e7e     dynamorio!privload_load_finalize+0xb3
12 00000004`f4afebc0 00000000`15011f3c     dynamorio!loader_init_epilogue+0x10e
13 00000004`f4afed60 00000000`1501162e     dynamorio!dynamorio_app_init_part_two_finalize+0x5fc
14 00000004`f4aff6e0 00000000`15027236     dynamorio!dynamorio_app_init+0xe
15 00000004`f4aff710 00000000`153565b9     dynamorio!dynamorio_earliest_init_takeover_C+0x46
16 00000004`f4aff760 000001e2`527a1000     dynamorio!dynamorio_earliest_init_takeover+0x83


1:004> ?? pretend_writable_areas
struct vm_area_vector_t * 0x00000000`00000000


1:004> Uf 00007ff6`47ab3f89
drmemtrace!__acrt_initialize_winapi_thunks:
00007ff6`47ab3f60 4883ec38        sub     rsp,38h
00007ff6`47ab3f64 c744242400000000 mov     dword ptr [rsp+24h],0
00007ff6`47ab3f6c 4c8d4c2424      lea     r9,[rsp+24h]
00007ff6`47ab3f71 41b802000000    mov     r8d,2
00007ff6`47ab3f77 ba00010000      mov     edx,100h
00007ff6`47ab3f7c 488d0d7da00700  lea     rcx,[drmemtrace!function_pointers (00007ff6`47b2e000)]
00007ff6`47ab3f83 ff1517c30200    call    qword ptr [drmemtrace!_imp_VirtualProtect (00007ff6`47ae02a0)]
00007ff6`47ab3f89 85c0            test    eax,eax
00007ff6`47ab3f8b 7407            je      drmemtrace!__acrt_initialize_winapi_thunks+0x34 (00007ff6`47ab3f94)

drmemtrace!__acrt_initialize_winapi_thunks+0x2d:
00007ff6`47ab3f8d c644242001      mov     byte ptr [rsp+20h],1
00007ff6`47ab3f92 eb05            jmp     drmemtrace!__acrt_initialize_winapi_thunks+0x39 (00007ff6`47ab3f99)

drmemtrace!__acrt_initialize_winapi_thunks+0x34:
00007ff6`47ab3f94 c644242000      mov     byte ptr [rsp+20h],0

drmemtrace!__acrt_initialize_winapi_thunks+0x39:
00007ff6`47ab3f99 0fb6442420      movzx   eax,byte ptr [rsp+20h]
00007ff6`47ab3f9e 4883c438        add     rsp,38h
00007ff6`47ab3fa2 c3              ret
```

So that is one problem explained: VirtualProtect called by client lib entry before vmareas is initialized.

### PR DESCRIPTION
**Pull request by derekbruening**
Updates our Windows jobs to use the "windows-2022" Github runner.

Also fixes multiple build and run problems to get things green:
+ Fixes several compiler warnings.
+ Once of the fixed compiler warnings looks like a real bug in drwrap: looking at the wrong flags value.
+ Downgrades asserts on `!is_dynamo_address(dcontext->app_fls_data)` to ASSERT_CURIOSITY_ONCE as they fire in many tests and we do not have resources to root cause. This is related to #7220.
+ Fixes what is now filed as #7528: a crash in many drmemtrace, drcpusim, and other tests coming from the VS2022 toolchain CRT init calling VirtualProtect before vmareas setup.
+ Works around #6962 combase initializer silent crashes by not calling the combase initializers.
+ Adds the remaining failing tests to the ignore list, with #7529 covering fixing them.

Fixes #7499
Fixes #7528 
Issue: #7499, #7528, #7220, #6962

### CODE REVIEW

**Comment by derekbruening** [comment]
Should be green now if the windows test failures are deterministic.

File: core/dispatch.c [hunk 1]
```diff
@@ -1061,7 +1061,10 @@ dispatch_exit_fcache(dcontext_t *dcontext)
 
 #if defined(WINDOWS) && defined(DEBUG)
     if (should_swap_teb_nonstack_fields()) {
-        ASSERT(!is_dynamo_address(dcontext->app_fls_data));
+        /* XXX i#7220: We'd like to fix app_fls_data problems but for now we
```
Comment (abhinav92003) [inline core/dispatch.c]: Is this benign enough to be just an XXX and not a TODO?

File: core/win32/loader.c [hunk 2]
```diff
@@ -774,7 +774,10 @@ swap_peb_pointer_ex(dcontext_t *dcontext, bool to_priv, dr_state_flags_t flags)
         ASSERT(!is_dynamo_address((byte *)dcontext->app_stack_base - 1) ||
                IS_CLIENT_THREAD(dcontext));
         if (should_swap_teb_nonstack_fields()) {
-            ASSERT(!is_dynamo_address(dcontext->app_fls_data));
+            /* XXX i#7220: We'd like to fix app_fls_data problems but for now we
```
Comment (abhinav92003) [inline core/win32/loader.c]: Is this benign enough to be just an XXX and not a TODO?

File: core/dispatch.c (hunk 1 above)
Comment (derekbruening) [reply core/dispatch.c]: Made it a TODO.

File: core/win32/loader.c (hunk 2 above)
Comment (derekbruening) [reply core/win32/loader.c]: Made it a TODO.
