### PR TITLE
i#6744: Use xrstors32 and xsaves32 for invariant checker test on x86-32.

### LINKED ISSUE #6744: X86_32 Invariant checker test failure in check_kernel_syscall_trace: Too many read/write records
Skip INSTR_CREATE_xsaves64 and INSTR_CREATE_xrstors64 for X86_32 in invariant_checker_test.cpp::check_kernel_syscall_trace. 

The test has the following failure:

 11/371 Test  #11: tool.drcachesim.invariant_checker_test ...........................***Failed    0.04 sec

Recording |Too many read records| in T1 @ ref # 16 (6 instrs since timestamp 0)
Recording |Too many read records| in T1 @ ref # 17 (6 instrs since timestamp 0)
Recording |Too many read records| in T1 @ ref # 18 (6 instrs since timestamp 0)
Recording |Too many read records| in T1 @ ref # 19 (6 instrs since timestamp 0)
Recording |Too many write records| in T1 @ ref # 21 (7 instrs since timestamp 0)
Recording |Too many write records| in T1 @ ref # 22 (7 instrs since timestamp 0)
Recording |Too many write records| in T1 @ ref # 23 (7 instrs since timestamp 0)
Recording |Too many write records| in T1 @ ref # 24 (7 instrs since timestamp 0)
Unexpected error: Too many read records at ref: 16
Unexpected error: Too many read records at ref: 17
Unexpected error: Too many read records at ref: 18
Unexpected error: Too many read records at ref: 19
Unexpected error: Too many write records at ref: 21
Unexpected error: Too many write records at ref: 22
Unexpected error: Too many write records at ref: 23
Unexpected error: Too many write records at ref: 24

### PR DESCRIPTION
**Pull request by ivankyluk**
tool.drcachesim.invariant_checker_test  fails on x86-32 with the following error:

1/371 Test https://github.com/DynamoRIO/dynamorio/issues/11: tool.drcachesim.invariant_checker_test ...........................***Failed 0.04 sec

Recording |Too many read records| in T1 @ ref # 16 (6 instrs since timestamp 0)
Recording |Too many read records| in T1 @ ref # 17 (6 instrs since timestamp 0)
Recording |Too many read records| in T1 @ ref # 18 (6 instrs since timestamp 0)
Recording |Too many read records| in T1 @ ref # 19 (6 instrs since timestamp 0)
Recording |Too many write records| in T1 @ ref # 21 (7 instrs since timestamp 0)
Recording |Too many write records| in T1 @ ref # 22 (7 instrs since timestamp 0)
Recording |Too many write records| in T1 @ ref # 23 (7 instrs since timestamp 0)
Recording |Too many write records| in T1 @ ref # 24 (7 instrs since timestamp 0)
Unexpected error: Too many read records at ref: 16
Unexpected error: Too many read records at ref: 17
Unexpected error: Too many read records at ref: 18
Unexpected error: Too many read records at ref: 19
Unexpected error: Too many write records at ref: 21
Unexpected error: Too many write records at ref: 22
Unexpected error: Too many write records at ref: 23
Unexpected error: Too many write records at ref: 24

OP_xsaves64 and OP_xrstors32 are marked as o64 (X86_INVALID) in core/ir/x86/decode_table.c. 

instr_is_xsave() and instr_is_xrstor() return false on x86-32, hence not skipping the number of read/write record check in the invariant check on x86_32.

Use xrstors32 and xsaves32 instead for the test on x86_32.

Fixes #6744

### CODE REVIEW

File: clients/drcachesim/tests/invariant_checker_test.cpp [hunk 1]
```diff
@@ -3272,12 +3272,14 @@ check_kernel_syscall_trace(void)
         instr_t *sti = INSTR_CREATE_sti(GLOBAL_DCONTEXT);
         instr_t *nop1 = XINST_CREATE_nop(GLOBAL_DCONTEXT);
         instr_t *nop2 = XINST_CREATE_nop(GLOBAL_DCONTEXT);
+#        if defined(X64)
         instr_t *xrstors = INSTR_CREATE_xrstors64(
```
Comment (abhinav92003) [inline clients/drcachesim/tests/invariant_checker_test.cpp:3276]: Maybe use xrstors32 and xsaves32?

**Review by abhinav92003 — CHANGES_REQUESTED** [review]

File: clients/drcachesim/tests/invariant_checker_test.cpp (hunk 1 above)
Comment (ivankyluk) [reply clients/drcachesim/tests/invariant_checker_test.cpp:3276]: Done.

**Review by abhinav92003 — APPROVED** [review]
