### PR TITLE
i#3268: fix implied opcode lookup for VEX prefix.

### LINKED ISSUE #3268: byte0/byte1 lookup incorrect for instructions w/ VEX prefix in decode_fast
The 'interesting' array lookup is using the wrong opcode bytes for instructions w/ VEX prefix. Such instructions imply at least one leading opcode byte dependent on 2-byte or 3-byte VEX prefix and the 'mm' bits in the 2nd byte of the 3-byte VEX prefix.

See decode_fast.c:decode_sizeof.

### PR DESCRIPTION
**Pull request by hgreving2304**
Instructions with VEX prefix always imply at least one leading 0x0f opcode byte. This patch fixes looking up "interesting" flag for such instructions.

Fixes #3268

### CODE REVIEW

File: core/arch/x86/decode_fast.c [hunk 1]
```diff
@@ -1245,6 +1245,27 @@ intercept_fip_save(byte *pc, byte byte0, byte byte1)
...
+        break;
+    case 2:
+        *byte0 = 0x0f;
+        *byte1 = 0x38;
+        break;
+    case 3:
+        *byte0 = 0x0f;
+        *byte1 = 0x3a;
+        break;
+    default: CLIENT_ASSERT(false, "decode_cti: internal prefix error");
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/decode_fast.c]: Fixed

File: core/arch/x86/decode_fast.c [hunk 2]
```diff
@@ -1299,24 +1320,38 @@ decode_cti(dcontext_t *dcontext, byte *pc, instr_t *instr)
...
-     * fairly rare to begin with. */
-    if (prefixes > 0) {
-        for (i = 0; i < prefixes; i++, pc++) {
-            switch (*pc) {
-            case FS_SEG_OPCODE: instr_set_prefix_flag(instr, PREFIX_SEG_FS); break;
-            case GS_SEG_OPCODE: instr_set_prefix_flag(instr, PREFIX_SEG_GS); break;
-            default: break;
+     * fairly rare to begin with.
+     */
+
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/decode_fast.c]: Reverted.

File: core/arch/x86/decode_fast.c [hunk 3]
```diff
@@ -1299,24 +1320,38 @@ decode_cti(dcontext_t *dcontext, byte *pc, instr_t *instr)
...
+    if ((*pc == VEX_2BYTE_PREFIX_OPCODE) &&
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/decode_fast.c]: Ok, I didn't know. Looks like all the segment overrides and the address-size override (67H) is allowed. I will re-factor / fix

File: core/arch/x86/decode_fast.c [hunk 4]
```diff
@@ -1376,6 +1411,7 @@ decode_cti(dcontext_t *dcontext, byte *pc, instr_t *instr)
     if (interesting[byte0] == 0) {
         /* assumption: opcode already OP_UNDECODED */
         /* assumption: operands are already marked invalid (instr was reset) */
+        /* vex always implies at least an 0x0f opcode byte */
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/decode_fast.c]: Ok, it does seem misplaced. Removed.

File: core/arch/x86/opcode.h [hunk 5]
```diff
@@ -1433,6 +1433,8 @@ enum { /* FIXME: vs RAW_OPCODE_* enum */
        RET_NOIMM_OPCODE = 0xc3,
        RET_IMM_OPCODE = 0xc2,
        MOV_IMM_EDX_OPCODE = 0xba,
+       VEX_2BYTE_PREFIX_OPCODE = 0xc5,
+       VEX_3BYTE_PREFIX_OPCODE = 0xc4,
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/opcode.h]: I thought so, too, but no enums are used there. I can change all of them and add to this patch, sure.

File: core/arch/x86/decode_fast.c [hunk 6]
```diff
@@ -1299,24 +1320,38 @@ decode_cti(dcontext_t *dcontext, byte *pc, instr_t *instr)
...
-            default: break;
+     * fairly rare to begin with.
+     */
+
+    if ((*pc == VEX_2BYTE_PREFIX_OPCODE) &&
+        (X64_MODE_DC(dcontext) || TESTALL(MODRM_BYTE(3, 0, 0), *(pc + 1)))) {
+        byte0 = 0x0f;
+        byte1 = *(pc + prefixes);
+    } else if ((*pc == VEX_3BYTE_PREFIX_OPCODE) &&
+               (X64_MODE_DC(dcontext) || TESTALL(MODRM_BYTE(3, 0, 0), *(pc + 1)))) {
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/decode_fast.c]: One reason why I had to duplicate this is that I didn't want to change decode_sizeof. Ideally, decode_sizeof could already return vex_mm bits, isvex (isexex later) and/or the vex position. I should add a function that does this and is called by (but keep as-is) the API-version of decode_sizeof

File: core/arch/x86/decode_fast.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/decode_fast.c]: Fixed.

File: core/arch/x86/decode_fast.c [hunk 7]
```diff
@@ -1299,24 +1320,38 @@ decode_cti(dcontext_t *dcontext, byte *pc, instr_t *instr)
...
+        byte vex_mm = *(pc + 1) & 0x1f;
+        get_implied_mm_vex_opcode_bytes(pc, prefixes, vex_mm, &byte0, &byte1);
+    } else {
+        if (prefixes > 0) {
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/decode_fast.c]: See above.

File: core/arch/x86/decode_fast.c [hunk 8]
```diff
@@ -1299,24 +1320,38 @@ decode_cti(dcontext_t *dcontext, byte *pc, instr_t *instr)
...
-    byte1 = *(pc + 1);
+        byte0 = *pc;
+        byte1 = *(pc + 1);
+    }
 
     /* eflags analysis
      * we do this even if -unsafe_ignore_eflags b/c it doesn't cost that
      * much and we can use the analysis to detect any bb that reads a flag
      * prior to writing it
+     * XXX: I don't think this is working correctly for vex (and definitely
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/decode_fast.c]: Fixed. i#3267

File: core/arch/x86/opcode.h (hunk 5 above)
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/opcode.h]: Added enums.

File: core/arch/x86/decode_fast.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/decode_fast.c]: Re-factored into _internal function w/o the need for an additional prefix lookup.

File: core/arch/x86/opcode.h [hunk 9]
```diff
@@ -1387,8 +1387,12 @@ enum {
 };
 
 enum { /* FIXME: vs RAW_OPCODE_* enum */
+       CS_SEG_OPCODE = 0x2e,
```
Comment (derekbruening) [inline core/arch/x86/opcode.h]: `= RAW_PREFIX_jcc_not_taken`.  (Do not merge the 2 enums in this PR -- even this addition is a little off track for this PR and could be separated.)

File: core/arch/x86/opcode.h [hunk 10]
```diff
@@ -1387,8 +1387,12 @@ enum {
...
+       DS_SEG_OPCODE = 0x3e,
```
Comment (derekbruening) [inline core/arch/x86/opcode.h]: `= RAW_PREFIX_jcc_taken`

File: core/arch/x86/decode_fast.c [hunk 11]
```diff
@@ -1282,7 +1316,9 @@ decode_cti(dcontext_t *dcontext, byte *pc, instr_t *instr)
      * on every return. */
     uint rip_rel_pos;
 #endif
-    int sz = decode_sizeof(dcontext, pc, &prefixes _IF_X64(&rip_rel_pos));
+    byte vex = 0, vex_mm = 0;
+    int sz = decode_sizeof_internal(dcontext, pc, &prefixes, &vex,
+                                    &vex_mm _IF_X64(&rip_rel_pos));
```
Comment (derekbruening) [inline core/arch/x86/decode_fast.c]: I don't know, it seems simpler, cleaner, and my intuition says it's more efficient to leave decode_sizeof as it is and put in the change I originally suggested, just checking for the vex prefixes in the loop on line 1342 which is already checking prefixes.  What was your logic for doing it this way instead?  Adding extra conditionals and stores to decode_sizeof seems to add more code complexity and probably overhead (have to measure to say for sure) than adding some case statements to the existing loop (or change to if-else if compiler isn't doing that for opt).

File: core/arch/x86/opcode.h (hunk 9 above)
Comment (derekbruening) [reply core/arch/x86/opcode.h]: No, just set to the existing one (hence quoted snippet)

Comment (hgreving2304) [reply core/arch/x86/opcode.h]: Do you want
[..]
CS_SEG_OPCODE = RAW_PREFIX_jcc_not_taken,
[..]
or
not have CS_SEG_OPCODE at all and use RAW_PREFIX_jcc_not_taken in decode_fast
?

File: core/arch/x86/decode_fast.c (hunk 11 above)
Comment (hgreving2304) [reply core/arch/x86/decode_fast.c]: Well the rationale was since decode_sizeof already looks at the prefixes and decodes vex_mm, why duplicate it and do it again. So I moved it into an internal function. I don't have a strong preference, the original suggestion will work as well, except it doesn't check the ordering of the prefixes (but neither does decode_sizeof).

File: core/arch/x86/opcode.h (hunk 9 above)
Comment (derekbruening) [reply core/arch/x86/opcode.h]: My original suggestion was trying to be precise with the quoted code. 
 Trying again: `s/0x2e/RAW_PREFIX_jcc_not_taken/` to avoid having 0x2e twice.

Comment (hgreving2304) [reply core/arch/x86/opcode.h]: Done.

**Comment by hgreving2304** [comment]
PTAL

File: core/arch/x86/decode_fast.c [hunk 12]
```diff
@@ -472,7 +472,7 @@ static const byte xop_a_extra[256] = {
  */
 int
 decode_sizeof(dcontext_t *dcontext, byte *start_pc,
-              int *num_prefixes _IF_X64(uint *rip_rel_pos))
+              int *num_prefixes _IF_X86_64(uint *rip_rel_pos))
```
Comment (derekbruening) [inline core/arch/x86/decode_fast.c]: This is a nop: prob best for history to not change the line

File: core/arch/x86/decode_fast.c [hunk 13]
```diff
@@ -1291,32 +1313,47 @@ decode_cti(dcontext_t *dcontext, byte *pc, instr_t *instr)
...
+            case VEX_2BYTE_PREFIX_OPCODE:
+                /* VEX 2-byte prefix implies 0x0f opcode */
+                byte0 = 0x0f;
+                byte1 = *(pc + prefixes);
+                break;
+            case VEX_3BYTE_PREFIX_OPCODE: {
+                /* VEX 3-byte prefix implies instruction opcodes by setting mm bits */
+                byte vex_mm = (byte)(*(pc + 1) & 0x1f);
+                get_implied_mm_vex_opcode_bytes(pc, prefixes, vex_mm, &byte0, &byte1);
+                break;
```
Comment (derekbruening) [inline core/arch/x86/decode_fast.c]: It would be nice if there were some test that showed the prior bug and proved that this fixes it but we don't have good decode_cti tests, and it's not a public function so it's not as simple to add to the api.ir test.  Please state in the commit message how you tested this.

File: core/arch/x86/decode_fast.c (hunk 12 above)
Comment (hgreving2304) [reply core/arch/x86/decode_fast.c]: Reverted.

File: core/arch/x86/decode_fast.c (hunk 13 above)
Comment (hgreving2304) [reply core/arch/x86/decode_fast.c]: Ok. So far only manually debugged and "verified" with dis-udis86-randtest.raw and an own test I wrote with intrinsics.

**Comment by derekbruening** [comment]
The "Fixes #3268" was lost in the final commit message...
