### PR TITLE
i#3333: cut runtime of client.mangle_suspend.

### LINKED ISSUE #3333: client.mangle_suspend test failing on cdash machine
This CDash machine didn't run over the weekend so this is the first time it ran this new mangle_suspend test, I believe.

debug-internal-64 hung and timed out it looks like:

http://dynamorio.org/CDash/testDetails.php?test=608025&build=40374

```
Exit Value	9
Fail Reason	Required regular expression not found.Regex=[^Test 1 finished
Test 2 finished
$
]

Test output
Test 1 finished
```

### PR DESCRIPTION
**Pull request by hgreving2304**
Limits the runtime of client.mangle_suspend test and adds sched_yield to wait loops.

Fixes #3333

### CODE REVIEW

File: suite/tests/client-interface/mangle_suspend.c [hunk 1]
```diff
@@ -34,6 +34,11 @@
  * by asynch interrupt.
  */
 
+/* clang-format off */
+/* XXX: clang-format incorrectly detected a tab difference at "clang-format on"
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.c]: A "tab difference"?  As in, there are tab characters somewhere?  This disabling of clang-format for all the code here seems like overkill.  Are you sure there's not some other solution?  I don't really understand the problem though.  Do you mean clang-format-diff?

File: suite/tests/client-interface/mangle_suspend.c [hunk 2]
```diff
@@ -34,6 +34,11 @@
...
+ * below. This is why "clang-format off" has been moved outside the ifdef until
+ * bug is fixed.
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.c]: nit: the bug

Also, if this is a bug in clang-format-diff and this comment expects it to be fixed, presumably it is filed somewhere (else it would never be fixed?) and we can cite that here?

File: suite/tests/client-interface/mangle_suspend.c (hunk 1 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.c]: It's the same issue as a while ago in drreg-test.c. You actually wanted to 'clang-format off' the entire file back then per-review. I'll re-phrase the comment, it's not really a 'tab difference' per se.

File: suite/tests/client-interface/mangle_suspend.c (hunk 2 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.c]: Yes, I can file this. Since the source file of this test is open source, I can link/attach this I assume?

Comment (derekbruening) [reply suite/tests/client-interface/mangle_suspend.c]: Yes, this is public.

File: suite/tests/client-interface/mangle_suspend.c (hunk 1 above)
Comment (derekbruening) [reply suite/tests/client-interface/mangle_suspend.c]: I see, ok.

File: suite/tests/client-interface/mangle_suspend.c (hunk 2 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.c]: Merging now and filing clang bug shortly.
