### PR TITLE
i#2449 memval_simple: fix missing register restoration

### LINKED ISSUE #2449: ASSERT in memval_simple client
Hi all,
I  tried to use memval_simple.c, and got the error:
Data file /home/ubuntu/Dynamorio/dynamorio/bin32/../api/bin/memval_simple.xxxx.03169.0000.log created
ASSERT FAILURE: /home/ubuntu/Dynamorio/dynamorio/api/samples/memval_simple.c:147: write_base <= write_ptr ()

I compiled the source code on ubuntu 14.04, 32bit

write_base buffer is used to store the value of memory address?

Anyone can help me solve the problem?

### PR DESCRIPTION
**Pull request by toshipiazza**
If `instrument_post_write` and `instrument_mem` both reserve the same
register via drreg, drreg may elide a register save and restore in
between them. If the application instruction relies on this particular
register as well, `drutil_insert_get_mem_addr` will also compute the
address incorrecly.

We fix this by restoring the app register explicitly.

Fixes #2449

### CODE REVIEW

File: api/samples/memval_simple.c [hunk 1]
```diff
@@ -403,7 +421,7 @@ event_exit(void)
 DR_EXPORT void
 dr_client_main(client_id_t id, int argc, const char *argv[])
 {
-    drreg_options_t ops = {sizeof(ops), 3 /*max slots needed*/, false};
+    drreg_options_t ops = {sizeof(ops), 3 /*max slots needed*/, true};
```
Comment (derekbruening) [inline api/samples/memval_simple.c]: Wait, I missed this part of the change -- why do we need this?  I thought memval_simple managed to work within drreg's framework by not inserting post-instr instru until it hit the next instr, so it was always doing pre-instr instru, which is what drreg assumes.

Comment (toshipiazza) [inline api/samples/memval_simple.c]: Sorry, probably should've made a specific comment on this. I saw this entry in the docs for `drreg_get_app_value`

> If `app_reg` is a dead register, `DRREG_ERROR_NO_APP_VALUE` may be returned. Set conservative in `drreg_options_t` to avoid this error

I assumed this meant conservative was required by the sample.

Comment (toshipiazza) [inline api/samples/memval_simple.c]: That being said, I can try using the default non-conservative approach and hope for the best, since logically `app_reg` should never be dead--we only call `drreg_get_app_value` when `where` depends on a register that `drreg` has reserved.

Comment (derekbruening) [inline api/samples/memval_simple.c]: If it were dead why would we need the value?  You'd only need it if being dead is somehow wrong: e.g., if the app goes and reads the seemingly-dead value in a fault handler: an extreme corner case we have never seen.

It should be impossible to be simultaneously dead and to satisfy your opnd_uses_reg check, right?

Comment (toshipiazza) [inline api/samples/memval_simple.c]: Gotcha, makes sense. I'll run some quick tests to make sure everything still works, but it looks like the conservative setting is *not* needed, as you said.

**Comment by toshipiazza** [comment]
Build failure was client.timer on OSX. Already redirected this travis case to the relevant issue.

Still working on making a functional test case. Unfortunately it's difficult as it relies on `drreg` reserving a certain register twice in a row (specifically `eax` or `ebx`), which I don't know is easily controllable. Any suggestions?

**Comment by derekbruening** [comment]
> Still working on making a functional test case. Unfortunately it's difficult as it relies on drreg reserving a certain register twice in a row (specifically eax or ebx), which I don't know is easily controllable. Any suggestions?

Short of having test-specific code in drx to set the vector, you'd have to target drreg's selection scheme by having eax and ebx be dead or the least-used in the block.

File: suite/tests/client-interface/memval-test.c [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+        PUSH_SEH(REG_XBP)
+        PUSH_SEH(REG_XSI)
+        PUSH_SEH(REG_XDI)
+        sub      REG_XSP, FRAME_PADDING /* align */
+        mov      REG_XBP, REG_XSP
+        sub      REG_XSP, 0x100
+        END_PROLOG
+        jmp      setup_test
+
+# if 0
```
Comment (derekbruening) [inline suite/tests/client-interface/memval-test.c]: Did you mean this to be disabled?  If so please add a comment explaining why it's disabled yet still here.

Comment (toshipiazza) [inline suite/tests/client-interface/memval-test.c]: Sorry, that was just for a very long comment. I can wrap it in `/* */` instead

Comment (derekbruening) [inline suite/tests/client-interface/memval-test.c]: Yes, I think a `/* */` comment would be clearer.

**Comment by toshipiazza** [comment]
Will look at the test failures shortly, though none seem directly related to my commit (except the compilation failure on OSX)

**Comment by toshipiazza** [comment]
One test failure on Windows was known to the issue tracker but not ignored in Appveyor--added the one failure to the existing issue (`api.detach`). The others failures, `client.loader` and `client.pcache-use`, were ignored.

**Comment by toshipiazza** [comment]
As for the OSX build failure, @derekbruening do you have any clue why this is breaking? Judging from the error nasm is being used as opposed to gas -- so how do the other tests (i.e. `drreg-test`) compile on OSX?

**Comment by derekbruening** [comment]
The memory reference displacements should be inside the brackets.  Also for Windows the hex literals need to use HEX().

File: suite/tests/client-interface/memval-test.c (hunk 2 above)
Comment (toshipiazza) [inline suite/tests/client-interface/memval-test.c]: Done.

**Comment by toshipiazza** [comment]
Oddly enough, GitHub still asked me to update my branch, even though I had done a `git rebase origin master` beforehand. That's why fhahn's commits appear in my checkin, and also why the merge commit has no diff.

**Comment by toshipiazza** [comment]
Can't catch a break, looks like Appveyor failed with another known issue, `win32.earlythread` which is #2286

**Comment by derekbruening** [comment]
> Oddly enough, GitHub still asked me to update my branch, even though I had done a git rebase origin master beforehand. That's why fhahn's commits appear in my checkin, and also why the merge commit has no diff.

I assume you mean that you rebased before sharing the branch and not after.  Note that our workflow recommends never directly running rebase: "git pullall" is there to help avoid accidentally rebasing a shared branch.

This squash-and-merge workflow requires a fast-foward merge, which requires a completely up to date branch, so any subsequent commit to master will render your branch "out of date".

File: suite/tests/CMakeLists.txt [hunk 3]
```diff
@@ -2305,7 +2305,14 @@ if (CLIENT_INTERFACE)
                 "-thread_private -prof_pcs -opt_cleancall 0" "")
             endif (NOT X64)
           endif (UNIX AND NOT ARM)
-        endif ()
+        elseif (sample STREQUAL "memval_simple")
+          # i#2449: only witnessed crash on 32-bit linux
```
Comment (derekbruening) [inline suite/tests/CMakeLists.txt]: Unless it's extra work wouldn't we want to run the test for as many platforms as possible?  Porting it to ARM is work but x86_64 should "just work"?

**Comment by derekbruening** [comment]
I will override the appveyor failure

File: suite/tests/CMakeLists.txt (hunk 3 above)
Comment (toshipiazza) [inline suite/tests/CMakeLists.txt]: True, x86_64 should just work. However, I assumed that enabling this test for 64-bit would not yield much information, as we could never get `memval_simple` to crash on 64-bit to begin with (probably due to a drastic increase in the number of registers available to `drreg`). If you'd like I can enable it in a new PR.

Comment (derekbruening) [inline suite/tests/CMakeLists.txt]: Not worth it.

**Comment by junwei-wang** [comment]
I compile this sample with DynamoRIO-Linux-7.0.0-RC1 and run this client with /bin/ls and /bin/pwd, it seems this client is too slow to use.

**Comment by derekbruening** [comment]
> I compile this sample with DynamoRIO-Linux-7.0.0-RC1 and run this client with /bin/ls and /bin/pwd, it seems this client is too slow to use.

Please provide actual numbers and context.  Certainly the tool is fast enough on "pwd" itself, and that tiny app is too short to serve as a benchmark for estimating typical overheads on larger apps.

**Comment by junwei-wang** [comment]
It takes more than 10 minutes and I quit without success. It ate a lot of
memory and CPU.

But if I build it with the source code, it is then fast enough.

**Comment by derekbruening** [comment]
> It takes more than 10 minutes and I quit without success. It ate a lot of memory and CPU.

It should take less than half a second so clearly something else was going on unrelated to the tool's actual operation: a livelock or something spinning.  Please file a separate issue with details of exactly how it was built and run and ideally callstacks while it's spinning.
