### PR TITLE
i#3201: In non-static/Linux, read library name from maps instead of using hard-coded name.

### LINKED ISSUE #3201: Resolve hard-coded libdynamorio name in memquery.
At least in Linux.

Currently, the library name is hard-coded as DYNAMORIO_LIBRARY_NAME and is used in compares in memquery. If the actual name diverts from this, the loader bails / takes the wrong path (i.e. falsely detecting app maps overlap). 

Support drrun -use_dll ./randomname.so -- <app>
and drrun -use_dll ./libdynamorio.so -- <app> w/ libdynamorio.so being symlink to randomname.so.

### PR DESCRIPTION
**Pull request by hgreving2304**
Use get_dynamorio_library_path() instead of DYNAMORIO_LIBRARY_NAME in Linux memquery.

Fixes #3201

### CODE REVIEW

File: core/unix/memquery.c [hunk 1]
```diff
@@ -144,6 +145,9 @@ memquery_library_bounds_by_iterator(const char *name, app_pc *start /*IN/OUT*/,
                         /* we keep the last '/' at end */
                         ++slash;
                         strncpy(dst, src, MIN(dstsz, (slash - src)));
+                        if (filename != NULL)
```
Comment (derekbruening) [inline core/unix/memquery.c]: style violation: {} on multi-line body

File: core/unix/memquery.c [hunk 2]
```diff
@@ -144,6 +145,9 @@ memquery_library_bounds_by_iterator(const char *name, app_pc *start /*IN/OUT*/,
...
+                            /* slash is filename */
+                            strncpy(filename, slash, MIN(strlen(slash), filename_size));
```
Comment (derekbruening) [inline core/unix/memquery.c]: bug: fails to set terminating null char if it maxes out (done below for dst)

File: core/unix/memquery.c (hunk 1 above)
Comment (derekbruening) [inline core/unix/memquery.c]: `&& slash != NULL`?  Else change the `slash != NULL` to an invariant by removing `_CURIOSITY`.

File: core/unix/memquery.c [hunk 3]
```diff
@@ -55,7 +55,8 @@
 int
 memquery_library_bounds_by_iterator(const char *name, app_pc *start /*IN/OUT*/,
                                     app_pc *end /*OUT*/, char *fullpath /*OPTIONAL OUT*/,
-                                    size_t path_size)
+                                    size_t path_size, char *filename,
```
Comment (derekbruening) [inline core/unix/memquery.c]: Mirror the `OPTIONAL OUT` of fullpath

File: core/unix/loader.c [hunk 4]
```diff
@@ -1574,7 +1574,7 @@ dynamorio_lib_gap_empty(void)
         while (memquery_iterator_next(&iter) && iter.vm_start < dr_end) {
             if (iter.vm_start >= dr_start && iter.vm_end <= dr_end &&
                 iter.comment[0] != '\0' &&
-                strstr(iter.comment, DYNAMORIO_LIBRARY_NAME) == NULL) {
+                strstr(iter.comment, get_dynamorio_library_path()) == NULL) {
```
Comment (derekbruening) [inline core/unix/loader.c]: I worry that this won't get inlined or sthg inside this loop -- maybe worth explicitly putting into a local?

File: core/unix/loader.c [hunk 5]
```diff
@@ -1778,7 +1778,7 @@ privload_early_inject(void **sp, byte *old_libdr_base, size_t old_libdr_size)
                     (iter.comment[0] == '\0' /* .bss */ ||
                      /* The kernel sometimes mis-labels our .bss as "[heap]". */
                      strcmp(iter.comment, "[heap]") == 0 ||
-                     strstr(iter.comment, DYNAMORIO_LIBRARY_NAME) != NULL)) {
+                     strstr(iter.comment, get_dynamorio_library_path()) != NULL)) {
```
Comment (derekbruening) [inline core/unix/loader.c]: Ditto, ditto

File: core/unix/memquery.h [hunk 6]
```diff
@@ -104,15 +104,17 @@ memquery_iterator_next(memquery_iter_t *iter);
  */
 int
 memquery_library_bounds(const char *name, app_pc *start /*IN/OUT*/, app_pc *end /*OUT*/,
-                        char *fullpath /*OPTIONAL OUT*/, size_t path_size);
+                        char *fullpath /*OPTIONAL OUT*/, size_t path_size,
```
Comment (derekbruening) [inline core/unix/memquery.h]: Hmm, should we s/path/dir/ to make it clear it does not have the name?  So `fulldir` and `dir_size` (or `fulldir_size`), here and the other places.

File: core/unix/os.c [hunk 7]
```diff
@@ -8765,11 +8765,24 @@ get_dynamo_library_bounds(void)
     check_start = dynamo_dll_start;
     dynamorio_libname = IF_UNIT_TEST_ELSE(UNIT_TEST_EXE_NAME, DYNAMORIO_LIBRARY_NAME);
 #    endif /* STATIC_LIBRARY */
+
+#    if !defined(STATIC_LIBRARY) && defined(LINUX)
```
Comment (derekbruening) [inline core/unix/os.c]: It seems like there's no need for the ifdef: other configs can use this same new code, right?

File: core/unix/os.c [hunk 8]
```diff
@@ -8869,7 +8882,8 @@ get_application_base(void)
         const char *name = get_application_name();
         if (name != NULL && name[0] != '\0') {
             DEBUG_DECLARE(int count =)
-            memquery_library_bounds(name, &executable_start, &executable_end, NULL, 0);
+            memquery_library_bounds(name, &executable_start, &executable_end, NULL, 0,
+                                    NULL, 0);
             ASSERT(count > 0 && executable_start != NULL);
         }
 #    else
```
Comment (derekbruening) [inline core/unix/os.c]: I thought this would replace the other uses of `DYNAMORIO_LIBRARY_NAME` and remove the define?

(I assumed the issue covered that.  If that is too involved this would become incremental for that issue and no longer `Fixes`.)

File: core/unix/loader.c (hunk 4 above)
Comment (derekbruening) [inline core/unix/loader.c]: So this is now the full path: does `strstr` still make sense or should it be `strcmp`?

File: core/unix/os.c [hunk 9]
```diff
@@ -8765,11 +8765,24 @@ get_dynamo_library_bounds(void)
...
     res = memquery_library_bounds(dynamorio_libname, &check_start, &check_end,
                                   dynamorio_library_path,
-                                  BUFFER_SIZE_ELEMENTS(dynamorio_library_path));
+                                  BUFFER_SIZE_ELEMENTS(dynamorio_library_path), NULL, 0);
+#    endif
+
     LOG(GLOBAL, LOG_VMAREAS, 1, PRODUCT_NAME " library path: %s\n",
         dynamorio_library_path);
+    LOG(GLOBAL, LOG_VMAREAS, 1, PRODUCT_NAME " library file path: %s\n",
+        dynamorio_library_filepath);
```
Comment (derekbruening) [inline core/unix/os.c]: Shouldn't be printed until it's set below!

File: core/unix/os.c [hunk 10]
```diff
@@ -8765,11 +8765,24 @@ get_dynamo_library_bounds(void)
     check_start = dynamo_dll_start;
     dynamorio_libname = IF_UNIT_TEST_ELSE(UNIT_TEST_EXE_NAME, DYNAMORIO_LIBRARY_NAME);
 #    endif /* STATIC_LIBRARY */
+
+#    if !defined(STATIC_LIBRARY) && defined(LINUX)
+    static char dynamorio_libname_buf[MAXIMUM_PATH];
```
Comment (derekbruening) [inline core/unix/os.c]: See below: I thought we'd have a new file-scope place for the basename and replace `DYNAMORIO_LIBRARY_NAME` with it.

File: core/unix/memquery.c (hunk 1 above)
Comment (hgreving2304) [reply core/unix/memquery.c]: Done

File: core/unix/memquery.c (hunk 2 above)
Comment (hgreving2304) [reply core/unix/memquery.c]: Done

File: core/unix/memquery.c (hunk 1 above)
Comment (hgreving2304) [reply core/unix/memquery.c]: Done

File: core/unix/memquery.c (hunk 3 above)
Comment (hgreving2304) [reply core/unix/memquery.c]: Done

File: core/unix/loader.c (hunk 4 above)
Comment (hgreving2304) [reply core/unix/loader.c]: Done

File: core/unix/os.c (hunk 7 above)
Comment (hgreving2304) [reply core/unix/os.c]: I think I need to keep
#ifndef  STATIC_LIBRARY
    dynamorio_libname = IF_UNIT_TEST_ELSE(UNIT_TEST_EXE_NAME, dynamorio_libname_buf);
#endif

File: core/unix/os.c (hunk 8 above)
Comment (hgreving2304) [reply core/unix/os.c]: Ok let me look at that.

File: core/unix/loader.c (hunk 4 above)
Comment (hgreving2304) [reply core/unix/loader.c]: Good point. I think it could be strcmp, i'll check and resolve if true.

File: core/unix/os.c (hunk 9 above)
Comment (hgreving2304) [reply core/unix/os.c]: Thanks.

File: core/unix/loader.c (hunk 4 above)
Comment (hgreving2304) [reply core/unix/loader.c]: Done.

File: core/unix/os.c (hunk 10 above)
Comment (hgreving2304) [reply core/unix/os.c]: (Removed)

File: core/unix/memquery.h (hunk 6 above)
Comment (hgreving2304) [reply core/unix/memquery.h]: Ok

File: core/unix/os.c (hunk 8 above)
Comment (hgreving2304) [reply core/unix/os.c]: I have removed DYNAMORIO_LIBRARY_NAME, but only on Unix.

File: core/unix/os.c [hunk 11]
```diff
@@ -5684,20 +5684,22 @@ add_dr_env_vars(dcontext_t *dcontext, char *inject_library_path, const char *app
             "WARNING: execve env does NOT preload DynamoRIO, forcing it!\n");
         if (preload >= 0) {
             /* replace the existing preload */
+            char *dynamorio_library_path = get_dynamorio_library_path();
             sz = strlen(envp[preload]) + strlen(DYNAMORIO_PRELOAD_NAME) +
-                strlen(DYNAMORIO_LIBRARY_NAME) + 3;
+                strlen(dynamorio_library_path) + 3;
```
Comment (derekbruening) [inline core/unix/os.c]: This direct ref is relying on the call above?  I guess it's technically correct but it seems fragile, and the uses in the else below are not guaranteed to have called get_dynamorio_library_path() right?  Maybe have a local var and call at top of the routine?

File: core/unix/loader.c [hunk 12]
```diff
@@ -1571,10 +1571,11 @@ dynamorio_lib_gap_empty(void)
         byte *dr_start = get_dynamorio_dll_start();
         byte *dr_end = get_dynamorio_dll_end();
         byte *gap_start = dr_start;
+        char *dynamorio_library_path = get_dynamorio_library_path();
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/loader.c]: Done

File: core/unix/loader.c [hunk 13]
```diff
@@ -1771,14 +1772,15 @@ privload_early_inject(void **sp, byte *old_libdr_base, size_t old_libdr_size)
         /* i#2641: we can't blindly unload the whole region as vvar+vdso may be
          * in the text-data gap.
          */
+        char *dynamorio_library_path = get_dynamorio_library_path();
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/loader.c]: Done

File: core/unix/os_exports.h [hunk 14]
```diff
@@ -52,10 +52,8 @@
 
 #ifdef MACOS
```
Comment (derekbruening) [inline core/unix/os_exports.h]: Be sure to watch the Mac Travis test on the merge to master (xref issues on Mac delays so we relegated to master-only, and issue on Travis not sending us emails on Mac failures...)

Comment (derekbruening) [reply core/unix/os_exports.h]: (Alternatively temporarily enable Mac in .travis.yml for this PR)

File: core/unix/memquery_linux.c [hunk 15]
```diff
@@ -323,9 +323,11 @@ memquery_iterator_next(memquery_iter_t *iter)
  */
 int
 memquery_library_bounds(const char *name, app_pc *start /*IN/OUT*/, app_pc *end /*OUT*/,
-                        char *fullpath /*OPTIONAL OUT*/, size_t path_size)
+                        char *fulldir /*OPTIONAL OUT*/, size_t path_size,
+                        char *fullfilepath /*OPTIONAL OUT*/, size_t filepath_size)
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/memquery_linux.c]: I made everything consistent now, fulldir, fulldir_size, filename, filename_size

File: core/unix/os_exports.h (hunk 14 above)
Comment (hgreving2304) [reply core/unix/os_exports.h]: Ok.
