### PR TITLE
i#3049: clean postcall_cache when drwrap_exit

### LINKED ISSUE #3049: Bug to fix: drwrap does not clean up all resources when exit
It looks like drwrap doesn't clean up all the resources when calling drwrap_exit() in client.
In might cause potential problems in clients when DR is actively invoked and stopped by the same user application several times in one run. Here is how I reproduce the problem in drcachesim client test case:
1. Call `drwrap_init()` inside `clients/drcachesim/tracer/tracer.cpp:drmemtrace_client_main`
2. Call `drwrap_exit()` inside `clients/drcachesim/tracer/tracer.pp:event_exit`
3. `include "drwrap.h"` in `clients/drcachesim/tracer/tracer.pp`, add `use_DynamoRIO_extension(${name} drwrap${ext_sfx})` under `clients/drcachesim/CMakeLists.txt:configure_DynamoRIO_client`
4. Build with test cases
5. `ctest -R .*burst_static` will fail 2 out of 3 times (test case: tool.drcacheoff.burst_static).

### PR DESCRIPTION
**Pull request by Louis-Ye**
This commit is a supplement for PR #3050.
We need to clean `postcall_cache` on `drwrap_exit` as well, otherwise
post-callback (one of the arguments when calling `drwrap_wrap_ex`) will not be invoked at re-attach. This is because the registration of post-callback relies on pre-callback, and pre-callback checks postcall-cache before registering the post-callback. Stale data in `postcall_cache` prevents post-callback being registered to the hash table.

Fixes #3049

### CODE REVIEW

File: ext/drwrap/drwrap.c [hunk 1]
```diff
@@ -970,7 +970,7 @@ void
 drwrap_exit(void)
 {
     /* handle multiple sets of init/exit calls */
-    int count = dr_atomic_add32_return_sum(&drwrap_init_count, -1);
+    int i, count = dr_atomic_add32_return_sum(&drwrap_init_count, -1);
```
Comment (derekbruening) [inline ext/drwrap/drwrap.c]: Please declare i on a separate line: I find this harder to read

File: ext/drwrap/drwrap.c [hunk 2]
```diff
@@ -981,6 +981,11 @@ drwrap_exit(void)
         !dr_unregister_delete_event(drwrap_fragment_delete))
         ASSERT(false, "failed to unregister in drwrap_exit");
 
+    for (i = 0; i < POSTCALL_CACHE_SIZE; i++) {
+        postcall_cache[i] = NULL;
+    }
```
Comment (derekbruening) [inline ext/drwrap/drwrap.c]: This is fine for this CL but it brings up two thoughts:

1) For large data structures zeroing at exit is costly when there's no chance or re-attach: which is all of the time for regular non-static DR.  Inside DR we only zero for doing_detach.  We may want to export that for extensions.

2) We should add a re-attach test for drwrap.

I filed #3065 for this, split from #2157.  Let's reference both issues in the merge commit message.

Comment (Louis-Ye) [reply ext/drwrap/drwrap.c]: Sure
