### PR TITLE
i#2158: Warn client on incorrect usage of instrlist_encode_to_copy

### LINKED ISSUE #2158: warn when trying to encode an instrlist with labels without a second pass
When creating a code cache with `dr_nonheap_alloc` that has a jump, I find that all jumps to labels are replaced with an infinite loop because the jump's operand points to itself.

```c
void
insert_jmp(void *drcontext, instrlist_t *ilist, instr_t *where)
{
    instr_t *label = INSTR_CREATE_label(drcontext);
    instrlist_meta_preinsert(ilist, where, XINST_CREATE_jump
                             (drcontext,
                              opnd_create_instr(label)));
    instrlist_meta_preinsert(ilist, where, label);
}

static void *
code_cache_init(void *drcontext)
{
    void *code_cache = dr_nonheap_alloc(dr_page_size(), DR_MEMPROT_READ  |
                                                        DR_MEMPROT_WRITE |
                                                        DR_MEMPROT_EXEC);
    instrlist_t *ilist = instrlist_create(drcontext);
    instr_t *where = INSTR_CREATE_ret(drcontext);
    instrlist_meta_append(ilist, where);

    /* jumping to this label causes an infinite loop */
    insert_jmp(drcontext, ilist, where);

    instrlist_encode(drcontext, ilist, code_cache, false);
    instrlist_clear_and_destroy(drcontext, ilist);
    return code_cache;
}

static dr_emit_flags_t
event_basic_block(void *drcontext, void *tag, instrlist_t *bb,
                  bool for_trace, bool translating)
{
    instr_t *where = instrlist_first(bb);
    /* jumping to this label works... */
    insert_jmp(drcontext, bb, where);
    dr_insert_clean_call(drcontext, bb, where, code_cache_init(drcontext), false, 0);
    return DR_EMIT_DEFAULT;
}
```

This is similar to what we do in the `memtrace_x86` sample, however we use an absolute jump as opposed to a clean call in that sample.

I would like to use a clean call here, but if this behavior is intended I will instead use `dr_prepare_for_call` followed by the absolute jump.

### PR DESCRIPTION
**Pull request by toshipiazza**
If a client mistakenly calls instrlist_encode_to_copy() on an instrlist
that has indication of meta control flow (i.e. labels) but has not set
has_instr_jmp_targets, we warn the client that setting this flag may be
necessary to correctly encode the basic block.

Fixes #2158

### CODE REVIEW

**Comment by toshipiazza** [comment]
One thing to mention is that with this patch, I see this warning even with only DR running:

```
$ ./bin64/drrun -- ls
<Starting application /bin/ls (23892)>
<Paste into GDB to debug DynamoRIO clients:  (...)>
<has_instr_jmp_targets was unset but a label was found>
<Initial options = (...)>
<(1+x) Handling our fault in a TRY at 0x0000561f77fc0e2e>
<spurious rep/repne prefix @0x00007f462e1977f8 (f2 41 ff e3): >
(ls output)
<Stopping application /bin/ls (23892)>
```

Should I investigate or leave this be?

**Comment by derekbruening** [comment]
Better to look for an instr opnd, then, than to look for a label -- prob somebody adds a label that is never used there.

File: core/arch/instrlist.c [hunk 1]
```diff
@@ -481,15 +481,19 @@ instrlist_encode_to_copy(dcontext_t *dcontext, instrlist_t *ilist, byte *copy_pc
...
         encode_reset_it_block(dcontext);
 #endif
-    if (has_instr_jmp_targets || max_pc != NULL) {
+    if (IF_DEBUG_ELSE(true, has_instr_jmp_targets) || max_pc != NULL) {
         /* must set note fields first with offset, or compute length */
         for (inst = instrlist_first(ilist); inst; inst = instr_get_next(inst)) {
+            if (IF_DEBUG_ELSE(!has_instr_jmp_targets && instr_is_label(inst), false)) {
+                SYSLOG_INTERNAL_WARNING(
+                        "has_instr_jmp_targets was unset but a label was found");
+            }
```
Comment (derekbruening) [inline core/arch/instrlist.c]: Hmm, this may end up being confusing: everything will work in debug (with a warning), but won't in release.  I was thinking we could detect most instances of this during actual encoding, though it's not foolproof: look for instr_t.note being zero in encode_operand (e.g., at x86/encode.c:1822).  Maybe *also* have a DOCHECK here that does a walk through the instrlist, but at a higher checklevel?

Comment (toshipiazza) [inline core/arch/instrlist.c]: Done w/ adding the `CLIENT_ASSERT` in x86/encode.c, but for some reason I am unable to perform the `DOCHECK` in `instrlist_encode_to_copy`, here.

If I try to call `instr_num_srcs` (i.e. to check for an inst opnd as in your comment above) I get a segfault because `dcontext` is NULL. The stacktrace also is puzzling, because it seems that `instr_num_srcs` is trying to decode the instruction and perform some heap allocation:

```
#0  0x0000555555705191 in heap_alloc (dcontext=0x0, size=0x20, which=ACCT_IR) at /home/piazzt/Build/dynamorio/core/heap.c:3589
#1  0x00005555557aa610 in instr_set_num_opnds (dcontext=0x0, instr=0x4e4689f8, instr_num_dsts=0x2, instr_num_srcs=0x1)
    at /home/piazzt/Build/dynamorio/core/arch/instr_shared.c:535
#2  0x00005555557be553 in decode_common (dcontext=0x0, pc=0x4e468c68 "\234\274\274\274\274\274\274\274",
    orig_pc=0x4e468c68 "\234\274\274\274\274\274\274\274", instr=0x4e4689f8)
    at /home/piazzt/Build/dynamorio/core/arch/x86/decode.c:2070
#3  0x00005555557bea9e in decode (dcontext=0x0, pc=0x4e468c68 "\234\274\274\274\274\274\274\274", instr=0x4e4689f8)
    at /home/piazzt/Build/dynamorio/core/arch/x86/decode.c:2145
#4  0x00005555557ac5ca in instr_decode (dcontext=0x0, instr=0x4e4689f8)
    at /home/piazzt/Build/dynamorio/core/arch/instr_shared.c:1529
#5  0x00005555557ac6a0 in instr_decode_with_current_dcontext (instr=0x4e4689f8)
    at /home/piazzt/Build/dynamorio/core/arch/instr_shared.c:1554
#6  0x00005555557b8a04 in instrlist_encode_to_copy (dcontext=0xffffffffffffffff, ilist=0x7fffffffd000,
    copy_pc=0x4e47eeaa "\234", '\253' <repeats 199 times>..., final_pc=0x4e47eeaa "\234", '\253' <repeats 199 times>...,
    max_pc=0x0, has_instr_jmp_targets=0x0) at /home/piazzt/Build/dynamorio/core/arch/instrlist.c:514
#7  0x00005555557b8a87 in instrlist_encode (dcontext=0xffffffffffffffff, ilist=0x7fffffffd000, pc=0x4e47edc0 "eH\211<%\030",
    has_instr_jmp_targets=0x0) at /home/piazzt/Build/dynamorio/core/arch/instrlist.c:533
#8  0x0000555555791862 in emit_fcache_return_shared (dcontext=0xffffffffffffffff, code=0x4e47d000, pc=0x4e47edc0 "eH\211<%\030")
    at /home/piazzt/Build/dynamorio/core/arch/emit_utils_shared.c:2522
#9  0x0000555555784848 in shared_gencode_emit (gencode=0x4e47d000, x86_mode=0x0)
    at /home/piazzt/Build/dynamorio/core/arch/arch.c:328
#10 0x0000555555784f5a in shared_gencode_init (gencode_mode=GENCODE_X64) at /home/piazzt/Build/dynamorio/core/arch/arch.c:545
#11 0x0000555555785213 in arch_init () at /home/piazzt/Build/dynamorio/core/arch/arch.c:723
#12 0x00005555555e4c02 in dynamorio_app_init () at /home/piazzt/Build/dynamorio/core/dynamo.c:543
#13 0x000055555585d0bc in privload_early_inject (sp=0x7fffffffe360, old_libdr_base=0x555555580a58 "\250\204`q",
    old_libdr_size=0x7fffffffe1a0) at /home/piazzt/Build/dynamorio/core/unix/loader.c:1838
#14 0x0000555555811b38 in reloaded_xfer () at /home/piazzt/Build/dynamorio/core/arch/x86/x86.asm:1186
#15 0x0000000000000001 in ?? ()
#16 0x00007fffffffe5ed in ?? ()
#17 0x0000000000000000 in ?? ()
```

Do you have any suggestions? Should I just go back to checking for labels instead of for opnd inst's?

Comment (toshipiazza) [inline core/arch/instrlist.c]: Another note: when I added the `CLIENT_ASSERT` in x86/encode.c which checked that the note was non-zero, I failed to realize that zero is perfectly valid for a note for the first instruction. If we perform a jump to a label as the first instruction in the basic block, we set its note to `len = 0`. Will try to relax the assert as appropriate.

**Comment by toshipiazza** [comment]
Committing what I have now, but see the comment in x86/encode.c. Not sure what the best way is to relax the assert I added -- since it hinders a few samples (i.e. memtrace_x86 on master), I had to change it to a `SYSLOG_INTERNAL_WARNING`.

**Comment by derekbruening** [comment]
Yeah this is more complex than it seemed at first.  Will reply more later.

Note that there are build errors on VS010 on AppVeyor.

File: core/arch/instrlist.c [hunk 2]
```diff
@@ -469,6 +470,16 @@ void instrlist_append_instrlist(dcontext_t *dcontext,instrlist_t *ilist,
...
 }
 
+void
+check_inst_opnds(instr_t *inst)
+{
+    int i;
+
+    for (i = 0; i < instr_num_srcs(inst); ++i) {
+        CLIENT_ASSERT(!opnd_is_instr(instr_get_src(inst, i)),
+                "has_instr_jmp_targets was unset but a label was found");
```
Comment (derekbruening) [inline core/arch/instrlist.c]: Not a label, an instr opnd

Comment (derekbruening) [inline core/arch/instrlist.c]: Indentation looks off

File: core/arch/x86/encode.c [hunk 3]
```diff
@@ -1819,6 +1819,13 @@ encode_operand(decode_info_t *di, int optype, opnd_size_t opsize, opnd_t opnd)
              * This only works if the instr has no other immeds!
              */
             instr_t *target_instr = opnd_get_instr(opnd);
+            /* XXX: This check could be inaccurate, say if the first instruction in
+             * the instrlist containted the noted near instr operand.
```
Comment (derekbruening) [inline core/arch/x86/encode.c]: Yeah I'm thinking we should just remove this, if we have the DOCHECK.  It's not easy to make it have no false positives.

("containted", "note == NULL")

File: core/arch/instrlist.c [hunk 4]
```diff
@@ -481,15 +492,18 @@ instrlist_encode_to_copy(dcontext_t *dcontext, instrlist_t *ilist, byte *copy_pc
...
     if (instr_get_isa_mode(instrlist_first(ilist)) == DR_ISA_ARM_THUMB)
         encode_reset_it_block(dcontext);
 #endif
-    if (has_instr_jmp_targets || max_pc != NULL) {
+    if (IF_DEBUG_ELSE(true, has_instr_jmp_targets) || max_pc != NULL) {
         /* must set note fields first with offset, or compute length */
         for (inst = instrlist_first(ilist); inst; inst = instr_get_next(inst)) {
+            if (IF_DEBUG_ELSE(!has_instr_jmp_targets, false)
+                    && TEST(INSTR_OPERANDS_VALID, (inst)->flags))
+                DOCHECK(3, { check_inst_opnds(inst); });
```
Comment (derekbruening) [inline core/arch/instrlist.c]: This causes the instrlist walk at -checklevel 0 though: we want the walk to be a higher checklevel.

I suggest just making a completely separate walk inside "DOCHECK(2" (voting for 2 b/c it's the default, so people will see the assert, unless they deliberately set a different -checklevel, in which case they'll get the speed they're looking for).

File: core/arch/instrlist.c [hunk 5]
```diff
@@ -481,15 +492,18 @@ instrlist_encode_to_copy(dcontext_t *dcontext, instrlist_t *ilist, byte *copy_pc
...
             if (has_instr_jmp_targets)
```
Comment (derekbruening) [inline core/arch/instrlist.c]: Hmm, with this conditional, I was wrong before: the debug loop won't work.  Still I would vote for a clean, separate loop.

File: core/arch/instrlist.c [hunk 6]
```diff
@@ -469,6 +470,16 @@ void instrlist_append_instrlist(dcontext_t *dcontext,instrlist_t *ilist,
...
+void
+check_inst_opnds(instr_t *inst)
+{
+    int i;
+
+    for (i = 0; i < instr_num_srcs(inst); ++i) {
+        CLIENT_ASSERT(!opnd_is_instr(instr_get_src(inst, i)),
+                "has_instr_jmp_targets was unset but a label was found");
+    }
+}
```
Comment (derekbruening) [inline core/arch/instrlist.c]: Maybe just inline this?  Needs to be static and ifdef debug o/w.

File: core/arch/instrlist.c (hunk 2 above)
Comment (toshipiazza) [inline core/arch/instrlist.c]: Done.

Comment (toshipiazza) [inline core/arch/instrlist.c]: Done.

File: core/arch/instrlist.c (hunk 6 above)
Comment (toshipiazza) [inline core/arch/instrlist.c]: Done.

File: core/arch/instrlist.c (hunk 4 above)
Comment (toshipiazza) [inline core/arch/instrlist.c]: Alternatively, could I use the `DEBUG_CHECKS` macro, so we don't have to perform 2 separate walks over the instrlist? Sthg like

```c
    if (DEBUG_CHECKS(2) || has_instr_jmp_targets || max_pc != NULL) {
        /* must set note fields first with offset, or compute length */
        for (inst = instrlist_first(ilist); inst; inst = instr_get_next(inst)) {
            if (DEBUG_CHECKS(2) && !has_instr_jmp_targets
                    && TEST(INSTR_OPERANDS_VALID, (inst)->flags)) {
                // perform inlined check on opnds
```

That way with -checklevel 0 we still don't walk the instrlist but we don't do two passes over the instrlist on the default checklevel.

File: core/arch/x86/encode.c (hunk 3 above)
Comment (toshipiazza) [inline core/arch/x86/encode.c]: Agreed, Done.

File: core/arch/instrlist.c (hunk 5 above)
Comment (toshipiazza) [inline core/arch/instrlist.c]: Could you elaborate? To which debug loop are you referring?

File: core/arch/instrlist.c (hunk 4 above)
Comment (derekbruening) [inline core/arch/instrlist.c]: I assume you mean two separate passes in the source code?  At runtime there would only be one, as the DOCHECK walk would only do the walk if !has_instr_jmp_targets.

My argument is that the DOCHECK loop's body shares absolutely nothing with the existing loop body: we don't want to set the note and we don't want to get the length (which sometimes needs a private encode into an allocated buffer that is then copied later, so it's is less efficient then encoding directly to the dest).  So we're duplicating part of the if condition and the for() line is all, to have IMHO less cluttered code.  WDYT?  If you really prefer it all in one loop with extra conditionals, just make sure DEBUG_CHECKS is set to false for release build (doesn't look like it today).

File: core/arch/instrlist.c (hunk 5 above)
Comment (derekbruening) [inline core/arch/instrlist.c]: My earlier comment -- can't find a way to link to it so pasting here: "this may end up being confusing: everything will work in debug (with a warning), but won't in release".

File: core/arch/instrlist.c (hunk 4 above)
Comment (toshipiazza) [inline core/arch/instrlist.c]: Gotcha, you've convinced me. I just went with your suggestion of the separate loops.

File: core/arch/instrlist.c (hunk 5 above)
Comment (toshipiazza) [inline core/arch/instrlist.c]: Understood.

**Comment by toshipiazza** [comment]
Note that after I changed the `DOCHECK` to checklevel 2, I saw 2 failures in the test suite (because previously I had forgotten to run my changes on the test suite with checklevel 3)

These have been fixed, though since these tests have always worked perhaps our assert is too stringent?

File: suite/tests/api/ir_x86_all_opc.h [hunk 7]
```diff
@@ -57,7 +57,7 @@
 #   undef OPCODE
 #   undef XOPCODE
 
-    end = instrlist_encode(dc, ilist, buf, false);
+    end = instrlist_encode(dc, ilist, buf, true);
```
Comment (derekbruening) [inline suite/tests/api/ir_x86_all_opc.h]: Hmm, interesting: yes, the cti instrs are given instr opnds, for simplicity I guess rather than making up some PC.  They are never executed so everything passed before.

File: suite/tests/client-interface/inline.dll.c [hunk 8]
```diff
@@ -207,7 +207,7 @@ codegen_instrumentation_funcs(void)
         dr_log(dc, LOG_EMIT, 3, "Generated instrumentation function %s at "PFX
                ":", func_names[i], pc);
         instrlist_disassemble(dc, pc, ilists[i], dr_get_logfile(dc));
-        pc = instrlist_encode(dc, ilists[i], pc, false);
+        pc = instrlist_encode(dc, ilists[i], pc, true);
```
Comment (derekbruening) [inline suite/tests/client-interface/inline.dll.c]: Also interesting: this test sets its own note fields, which seems a little hacky.  Please update the comment up above on line 201-201 (I can't seem to add a review comment there -- another limitation of github reviews...) b/c we are now telling the encoder to "worry about labels" and it will clobber the notes -- so should also remove the set_note at line 189.

File: suite/tests/api/ir_x86_all_opc.h (hunk 7 above)
Comment (toshipiazza) [inline suite/tests/api/ir_x86_all_opc.h]: Acknowledged.

File: suite/tests/client-interface/inline.dll.c (hunk 8 above)
Comment (toshipiazza) [inline suite/tests/client-interface/inline.dll.c]: Done.

Comment (toshipiazza) [inline suite/tests/client-interface/inline.dll.c]: FYI you can click the "expand" button at the top left of where the diff ends in the github UI to view more of the file. Just realized that now.

**Comment by toshipiazza** [comment]
Hmm, do you see why travis-ci hasn't fired? Was it because I did a force push (I rebased from master so I wouldn't get another travis-ci failure)

File: suite/tests/client-interface/inline.dll.c (hunk 8 above)
Comment (derekbruening) [inline suite/tests/client-interface/inline.dll.c]: Yup, that's what I did to view it, but I could not find a way to add a comment on any part of the existing file: only on the parts that were changed.  This is a not uncommon thing to want to do, and Rietveld supports it.  Maybe I missed something: did you see any way to add such a comment?

**Comment by derekbruening** [comment]
> Hmm, do you see why travis-ci hasn't fired? Was it because I did a force push (I rebased from master so I wouldn't get another travis-ci failure)

Travis is shown as running.  I have seen delays with the github hook before, maybe there was just a delay.

File: suite/tests/client-interface/inline.dll.c [hunk 9]
```diff
@@ -184,11 +184,8 @@ codegen_instrumentation_funcs(void)
     for (i = 0; i < N_FUNCS; i++) {
```
Comment (derekbruening) [inline suite/tests/client-interface/inline.dll.c]: I want to put this comment one line higher: please update the comment "set each note..."

File: suite/tests/client-interface/inline.dll.c (hunk 8 above)
Comment (derekbruening) [inline suite/tests/client-interface/inline.dll.c]: To clarify: I can use the hovering + to add a comment on unchanged lines that are part of the context diff, just not on a line from the expansion.

File: suite/tests/client-interface/inline.dll.c (hunk 9 above)
Comment (toshipiazza) [inline suite/tests/client-interface/inline.dll.c]: Done.

File: suite/tests/client-interface/inline.dll.c (hunk 8 above)
Comment (toshipiazza) [inline suite/tests/client-interface/inline.dll.c]: Whoops, you're right. I didn't realize that you couldn't comment on the expanded area.
