### PR TITLE
i#4718: Fix drwrap restore state arm bug

### LINKED ISSUE #4718: client.drwrap-test-detach fails 28/100 times on aarch64: hang
Split from #1578 
Xref #4474

Other issues revealed by this test:
Xref #4616: timeout on Windows
Xref #4593: failed several times on GA CI on 32-bit x86: mysterious crashes
Xref #4219: Translation problems in clean call mangling causing post-detach crashes

See https://github.com/DynamoRIO/dynamorio/pull/4467#issuecomment-705049234 where it fails 28/100 times on Jenkins.

On tx1 I saw a weird failure where the output seems to match:
```
derek@tx1:~/dr/build$ ctest --repeat-until-fail 100 -V -R drwrap-test-detach

209: Test command: /home/derek/dr/build/bin64/runstats "-s" "90" "-killpg" "-silent" "-env" "LD_LIBRARY_PATH" "/home/derek/dr/build/lib64/debug:/home/derek/dr/build/ext/lib64/debug:" "-env" "DYNAMORIO_OPTIONS" "-stderr_mask 0xC -dumpcore_mask 0 -code_api" "/home/derek/dr/build/suite/tests/bin/client.drwrap-test-detach"
209: Test timeout computed to be: 1500
209: in dr_client_main
209: client done
209: app done
    Test #209: code_api|client.drwrap-test-detach ...   Passed    0.63 sec
    Start 209: code_api|client.drwrap-test-detach

209: Test command: /home/derek/dr/build/bin64/runstats "-s" "90" "-killpg" "-silent" "-env" "LD_LIBRARY_PATH" "/home/derek/dr/build/lib64/debug:/home/derek/dr/build/ext/lib64/debug:" "-env" "DYNAMORIO_OPTIONS" "-stderr_mask 0xC -dumpcore_mask 0 -code_api" "/home/derek/dr/build/suite/tests/bin/client.drwrap-test-detach"
209: Test timeout computed to be: 1500
209: in dr_client_main
209: client done
209: app done
    Test #209: code_api|client.drwrap-test-detach ...***Failed  Required regular expression not found.Regex=[^in dr_client_main
client done
app done
$
]  0.63 sec
```

Instead running in a loop we see a hang on the 3rd invocation:
```
derek@tx1:~/dr/build$ for ((i=0; i<100; i++)); do echo -e "\n============\n$i\n"; LD_LIBRARY_PATH=lib64/debug DYNAMORIO_OPTIONS="-stderr_mask 0xf -dumpcore_mask 0 -code_api" suite/tests/bin/client.drwrap-test-detach; done > OUT 2>&1
```

A loop with the harness to time out:
```
derek@tx1:~/dr/build$ for ((i=0; i<100; i++)); do echo -e "\n============\n$i\n"; ctest -V -R drwrap-test-detach; done > OUT 2>&1
```
That is in progress; will update when done.  So far, seeing a lot of hangs.  Has no reproduced the weird failure above.

### PR DESCRIPTION
**Pull request by derekbruening**
Fixes a bug in drwrap state restoring on arm where its stack scan loop has the wrong termination condition, resulting in failures to restore and hangs when the start equals the end.

(Re-)Enables the drwrap-test-detach test on arm.  Confirmed it passes
100x in a row now where before it hung every couple of runs.

Fixes #4718

### CODE REVIEW

**Review by abhinav92003 — APPROVED** [review]

File: ext/drwrap/drwrap.c [hunk 1]
```diff
@@ -2592,7 +2592,7 @@ drwrap_event_restore_state_ex(void *drcontext, bool restore_memory,
                 scan_stop = (app_pc *)pt->app_esp[i + 1];
```
Comment (abhinav92003) [inline ext/drwrap/drwrap.c:2592]: You mentioned offline that you also wanted to add a test?

**Review by abhinav92003 — APPROVED** [review]

File: ext/drwrap/drwrap.c (hunk 1 above)
Comment (derekbruening) [reply ext/drwrap/drwrap.c:2592]: That was before I found that drwrap-test-detach reproduced the hang, and is already targeting the return address replacement, but was just disabled on arm.
