### PR TITLE
i#2469: fix XINST_CREATE macros used by drcachesim on AArch64

### LINKED ISSUE #2469: code_api|tool.drcachesim.filter and code_api|tool.drcacheoff.filter broken on AArch64
One of the latest changes to drcachesim seems to have broken AArch64. Unfortunately the AArch64 nightly builds are currently down due to a power failure, but they should be back soon.

    09:56:04.879 132/149 Test #134: code_api|tool.drcachesim.filter .................***Failed  Required regular expression not found.Regex=[^Hello, world!
    09:56:04.879 ---- <application exited with code 0> ----
    09:56:04.879 Cache simulation results:
    09:56:04.879 Core #0 \(1 thread\(s\)\)
    09:56:04.879   L1I stats:
    09:56:04.879     Hits:                         *[0-9,\.]*
    09:56:04.879     Misses:                       *[0-9,\.]*.
    09:56:04.879 .*   Miss rate:                   *[1-9][0-9][,\.]..%
    09:56:04.879   L1D stats:
    09:56:04.879     Hits:                         *[0-9,\.]*
    09:56:04.879     Misses:                       *[0-9,\.]*.
    09:56:04.879 .*   Miss rate:                   *[1-9][0-9][,\.]..%
    09:56:04.879 Core #1 \(0 thread\(s\)\)
    09:56:04.879 Core #2 \(0 thread\(s\)\)
    09:56:04.879 Core #3 \(0 thread\(s\)\)
    09:56:04.879 LL stats:
    09:56:04.879     Hits:                         *[0-9,\.]*.
    09:56:04.879     Misses:                       *[0-9,\.]*..
    09:56:04.879 .*   Local miss rate:             *[1-9][0-9][,\.]..%
    09:56:04.879     Child hits:                   *[0-9,\.]*.
    09:56:04.879     Total miss rate:              *[1-9][0-9][,\.]..%
    09:56:04.879 $
    09:56:04.879 ]  0.20 sec
    09:56:04.879 <Internal Error: Failed to encode instruction: 'lsrv   %x30 $0x06 -> %x30'
    09:56:04.879 >
    09:56:04.879 <Application /var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/suite/tests/bin/simple_app (27354).  Internal Error: DynamoRIO debug check failure: Not implemented @/var/lib/go-agent/pipelines/dynamorio-verification/dynamorio/core/arch/aarch64/encode.c:172 (0)

    09:56:04.880 135/149 Test #141: code_api|tool.drcacheoff.filter .................***Failed    0.60 sec
    09:56:04.880 Running |/usr/bin/cmake;-E;remove_directory /var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/suite/tests/drmemtrace.simple_app.26405.1511.dir|
    09:56:04.880 Running cmd |/var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/bin64/drrun;-s;90;-quiet;-debug;-killpg;-stderr_mask;0xC;-dumpcore_mask;0;-code_api;-t;drcachesim;-offline;-L0_filter;--;/var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/suite/tests/bin/simple_app|
    09:56:04.880 Running postcmd |/var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/clients/bin64/drcachesim;-indir;/var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/suite/tests/drmemtrace.simple_app.27371.4030.dir|
    09:56:04.880 CMake Error at /var/lib/go-agent/pipelines/dynamorio-verification/dynamorio/suite/tests/runmulti.cmake:99 (message):
    09:56:04.880   *** postcmd failed (1): ERROR: Failed to parse module file
    09:56:04.880   /var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/suite/tests/drmemtrace.simple_app.27371.4030.dir/raw/modules.log
    09:56:04.880 
    09:56:04.880 
    09:56:04.880   ***
    09:56:04.880 
    09:56:04.880 Call Stack (most recent call first):
    09:56:04.880   /var/lib/go-agent/pipelines/dynamorio-verification/dynamorio/suite/tests/runmulti.cmake:111 (process_cmdline)
    09:56:04.880   
    09:56:04.880 
    09:56:04.880 
    09:56:04.880

### PR DESCRIPTION
**Pull request by fhahn**
This patch fixes the following bugs with XINST_CREATE/ INSTR_CREATE 
macros on AArch64:
  * XINST_CREATE_jump_cond: use bcond opcode which encodes the predicate
    set using INSTR_PRED
  * XINST_CREATE_slr_s: use lsrv for register shift and ubfm for
    immediate shifts
  * INSTR_CREATE_cmp: use INSTR_CREATE_subs (which sets immediate
  * arguments) instead of manually created the instruction

Fixes #2469.

### CODE REVIEW

**Comment by derekbruening** [comment]
Two typos in the commit message: "XINSTR_CREATE"

File: core/arch/aarch64/instr_create.h [hunk 1]
```diff
@@ -369,8 +369,11 @@
  * they just need to know whether they need to preserve the app's flags, so maybe
  * we can just document that this may not write them.
  */
-#define XINST_CREATE_slr_s(dc, d, s) \
-  instr_create_1dst_2src((dc), OP_lsrv, (d), (d), (s))
+#define XINST_CREATE_slr_s(dc, d, rm_or_imm) \
+  opnd_is_reg(rm_or_imm) ? \
+    instr_create_1dst_2src((dc), OP_lsrv, (d), (d), (rm_or_imm)) : \
+    instr_create_1dst_3src((dc), OP_ubfm, (d), (d), (rm_or_imm), \
```
Comment (derekbruening) [inline core/arch/aarch64/instr_create.h]: So the FIXME above still applies as these are using raw creation rather than INSTR_CREATE macros but the comment should be updated to include INSTR_CREATE_ubfm.

Comment (fhahn) [inline core/arch/aarch64/instr_create.h]: The comment mentions using INSTR_CREATE_lsr, which should support both register and immediate shifts, so I think there is no need to mention INSTR_CREATE_ubfm

File: core/arch/aarch64/instr_create.h [hunk 2]
```diff
@@ -369,8 +369,11 @@
  * they just need to know whether they need to preserve the app's flags, so maybe
  * we can just document that this may not write them.
  */
-#define XINST_CREATE_slr_s(dc, d, s) \
-  instr_create_1dst_2src((dc), OP_lsrv, (d), (d), (s))
+#define XINST_CREATE_slr_s(dc, d, rm_or_imm) \
+  opnd_is_reg(rm_or_imm) ? \
```
Comment (fhahn) [inline core/arch/aarch64/instr_create.h]: done

**Comment by fhahn** [comment]
Remove XINSTR_CREATE from PR message

File: core/arch/aarch64/instr_create.h (hunk 1 above)
Comment (egrimley) [inline core/arch/aarch64/instr_create.h]: Some musings:

1. The Travis failure comes from the `\param s` when the argument is now called `rm_or_imm`. It's not exactly obvious from the published build log, is it?

2. There are an awful lot of unnecessary parentheses here. There's no need to bracket a macro argument when it's sitting between two commas.

3. Line 376 has more than 90 characters. Something for the automatic style check?

4. Are we sure that `INSTR_CREATE_lsr` should accept immediate and register arguments? It's not clear to me what the rules are for INSTR_CREATE macros. I read somewhere (arm/instr_create.h) that there is one INSTR_CREATE_xxx for each OP_xxx and the macro supplies any implicit operands. It might be better to leave it at that rather than aim at accepting every "alias". If you did want to accept every alias, then `INSTR_CREATE_mov` might be a monster (MOV is officially an alias of ADD, DUP, INS, MOVN, MOVZ, ORR or UMOV).

Comment (fhahn) [inline core/arch/aarch64/instr_create.h]: 1. Probably, thanks for spotting that!

2. Got rid of them. It seems like aarch64/instr_create.h could do with some cleanup, there seem to be a lot of unnecessary parentheses.

3. Fixed as well, instr_create.h is excluded from the line length style check (https://github.com/DynamoRIO/dynamorio/blob/master/make/style_checks/scripts/rules/line_length_content.tcl#L48), probably because there are plenty of violations on other architectures?

4. We should definitely discuss how to deal with aliases, maybe the mailing list would be a good place? I think it makes live easier for users if we provide macros for aliases that can deal with different operand types properly. Although as you pointed out, `INSTR_CREATE_mov` would be massive.

Comment (derekbruening) [inline core/arch/aarch64/instr_create.h]: I disagree with the parentheses comments here: even where not technically needed like ", (d), ", it is all too easy to later edit the macro and add something in between the commas and forget to add the parens, or to copy-paste a param name somewhere else where parens are needed, so IMHO it is not a waste to have them there.

Re: the line length exclusion: feel free to remove aarch64/instr_create.h from the list.  I planned to have some files like the x86 and arm decode tables and probably those arch's instr_create.h permanently excluded.
