### PR TITLE
i#3446: Fix AVX(-512) get_[ymm|zmm]_caller_saved unit tests.

### LINKED ISSUE #3446: new avx unit test failing on 6 cdash builds
Failing in 6 different CDash builds, all release builds looks like: 
http://dynamorio.org/CDash/testSummary.php?project=1&name=unit_tests&date=2019-03-15

E.g.:
http://dynamorio.org/CDash/testDetails.php?test=642583&build=41745
```
EXPECT failed at /work/dr/nightly/src/core/arch/x86_code.c:596 in test unit_test_get_ymm_caller_saved: memcmp(ref_buffer, get_buffer, proc_num_simd_registers() * MCXT_SIMD_SLOT_SIZE)
```

### PR DESCRIPTION
**Pull request by hgreving2304**
Re-factor unit tests for get_[ymm|zmm]_caller functions that were failing on CDash in
release, due to multiple reasons.

* ymm and zmm registers are call-clobbered in x86. Impossible in C to make them live out
  of a function. Fixed by inlining all code.
* gcc is adding vzeroupper instructions for AVX(-512) - SSE boundaries for performance
  reasons. This doesn't work with this test. Fixed by adding -mno-vzeroupper directives
  (or -mllvm -x86-use-vzeroupper=0 for clang).
* It's almost impossible to cleanly avoid SSE instructions in C-code when mixing with
  AVX in inline asm. For example there may be a xmm register assignment if there is
  (too-) much C-code between writing and reading of AVX registers in the test. This patch
  simplifies the tests to avoid this. Some barriers have been added as well.
* Travis GCC 4.8.4 does not fully support AVX. e.g. "ymm%d" registers are not known in asm volatile 
  clobber lists as well as in register asm("") statements. The AVX and AVX-512 proc checks now
  include this.
* This patch moves the unit tests from x86_code module into a new x86_code_test module that
   gets its own clang/gcc options for testing (-mno-vzeroupper). We want this option to apply only
   to code compiled for unit_test. Also because of #3458 , clang specific target options break the
   clang build.

The unit "test" in this context here basically replicates the hand encoded
get_[ymm|zmm]_caller saved functions in C-code and inline asm with mnemonics.

Fixes #3446
Issue: #1312

### CODE REVIEW

**Comment by hgreving2304** [comment]
PTAL

File: core/arch/x86_code_test.c [hunk 1]
```diff
@@ -0,0 +1,351 @@
...
+ * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
+ * DAMAGE.
+ */
+
+/* Copyright (c) 2003-2007 Determina Corp. */
+/* Copyright (c) 2001-2003 Massachusetts Institute of Technology */
+/* Copyright (c) 2001 Hewlett-Packard Company */
+/* Copyright (c) 2019 Google, Inc.  All rights reserved. */
+/*
+ * x86_code_test.c - unit tests for auxiliary C routines in x86_code.c
```
Comment (derekbruening) [inline core/arch/x86_code_test.c]: Mostly for asm routines in x86.asm, not just C routines

File: core/arch/x86_code_test.c [hunk 2]
```diff
@@ -0,0 +1,351 @@
...
+    register __m256 ymm11 asm("ymm11");
+    register __m256 ymm12 asm("ymm12");
+    register __m256 ymm13 asm("ymm13");
+    register __m256 ymm14 asm("ymm14");
+    register __m256 ymm15 asm("ymm15");
+#        endif
+
+    for (int regno = 0; regno < proc_num_simd_registers(); ++regno) {
+        for (int dword = 0; dword < sizeof(dr_ymm_t) / sizeof(uint); ++dword) {
+            ref_buffer[regno].u32[dword] = 0;
```
Comment (derekbruening) [inline core/arch/x86_code_test.c]: Why set this to 0 if it's going to be clobbered on line 146?  Seems like this line should be removed.

File: core/arch/x86_code_test.c [hunk 3]
```diff
@@ -0,0 +1,351 @@
...
+            get_buffer[regno].u32[dword] = 0;
```
Comment (derekbruening) [inline core/arch/x86_code_test.c]: Could just delete this line (and this loop since the line above will disappear too) and add "={0,}" to the declaration to have it memset to 0.

File: core/arch/x86_code.c [hunk 4]
```diff
@@ -442,263 +442,3 @@ safe_read_resume_pc(void)
 {
     return (app_pc)&safe_read_asm_recover;
 }
-
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86_code.c]: There is an option I need to add to compile this code that is different for gcc and clang (clang frontend does not support yet, unusual but happens). I can't add the option to the target, because then the clang build fails, because of i#3458 (g++ is used, even in clang build). If I add the option to the x86_code module, then the option is added even to libdynamorio, which I don't want either. So the best way is to put the tests in a separate module that's only part of the unit_test.

So it's actually for the two reasons above that I moved the tests, not only i#3458. I'll rephrase the comment.

File: core/CMakeLists.txt [hunk 5]
```diff
@@ -1060,9 +1060,26 @@ if (BUILD_TESTS)
...
+    endif ()
   elseif (proc_supports_avx)
-    set(unit_tests_extra_flags "${unit_tests_extra_flags} ${CFLAGS_AVX}")
+    if (UNIX)
+      set(unit_tests_extra_flags
+        "${unit_tests_extra_flags} ${CFLAGS_AVX}")
+    endif ()
+  endif ()
+  if (proc_supports_avx OR proc_supports_avx512)
+    if (UNIX)
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/CMakeLists.txt]: Added XXX comment.

File: core/arch/x86_code.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (derekbruening) [reply core/arch/x86_code.c]: > If I add the option to the x86_code module, then the option is added even to libdynamorio

unit_tests is a separate build so the option would not be added to libdynamorio.

File: core/CMakeLists.txt [hunk 6]
```diff
@@ -1060,9 +1060,26 @@ if (BUILD_TESTS)
...
+      if (CLANG)
+        set_source_files_properties(arch/x86_code_test.c PROPERTIES COMPILE_FLAGS
+          "-mllvm -x86-use-vzeroupper=0")
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/CMakeLists.txt]: Done.

File: core/arch/x86_code.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (derekbruening) [reply core/arch/x86_code.c]: Oh you mean as a source file property in cmake -- ok, I guess there is no way to do source-for-target-only.  If this happens again though I would think it would be better to fix #3458 than to move more code around.

File: core/arch/x86_code_test.c (hunk 1 above)
Comment (hgreving2304) [reply core/arch/x86_code_test.c]: Re-phrased.

File: core/arch/x86_code.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (derekbruening) [reply core/arch/x86_code.c]: > than to move more code around.

(Because we can't test static functions of a module in a separate file, having separate _test files is not viable)

File: core/arch/x86_code_test.c (hunk 2 above)
Comment (hgreving2304) [reply core/arch/x86_code_test.c]: Yes I can also remove the second loop, sure. Done.

File: core/arch/x86_code_test.c (hunk 3 above)
Comment (hgreving2304) [reply core/arch/x86_code_test.c]: Instead, I removed the second loop, leaving this one, see above.

File: core/CMakeLists.txt [hunk 7]
```diff
@@ -1047,7 +1047,7 @@ endif ()
 
 if (BUILD_TESTS)
   add_executable(unit_tests unit_tests.c
-    ${CORE_SRCS} ${ARCH_SRCS} ${OS_SRCS})
+    ${CORE_SRCS} ${ARCH_SRCS} ${OS_SRCS} arch/x86_code_test.c)
```
Comment (derekbruening) [inline core/CMakeLists.txt]: It may be worth a comment explaining why just this one test is in a separate file, so someone adding new tests knows which model to follow.

File: core/arch/x86_code_test.c (hunk 3 above)
Comment (derekbruening) [reply core/arch/x86_code_test.c]: I don't understand: the 2nd loop is the one that sets the "base++" values.  I don't see why that would be removed?

File: core/CMakeLists.txt (hunk 7 above)
Comment (hgreving2304) [reply core/CMakeLists.txt]: Explained in commit message and where we're adding options. I am adding another comment here now.

Comment (hgreving2304) [reply core/CMakeLists.txt]: Done.

File: core/arch/x86_code_test.c (hunk 3 above)
Comment (hgreving2304) [reply core/arch/x86_code_test.c]: Re-phrase: Consolidated the two loops into one.
