### PR TITLE
i#1840: Add helpful error if /proc is not mounted on Linux

### LINKED ISSUE #1840: give helpful message if /proc is not mounted
I sometimes forget to mount /proc in my chroots. It saves me time when a program tells me immediately what the problem is. Currently the behaviour is:

```
$ bin64/drrun echo
<Application /bin/echo (12345) DynamoRIO usage error : Failed to map ELF interpreter.>
```

Here are two examples of helpful messages:

```
$ ps
Error, do this: mount -t proc proc /proc
```

```
$ vmstat
...
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"
```

### PR DESCRIPTION
**Pull request by GandholiSarat**
Adds a Linux-only check during core initialization to verify that
/proc is mounted when running in managed mode. If not, DynamoRIO
emits a clear and actionable usage error instead of failing later
with a confusing loader error.

The check is guarded by !standalone_library so it applies to all
managed modes (injection, dr_app, attach/detach) while excluding
standalone/library-only usage such as drdecode.

Fixes #1840.

### CODE REVIEW

File: tools/drdeploy.c [hunk 1]
```diff
@@ -54,6 +54,12 @@
```
Comment (derekbruening) [inline tools/drdeploy.c:54]: > The check is intentionally implemented in the tool layer rather than
core to avoid affecting embedding, static mode, detach/reattach, and
code_api tests.

I see an earlier commit has the check inside DR: doesn't that seem more complete, so that this issue has a clear message for app-linked DR where drrun is not used? What problems did you hit that made you switch to only having drrun do this check? Looking at your 1st commit: is the only failure #5123 a known separate issue?

Comment (GandholiSarat) [reply tools/drdeploy.c:54]: I initially placed the check in `d_r_os_init()`, but that caused widespread failures in `code_api` and static tests because core initialization runs in embedding, static, and attach/detach modes as well. Enforcing /proc globally was too strict for those cases.

Since #1840 specifically concerns drrun in a chroot, I moved the check to drdeploy (DRRUN/DRINJECT) to scope it to injection-only usage and avoid impacting other modes.

If desired, we could explore a more targeted core check limited to injection mode rather than unconditional startup.Would you prefer that I revert to the earlier core-based implementation and instead refine it to run only in injection mode? I can revisit that approach if you think covering app-linked DR in core is preferable.

Comment (derekbruening) [reply tools/drdeploy.c:54]: > I initially placed the check in d_r_os_init(), but that caused widespread failures in code_api and static tests because core initialization runs in embedding, static, and attach/detach modes as well. Enforcing /proc globally was too strict for those cases.

I'm still confused: why would there be failures when /proc is available? Isn't /proc there for all GA VMs? Can you point to the run with all the failures?

I understand not wanting to check /proc for sthg like the drdecode library which I assume doesn't require /proc: but if core DR itself assumes and uses /proc in managed mode, wouldn't we want this check in all managed modes, including the dr_app interface, attach/detach, and launch-injection?

Does standalone DR end up needing /proc? Maybe not: so probably we just don't want this check for non-managed-mode, meaning standalone DR (just used as utility library) and drdecode.

**Comment by GandholiSarat** [comment]
I’ve reverted the check to core and guarded it with `!standalone_library`, so it now runs only in managed modes (injection, dr_app, attach/detach) while excluding standalone/library-only usage such as drdecode.

With /proc unmounted, drrun now emits the intended error and exits cleanly. Since core in managed mode relies on /proc, this ensures all managed entry points provide the helpful message without impacting standalone use.

Please let me know if you’d prefer a different managed-mode boundary.

File: tools/drdeploy.c [hunk 2]
```diff
@@ -1267,6 +1273,17 @@ _tmain(int argc, TCHAR *targv[])
         fatal("failed to process args: %d", sc);
 #endif
 
+#if defined(LINUX) && (defined(DRRUN) || defined(DRINJECT))
+    /* i#1840: Provide a clear error when /proc is not mounted. */
+    struct statfs stat;
+    if (statfs("/proc", &stat) != 0 || stat.f_type != PROC_SUPER_MAGIC) {
```
Comment (derekbruening) [inline tools/drdeploy.c]: Your top level comment (note: normally it's good to reply to the threads within the review system so the thread topics are contained; the top level comments on the Conversation page are hard to reply to and hard to mark resolved: hard to track) says you reverted to checking in core: but this check is still here in drdeploy.c? Is that intentional or necessary?

Comment (GandholiSarat) [reply tools/drdeploy.c]: Thanks, the tool-layer check was a leftover. I’ve removed it, so the /proc validation now lives solely in core (guarded by !standalone_library).

**Comment by GandholiSarat** [comment]
Since this is my first time , I wanted to ask about the testing approach.

To validate the /proc-missing scenario locally, I’ve been using:

```
sudo unshare -m -- sh -c '
  mount --make-rprivate /
  umount -l /proc 2>/dev/null || true
  ./build/bin64/drrun -- /bin/true
'
```

This lets me simulate a missing /proc using a separate mount namespace without affecting the host system.

Is this the recommended way to validate environment-dependent behavior like this, or is there a more idiomatic way within the DR test framework to exercise such scenarios?

I’m still learning the project conventions, so I’d appreciate any guidance.

**Comment by derekbruening** [comment]
> Since this is my first time , I wanted to ask about the testing approach.
> 
> To validate the /proc-missing scenario locally, I’ve been using:
> 
> ```
> sudo unshare -m -- sh -c '
>   mount --make-rprivate /
>   umount -l /proc 2>/dev/null || true
>   ./build/bin64/drrun -- /bin/true
> '
> ```
> 
> This lets me simulate a missing /proc using a separate mount namespace without affecting the host system.
> 
> Is this the recommended way to validate environment-dependent behavior like this, or is there a more idiomatic way within the DR test framework to exercise such scenarios?
> 
> I’m still learning the project conventions, so I’d appreciate any guidance.

If you're asking whether to add a regression test: generally for new features or bug fixes it is best to add a test. For this check it feels less necessary and manual testing at commit time seems ok, but a regression test could be nice. If going the manual testing route it is good to describe in the description how it was tested.

If you're asking about using sudo in a regression test: we do have some existing sudo-requiring tests, and GA (Github Actions) VMs do allow that in batch mode. We mark such tests with a _SUDO suffix and have a cmake option RUN_SUDO_TESTS so they can be turned off to avoid annoying developers in setups where a hard to see password prompt in the middle of a set of tests is confusing.

If you're asking about using "unshare": I don't know myself if there's a better way; this would be specific to Linux but  presumably would run on GA VMs. We don't have a lot of existing regression tests of this sort so there's not much precedence. I guess related tests would be trying to support various BSD flavors which I believe don't mount procfs nearly as readily but we don't have much effort in that direction.
