### PR TITLE
i#6921: Fix heap allocation on latest Linux kernel

### LINKED ISSUE #6921: CRASH raw2trace heap allocation
This is a regression that just started happening on certain machines (maybe after an OS update?).  Still figuring it out.

raw2trace crashes on heap alloc after a heap warning:

```
$ rm -rf drmemtrace.*.dir; bin64/drrun -t drcachesim -offline -- suite/tests/bin/simple_app
$ bin64/drrun -t drcachesim -indir drmemtrace.*.dir
<Full size vmm heap allocation failed>
Segmentation fault
```

The crash:
```
Program received signal SIGSEGV, Segmentation fault.
is_region_memset_to_char (addr=0x7147a0f8 <nonshared_stats+41016> "\240\213 ", size=1608608, val=0 '\000') at <path>/dr/git/src/core/utils.c:2488
2488    {
(gdb) bt
#0  is_region_memset_to_char (addr=0x7147a0f8 <nonshared_stats+41016> "\240\213 ", size=1608608, val=0 '\000') at <path>/dr/git/src/core/utils.c:2488
#1  0x0000000071191815 in common_heap_alloc (tu=0x7ffdf7841f60, size=524288, which=ACCT_CLIENT) at <path>/dr/git/src/core/heap.c:4451
#2  0x000000007118bcff in common_global_heap_alloc (tu=0x7ffdf7841f60, size=524288, which=ACCT_CLIENT) at <path>/dr/git/src/core/heap.c:3500
#3  0x000000007119329c in heap_reachable_alloc (dcontext=0xffffffffffffffff, size=524288, which=ACCT_CLIENT) at <path>/dr/git/src/core/heap.c:4818
#4  0x0000000071202282 in dr_global_alloc (size=524288) at <path>/dr/git/src/core/lib/instrument.c:2934
#5  0x00005555557cf7d2 in hash_alloc (size=524288) at <path>/dr/git/src/ext/drcontainers/hashtable.c:139
#6  0x00005555557cfac9 in hashtable_init_ex (table=0x55555598eb70, num_bits=16, hashtype=HASH_INTPTR, str_dup=0 '\000', synch=0 '\000', 
    free_payload_func=0x5555556fac73 <dynamorio::drmemtrace::raw2trace_t::block_hashtable_t::free_payload(void*)>, hash_key_func=0x0, cmp_key_func=0x0)
    at <path>/dr/git/src/ext/drcontainers/hashtable.c:208
#7  0x00005555556fab47 in dynamorio::drmemtrace::raw2trace_t::block_hashtable_t::block_hashtable_t (this=0x55555598eb70, worker_count=12)
    at <path>/dr/git/src/clients/drcachesim/tracer/raw2trace.h:1533
#8  0x00005555556ff85a in std::__new_allocator<dynamorio::drmemtrace::raw2trace_t::block_hashtable_t>::construct<dynamorio::drmemtrace::raw2trace_t::block_hashtable_t, int&> (
    __p=0x55555598eb70, this=0x7fffffffc398) at /usr/include/c++/13/bits/new_allocator.h:191
#9  std::allocator_traits<std::allocator<dynamorio::drmemtrace::raw2trace_t::block_hashtable_t> >::construct<dynamorio::drmemtrace::raw2trace_t::block_hashtable_t, int&> (
    __p=0x55555598eb70, __a=...) at /usr/include/c++/13/bits/alloc_traits.h:538
#10 std::vector<dynamorio::drmemtrace::raw2trace_t::block_hashtable_t, std::allocator<dynamorio::drmemtrace::raw2trace_t::block_hashtable_t> >::emplace_back<int&> (
    this=0x7fffffffc398) at /usr/include/c++/13/bits/vector.tcc:117
#11 0x00005555556f831b in dynamorio::drmemtrace::raw2trace_t::raw2trace_t (this=0x7fffffffc2e0, 
    module_map=0x555555977490 "Module Table: version 5, count 22\nColumns: id, containing_id, start, end, entry, offset, preferred_base, (custom fields), path\n  0,   0, 0x00007f2fdfa08000, 0x00007f2fdfa1d000, 0x00007f2f6da08000, 000"..., thread_files=std::vector of length 1, capacity 1 = {...}, out_files=std::vector of length 0, capacity 0, 
    out_archives=std::vector of length 1, capacity 1 = {...}, encoding_file=5, serial_schedule_file=0x555555968d10, cpu_schedule_file=0x555555968e30, dcontext=0x0, 
    verbosity=0, worker_count=-1, alt_module_dir="", chunk_instr_count=10000000, Python Exception <class 'gdb.error'> No type named std::__detail::_Hash_node<struct std::pair<int const, std::basic_istream<char, std::char_traits<char> >*>, false>.: 
kthread_files_map=std::unordered_map with 0 elements, kcore_path="", kallsyms_path="", 
    syscall_template_file_reader=std::unique_ptr<class dynamorio::drmemtrace::record_reader_t> = {...})
    at <path>/dr/git/src/clients/drcachesim/tracer/raw2trace.cpp:3778
#12 0x000055555565462f in dynamorio::drmemtrace::analyzer_multi_tmpl_t<dynamorio::drmemtrace::_memref_t, dynamorio::drmemtrace::reader_t>::analyzer_multi_tmpl_t (
    this=0x555555976f30) at <path>/dr/git/src/clients/drcachesim/analyzer_multi.cpp:419
#13 0x00005555555b1a9b in main (argc=13, targv=0x7fffffffd688) at <path>/dr/git/src/clients/drcachesim/launcher.cpp:334
```

### PR DESCRIPTION
**Pull request by derekbruening**
Fixes 3 problems hit on recent Linux kernels where our mmap hints are being ignored:

1) os_heap_reserve_in_region()'s POINTER_MAX check fails as the end is aligned,
   causing an unnecessary bounded-region search.

2) vmm_place_vmcode() tries smaller sizes on failure but does not propagate
   the new size to the caller, resulting in memory corruption.

3) os_heap_reserve() for Linux now uses the new-ish MAP_FIXED_NOREPLACE
   to get the behavior various code expects without risk of clobbering.

Tested on a 6.7.12 kernel where raw2trace failed up front reliably without these fixes but now succeeds.

Further tested the size propagation with the other fixes disabled and now we have a graceful failure instead of memory corruption and a weird crash:

```
$ clients/bin64/drmemtrace_launcher -indir drmemtrace.*.dir
<Full size vmm heap allocation failed>
<Application <path>/clients/bin64/drmemtrace_launcher (3686844).  Out of memory.  Program aborted.  Source I, type 0x0000000000000001, code 0x0000000000000001.>
```

Fixes #6921

### CODE REVIEW

**Comment by derekbruening** [comment]
win64 failure is callback.c assert in windows-timestamps: #6081

File: core/heap.c [hunk 1]
```diff
@@ -877,29 +877,30 @@ vmm_place_vmcode(vm_heap_t *vmh, size_t size, heap_error_code_t *error_code)
...
-            preferred, size / (1024 * 1024), vmh->start_addr);
+            preferred, *size / (1024 * 1024), vmh->start_addr);
         if (vmh->alloc_start == NULL && DYNAMO_OPTION(vm_allow_smaller)) {
             /* Just a little smaller might fit */
             size_t sub = (size_t)ALIGN_FORWARD(size / 16, 1024 * 1024);
             SYSLOG_INTERNAL_WARNING_ONCE("Full size vmm heap allocation failed");
-            if (size > sub)
-                size -= sub;
+            /* Don't go too small. */
+            if (*size > 2 * sub)
```
Comment (brettcoon) [inline core/heap.c:902]: Should this be >= or does it really need to be greater?  Assuming these are all aligned sizes that could be a meaningful difference.

**Review by brettcoon — APPROVED** [review]
Just one question.  Thanks for the quick and non-obvious fix.

File: core/heap.c (hunk 1 above)
Comment (derekbruening) [reply core/heap.c:902]: I think the original >sub or written as >=2*sub are equivalent; I was trying to keep it slightly larger and not drop all the way to 1M as happened in the bug but 2M isn't much better so maybe it's not a worthwhile heuristic change.

Comment (derekbruening) [reply core/heap.c:902]: To answer your question more directly it could be = and not go to 0 or something catastrophic; I was trying to keep it a little bit bigger.  Leaning toward just leaving it this way.
