### PR TITLE
i#6596 linux.clone* tests on Ubuntu: Handle struct clone_args not defined

### LINKED ISSUE #6596: linux.clone* tests fail when run in a container under Ubuntu 22.04
The linux.clone* tests expect clone3 to be available if SYS_clone3 is defined.

However in some scenarios SYS_clone3 is defined but clone3 returns ENOSYS e.g. when running in a container under Ubuntu 22.04
(see https://github.com/moby/moby/pull/42681).

The linux.clone* tests should not fail if clone3 returns ENOSYS.

**To Reproduce**
# On Ubuntu 22.04:
docker run --rm -it --name dynamorio ubuntu/base:22.04 bash

git clone https://github.com/DynamoRIO/dynamorio.git && cd dynamorio
git submodule init
git submodule update

# build tests
cd ..
mkdir dynamorio_build
cd dynamorio_build
cmake -DDEBUG=ON -DBUILD_TESTS=ON ../dynamorio
make -j

# run tests
ctest --output-on-failure --timeout 120

### PR DESCRIPTION
**Pull request by xdje42**
Fix build errors resulting from #6597 by using DR's copy of struct clone_args

This has happened on Android.

Fixes #6596

### CODE REVIEW

File: suite/tests/linux/clone.c [hunk 1]
```diff
@@ -124,20 +129,23 @@ main()
     int ret_failure_clone3 = make_clone3_syscall(NULL, 0, NULL);
     assert(ret_failure_clone3 == -1);
 
-#ifndef ANDROID /* clone3 not supported on Android */
+    /* On some environments, we see that the kernel supports clone3 even though
+     * SYS_clone3 is not defined by glibc.
```
Comment (derekbruening) [inline suite/tests/linux/clone.c:133]: This doesn't all seem consistent: it makes a clone3 syscall outside of any ifdefs, and has a comment saying clone3 may be available even if SYS_clone3 is not defined, yet it puts the enabling and use of it back under an ifdef for SYS_clone3?  It doesn't seem worth trying the syscall, or implying here we should go ahead and use clone3, if below we go back to the ifdef for what matters, setting clone3_available.  This code sequence lines 128 through 147 would be simpler and more understandable if it were all under ifdef SYS_clone3 if we're never going to use clone3 if that's not defined.

**Comment by philramsey-arm** [comment]
Have confirmed that the linux.clone* tests still pass in a Ubuntu 22:04 container.

File: suite/tests/linux/clone.c (hunk 1 above)
Comment (xdje42) [reply suite/tests/linux/clone.c:133]: One needs to go back to how things were, pre- #6597.
That code was calling clone3 outside of ifdefs, presumably to make sure the right errno was returned?
Removing that is outside the scope of #6596 (which #6597 was an attempt to fix).

Comment (derekbruening) [reply suite/tests/linux/clone.c:133]: I don't follow the argument: this PR is taking a sequence of code that does work to compute `clone3_available` and adds an ifdef only around the final step instead of around all the work, when all the work is *only* for computing that final step `clone3_available`: so it is this PR which is introducing the awkward code.  Not seeing why the history matters.

Comment (abhinav92003) [reply suite/tests/linux/clone.c:133]: > Question: Why does it make a clone3 syscall ifndef SYS_clone3 ?
> That code was calling clone3 outside of ifdefs, presumably to make sure the right errno was returned?

Maybe your question is why do we need to verify clone3 behaviour if SYS_clone3 is not defined?

Note that clone3 is one of the syscalls that DR intercepts. So if SYS_clone3 is not defined but the app still tries to make the syscall, we want to make sure that DR returns the correct error code.

Comment (xdje42) [reply suite/tests/linux/clone.c]: Rewrote patch to use DR's copy of struct clone_args from core/unix/include/clone3.h.

File: suite/tests/linux/clone.c [hunk 2]
```diff
@@ -48,6 +48,7 @@
 #include <errno.h>
```
Comment (abhinav92003) [inline suite/tests/linux/clone.c:48]: Q: Is the test failing by not building successfully, or by running incorrectly? I assume it's the latter because the issue description says "The linux.clone* tests should not fail if clone3 returns ENOSYS." But I would have expected a missing struct definition to cause a build failure.

I'm probably missing some context. Could you clarify in the PR description?

Comment (xdje42) [reply suite/tests/linux/clone.c:48]: The test is failing due to build errors.

File: suite/tests/linux/clone.c [hunk 3]
```diff
@@ -120,23 +121,23 @@ test_thread(bool share_sighand, bool clone_vm, bool use_clone3)
...
     int ret_failure_clone3 = make_clone3_syscall(NULL, 0, NULL);
     assert(ret_failure_clone3 == -1);
 
-#ifndef ANDROID /* clone3 not supported on Android */
-    /* i#6596 In some scenarios SYS_clone3 is defined but clone3 returns ENOSYS
-     * e.g. when running in a container under Ubuntu 22.04
+    /* In some environments, we see that the kernel supports clone3 even though
+     * SYS_clone3 is not defined by glibc. So we don't predicate our efforts on
+     * whether SYS_clone3 is defined.
+    /* Plus in some scenarios SYS_clone3 is defined but clone3 returns ENOSYS.
```
Comment (abhinav92003) [inline suite/tests/linux/clone.c:134]: Since this "Plus..." is a continuation of the above statement, better to not keep it in a separate comment, otherwise it loses context.

File: suite/tests/linux/clone.c [hunk 4]
```diff
@@ -48,6 +48,7 @@
 #include <errno.h>
 
 #include "tools.h" /* for nolibc_* wrappers. */
```
Comment (abhinav92003) [inline suite/tests/linux/clone.c:50]: Re the PR description: The issue is likely not specific to Ubuntu. It probably happens where the glibc version is older (so the struct is not defined)?

Either way, instead of trying to fit that into the concise PR title, maybe include the affected platforms in the PR description.

**Review by abhinav92003 — APPROVED** [review]

File: suite/tests/linux/clone.c (hunk 4 above)
Comment (xdje42) [reply suite/tests/linux/clone.c:50]: Done, modulo internal builds.

File: suite/tests/linux/clone.c (hunk 3 above)
Comment (xdje42) [reply suite/tests/linux/clone.c]: Done
