### PR TITLE
i#4496: Fix reset issues on AArch64 and x86

### LINKED ISSUE #4496: ASSERT failure using `reset_at_nth_thread 2` on test app
**Describe the bug**
DR crashes with an assert failure with the `-reset_at_nth_thread 2` option. The assert failure is different on AArch64 and x86.

**To Reproduce**
`bin64/drrun -enable_reset -reset_at_nth_thread 2  -- suite/tests/bin/linux.thread`

**Screenshots or Pasted Text**
On AArch64:
```
<proactive reset @ 1309 fragments>
Sideline thread started
<Application build/dynamorio/suite/tests/bin/linux.thread (33389).  Internal Error: DynamoRIO debug check failure: Not implemented @src/dynamorio/core/unix/signal_linux_aarch64.c:53 (0)
(Error occurred @1327 frags)
version 8.0.18562, custom build
-no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -enable_reset -reset_at_nth_thread 2 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
```

On x86:
```
 <proactive reset @ 1736 fragments>
<Application build/dynamorio/suite/tests/bin/linux.thread (2261478).  Internal Error: DynamoRIO debug check failure: src/dynamorio/core/dispatch.c:751 wherewasi == DR_WHERE_FCACHE || wherewasi == DR_WHERE_TRAMPOLINE || wherewasi == DR_WHERE_APP || (dcontext->go_native && wherewasi == DR_WHERE_DISPATCH)
(Error occurred @1736 frags)
version 8.0.18563, custom build
-no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -reset_at_nth_thread 2 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
```

**Versions**
Working on PR #4491 

**Additional context**
The same issue comes up with `-reset_at_created_thread_count 2` (this is a new flag tried while working on the above PR; this flag resets when created thread count reaches 2, unlike `reset_at_nth_thread` which checks the active thread count). But the failure does not come up with `-reset_at_created_thread_count 3`.
(Note that `reset_at_nth_thread 3` doesn't invoke the failing path at all)

### LINKED ISSUE #4497: SIGSEGV due to wrong stolen reg value after synchall
While working on PR #4491 which adds a synchall to drcachesim while enabling tracing, I encountered a crash due to the stolen reg having a value that doesn't seem like an address.

The segfaulting threads were redirected to the reset exit stub by DR at [1]. The `SIGSEGV` occurs in the exit stub shown below.

```
Thread xxx received signal SIGSEGV, Segmentation fault.
0x0000000046fc2458 in ?? ()
(gdb) x/50i 0x46fc2458
=> 0x46fc2458:	stp	x0, x1, [x28]
   0x46fc245c:	mov	x0, #0x4c20                	// #19488
   0x46fc2460:	movk	x0, #0xf7f0, lsl #16
   0x46fc2464:	movk	x0, #0xffff, lsl #32
   0x46fc2468:	ldr	x1, [x28, #64]
   0x46fc246c:	br	x1
   ...
```
The exit stub expects the stolen reg to be set up already, but it doesn't seem to be -- see `x28` below.
```
(gdb) i r 
x0             0xfffffffffffffffc  -4
x1             0xfffff45bcc80      281474781400192
...
x28            0x30000             196608
...
pc             0x46fc2458          0x46fc2458
```

The issue was fixed by adding a stolen reg store. Also there's a bug in the reset tests `linux.thread-reset` and `linux.clone-reset`, due to which they don't fail on AArch64 when they should.

Filing and fixing these separately from the PR #4491.

[1]: `translate_from_synchall_to_dispatch` https://github.com/DynamoRIO/dynamorio/blob/9bedb9c72d5808785e28d20df3ed1c932b555ac9/core/synch.c#L1816

### PR DESCRIPTION
**Pull request by abhinav92003**
Changes reset trigger for `linux.thread-reset` and `linux.clone-reset` tests to `-reset_at_nth_thread`. To increase coverage of these tests, we need to trigger reset at a time when multiple threads are active. This is difficult to do using the existing` -reset_at_fragment_count` option in tests, which may need to be tuned regularly to its ideal value, which also differs based on platform.

Implements some missing AArch64 pieces for `dynamorio_sigreturn`.

Relaxes dispatch assert to allow threads to enter dispatch after reset. The current condition allows it only when sending threads native.

Fixes #4496
Fixes #4497

### CODE REVIEW

File: core/unix/signal.c [hunk 1]
```diff
@@ -2676,12 +2675,16 @@ thread_set_self_context(void *cxt)
...
 #ifdef LINUX
 #    ifdef X86
+    dcontext_t *dcontext = get_thread_private_dcontext();
     byte *xstate = get_and_initialize_xstate_buffer(dcontext);
     frame.uc.uc_mcontext.fpstate = &((kernel_xstate_t *)xstate)->fpstate;
 #    endif /* X86 */
     frame.uc.uc_mcontext = *sc;
 #endif
+    IF_ARM(ASSERT_NOT_TESTED());
+#if defined(LINUX) && defined(X86)
```
Comment (abhinav92003) [inline core/unix/signal.c:2685]: @AssadHashmi Do we need any special handling for fpstate on AArch64/ARM?

Copying over the [conversation](https://github.com/DynamoRIO/dynamorio/issues/4496#issuecomment-718945863) from #4496. 

> > abhinav92003: @derekbruening About the `ASSERT_NOT_IMPLEMENTED` in `save_fpstate` for AArch64: Do we need special handling for fpstate on AArch64/ARM?
> 
> derekbruening: I don't think so: dr_mcontext.simd[] should hold all the direct values (i.e., it's not like x86 where the x87 state is not in dr_mcontext_t _at all_). Maybe there are status registers or sthg though? I remember this coming up recently in some issue or PR and Assad was not sure -- I can't find the issue though: recent ones are #4467, #4488.
> 
> @AssadHashmi -- if you could comment.

File: core/dispatch.c [hunk 2]
```diff
@@ -752,9 +752,10 @@ dispatch_enter_dynamorio(dcontext_t *dcontext)
            wherewasi == DR_WHERE_APP ||
            /* If the thread was waiting at check_wait_at_safe_point when getting
             * suspended, we were in dispatch (ref i#3427). We will be here after the
-            * thread's context is being reset before sending it native.
+            * thread's context is being reset proactively (due to some -reset_at_*
+            * option) or before sending it native.
             */
-           (dcontext->go_native && wherewasi == DR_WHERE_DISPATCH));
+           wherewasi == DR_WHERE_DISPATCH);
```
Comment (derekbruening) [inline core/dispatch.c:758]: Could this instead keep the `go_native` and add to it "or the last exit was the special reset exit"?

File: core/unix/signal.c [hunk 3]
```diff
@@ -2676,12 +2675,16 @@ thread_set_self_context(void *cxt)
     memset(&frame, 0, sizeof(frame));
 #ifdef LINUX
 #    ifdef X86
+    dcontext_t *dcontext = get_thread_private_dcontext();
```
Comment (derekbruening) [inline core/unix/signal.c:2678]: It seems fragile to put this decl in a different ifdef set from the save_fpstate usage below.

File: core/unix/signal.c (hunk 1 above)
Comment (derekbruening) [inline core/unix/signal.c:2685]: The prior code called this for non-Linux too (e.g., MacOS) so this does not seem like a safe change.

File: core/unix/signal.c [hunk 4]
```diff
@@ -2709,12 +2715,13 @@ thread_set_self_context(void *cxt)
     asm("mov  %0, %%" ASM_XCX : : "m"(asm_jmp_tgt));
     asm("jmp  *%" ASM_XCX);
 #    endif /* MACOS/LINUX */
-#elif defined(AARCH64)
-    ASSERT_NOT_IMPLEMENTED(false); /* FIXME i#1569 */
+#elif defined(AARCH64) && !defined(DR_HOST_NOT_TARGET)
```
Comment (derekbruening) [inline core/unix/signal.c:2718]: This additional host check should not just be added to one of these arches: the behavior should be the same for other host-target combinations.  Instead, in general either A) DR_HOST_<arch> should be used as the condition for each of asm block or B) We don't support host!=target here since we only support non-code-execution use (decoding; standalone lib) and there should be a check for that with ASSERT_NOT_REACHED just like elsewhere in this file (e.g., notify_and_jmp_without_stack()).

File: core/synch.c [hunk 5]
```diff
@@ -1815,9 +1815,17 @@ translate_from_synchall_to_dispatch(thread_record_t *tr, thread_synch_state_t sy
...
         LOG(GLOBAL, LOG_CACHE, 2, "\tsent to reset exit stub " PFX "\n", mc->pc);
-        /* TODO i#4497: Replace with the official fix from PR#4498. */
-        IF_AARCHXX(set_stolen_reg_val(mc, (reg_t)os_get_dr_tls_base(dcontext)));
-        IF_AARCHXX(ASSERT_NOT_TESTED()); /* PR#4498 will improve test coverage. */
+        /* The reset exit stub expects the stolen reg to contain the TLS base address.
+         * But the stolen reg was restored to the application value during
+         * translate_mcontext.
+         */
+        IF_AARCHXX({
+            // XXX i#4495: Consider saving stolen reg's translated application value.
```
Comment (derekbruening) [inline core/synch.c:1823]: style nit: It does say at https://github.com/DynamoRIO/dynamorio/wiki/Code-Style#commenting-conventions to prefer `/* */` to `//` in C code though we could vote to change that.

I would use something stronger than "Consider" since this seems to be a correctness bug.

Ditto below.

File: core/unix/signal.c (hunk 4 above)
Comment (abhinav92003) [reply core/unix/signal.c:2718]: There's an `ASSERT_NOT_REACHED` after this ladder, but +1 on making it clearer like `notify_and_jmp_without_stack`.

File: core/unix/signal.c (hunk 1 above)
Comment (abhinav92003) [reply core/unix/signal.c:2685]: Non-Linux seems to skip `save_fpstate` at other spots too.
https://github.com/DynamoRIO/dynamorio/blob/420adb01d466e134037b1db6ed7023749c3f8034/core/unix/signal.c#L5575
Do we need a fix there as well?

Comment (derekbruening) [reply core/unix/signal.c:2685]: Huh, that's weird.  I would expect Mac on x86 to need the same thing, yes, for the x87 state which is not in the mcontext and so can't be updated from there.  Wondering if changing that will hit the assert on the mac tests though.

File: core/dispatch.c (hunk 2 above)
Comment (abhinav92003) [reply core/dispatch.c]: Done.

File: core/unix/signal.c (hunk 4 above)
Comment (abhinav92003) [reply core/unix/signal.c]: Done.

File: core/synch.c (hunk 5 above)
Comment (abhinav92003) [reply core/synch.c]: Oh sorry about that. Done.

File: core/unix/signal.c (hunk 3 above)
Comment (abhinav92003) [reply core/unix/signal.c]: Separated the declaration into its own ifdef.

File: core/unix/signal.c (hunk 1 above)
Comment (abhinav92003) [reply core/unix/signal.c]: macOS doesn't implement `save_fpstate`
https://github.com/DynamoRIO/dynamorio/blob/a5ab87c9c24f176a474dc1b7d3cb4cc4fe4d8ed4/core/unix/signal_macos.c#L145

I modified the preprocessor guard to allow `save_fpstate` for macOS builds, but macOS still passes on Travis: https://travis-ci.com/github/DynamoRIO/dynamorio/jobs/425890837.

Comment (abhinav92003) [reply core/unix/signal.c]: In a bunch of spots in `signal.c`, I see that fpstate handling is done only for `X86 && LINUX` (not including macOS). Do we need to re-evaluate this, perhaps as part of a separate issue?

Comment (derekbruening) [reply core/unix/signal.c]: The signal frame extended state layout is different: maybe you're seeing code specific to how Linux lays it out.  The general step of updating the fpstate on a delayed signal to have the new delivery spot's state is what is common and that should only be in a couple of places calling save_fpstate.   I'm guessing you're looking at different code that is not related to that step.

File: core/unix/signal.c [hunk 6]
```diff
@@ -2692,11 +2697,16 @@ thread_set_self_context(void *cxt)
                         sizeof(frame.uc.uc_sigmask));
     LOG(THREAD_GET, LOG_ASYNCH, 2, "thread_set_self_context: pc=" PFX "\n", sc->SC_XIP);
     LOG(THREAD_GET, LOG_ASYNCH, 3, "full sigcontext\n");
-    DOLOG(LOG_ASYNCH, 3,
-          { dump_sigcontext(dcontext, get_sigcontext_from_rt_frame(&frame)); });
+    DOLOG(LOG_ASYNCH, 3, {
+        dcontext_t *dcontext = get_thread_private_dcontext();
```
Comment (derekbruening) [inline core/unix/signal.c:2701]: This is shadowing the var of the same name in the outer scope: please fix.  Surprising the compiler doesn't warn about it (MSVC complains about such things).  Maybe best to just put it back how it was, with dcontext in all builds.  Your goal was to remove the call to gtpd for arm?  Is it not removed by the compiler in a release build?

**Review by derekbruening — APPROVED** [review]

File: core/unix/signal.c (hunk 6 above)
Comment (abhinav92003) [reply core/unix/signal.c:2701]: All usages of `dcontext` in this function are conditional (on either some environment or build type) now, unlike before this PR. So it's slightly tricky to avoid unused var errors.

For this case, it seems that `DOLOG` is defined only under a complex combination (`INTERNAL && DEBUG && !STANDALONE_DECODER`). So I figured it's best to let there be a separate declaration here; I'll just change the identifier so that it doesn't shadow the one in outer scope.

File: core/unix/signal.c (hunk 1 above)
Comment (abhinav92003) [reply core/unix/signal.c]: Oh okay. 

The other `save_fpstate` instance[1] in `signal.c` is invoked during `receive_pending_signal`, so we do expect that to be done for macOS too right? 

About this instance of `save_fpstate` not being hit in macOS tests: actually the reset tests don't seem to be enabled for macOS. Do we want them to be?

[1]: https://github.com/DynamoRIO/dynamorio/blob/420adb01d466e134037b1db6ed7023749c3f8034/core/unix/signal.c#L5575

File: core/unix/signal.c (hunk 6 above)
Comment (abhinav92003) [reply core/unix/signal.c]: Done.

File: core/unix/signal.c (hunk 1 above)
Comment (AssadHashmi) [reply core/unix/signal.c]: Apologies for the late response @abhinav92003 and @derekbruening, this slipped under the mat.

> Do we need special handling for fpstate on AArch64/ARM?

Not in this case AFAICT.

For future reference, the full implementation of `save_fpstate` for AArch64 is tracked by https://github.com/DynamoRIO/dynamorio/issues/2629

Comment (abhinav92003) [reply core/unix/signal.c]: Discussed offline. 

Added an XXX comment for now for the other `save_fpstate`. Will investigate in a separate PR if we need any changes there.

**Review by AssadHashmi — APPROVED** [review]

File: core/unix/signal.c (hunk 1 above)
Comment (abhinav92003) [reply core/unix/signal.c]: Thanks Assad and Derek. (Some more discussion on #2629).
