### PR TITLE
i#3526: Apply scheme of i#2089 to client threads.

### LINKED ISSUE #3526: ASSERT code_api|client.thread sporadic failure: os.c:1980 !is_thread_tls_initialized().
From a local run on modern Linux machine:

```
Starting application /usr/local/google/home/hgreving/dynamorio/build/suite/tests/bin/client.thread (238047)>
<Initial options = -no_dynamic_options -logdir 'logs' -loglevel 3 -client_lib '/usr/local/google/home/hgreving/dynamorio/build/suite/tests/bin/libclient.thread.dll.so;0;"-paramx" "-paramy"' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/usr/local/google/home/hgreving/dynamorio/build/suite/tests/bin/libclient.thread.dll.so' 0x0000000072001620
add-symbol-file '/usr/local/google/home/hgreving/dynamorio/build/lib64/debug/libdynamorio.so' 0x00007f9596a6c738
add-symbol-file '/lib64/libc.so.6' 0x00007f9596496910
add-symbol-file '/lib64/ld-linux-x86-64.so.2' 0x00007f9596250aa0
>
PR 216931: client options are -paramx -paramy
inside app client.thread.exe
PR 198871 locking test......passed
<Application /usr/local/google/home/hgreving/dynamorio/build/suite/tests/bin/client.thread (238047).  Internal Error: DynamoRIO debug check failure: /usr/local/google/home/hgreving/dynamorio/src/core/unix/os.c:1980 !is_thread_tls_initialized()                                      
(Error occurred @0 frags)
```

cat /proc/version 
Linux version 4.19.20-1rodete1-amd64

Seems to happens very rarely. Might be related to #3498 .

### PR DESCRIPTION
**Pull request by hgreving2304**
When creating client threads, we still attempted to invalidate the thread's TLS by writing
a null selector to its segment register. In 64-bit mode, this seemed to work most of the
time because presumably Intel and AMD are then zero'ing out the the hidden segment's
base. Intel doesn't precisely describe this in Vol. 3A 3.4.4.

This patch applies the same scheme introduced and described in #2089.

Before this patch, the test code_api|client.thread ran into all kinds of assertions,
because the client thread interfered with the parent's TLS. These failures are now gone.

Fixes #3526
Issue: #2089

### CODE REVIEW

File: core/unix/os.c [hunk 1]
```diff
@@ -3719,9 +3719,11 @@ dr_create_client_thread(void (*func)(void *param), void *arg)
 #        endif
     LOG(THREAD, LOG_ALL, 1, "dr_create_client_thread xsp=" PFX " dstack=" PFX "\n", xsp,
         get_clone_record_dstack(crec));
+    os_clone_pre(dcontext);
```
Comment (derekbruening) [inline core/unix/os.c]: But we're already doing os_switch_lib_tls to app a few lines above, so there is now redundancy we should alleviate.

Comment (derekbruening) [inline core/unix/os.c]: Should we be worried that os_clone_pre, which is meant to handle an app thread doing a clone, will in some future change do something extra that we do not want done for cloning while in DR mode?  At least a comment should be added to os_clone_{pre,post} that they are used for client threads too and they should not do anything that assumes the app.

Comment (derekbruening) [inline core/unix/os.c]: Won't the 32-bit CLONE_SETTLS undo this?  I don't think we should be doing both.

Comment (hgreving2304) [reply core/unix/os.c]: Wait, but this switches the "lib tls" (os_switch_*lib*_tls) right, i.e. "fs"? Not DR's "gs" (Linux X64).

Comment (hgreving2304) [reply core/unix/os.c]: Ok.

Comment (hgreving2304) [reply core/unix/os.c]: Again, I think it is "fs". The 32-bit version of the test works fine it seems. Not sure why we are treating 32-bit different using SETTLS? It does seem like os_switch_lib_tls and the SETTLS are redundant in a way, for 32-bit.

Comment (derekbruening) [reply core/unix/os.c]: Like I said, this code is already doing os_switch_lib_tls, and you're adding code doing the exact same thing over again (one of the 2 things that os_clone_pre does).

Comment (derekbruening) [reply core/unix/os.c]: That is the point: you're adding code for 32-bit which is undone by the existing code.  One or the other should be changed.  Probably the older, to avoid having the correct magic, though I have not thought it through.

Comment (hgreving2304) [reply core/unix/os.c]: I see now! => redundant one removed.

Comment (hgreving2304) [reply core/unix/os.c]: Done.

Comment (hgreving2304) [reply core/unix/os.c]: Yes that's true. I did not understand why SETTLS is used for 32-bit. I felt it is more safe to leave it than changing it. There is nothing I can see where this seems necessary. Clearing the segment register in dynamorio_clone and the SETTLS seem redundant. I felt more comfortable with leaving this, but that said, I removed it, test(s) look(s) fine.

File: core/unix/os.c [hunk 2]
```diff
@@ -3686,9 +3695,9 @@ dr_create_client_thread(void (*func)(void *param), void *arg)
      * the thread list for the app, making it more invisible.
      */
     uint flags = CLONE_VM | CLONE_FS | CLONE_FILES |
-        CLONE_SIGHAND IF_NOT_X64(| CLONE_SETTLS)
-        /* CLONE_THREAD required.  Signals and itimers are private anyway. */
-        IF_VMX86(| (os_in_vmkernel_userworld() ? CLONE_THREAD : 0));
+        CLONE_SIGHAND
+            /* CLONE_THREAD required.  Signals and itimers are private anyway. */
```
Comment (derekbruening) [inline core/unix/os.c]: Without CLONE_SETTLS we do not need to create and pass &desc, so that code can go, right.

Comment (hgreving2304) [reply core/unix/os.c]: Looks like yes. It mentions 'Linux' and VMX86_SERVER in the comment. But I think this is just with regards to differences setting the tls in clone. So I guess it is hopefully ok even though I didn't want to touch it. Done.

Comment (derekbruening) [reply core/unix/os.c]: Well, you can't remove CLONE_SETTLS and leave desc: without CLONE_SETTLS that &desc parameter is ignored by the kernel and it is not clean code to pass it in.

Comment (hgreving2304) [reply core/unix/os.c]: (I didn't want to touch the entire CLONE_SETTLS but I think it's ok.)
