### PR TITLE
i#6612: Add code_api|api.rseq to Linux x64 flaky test ignore list

### LINKED ISSUE #6612: Ignore failing api.rseq test
Add api.rseq test to blocklist in runsuite_wrapper.pl.

Xref #6185

### PR DESCRIPTION
**Pull request by edeiana**
Adds code_api|api.rseq test to Linux 64-bit ignore list
in suite/runsuite_wrapper.pl.

Issue: #1807 #6185

### CODE REVIEW

**Comment by edeiana** [comment]
I'm currently unable to check if this test is actually ignored (I am missing too many things on my current machine), but it's a one line change, so it should be easy to see if I messed up something.

File: suite/runsuite_wrapper.pl [hunk 1]
```diff
@@ -305,6 +305,7 @@
                 'finite_shared_bb_cache,cache_shared_bb_regen|common.nativeexec' => 1, # i#1807
                 'finite_shared_trace_cache,cache_shared_trace_regen|common.nativeexec' => 1, # i#1807
                 # We list this without any "options|" which will match all variations.
+                'api.rseq' => 1, # i#6612
```
Comment (derekbruening) [inline suite/runsuite_wrapper.pl:308]: This is the Windows 64-bit list: the Linux one is below (~line 396).

**Review by derekbruening — CHANGES_REQUESTED** [review]

File: suite/runsuite_wrapper.pl (hunk 1 above)
Comment (edeiana) [reply suite/runsuite_wrapper.pl]: My bad, didn't see the outer condition. Fixed.

File: suite/runsuite_wrapper.pl [hunk 2]
```diff
@@ -391,6 +391,7 @@
                 'prof_pcs,thread_private|common.nativeexec_bindnow_opt' => 1, # i#2052
```
Comment (derekbruening) [inline suite/runsuite_wrapper.pl:391]: > Fixes https://github.com/DynamoRIO/dynamorio/issues/6612

No need for a new issue for something like this which targets the existing #6185 on the failing test: #6185 should be the issue in the title and description.  A PR is like an issue (same namespace) so this PR documents the act of ignoring it.

Comment (derekbruening) [inline suite/runsuite_wrapper.pl:391]: Add a ref to #1807 in the Issue line since this is part of trying to get the post-merge suite green.

File: suite/runsuite_wrapper.pl [hunk 3]
```diff
@@ -391,6 +391,7 @@
...
                 );
             %ignore_failures_64 = (
+                'api.rseq' => 1, # i#6612
```
Comment (derekbruening) [inline suite/runsuite_wrapper.pl:394]: Have you seen it fail in other than `code_api|`?  Or you're just being proactive, just in case?

**Review by derekbruening — CHANGES_REQUESTED** [review]

File: suite/runsuite_wrapper.pl (hunk 2 above)
Comment (edeiana) [reply suite/runsuite_wrapper.pl:391]: Got it!

File: suite/runsuite_wrapper.pl (hunk 3 above)
Comment (edeiana) [reply suite/runsuite_wrapper.pl:394]: I have not, I followed our document and assumed we didn't want to include `code_api|`.
Although, `ctest -N` shows that only `code_api|api.rseq` exists, so I'll put the full name.

File: suite/runsuite_wrapper.pl (hunk 2 above)
Comment (edeiana) [reply suite/runsuite_wrapper.pl:391]: Done.

File: suite/runsuite_wrapper.pl (hunk 3 above)
Comment (derekbruening) [reply suite/runsuite_wrapper.pl]: Curious which document this is?

It would have been fine to not have the prefix; tradeoffs between tighter relaxation to avoid hiding problems vs not relaxing enough so could see it either way.

**Comment by edeiana** [comment]
However, looking at the output of github action: "ci-x86/x86-64" it seems like `code_api|api.rseq` is still being executed.

`Start 469: code_api|api.rseq
469: Test command: /home/runner/work/dynamorio/dynamorio/build_debug-internal-64/bin64/runstats "-s" "90" "-killpg" "-silent" "-env" "LD_LIBRARY_PATH" "/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/lib64/debug:/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/ext/lib64/debug:" "-env" "DYNAMORIO_OPTIONS" "-stderr_mask 0xC -dumpcore_mask 0 -code_api" "/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/suite/tests/bin/api.rseq"
469: Test timeout computed to be: 120
469: kernel_xfer_event: type 10
469: kernel_xfer_event: type 0
469: kernel_xfer_event: type 1
469: kernel_xfer_event: type 10
469: kernel_xfer_event: type 0
469: kernel_xfer_event: type 1
469: kernel_xfer_event: type 10
469: kernel_xfer_event: type 0
469: kernel_xfer_event: type 1
469: kernel_xfer_event: type 10
469: kernel_xfer_event: type 10
469: kernel_xfer_event: type 0
469: kernel_xfer_event: type 1
469: kernel_xfer_event: type 10
469: All done
466/487 Test #469: code_api|api.rseq ................................................   Passed    1.12 sec`

(https://github.com/DynamoRIO/dynamorio/actions/runs/7736068871/job/21092792695?pr=6613#step:7:40965)

Am I looking in the wrong place or is the ignoring part actually not working?

File: suite/runsuite_wrapper.pl (hunk 2 above)
[the remark this answers is not in the document]
Comment (edeiana) [reply suite/runsuite_wrapper.pl:391]: Done.

[the remark this answers is not in the document]
Comment (edeiana) [reply suite/runsuite_wrapper.pl:391]: Got it, PR title changed.
Now, only referencing the relevant issues.

File: suite/runsuite_wrapper.pl [hunk 4]
```diff
@@ -391,6 +391,7 @@
                 'prof_pcs,thread_private|common.nativeexec_bindnow_opt' => 1, # i#2052
                 );
             %ignore_failures_64 = (
+                'code_api|api.rseq' => 1, # i#6185 i#1807
```
[the remark this answers is not in the document]
Comment (edeiana) [reply suite/runsuite_wrapper.pl:394]: I think the title has all the info in this case, so now the PR description only references the issues #1807 #6185 mentioned before.

File: suite/runsuite_wrapper.pl (hunk 3 above)
Comment (edeiana) [reply suite/runsuite_wrapper.pl]: The "bespoke circuits weekly" it states only `api.rseq` without `code_api|`.

File: suite/runsuite_wrapper.pl (hunk 4 above)
[the remark this answers is not in the document]
Comment (edeiana) [reply suite/runsuite_wrapper.pl:394]: Or did I misinterpreted? Did you mean I should add `i#6612` to `suite/runsuite_wrapper.pl`?

**Comment by derekbruening** [comment]
> However, looking at the output of github action: "ci-x86/x86-64" it seems like code_api|api.rseq is still being executed.

This list only ignores a failure: it does not stop it from executing.

File: suite/runsuite_wrapper.pl (hunk 3 above)
Comment (derekbruening) [reply suite/runsuite_wrapper.pl]: Ah, that was me using shorthand; nothing deliberately implied.

File: suite/runsuite_wrapper.pl (hunk 4 above)
[the remark this answers is not in the document]
Comment (derekbruening) [reply suite/runsuite_wrapper.pl:394]: I meant that the PR description talked about having no prefix while the code now has a prefix.

> I think the title has all the info in this case, so now the PR description only references the issues https://github.com/DynamoRIO/dynamorio/issues/1807 https://github.com/DynamoRIO/dynamorio/issues/6185 mentioned before.

Generally we make the body stand on its own and usually repeat part of or the gist of the title in the body so I would still put a first sentence even if it duplicates most of the title (some tools separate the two completely and you find yourself just looking at the body).

File: suite/runsuite_wrapper.pl (hunk 3 above)
Comment (edeiana) [reply suite/runsuite_wrapper.pl]: Our internal document :)

**Review by derekbruening — APPROVED** [review]

File: suite/runsuite_wrapper.pl (hunk 4 above)
[the remark this answers is not in the document]
Comment (edeiana) [reply suite/runsuite_wrapper.pl:394]: Understood, fixed.
