### PR TITLE
i#3307 mangling epilogue asynch interrupt: fix rip-rel mangling case

### LINKED ISSUE #2941: burst_threadfilter test failing with "Cannot correctly handle a received signal"
Xref #26

https://travis-ci.org/DynamoRIO/dynamorio/jobs/368242799
```
  5/290 Test #250: code_api|tool.drcacheoff.burst_threadfilter ..................***Failed   11.62 sec
Running cmd |/home/travis/build/DynamoRIO/dynamorio/build_debug-internal-64/clients/bin64/tool.drcacheoff.burst_threadfilter|
CMake Error at /home/travis/build/DynamoRIO/dynamorio/suite/tests/runmulti.cmake:106 (message):
  *** cmd failed (40): pre-DR init
  pre-DR start
  pre-DR detach
  pre-DR init
  pre-DR start
  pre-DR detach
  pre-DR init
  pre-DR start
  pre-DR detach
  <ERROR: master_signal_handler with no siginfo (i#26?): tid=18964, sig=11>
  <Application
  /home/travis/build/DynamoRIO/dynamorio/build_debug-internal-64/clients/bin64/tool.drcacheoff.burst_threadfilter
  (18958).  Cannot correctly handle a received signal.>
  ***
```

### PR DESCRIPTION
**Pull request by hgreving2304**
Supports xl8 of spots in epilogue of rip-rel mangling, e.g. caused by an asynch signal. This patch adds support to advance the program counter properly as described in xref #3307 for the simplest case, which is rip-rel mangled instruction not part of another mangled region. These simple mangling epilogue instructions are marked with a new flag, and checks have been added to constrain this to the simplest case.

Adds XXX i#3307 comments to parts in mangling that need to get reviewed.

Adds 2 tests. The test client.mangle_suspend reliably exposes bug as described above.

Issue: #3307
Fixes #2941

### CODE REVIEW

**Comment by derekbruening** [comment]
> The bug is exposed only if we xl8 the PC, e.g. during detach.
Or any synchall: e.g., a client calling dr_suspend_all_other_threads

File: core/arch/instr_shared.c [hunk 1]
```diff
@@ -2159,6 +2159,37 @@ instr_set_our_mangling(instr_t *instr, bool ours)
         instr->flags &= ~INSTR_OUR_MANGLING;
 }
 
+bool
+instr_is_our_mangling_epilogue(instr_t *instr)
+{
+    ASSERT(!TEST(INSTR_OUR_MANGLING_EPILOGUE, instr->flags) ||
+           instr_is_our_mangling(instr));
```
Comment (derekbruening) [inline core/arch/instr_shared.c]: This should be in the header comment: as written a caller would expect this to return false for !instr_is_our_mangling with INSTR_OUR_MANGLINE_EPILOGUE set, instead of an assert firing.  The assumption/requirements should be documented: this routine requires the caller to already know that instr is our-mangling.

File: core/arch/instr_shared.c [hunk 2]
```diff
@@ -2159,6 +2159,37 @@ instr_set_our_mangling(instr_t *instr, bool ours)
...
+instr_set_our_mangling_epilogue(instr_t *instr, bool epilogue)
+{
+    if (epilogue) {
+        instr->flags |= INSTR_OUR_MANGLING_EPILOGUE;
+    } else
+        instr->flags &= ~INSTR_OUR_MANGLING_EPILOGUE;
+}
+
+instr_t *
+instr_set_translation_mangling_epilogue(dcontext_t *dcontext, instr_t *mangle_instr,
```
Comment (derekbruening) [inline core/arch/instr_shared.c]: I found this name mangle_instr confusing: it sounds like one or our inserted instructions for mangling, but in usage this is the app instruction.  Maybe it's better to remove this parameter and instead call instrlist_get_translation_target() here?  That will avoid subtle bugs with "instr" being something else: we know the instrlist xl8 is the right thing.

File: core/arch/x86/mangle.c [hunk 3]
```diff
@@ -1495,6 +1495,7 @@ mangle_direct_call(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
     if (target == (app_pc)retaddr) {
         LOG(THREAD, LOG_INTERP, 3, "found call to next instruction " PFX "\n", target);
     } else {
+        /* XXX i#3307: necessary to instr_set_translation_mangling_epilogue? */
```
Comment (derekbruening) [inline core/arch/x86/mangle.c]: No, we can't skip any of the mangling after the suspend point: this should follow the other mangling and undo its push.

File: core/arch/x86/mangle.c [hunk 4]
```diff
@@ -1754,6 +1755,7 @@ mangle_indirect_call(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
     instr_set_our_mangling(instr, true);
 
 #    ifdef CHECK_RETURNS_SSE2
+    /* XXX i#3307: necessary to instr_set_translation_mangling_epilogue? */
```
Comment (derekbruening) [inline core/arch/x86/mangle.c]: Ditto

File: core/arch/x86/mangle.c [hunk 5]
```diff
@@ -1798,6 +1800,7 @@ mangle_return(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
     opnd_size_t retsz;
 
 #    ifdef CHECK_RETURNS_SSE2
+    /* XXX i#3307: necessary to instr_set_translation_mangling_epilogue? */
```
Comment (derekbruening) [inline core/arch/x86/mangle.c]: Ditto

File: core/arch/x86/mangle.c [hunk 6]
```diff
@@ -1823,6 +1826,7 @@ mangle_return(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
         IF_X64(ASSERT_TRUNCATE(val, int, opnd_get_immed_int(instr_get_src(instr, 0))));
         /* addl sizeof_param_area, %xsp
          * except that clobbers the flags, so we use lea */
+        /* XXX i#3307: necessary to instr_set_translation_mangling_epilogue? */
```
Comment (derekbruening) [inline core/arch/x86/mangle.c]: Looking at translate_walk_track(), this OP_lea won't match any of the cases, and so will set unsupported_mangle to true and just fail, which is a perfectly acceptable thing to do for a situation that can't involve a synchronous fault.

In fact this brings up an alternative way to solve this rip-rel case: if it's easy to identify the spilled reg restore for rip-rel we can just fail and not bother to translate.  Not sure we were seriously considering that before?  Is that simpler than doing all of this?

File: core/arch/x86/mangle.c [hunk 7]
```diff
@@ -2162,6 +2166,7 @@ mangle_syscall_arch(dcontext_t *dcontext, instrlist_t *ilist, uint flags, instr_
                                         NULL);
         /* sysenter goes here */
         PRE(ilist, next_instr, post_sysenter);
+        /* XXX i#3307: necessary to instr_set_translation_mangling_epilogue? */
```
Comment (derekbruening) [inline core/arch/x86/mangle.c]: This one seems like it needs something.  translate_walk_track() claims we'll just fail for syscall mangling but I don't see how that's accomplished, at least for this Mac mangling.

File: core/arch/x86/mangle.c [hunk 8]
```diff
@@ -2565,18 +2570,21 @@ mangle_float_pc(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
         if (op == OP_fnsave || op == OP_fnstenv) {
             opnd_set_disp(&memop, opnd_get_disp(memop) + FNSAVE_PC_OFFS);
             opnd_set_size(&memop, OPSZ_4);
+            /* XXX i#3307: necessary to instr_set_translation_mangling_epilogue? */
```
Comment (derekbruening) [inline core/arch/x86/mangle.c]: I think it's ok to re-execute these state save instructions.  Certainly it would be wrong to xl8 to the next instr w/o having fixed up the stored PC.

File: core/arch/x86/mangle.c [hunk 9]
```diff
@@ -2565,18 +2570,21 @@ mangle_float_pc(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
...
             PRE(ilist, next_instr,
                 INSTR_CREATE_mov_st(dcontext, memop,
                                     OPND_CREATE_INT32((int)(ptr_int_t)prior_float)));
         } else if (op == OP_fxsave32) {
             opnd_set_disp(&memop, opnd_get_disp(memop) + FXSAVE_PC_OFFS);
             opnd_set_size(&memop, OPSZ_4);
+            /* XXX i#3307: necessary to instr_set_translation_mangling_epilogue? */
```
Comment (derekbruening) [inline core/arch/x86/mangle.c]: Ditto

File: core/arch/x86/mangle.c [hunk 10]
```diff
@@ -2565,18 +2570,21 @@ mangle_float_pc(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
...
             PRE(ilist, next_instr,
                 INSTR_CREATE_mov_st(dcontext, memop,
                                     OPND_CREATE_INT32((int)(ptr_int_t)prior_float)));
         } else if (op == OP_fxsave64) {
             opnd_set_disp(&memop, opnd_get_disp(memop) + FXSAVE_PC_OFFS);
             opnd_set_size(&memop, OPSZ_8);
+            /* XXX i#3307: necessary to instr_set_translation_mangling_epilogue? */
```
Comment (derekbruening) [inline core/arch/x86/mangle.c]: Ditto

File: core/arch/x86/mangle.c [hunk 11]
```diff
@@ -2823,6 +2831,7 @@ mangle_rel_addr(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
     uint opc = instr_get_opcode(instr);
     app_pc tgt;
     opnd_t dst, src;
+
```
Comment (derekbruening) [inline core/arch/x86/mangle.c]: Unrelated change: best to revert

File: core/arch/x86/mangle.c [hunk 12]
```diff
@@ -3076,6 +3085,7 @@ mangle_mov_seg(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
         PRE(ilist, instr,
             instr_create_save_to_tls(dcontext, reg, tls_slots[reg - REG_XAX]));
         /* restore reg */
+        /* XXX i#3307: necessary to instr_set_translation_mangling_epilogue? */
```
Comment (derekbruening) [inline core/arch/x86/mangle.c]: These move instructions should be ok to re-execute.

File: core/translate.c [hunk 13]
```diff
@@ -177,13 +195,18 @@ translate_walk_track(dcontext_t *tdcontext, instr_t *inst, translate_walk_t *wal
     if (walk->in_mangle_region &&
         /* On ARM, we spill registers across an app instr, so go solely on xl8 */
         (IF_X86(!instr_is_our_mangling(inst) ||)
-             instr_get_translation(inst) != walk->translation)) {
+         /* handle adjacent mangle regions */
+         IF_X86(translate_walk_exits_mangling_epilogue(tdcontext, inst, walk) ||)
+         /* Entering the mangling region's epilogue can have different xl8 */
```
Comment (derekbruening) [inline core/translate.c]: But then the existing translation check would apply, right?  Do we need these new conditions here?

File: core/translate.c [hunk 14]
```diff
@@ -225,6 +248,14 @@ translate_walk_track(dcontext_t *tdcontext, instr_t *inst, translate_walk_t *wal
             walk->translation = instr_get_translation(inst);
             LOG(THREAD_GET, LOG_INTERP, 5, "%s: entering mangle region xl8=" PFX "\n",
                 __FUNCTION__, walk->translation);
+        } else if (IF_X86_ELSE(
```
Comment (derekbruening) [inline core/translate.c]: Do we know that AARCHXX doesn't have the same problem?

File: core/translate.c [hunk 15]
```diff
@@ -1632,7 +1666,10 @@ stress_test_recreate_state(dcontext_t *dcontext, fragment_t *f, instrlist_t *ili
             (!instr_is_our_mangling(in) ||
              /* handle adjacent mangle regions */
              (TEST(FRAG_IS_TRACE, f->flags) /* we have translation only for traces */ &&
-              mangle_translation != instr_get_translation(in)))) {
+              IF_X86((prev_in &&
```
Comment (derekbruening) [inline core/translate.c]: style: != NULL

Comment (derekbruening) [inline core/translate.c]: What about the comment at line 1663

File: core/translate.c [hunk 16]
```diff
@@ -387,16 +418,19 @@ translate_walk_good_state(dcontext_t *tdcontext, translate_walk_t *walk,
...
-            /* If we're at the instr AFTER the mangle region, we're ok */
+            /* If we're at the instr AFTER the mangle region, or at an instruction
+             * in the mangled region's EPILOGUE, we're ok. */
             (walk->in_mangle_region && translate_pc != walk->translation));
 }
 
 static void
-translate_walk_restore(dcontext_t *tdcontext, translate_walk_t *walk, app_pc translate_pc)
+translate_walk_restore(dcontext_t *tdcontext, translate_walk_t *walk, instr_t *inst,
+                       app_pc translate_pc)
```
Comment (derekbruening) [inline core/translate.c]: It feels dangerous to point at the next app instr w/o changing how the state restore is done: I suppose the outstanding-spills code should emulate the restores not yet executed, but what about the xsp_adjust?  That code assumes it should prepare for re-executing the instr.

File: suite/tests/CMakeLists.txt [hunk 17]
```diff
@@ -3143,6 +3143,13 @@ if (UNIX)
 
     tobuild(linux.signest linux/signest.c)
     link_with_pthread(linux.signest)
+
+    if (UNIX)
+      tobuild_ops(linux.sigmangle_asynch linux/sigmangle_asynch.c "-vm_base 0x100000000 -no_vm_base_near_app" "")
```
Comment (derekbruening) [inline suite/tests/CMakeLists.txt]: This asynch xl8 problem is not limited to signals nor to UNIX: our synchall, or an app suspending one of its threads, can hit this on Windows.  At least add a XXX comment about testing it on Windows too.  The idea about using a client w/ the synchall API would be a cross-platform test.

Also, I don't think "sig" is adding to the name: how about just "mangle_asynch" or "asynch_mangle".

File: suite/tests/linux/sigmangle_asynch.c [hunk 18]
```diff
@@ -0,0 +1,172 @@
...
+#    endif
+}
+
+static void *
+thread_routine(void *arg)
+{
+#    ifdef X86_64
+    pthread_t main_thread = *(pthread_t *)arg;
+    while (!test_ready)
+        ;
```
Comment (derekbruening) [inline suite/tests/linux/sigmangle_asynch.c]: style: Add  a comment `/* Empty. */` or sthg so we know this is deliberate.

File: core/translate.c (hunk 16 above)
Comment (derekbruening) [reply core/translate.c]: Re: the outstanding-spills code: this is assuming the restores exactly mirror the spills.  Maybe worth mentioning that as it may not always be the case for complex mangling.

File: core/arch/instr.h [hunk 19]
```diff
@@ -194,6 +194,8 @@ enum {
     INSTR_CLOBBER_RETADDR = 0x02000000,
 #    endif
 
+    /* instruction of our own mangling region's epilogue, see i#3307 */
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/instr.h]: Done

File: core/arch/instr_shared.c (hunk 1 above)
Comment (hgreving2304) [reply core/arch/instr_shared.c]: Done

File: core/arch/instr_shared.c (hunk 2 above)
Comment (hgreving2304) [reply core/arch/instr_shared.c]: And pass in ilist instead?

File: core/arch/x86/mangle.c (hunk 3 above)
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Comment removed.

File: core/translate.c (hunk 15 above)
Comment (hgreving2304) [reply core/translate.c]: Thanks

Comment (hgreving2304) [reply core/translate.c]: I wasn't sure what it meant. Sounds like something is unsupported for mangle_rel_addr?

File: core/translate.c (hunk 16 above)
Comment (hgreving2304) [reply core/translate.c]: I've added a comment for the outstanding-spills code (that I didn't touch). I have added the !translate_walk_enters_mangling_epilogue to keep the function's current semantics. Since mangling epilogue now changes the translation, it adds a check to the exclude mangling epilogue from the outstanding_spills checks.

File: suite/tests/CMakeLists.txt (hunk 17 above)
Comment (hgreving2304) [reply suite/tests/CMakeLists.txt]: I'll change the test's name. I am currently working on a client test using synchall and will try if that exposes the bug.

Comment (hgreving2304) [reply suite/tests/CMakeLists.txt]: Done

File: suite/tests/linux/sigmangle_asynch.c (hunk 18 above)
Comment (hgreving2304) [reply suite/tests/linux/sigmangle_asynch.c]: Done

File: core/translate.c (hunk 15 above)
Comment (derekbruening) [reply core/translate.c]: Looking at the code below, it only checks xcx, xsp, and pc: it's targeting ind branches.

File: core/arch/instr_shared.c (hunk 2 above)
Comment (derekbruening) [reply core/arch/instr_shared.c]: That would be necessary to call instrlist_get_translation_target(), yes.

File: core/translate.c (hunk 16 above)
Comment (derekbruening) [reply core/translate.c]: In some sense, it seems like if we're going to xl8 to the *next* instr, we should be re-arranging the whole translate_walk_restore: we should be walking the rest of the epilogue and looking at the restores, instead of looking at what happened earlier.

Comment (derekbruening) [reply core/translate.c]: And thus ignore earlier xsp changes.

File: core/translate.c (hunk 15 above)
Comment (hgreving2304) [reply core/translate.c]: Ok, I guess what I've added doesn't have any effect right now, but it should still be correct, leave it? I resolve this, re-open if necessary.

File: core/arch/instr_shared.c (hunk 2 above)
Comment (hgreving2304) [reply core/arch/instr_shared.c]: Done

File: core/arch/x86/mangle.c (hunk 4 above)
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Done.

File: core/arch/x86/mangle.c (hunk 5 above)
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Done

File: core/arch/x86/mangle.c (hunk 8 above)
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Comment removed.

File: core/arch/x86/mangle.c (hunk 9 above)
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Done.

File: core/arch/x86/mangle.c (hunk 10 above)
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Done.

File: core/arch/x86/mangle.c (hunk 11 above)
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Done

File: core/arch/x86/mangle.c (hunk 6 above)
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: I did not consider this as I thought it's a performance hit or creates other issues.

File: core/arch/x86/mangle.c (hunk 12 above)
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Comment removed.

File: core/translate.c (hunk 14 above)
Comment (hgreving2304) [reply core/translate.c]: Can't test, and some comment mentioned that ARCHXX has different assumptions about spills (might expose the more complex mangling case we just talked about!)

File: core/translate.c (hunk 13 above)
Comment (hgreving2304) [reply core/translate.c]: Yes, it fails to recognize adjacent mangling regions otherwise.

File: core/arch/x86/mangle.c (hunk 6 above)
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Offline discussion.

File: core/arch/x86/mangle.c (hunk 7 above)
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Keeping comment / offline discussion. May add or xref in comment

**Comment by hgreving2304** [comment]
PTAL

The patch keeps the notion of "mangling epilogue" but tailors its support to the most simplest case, a simple rip-rel mangled instruction with one spill/restore. Other cases like cti and xsp modifying app instructions are excluded (cti doesn't have post-app instruction epilogue, and xsp can be rolled back). There are comments on this at x86/mangle.c:2952 and a check at translate_walk_restore. Also the test client.mangle_suspend has explaining hand-coded asm to expose the bug.

File: core/arch/x86/mangle.c [hunk 20]
```diff
@@ -2943,9 +2949,26 @@ mangle_rel_addr(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
             /* we need the whole spill...restore region to all be marked mangle */
             instr_set_our_mangling(instr, true);
             if (spill) {
+                /* We are making several assumptions here. Firstly, we assume that any
+                 * instruction in the mangling code of any control-flow app instruction
+                 * is always before the actual commit point. This shold be safe to assume
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Added to comment.

File: core/translate.c [hunk 21]
```diff
@@ -387,16 +418,58 @@ translate_walk_good_state(dcontext_t *tdcontext, translate_walk_t *walk,
...
 {
     reg_id_t r;
 
-    if (translate_pc != walk->translation) {
+    if (IF_X86_ELSE(translate_walk_enters_mangling_epilogue(tdcontext, inst, walk),
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/translate.c]: This one I need to talk to you about and clarify.

File: core/translate.c [hunk 22]
```diff
@@ -167,6 +169,22 @@ instr_is_mov_PC_immed(dcontext_t *dcontext, instr_t *inst)
 }
 #endif
 
+#ifdef X86
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/translate.c]: https://github.com/DynamoRIO/dynamorio/issues/3329

[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/translate.c]: Comment added

File: core/arch/x86/mangle.c [hunk 23]
```diff
@@ -2943,9 +2949,26 @@ mangle_rel_addr(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
...
+                 * for any control-flow instruction. Such changes in the mangling code of
+                 * the former will be rolled back if needed if xl8 point is in mangling
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: I removed the entire sentence, it's not needed IMO.

File: suite/tests/client-interface/mangle_suspend.c [hunk 24]
```diff
@@ -0,0 +1,163 @@
...
+volatile bool test_ready = false;
+volatile bool test_done = false;
+volatile int loop_inc = 1;
+
+/* asm routines */
+void
+test_asm();
+
+static void *
+sus_thread_routine(void *arg)
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.c]: Done

File: suite/tests/CMakeLists.txt [hunk 25]
```diff
@@ -1946,6 +1946,11 @@ if (CLIENT_INTERFACE)
         "" "${trace_arg}" "${events_appdll_path}")
       tobuild_ci(client.nudge_test client-interface/nudge_test.runall "" "" "")
       tobuild_ci(client.timer client-interface/timer.c "" "" "")
+      tobuild_ci(client.mangle_suspend client-interface/mangle_suspend.c "" "-vm_base 0x100000000 -no_vm_base_near_app" "")
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply suite/tests/CMakeLists.txt]: Done (there are other lines > 90 that's why I left it like that)

File: core/translate.c [hunk 26]
```diff
@@ -387,16 +418,58 @@ translate_walk_good_state(dcontext_t *tdcontext, translate_walk_t *walk,
                           app_pc translate_pc)
 {
     return (!walk->unsupported_mangle ||
-            /* If we're at the instr AFTER the mangle region, we're ok */
+            /* If we're at the instr AFTER the mangle region, or at an instruction
+             * in the mangled region's EPILOGUE, we're ok. If it's epilogue, we only
+             * support a simple spill/restore case, which is checked in
+             * translate_walk_restore.
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/translate.c]: For the supported simple case, it will be walk->in_mangle_region && translate_pc != walk->translation

walk->translation will be the next PC due to being the mangling epilogue. This only holds for the simplest case, hence the comment. Unclear?

[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/translate.c]: (Re-open if necessary)

File: core/arch/x86/mangle.c [hunk 27]
```diff
@@ -2943,9 +2949,26 @@ mangle_rel_addr(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
...
+                 * either.
+                 */
+                instr_t *restore = instr_create_restore_from_tls(
+                    dcontext, scratch_reg, MANGLE_RIPREL_SPILL_SLOT);
+                int xsp_adjust;
                 PRE(ilist, next_instr,
-                    instr_create_restore_from_tls(dcontext, scratch_reg,
-                                                  MANGLE_RIPREL_SPILL_SLOT));
+                    instr_is_cti(instr) ||
+                            instr_check_xsp_mangling(dcontext, instr, &xsp_adjust)
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: I agree this is the thinnest part in the patch, hence the long comment and the check in translate_walk_restore. I do think with both the comment and the check it is quiet robust, in particular if the alternative is to either don't support at all and let xl8 fail (and still have to have a way to identify the epilogue), or by doing a more complex walk of the epilogue that understands all mangling cases (I think that's your B, but need to understand if we're on the same page regarding this). I am resolving this comment here now by putting this into a separate function instr_supports_simple_mangling_epilogue.

File: core/arch/x86/mangle.c [hunk 28]
```diff
@@ -2943,9 +2949,26 @@ mangle_rel_addr(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
...
+                 * be fully rolled back. We do not mark these restores as 'epilogue'
+                 * either.
+                 */
+                instr_t *restore = instr_create_restore_from_tls(
+                    dcontext, scratch_reg, MANGLE_RIPREL_SPILL_SLOT);
+                int xsp_adjust;
                 PRE(ilist, next_instr,
-                    instr_create_restore_from_tls(dcontext, scratch_reg,
-                                                  MANGLE_RIPREL_SPILL_SLOT));
+                    instr_is_cti(instr) ||
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: This is how I see this logically: A meta instruction (to be sure that my terminology matches DR language: I am using meta == generated instruction == not app instruction) in the mangling epilogue:
* will be marked with mangling epilogue flag, if it can be translated to the next PC post-app instruction.
* if not marked with mangling epilogue flag, it either is 1) logically not a PC post-app instruction, which is the case for all instr_is_cti. Or 2) it is unsupported to advance to the next PC, and we're making the assumption here that all such instructions can be fully rolled back to the current PC. This is the case e.g. for rip-rel push mangling.

As-is, this would be stable and checked. The way to get into trouble would be if there was a future instruction that needs more complex mangling (e.g. modifies xsp or multiple restores) that can't (or difficult to-) be rolled back (e.g. floating point operation).

File: suite/tests/client-interface/mangle_suspend.c [hunk 29]
```diff
@@ -0,0 +1,163 @@
...
+static void *
+suspend_thread_routine(void *arg)
+{
+#    ifdef X86_64
+    while (!test_ready) {
+        /* Empty. */
+    }
+    struct timespec sleeptime;
+    sleeptime.tv_sec = 0;
+    sleeptime.tv_nsec = 2000 * 1111;
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.c]: Please explain the unusual constant in a comment.

File: suite/tests/client-interface/mangle_suspend.c [hunk 30]
```diff
@@ -0,0 +1,163 @@
...
+        nanosleep(&sleeptime, NULL);
+    }
+#    endif
+    return NULL;
+}
+
+int
+main(int argc, const char *argv[])
+{
+    pthread_t sus_thread;
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.c]: suspend_thread

File: suite/tests/client-interface/mangle_suspend.c [hunk 31]
```diff
@@ -0,0 +1,163 @@
...
+ * ARE DISCLAIMED. IN NO EVENT SHALL GOOGLE, INC. OR CONTRIBUTORS BE LIABLE
+ * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
+ * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
+ * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
+ * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
+ * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
+ * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
+ * DAMAGE.
+ */
+
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.c]: Add a comment briefly explaining what this test is testing.

File: suite/tests/client-interface/mangle_suspend.dll.c [hunk 32]
```diff
@@ -0,0 +1,190 @@
...
+                opnd_get_reg(instr_get_dst(inst, 0)) == SUSPEND_TEST_REG) {
+                *user_data = (void *)val1;
+                instrlist_meta_postinsert(bb, inst, INSTR_CREATE_label(drcontext));
+            } else
+                prev_was_mov_const = true;
+        } else
+            prev_was_mov_const = false;
+    }
+#else
+        /* XXX i#3307: port to ARM if possible. */
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.dll.c]: This means you are not closing the issue, then?  Please add a comment to the end of the issue once this PR is in about what remains to be done, and maybe update the title, and update the labels (right now the labels show it's x86-only).

**Comment by hgreving2304** [comment]
s/commit fixes and clarifications/commit message fixes and clarifications/

File: suite/tests/client-interface/mangle_suspend.dll.c [hunk 33]
```diff
@@ -0,0 +1,190 @@
...
+        CHECK(false, "exit failed");
+
+    drmgr_exit();
+}
+
+DR_EXPORT void
+dr_init(client_id_t id)
+{
+    /* We actually need 3 slots (flags + 2 scratch) but we want to test using
+     * a DR slot.
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.dll.c]: ?  What is this comment referring to?

File: suite/tests/CMakeLists.txt [hunk 34]
```diff
@@ -1946,6 +1946,12 @@ if (CLIENT_INTERFACE)
         "" "${trace_arg}" "${events_appdll_path}")
       tobuild_ci(client.nudge_test client-interface/nudge_test.runall "" "" "")
       tobuild_ci(client.timer client-interface/timer.c "" "" "")
+      tobuild_ci(client.mangle_suspend client-interface/mangle_suspend.c ""
```
Comment (derekbruening) [inline suite/tests/CMakeLists.txt]: Seems like this should be 64-bit-only for x86, right?  It's a nop in 32-bit x86 and just wastes Travis resources?

File: suite/tests/client-interface/mangle_suspend.dll.c [hunk 35]
```diff
@@ -0,0 +1,190 @@
...
+
+    if (subaction == TEST_VAL_C) {
+        if (instr_is_label(inst)) {
+#ifdef X86_64
+            byte *pc = tag;
+            instr_t *instr = instr_create(drcontext);
+            while (true) {
+                instr_reset(drcontext, instr);
+                byte *prev_pc = pc;
+                pc = decode(drcontext, pc, instr);
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.dll.c]: This is unusual: DR has already decoded the block.  Normally you would walk the instrlist.  Is there a reason not to walk it?

File: suite/tests/client-interface/mangle_suspend.dll.c [hunk 36]
```diff
@@ -0,0 +1,190 @@
...
+                if (pc == NULL)
+                    CHECK(false, "Unexpected decode error");
+                if (instr_get_opcode(instr) == OP_add &&
+                    instr_has_rel_addr_reference(instr)) {
+                    add_instr_pc = prev_pc;
+                    instr_destroy(drcontext, instr);
+                    break;
+                }
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.dll.c]: There's a mem leak if there's no break -- but I guess there's an infinite loop before that.  In non-test code there should be a counter and escape.  I guess in a test it will time out and fail so we'll know so ok.

File: suite/tests/client-interface/mangle_suspend.c [hunk 37]
```diff
@@ -0,0 +1,163 @@
...
+    struct timespec sleeptime;
+    sleeptime.tv_sec = 0;
+    sleeptime.tv_nsec = 2000 * 1111;
+    while (!test_done) {
+        asm volatile("mov %0, %%rdx\n\t"
+                     "mov %0, %%rdx\n"
+                     :
+                     : "i"(SUSPEND_VAL_C)
+                     : "rdx");
+        nanosleep(&sleeptime, NULL);
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.c]: It is not clear what this thread is for: please add a comment

File: suite/tests/client-interface/mangle_suspend.dll.c [hunk 38]
```diff
@@ -0,0 +1,190 @@
...
+            }
+#endif
+        }
+    } else if (subaction == SUSPEND_VAL_C) {
+        if (instr_is_label(inst)) {
+            dr_insert_clean_call(drcontext, bb, inst, suspend_func, false, 0);
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.dll.c]: OK so this is what the other app thread is for: to have a control point from which to suspend the thread doing the rip-rel.  A commend here as well would help, explaining that this is expected to be in a separate thread.

File: suite/tests/client-interface/mangle_suspend.dll.c [hunk 39]
```diff
@@ -0,0 +1,190 @@
...
+    if (dr_suspend_all_other_threads(&drcontexts, &num_suspended, NULL)) {
+        if (num_suspended != 1)
+            CHECK(false, "num_suspended unexpected!");
+        dr_mcontext_t mc = { sizeof(mc), DR_MC_INTEGER | DR_MC_CONTROL };
+        if (!dr_get_mcontext(drcontexts[0], &mc))
+            CHECK(false, "dr_get_mcontext failed!");
+        /* Check xip such that we only perform the check if we are in the loop
+         * body of the test, in order to avoid races.
+         */
+        if (mc.xip >= add_instr_pc - 7 && mc.xip <= add_instr_pc + 24) {
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.dll.c]: Magic constants 7 and 24: please explain in a comment; a comment in the asm code would be good too to ensure these stay in synch.

File: suite/tests/linux/mangle_asynch.c [hunk 40]
```diff
@@ -0,0 +1,173 @@
...
+ * ARE DISCLAIMED. IN NO EVENT SHALL GOOGLE, INC. OR CONTRIBUTORS BE LIABLE
+ * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
+ * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
+ * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
+ * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
+ * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
+ * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
+ * DAMAGE.
+ */
+
```
Comment (derekbruening) [inline suite/tests/linux/mangle_asynch.c]: Add a comment explaining briefly what this test is doing

File: suite/tests/linux/mangle_asynch.c [hunk 41]
```diff
@@ -0,0 +1,173 @@
...
+      loop:
+        /* The address will get mangled into REG_XAX. */
+        add      LOOP_COUNT_REG_ASM, PTRSZ SYMREF(loop_inc)
+        sub      LOOP_TEST_REG_ASM, 1
+        cmp      LOOP_TEST_REG_ASM, 0
+        jnz      loop
+        jmp      epilog
+     epilog:
+        mov      BYTE SYMREF(test_done), HEX(1)
+        ud2
```
Comment (derekbruening) [inline suite/tests/linux/mangle_asynch.c]: Comments would help to understand this code: this will trigger the SIGILL handler which ensures there was no extra add within the loop from re-execution due to translating back.

File: core/translate.c (hunk 21 above)
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/translate.c]: Added comment.

File: core/arch/x86/mangle.c (hunk 28 above)
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Comment added.

File: suite/tests/client-interface/mangle_suspend.c (hunk 30 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.c]: Done

File: suite/tests/CMakeLists.txt (hunk 25 above)
[the remark this answers is not in the document]
Comment (derekbruening) [reply suite/tests/CMakeLists.txt]: I think those are harder to split (one really long string or sthg): here there's an easy split point.

File: suite/tests/client-interface/mangle_suspend.c (hunk 31 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.c]: Done

File: suite/tests/client-interface/mangle_suspend.dll.c (hunk 32 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.dll.c]: Changed comment to i#3329

File: core/translate.c (hunk 26 above)
[the remark this answers is not in the document]
Comment (derekbruening) [reply core/translate.c]: My point is that even if you're in the epilogue you still need to *not* have seen an unsupported mangle instr -- at least when using rollback state.  So you would never get to this second condition. (If you rewrote it to use rollforward state that may change.)

File: suite/tests/client-interface/mangle_suspend.dll.c (hunk 33 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.dll.c]: Removed, was left-over from copy-paste this part from drreg test.

File: core/translate.c (hunk 26 above)
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/translate.c]: Ok, removed comment.

File: suite/tests/CMakeLists.txt (hunk 34 above)
Comment (hgreving2304) [reply suite/tests/CMakeLists.txt]: Added if (X64). Thanks.

File: suite/tests/client-interface/mangle_suspend.dll.c (hunk 35 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.dll.c]: Wasn't clear to me. Fixed!

File: suite/tests/client-interface/mangle_suspend.dll.c (hunk 36 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.dll.c]: Obsolete, see above.

File: suite/tests/client-interface/mangle_suspend.c (hunk 37 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.c]: Added comment.

File: suite/tests/client-interface/mangle_suspend.dll.c (hunk 38 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.dll.c]: Done

File: suite/tests/client-interface/mangle_suspend.dll.c (hunk 39 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.dll.c]: Done

File: suite/tests/linux/mangle_asynch.c (hunk 40 above)
Comment (hgreving2304) [reply suite/tests/linux/mangle_asynch.c]: Done

File: suite/tests/linux/mangle_asynch.c (hunk 41 above)
Comment (hgreving2304) [reply suite/tests/linux/mangle_asynch.c]: Done

File: core/translate.c [hunk 42]
```diff
@@ -170,6 +170,9 @@ instr_is_mov_PC_immed(dcontext_t *dcontext, instr_t *inst)
 #endif
 
 #ifdef X86
+
+/* FIXME i#3329: add support for ARM/AArch64. */
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/translate.c]: Done

File: core/arch/x86/mangle.c [hunk 43]
```diff
@@ -1259,6 +1259,16 @@ instr_check_xsp_mangling(dcontext_t *dcontext, instr_t *inst, int *xsp_adjust)
...
 }
 
+/* Returns whether the instruction supports a simple mangling epilogue that is supported
+ * to xl8 to the next program counter post original app instruction.
+ */
+bool
+instr_supports_simple_mangling_epilogue(dcontext_t *dcontext, instr_t *inst)
+{
+    int xsp_adjust;
+    return !instr_is_cti(inst) && !instr_check_xsp_mangling(dcontext, inst, &xsp_adjust);
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Removed. Could not reproduce, really good catch. Will run through AppVeyor. I thought there was an issue with xsp adjust instruction. Possibly I had added instr_check_xsp_mangling before instr_is_cti.

[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Comment added.

File: core/arch/x86/mangle.c [hunk 44]
```diff
@@ -2951,24 +2958,22 @@ mangle_rel_addr(dcontext_t *dcontext, instrlist_t *ilist, instr_t *instr,
...
-                 * be fully rolled back. We do not mark these restores as 'epilogue'
-                 * either.
+                 * is always before the last commit point of the app instruction, i.e.
+                 * does not xl8 to a PC post app instruction. This should be safe to
+                 * assume for any control-flow instruction. We therefore do not mark the
+
+                 * rip-rel related restores here as 'epilogue'. Secondly, we assume that
+                 * any instructions in mangled code that require xsp adjustment to xl8 app
+                 * state are instructions that can be fully rolled back. We do not mark
+                 * these restores as 'epilogue' either.
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/arch/x86/mangle.c]: Added to comment.
