### PR TITLE
i#4627: Work around QEMU signal number bugs

### LINKED ISSUE #4627: ASSERT sigaction failure when DR run under QEMU emulating AArch64
We're seeing this assert at startup on sigaction failing when running DR under QEMU emulating AArch64 in user mode:
```
<Application xxx.  Internal Error: DynamoRIO debug check failure: dynamorio/trunk/core/unix/signal.c:1469 rc == 0 IF_VMX86(|| (sig >= 63 && rc == -EINVAL))
(Error occurred @0 frags)
```

I'll gather more info such as QEMU version, and try to repro with a standalone upstream QEMU.

### PR DESCRIPTION
**Pull request by derekbruening**
QEMU prior to 5.0 has a signal number mapping bug where it ends up
failing its app's attempts to invoke sigaction for signals 33 and 64.
We relax DR's assert on sigaction failure when -xarch_root is set for
those numbers, trying to continue for best-effort execution with a
syslog warning.

Tested manually on 4.2.0 and on the forthcoming GA CI QEMU testing in
PR #4747.

Fixes #4627

### CODE REVIEW

File: core/unix/signal.c [hunk 1]
```diff
@@ -1571,13 +1571,25 @@ set_handler_and_record_app(dcontext_t *dcontext, thread_sig_info_t *info, int si
...
+         */
+        if (rc == -EINVAL && !IS_STRING_OPTION_EMPTY(xarch_root) &&
+            (sig == 33 || sig == 64)) {
+            SYSLOG_INTERNAL_WARNING("Failed to register signal handler for %d: assuming "
+                                    "under QEMU<5.0 and continuing",
+                                    sig);
+        } else {
+            ASSERT(rc ==
+                   0
+                   /* Workaround for PR 223720, which was fixed in ESX4.0 but
```
Comment (abhinav92003) [inline core/unix/signal.c:1586]: Out of context question: how do I look up these PR refs? They don't seem to be in the Github repo.

**Review by abhinav92003 — APPROVED** [review]

File: core/unix/signal.c (hunk 1 above)
Comment (derekbruening) [reply core/unix/signal.c:1586]: It's from the old vmware bug tracker unfortunately.  Maybe these lines could just be removed -- maybe a separate cleanup.
