### PR TITLE
i#7275: decode/x86 decode xbegin/xabort more strictly.

### LINKED ISSUE #7275: DR decoder incorrectly thinks `c7 ff ff ff ff 56` is a valid XBEGIN encoding
The DR decoder incorrectly thinks `c7 ff ff ff ff 56` is a valid XBEGIN encoding when it is really an invalid encoding:

```
$ disasm c7 ff ff ff ff 56
llvm-mc:   <stdin>:1:1: warning: invalid instruction encoding\n0xc7 0xff 0xff 0xff 0xff 0x56
capstone:  ffc7 ffff <INVALID: errcode 0> 56ff 0000 <INVALID: errcode 0>
bfd:       c7 (bad)
xed:       0xc7 0xff 0xff 0xff 0xff 0x56 GENERAL_ERROR
xed32:       0xc7 0xff 0xff 0xff 0xff 0x56 GENERAL_ERROR
DynamoRIO: c7 ff ff ff ff 56 xbegin 0x000055b5c2348555
```

### PR DESCRIPTION
**Pull request by khuey**
XBEGIN/ABORT are accepted only if their modrm byte is f8. Filter out other previously modrm bytes by introducing the necessary decode table entries to filter on the mod and rm fields in addition to the reg field.

Fixes #7275

### CODE REVIEW

**Comment by khuey** [comment]
I will say that I don't really understand the changes in the dis test. Are those code files randomly generated?

File: core/ir/x86/decode_table.c [hunk 1]
```diff
@@ -7241,6 +7248,27 @@ const instr_info_t rm_extensions[][8] = {
     {OP_rdpkru, 0xee0f0171, catUncategorized, "rdpkru", eax, edx, ecx, xx, xx, mrm, x, END_LIST},
     {OP_wrpkru, 0xef0f0171, catUncategorized, "wrpkru", xx, xx, ecx, edx, eax, mrm, x, END_LIST},
   },
+  { /* rm extension 6 */
+    /* XXX i#1314: this also sets eip */
+    {OP_xabort, 0xf8c60067, catUncategorized, "xabort", eax, xx, Ib, xx, xx, mrm, x, END_LIST},
```
Comment (derekbruening) [inline core/ir/x86/decode_table.c:7253]: Let's always give a category whenever we edit an uncategorized opcode.
I think catOther is the only option here.

File: core/ir/x86/decode_table.c [hunk 2]
```diff
@@ -7241,6 +7248,27 @@ const instr_info_t rm_extensions[][8] = {
...
+    {INVALID, 0xc60067, catUncategorized, "(bad)", xx, xx, xx, xx, xx, no, x, END_LIST},
+    {INVALID, 0xc60067, catUncategorized, "(bad)", xx, xx, xx, xx, xx, no, x, END_LIST},
+    {INVALID, 0xc60067, catUncategorized, "(bad)", xx, xx, xx, xx, xx, no, x, END_LIST},
+    {INVALID, 0xc60067, catUncategorized, "(bad)", xx, xx, xx, xx, xx, no, x, END_LIST},
+    {INVALID, 0xc60067, catUncategorized, "(bad)", xx, xx, xx, xx, xx, no, x, END_LIST},
+    {INVALID, 0xc60067, catUncategorized, "(bad)", xx, xx, xx, xx, xx, no, x, END_LIST},
+    {INVALID, 0xc60067, catUncategorized, "(bad)", xx, xx, xx, xx, xx, no, x, END_LIST},
+  },
+  { /* rm extension 7 */
+    {OP_xbegin, 0xf8c70067, catUncategorized, "xbegin", xx, xx, Jz, xx, xx, mrm, x, END_LIST},
```
Comment (derekbruening) [inline core/ir/x86/decode_table.c:7263]: catOther

File: suite/tests/api/dis-x64.expect [hunk 3]
```diff
@@ -308,11 +308,12 @@
 +0x02d3   63 15 16 c2 b9 d4    movsxd edx, <rel> dword ptr [0xffffffffe4b9c4ef]
 +0x02d9   d2 79 7d             sar    byte ptr [rcx+0x7d], cl
 +0x02dc   cb                   retf
-+0x02dd   c7 7c bb e4 8e 81 93 xbegin 0x0000000054938473
++0x02dd   c7 7c bb e4 8e 81 93...??  <INVALID>
  44
-+0x02e5   7f e2                jnle   0x00000000100002c9
-+0x02e7   e1 66                loope  0x000000001000034f
-+0x02e9   c0 ea 87             shr    dl, 0x87
++0x02de   7c bb                jl     0x000000001000029b
```
Comment (derekbruening) [inline suite/tests/api/dis-x64.expect:313]: > I will say that I don't really understand the changes in the dis test. Are those code files randomly generated?

I assume you clobbered these expect files with the new output, right?
So I'm not sure what you're asking?  The binary file being decoded is fixed.
0x2dd is now invalid; so it tries again one byte after the start of the invalid, which is why these couple of lines also changed, until the offset lines up again.

If you mean where did the binary file come from: from a udis86 test.  See suite/tests/api/dis-udis86-randtest.license

**Review by derekbruening — APPROVED** [review]

File: suite/tests/api/dis-x64.expect (hunk 3 above)
Comment (khuey) [reply suite/tests/api/dis-x64.expect:313]: Yeah, I meant the instruction stream doesn't seem to make any sense. If it's randomly generated that explains a lot.
