### PR TITLE
i#4334: Fix leaks on thread exit

### LINKED ISSUE #4334: Test application on RHEL 7.8 with DynamoRio-Linux 8.0.0 runs out of memory and program gets aborted
We have a 64-bit test application for RHEL 7.8 that can run natively for more 24+ hours. But when it is run under DynamoRio-Linux 8.0.0 without any client, it gets aborted by the RHEL OS in ~10 minutes,

	$  /opt/dr-8.0.0-1/bin64/drrun -version
	drrun version 8.0.0 -- build 1
	$ date ; /opt/dr-8.0.0-1/bin64/drrun -- ./execute ; date
	Wed Jun 24 17:36:13 EDT 2020
	server: got connection from 127.0.0.1 port 59154
	<Out of memory.  Program aborted.>
	Wed Jun 24 17:49:14 EDT 2020

When run under the DynamoRio-Linux 7.1.0 release without any client, it runs out of memory in about 1 hour.

We have examined the memory usage using the "pmap" command at different time intervals. When the application is run natively, the total memory usage does not change. But under, DR 8.0.0 or DR 7.1.0, we notice increasing total memory usage with the time.

We would appreciate any help you can provide in the debug of this problem.

### PR DESCRIPTION
**Pull request by derekbruening**
These leaks are all cleaned up at process exit, which is why the
existing exit-time leak checks don't notice anything.  The global
block list lets us clean them up later, and hence a classic
reachability-based leak detector would not catch them either: so
perhaps they should be called "reachable accumulations" instead of
"leaks".

Fixes a memory leak on thread exit in all builds:
+ The private reachable_heap units were not being freed

Fixes a number of memory leaks on thread exit in release build:
+ Adds individual private fragment deletion on thread exit, to free
  stubs if -separate_private_stubs is on.
  Turns off -separate_private_stubs by default, to avoid this for
  shared caches where there are few benefits to separating private stubs.
  -thread_private turns it back on where the benefits probably outweight
  the thread exit costs.
+ Moves the privload_tls_exit call to release build too to properly
  unmap the TLS.
+ Moves the sigaltstack free to release build to properly free it.
+ Moves freeing of "local unprotected" heap to the release-build path,
  since it is actually global!  This is done for kstats, stats, and
  clone_tls.
+ Moves client_data_t, client_todo_list_t, and thread-private
  client_flush_req_t to be PROTECTED to make it thread-local and thus
  not need freeing (the free is avoided for i#271).

Adds an -rstats_to_stderr dump point when DR terminates for OOM to
make it much easier to diagnose what the problem is.

Adds a new api.thread_churn test which attaches twice, once with a few
threads and once with many threads, and confirms memory usage has not
gone up.  The 5 rstats on peak vmm block sizes are added to dr_stats_t
to facilitate this.

I tried to get api.thread_churn to work on Windows but hit a number of
issues with reattach.  I solved two of them before bailing and making
the test UNIX-only for now and filed the rest as #4349.
+ Unprotect .data on reattach
+ Clear the logfile flag on detach

Issue: #4334, #271, #4349
Fixes #4334

### CODE REVIEW

**Comment by derekbruening** [comment]
The failures look like flakes: fib-conflict (#3406) and client.winxfer (#4058)

File: core/lib/instrument.c [hunk 1]
```diff
@@ -1462,7 +1465,7 @@ instrument_thread_exit(dcontext_t *dcontext)
 #    endif
 
 #    ifdef DEBUG
-    /* PR 470957: avoid racy crashes by not freeing in release build */
+    /* i#271: avoid racy crashes by not freeing in release build. */
```
Comment (johnfxgalea) [inline core/lib/instrument.c:1468]: Your commit message suggests that these changes are done for release builds but here we have an ifdef DEBUG.

https://github.com/DynamoRIO/dynamorio/pull/4350#issue-443017097

Comment (derekbruening) [reply core/lib/instrument.c:1468]: Actually the commit message lists 3 other different places where the freeing is moved to release build, and has a separate list item for this one: "Moves client_data_t, client_todo_list_t, and thread-private client_flush_req_t to be PROTECTED to make it thread-local and thus not need freeing (the free is avoided for i#271).".  I will make it clearer in the message that this stays DEBUG-only.
