### PR TITLE
i#7729: Fix incorrect drmemtrace addr for stolen reg

### LINKED ISSUE #7729: drmemtrace records wrong address for arm loads using the stolen register with no index
We've found a bug in drmemtrace offline where it records the wrong address for arm (and RISCV presumably) loads using the stolen register with no index: the base reg optimization in offline_instru_t::insert_save_addr() doesn't account for the stolen register.

### PR DESCRIPTION
**Pull request by derekbruening**
Fixes a bug where drmemtrace records the wrong address for a load with no index and a base of the stolen register.

Adds a test case to burst_aarch64_sys which fails without the fix.

Adds a drutil base reg test case to the stolen-reg-index test as well, though drutil operates correctly here.

Fixes #7729

### CODE REVIEW

File: clients/drcachesim/tests/burst_aarch64_sys.cpp [hunk 1]
```diff
@@ -119,12 +119,30 @@ ic_unprivileged_flush()
...
 
+static int64_t global_var[2];
+constexpr int SENTINEL_MOV = 12345;
+
+static void
+stolen_reg_load()
+{
+    // Test the stolen register as a base reg of a load (test i#7729).
+    assert(dr_get_stolen_reg() == DR_REG_X28);
+    __asm__ __volatile__("adrp x28, %0\n\t"
```
Comment (abhinav92003) [inline clients/drcachesim/tests/burst_aarch64_sys.cpp:132]: Maybe useful to remind the reader of this adrp and `:lo12:` pattern to load a full absolute address. I wasn't aware of it before.

File: clients/drcachesim/tests/burst_aarch64_sys.cpp [hunk 2]
```diff
@@ -237,6 +288,9 @@ test_main(int argc, const char *argv[])
     int dc_zva_instr_count = 0;
     int dc_zva_memref_count = 0;
     addr_t last_dc_zva_pc = 0;
+    bool prev_instr_was_mov_123456 = false;
```
Comment (abhinav92003) [inline clients/drcachesim/tests/burst_aarch64_sys.cpp]: s/prev_instr_was_mov_123456/prev_instr_was_mov_sentinel/

File: suite/tests/client-interface/stolen-reg-index.dll.c [hunk 3]
```diff
@@ -89,9 +90,10 @@ insert_get_addr(void *drcontext, instrlist_t *ilist, instr_t *instr, opnd_t mref
     }
 
     /* Look for the precise stolen register cases in the test app. */
-    if (opnd_get_base(mref) == DR_REG_X0 &&
-        (opnd_get_index(mref) == dr_get_stolen_reg() ||
-         opnd_get_index(mref) == DR_REG_W28 && opnd_get_base(mref) == DR_REG_X0)) {
+    if (opnd_get_base(mref) == dr_get_stolen_reg() ||
+        (opnd_get_base(mref) == DR_REG_X0 &&
+         (opnd_get_index(mref) == dr_get_stolen_reg() ||
+          opnd_get_index(mref) == DR_REG_W28 && opnd_get_base(mref) == DR_REG_X0))) {
```
Comment (abhinav92003) [inline suite/tests/client-interface/stolen-reg-index.dll.c]: Better to use parenthesis to clarify precedence in this expression that has `||` and `&&` both.

Comment (abhinav92003) [reply suite/tests/client-interface/stolen-reg-index.dll.c]: The second part `opnd_get_index(mref) == DR_REG_W28 && opnd_get_base(mref) == DR_REG_X0` seems to have redundant `opnd_get_base(mref) == DR_REG_X0` which is already there on L94.

Also, I guess `opnd_get_index(mref) == DR_REG_W28` just adjusts for x28 vs w28? Can that be merged into L95 by normalizing `opnd_get_index(mref)` (and maybe dr_get_stolen_reg()) to the same size before comparison?

Comment (abhinav92003) [inline suite/tests/client-interface/stolen-reg-index.dll.c]: For L104 (Github review UI doesn't let me place the comment there): that's an interesting hack. So we assume tha the opnd_t can be reconstructed in that manner? Maybe add a comment there explaining, as it's not immediately apparent.

Comment (derekbruening) [reply suite/tests/client-interface/stolen-reg-index.dll.c]: I was also surprised when I saw this hack: was not aware of it, and it doesn't seem the cleanest solution. Trying to think of existing code that solves this in a different way: mostly I'm thinking of instr cloning.

Comment (derekbruening) [reply suite/tests/client-interface/stolen-reg-index.dll.c]: Wow, git blame claims I wrote this hacky code...

File: clients/drcachesim/tests/burst_aarch64_sys.cpp (hunk 1 above)
Comment (derekbruening) [reply clients/drcachesim/tests/burst_aarch64_sys.cpp:132]: Done.

File: clients/drcachesim/tests/burst_aarch64_sys.cpp (hunk 2 above)
Comment (derekbruening) [reply clients/drcachesim/tests/burst_aarch64_sys.cpp]: Done.

File: suite/tests/client-interface/stolen-reg-index.dll.c (hunk 3 above)
Comment (derekbruening) [reply suite/tests/client-interface/stolen-reg-index.dll.c]: Hmm, this is pre-existing code, but I agree it's weird: yes, removed 2nd base check, and used reg_to_pointer_sized.

Comment (derekbruening) [reply suite/tests/client-interface/stolen-reg-index.dll.c]: There is already a comment on line 98 for this.

Comment (abhinav92003) [reply suite/tests/client-interface/stolen-reg-index.dll.c]: Re the L98 comment: I did see that, but I thought it's lacking explanation that the opnd_t can be deconstructed in that way.

File: clients/drcachesim/tracer/instru_offline.cpp [hunk 4]
```diff
@@ -645,9 +645,10 @@ offline_instru_t::insert_save_addr(void *drcontext, instrlist_t *ilist, instr_t
          * store the base reg directly and add the disp during post-processing.
          */
         reg_addr = opnd_get_base(ref);
-        if (opnd_get_base(ref) == reg_ptr) {
-            /* Here we do need a scratch reg, and raw2trace can't identify this case:
-             * so we set disp to 0 and use the regular path below.
+        if (opnd_get_base(ref) == reg_ptr || opnd_get_base(ref) == dr_get_stolen_reg()) {
```
Comment (abhinav92003) [inline clients/drcachesim/tracer/instru_offline.cpp:648]: Sorry I had it in mind but forgot to ask before: is there a similar control point in raw2trace that should be aware of this? I know we share elision logic for that same reason between online tracer and raw2trace..

Comment (abhinav92003) [reply clients/drcachesim/tracer/instru_offline.cpp:648]: Oh this doesn't change the count of emitted addresses, so no need for raw2trace adjustmnet.

Comment (derekbruening) [reply clients/drcachesim/tracer/instru_offline.cpp:648]: The comment tries to explain that raw2trace will assume this has been treated like the regular base reg cases: it doesn't know which reg was the stolen one. So it will add the disp on; which is why we remove it here. No change to raw2trace code needed.

File: suite/tests/client-interface/stolen-reg-index.dll.c (hunk 3 above)
Comment (derekbruening) [reply suite/tests/client-interface/stolen-reg-index.dll.c]: Any type is desconstructible this way for the reader being the same instance: it has to have the same binary layout.

I added ", which works if it fits in our 2 args
         * as we pass it to ourselves so we know the layout is identical
         * for the reading code.".

There's already an assert ensuring the size.

**Comment by derekbruening** [comment]
x64 failure is scattergather #7678
