### PR TITLE
i#7831: Skip all non-syscall markers in `should_omit_syscall()`

### LINKED ISSUE #7831: `should_omit_syscall()` incorrectly omits syscalls due to interleaved markers
The `should_omit_syscall()` function in raw2trace.cpp is too eager to omit system calls. It currently only anticipates timestamps and CPU_ID markers between a syscall instruction and its corresponding `TRACE_MARKER_TYPE_SYSCALL` marker. If any other marker type appears (e.g., `WINDOW_ID` or `SPLIT_VALUE`), the function fails to find the syscall marker and incorrectly marks the instruction for omission.

### PR DESCRIPTION
**Pull request by bin-wang**
Currently `should_omit_syscall()` only skips timestamps and CPU_ID markers while searching for the SYSCALL marker. If other markers (e.g., a WINDOW_ID marker) appear between the syscall instruction and the SYSCALL marker, the syscall instruction will be omitted while the SYSCALL marker is left behind.

We fix this by skipping other non-syscall markers in `should_omit_syscall()`.

Fixes #7831

### CODE REVIEW

File: clients/drcachesim/tracer/raw2trace.cpp [hunk 1]
```diff
@@ -2134,15 +2134,17 @@ raw2trace_t::should_omit_syscall(raw2trace_thread_data_t *tdata)
     //    syscall is handled.
```
Comment (derekbruening) [inline clients/drcachesim/tracer/raw2trace.cpp:2134]: Early review request: file an issue in this tracker to track the bug since others may have hit it.

Comment (derekbruening) [inline clients/drcachesim/tracer/raw2trace.cpp:2134]: Early review request: add a unit test.

Comment (derekbruening) [inline clients/drcachesim/tracer/raw2trace.cpp:2134]: Early review request: mention whether any further testing was done on larger internal traces.

Comment (bin-wang) [reply clients/drcachesim/tracer/raw2trace.cpp:2134]: Created #7831

Comment (bin-wang) [reply clients/drcachesim/tracer/raw2trace.cpp:2134]: Done

Comment (bin-wang) [reply clients/drcachesim/tracer/raw2trace.cpp:2134]: Discussed via other channels

File: clients/drcachesim/tests/raw2trace_unit_tests.cpp [hunk 2]
```diff
@@ -1270,6 +1270,122 @@ test_false_syscalls(void *drcontext)
...
+    instr_t *move1 =
+        XINST_CREATE_move(drcontext, opnd_create_reg(REG1), opnd_create_reg(REG2));
+    // XXX: Adding an XINST_CREATE_syscall macro will simplify this but there are
+    // complexities (xref create_syscall_instr()).
+#    ifdef X86
+    instr_t *sys = INSTR_CREATE_syscall(drcontext);
+#    elif defined(AARCHXX)
+    instr_t *sys = INSTR_CREATE_svc(drcontext, opnd_create_immed_int((sbyte)0x0, OPSZ_1));
+#    elif defined(RISCV64)
+    instr_t *sys = INSTR_CREATE_ecall(drcontext);
```
Comment (derekbruening) [inline clients/drcachesim/tests/raw2trace_unit_tests.cpp:1295]: This syscall instr creation is now repeated several times in this file: how about a helper function to share this code sequence.

**Review by derekbruening — APPROVED** [review]

File: clients/drcachesim/tests/raw2trace_unit_tests.cpp (hunk 2 above)
Comment (bin-wang) [reply clients/drcachesim/tests/raw2trace_unit_tests.cpp:1295]: I'll make a separate PR for this refactor. Created #7835

Comment (edeiana) [reply clients/drcachesim/tests/raw2trace_unit_tests.cpp:1295]: Thank you, Bin, I'll merge this PR.
