### PR TITLE
i#7540: Check value of steal_reg on AArch64 as on ARM.

### LINKED ISSUE #7540: drrun should give an error rather than crash for bad values of steal_reg (stolen register)
On AArch64 drrun works with -steal_reg 6-7 and 9-29. The values that don't work cause a variety of different crashes rather than a clean error: even -steal_reg 111 looks more like a crash!

There are probably good reasons for 0-5 and 30-31 not working. It might be a bug that 8 doesn't work.

Xref: #2072

### PR DESCRIPTION
**Pull request by egrimley-arm**
The existing check was ARM-only, though it was probably intended to be used on AArch64 too. Also, use the MIN/MAX macros instead of just referring to them in a comment.

Fixes #7540

### CODE REVIEW

File: core/options.c [hunk 1]
```diff
@@ -2383,10 +2383,11 @@ check_option_compatibility_helper(int recurse_count)
...
 #    endif
 
-#    ifdef ARM
-    if (DYNAMO_OPTION(steal_reg) < 8 /* DR_REG_STOLEN_MIN */ ||
-        DYNAMO_OPTION(steal_reg) > IF_X64_ELSE(29, 12) /* DR_REG_STOLEN_MAX */) {
-        USAGE_ERROR("-steal_reg only supports register between r8 and r12(A32)/r29(A64)");
+#    ifdef AARCHXX
+    if (DYNAMO_OPTION(steal_reg) < DR_REG_STOLEN_MIN - DR_REG_R0 ||
+        DYNAMO_OPTION(steal_reg) > DR_REG_STOLEN_MAX - DR_REG_R0) {
+        USAGE_ERROR("-steal_reg only supports register between %d and %d",
```
Comment (abhinav92003) [inline core/options.c]: nit: how about prefixing the reg names with "r"; i.e., "between r%d and r%d"?

**Review by abhinav92003 — APPROVED** [review]

File: core/options.c (hunk 1 above)
Comment (egrimley-arm) [reply core/options.c]: Done.
