### PR TITLE
i#7511 avx512: Identify {x,y}mm16+ as AVX-512 for lazy state preservation

### LINKED ISSUE #6490: Incorrect burst_gencode output under DR
While working on PR #6469, I found that the `tool.drcacheoff.gencode_filtered` app's output statements showed incorrect results under DR. Like:

```
pre-DR init
pre-DR start
pre-DR detachall done // note how "all done" is appended here and also repeated below.
all done
```

https://github.com/DynamoRIO/dynamorio/pull/6469#discussion_r1402765884

The issue seems to happen with different frequency based on how the app completes the cerr statements:
* `"\n"`: happens couple times every 10 runs
* `std::endl`: happens almost every run
* `std::endl << std::flush`: happens almost every run
* `"\n" << std::flush`: doesn't happen

`tool.drcacheoff.gencode` also shows the issue but only with std::endl.

Running the app with strace shows that the write system call has a larger than expected size for the incorrect log:

```
write(2, "pre-DR detach\0all done", 22pre-DR detachall done) = 22
..
write(2, "\n", 1
)                       = 1
write(2, "all done", 8all done)                 = 8
write(2, "\n", 1
)                       = 1
```

Also, this issue doesn't happen when the app is running without DR.

### LINKED ISSUE #7511: App corruption: AVX-512 ymm16-31 not always preserved by core DR
I created a start-stop-using test for #7504 which contains a printf statement like this:
```
    print("For scale %d, got %d alrm, %d vtalrm, %d prof\n", expected_scale, count_alrm,
          count_vtalrm, count_prof);
```

The test runs that code under DR and again after detach.
On my AVX-512-enabled machine, it would print this:
```
For scale %d, got %d alrm, %d vtalrm, %d prof
client done
For scale 1, got 302 alrm, 0 vtalrm, 5 prof
```

So under DR it is printing the specifiers instead of the values!
After detach it works fine.

I did a process of elimination to track down the cause of the bug.
If the client registers a bb event, the bug happens; if not, it doesn't.

I narrowed it down to this block:
Good run Fragment 106:
```
interp: start_pc = 0x00007f37bec95980
  0x00007f37bec95980  62 e2 7d 28 7a c6    vpbroadcastb {%k0} %esi -> %ymm16
Detected AVX-512 code in use
  0x00007f37bec95986  89 f8                mov    %edi -> %eax
```

Bad run on same block never prints "Detected AVX-512":
```
interp: start_pc = 0x00007f331c21f980
  0x00007f331c21f980  62 e2 7d 28 7a c6    vpbroadcastb {%k0} %esi -> %ymm16
  0x00007f331c21f986  89 f8                mov    %edi -> %eax
```

After that point, the good run prints out zmm16-31 while the bad one does not:
```
        zmm15= 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000beb661d800007f35beb665f800007f35beba778000007f35
        zmm16= 0x25252525252525252525252525252525252525252525252525252525252525250000000000000000000000000000000000000000000000000000000000000000
        zmm17= 0x0000000000d6d68ccaabfafe00000002beb6721800007f35000002e000000000beb665f800007f35beba778000007f35988403a800007ffe1a2965c4000055af
...
```
vs
```
        zmm15= 0x000000000000000000000000000000000000000000000000000000000000000000000000000000001c0f01d800007f311c0f05f800007f311c13178000007f31
        k0= 0x00007ffdf877ead0
```

interp.c calls proc_set_num_simd_saved() in 2 places.
The client one checks instr_may_write_zmm_or_opmask_register() which must
be buggy.
The one in the decode loop checks for PREFIX_EVEX:
```
                        /* For AVX-512 detection in bb builder, we're checking only
                         * for the prefix flag, which for example can be set by
                         * decode_cti. In client_process_bb, post-client instructions
                         * are checked with instr_may_write_zmm_register.
                         */
```
But why isn't the decode loop check hit when a client is there?

There must be 2 bugs:
+ instr_may_write_zmm_or_opmask_register() check must be insufficient: have
  to look for writing ymm16-31 too?  Confirmed: it only checks zmm and opmask.
+ PREFIX_EVEX must not be set by full decode but only decode_cti?!?
  That looks like it may well be true: set in prefix loop of decode_cti
  but not set in full decode code at first glance.

Consequences: ymm16-31 not preserved (nor are zmm upper bits but if an
instr touches those instr_may_write_zmm_or_opmask_register() will turn on
preservation).

Question:
+ Should PREFIX_EVEX be set by full decode? It seems that we do not want that
  coarse-grain decode-loop check firing -- so we only fix the may_write bug by
 adding ymm16-31 to the conditions it checks?

### PR DESCRIPTION
**Pull request by derekbruening**
DR's lazy AVX-512 state preservation was only looking for zmm and opmask register usage: yet ymm16-31 are also AVX-512-only and my machine has ymm16 code before any zmm code runs. DR fails to preserve the state and the app state is corrupted.  Similarly, the gencode_filter test in #6490 has xmm16 in use, causing the weird printing there.

The check is augmented here to also look for xmm16+ or ymm16+.
Additionally, with full_decode, a check is added in build_bb_ilist, to fill a gap with full_decode but no client where AVX-512 would not be detected at all.

A new function reg_is_avx512() is added.

The PREFIX_EVEX is documented to clarify it is deliberately only set by decode_cti().

Tested:
My #7504 test's print() reliably printed the specifier ("%d") instead of the values when under DR without the fix; with the fix it prints the values every time.  Also confirmed in the logs with a client with a bb event that the trigger happens where expected:
```
interp: start_pc = 0x00007fd93eb06980
  0x00007fd93eb06980  62 e2 7d 28 7a c6    vpbroadcastb {%k0} %esi -> %ymm16
Detected AVX-512 code in use
  0x00007fd93eb06986  89 f8                mov    %edi -> %eax
...
        zmm16= 0x0000000000d79a481c56f7360000000200000000000000003e9d71d800007fd73e9d75f800007fd73ea1878000007fd719ccdf1000007ffd19ccde5000007ffd
        zmm17= 0x0000000000d79a481c3d8f8a000000023e9d821800007fd7000002e0000000003e9d75f800007fd73ea1878000007fd719cce32800007ffd9d117c3b00005580
```

Ran `ctest --repeat-until-fail 2000 -R off.gencode_f` to test the fix for #6490: all 2000 pass now when before it would fail every 40-100 tries.

I considered adding a regression test by modifying avx512lazy.c to use a ymm16 instruction: but that test is not useful on a machine where a system library first uses ymm16.  We would need a pure-static test, with a separate pure-static app per trigger.  I'm not sure it's worth the effort and CI runtime to build and run all of those tests.

Fixes #7511
Fixes #6490

### CODE REVIEW

File: core/arch/interp.c [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /* **********************************************************
```
Comment (abhinav92003) [inline core/arch/interp.c:1]: In PR description: s/specifies/specifier/

File: core/arch/interp.c [hunk 2]
```diff
@@ -3484,11 +3484,13 @@ build_bb_ilist(dcontext_t *dcontext, build_bb_t *bb)
...
             if (!d_r_is_avx512_code_in_use()) {
                 if (ZMM_ENABLED()) {
-                    if (instr_get_prefix_flag(bb->instr, PREFIX_EVEX)) {
+                    if (instr_get_prefix_flag(bb->instr, PREFIX_EVEX) ||
+                        (bb->full_decode && instr_may_write_avx512_register(bb->instr))) {
                         /* For AVX-512 detection in bb builder, we're checking only
-                         * for the prefix flag, which for example can be set by
-                         * decode_cti. In client_process_bb, post-client instructions
-                         * are checked with instr_may_write_zmm_register.
+                         * for the this generic prefix flag which is set by
```
Comment (abhinav92003) [inline core/arch/interp.c]: s/the this generic prefix flag/the generic PREFIX_EVEX flag/

s/is set by/is set only by/

File: core/ir/decode.h [hunk 3]
```diff
@@ -61,7 +61,10 @@
  */
 #    define PREFIX_SEG_FS 0x20
 #    define PREFIX_SEG_GS 0x40
-/* Prefix used for AVX-512 */
+/* Generic prefix used for AVX-512 by decode_cti().
+ * Full decode does *not* set this prefix, which is relied upon for
```
Comment (abhinav92003) [inline core/ir/decode.h]: Is this saying that build_bb_ilist needs the flag to not be set with full decode??

I see build_bb_ilist _adjusts_ for the flag not being set with full decode (by checking the operands too), but not that it _relies_ on it.

If PREFIX_EVEX and full_decode both are true, is that some error condition?

File: core/ir/instr.h [hunk 4]
```diff
@@ -565,12 +565,13 @@ bool
 instr_can_set_single_step(instr_t *instr);
 
 /* Returns true if \p instr is part of Intel's AVX-512 instructions that may write to a
- * zmm or opmask register. It approximates this by checking whether PREFIX_EVEX is set. If
- * not set, it checks the destinations of \p instr. The decoded instr should be
- * available for inspection as this is invoked only when some client is present.
+ * ymm16-31, zmm, or opmask register. It approximates this by checking whether
+ * PREFIX_EVEX is set, for fast-decode decode_cti() instructions. If not set, it checks
+ * the destinations of \p instr. The decoded instr should be available for inspection as
+ * this is invoked only when some client is present.
```
Comment (abhinav92003) [inline core/ir/instr.h]: > this is invoked only when some client is present

Does the implementation rely on this somehow? Otherwise, may be better to not include this, as it may become stale.

File: core/ir/opnd_shared.c [hunk 5]
```diff
@@ -2538,7 +2538,6 @@ reg_is_extended(reg_id_t reg)
 bool
 reg_is_avx512_extended(reg_id_t reg)
 {
-    /* Note that we do consider spl, bpl, sil, and dil to be "extended" */
```
Comment (abhinav92003) [inline core/ir/opnd_shared.c:2541]: Why was this comment removed?

I don't recognize the "spl, bpl, sil, and dil". What are those?

File: core/ir/x86/instr.c [hunk 6]
```diff
@@ -980,7 +980,8 @@ instr_may_write_zmm_or_opmask_register(instr_t *instr)
         opnd_t dst = instr_get_dst(instr, i);
         if (opnd_is_reg(dst)) {
             if (reg_is_strictly_zmm(opnd_get_reg(dst)) ||
-                reg_is_opmask(opnd_get_reg(dst)))
+                reg_is_opmask(opnd_get_reg(dst))
+                    IF_X64(|| reg_is_avx512_extended(opnd_get_reg(dst))))
```
Comment (abhinav92003) [inline core/ir/x86/instr.c]: Separate question: `DR_REG_XMM16` etc are not 64-bit only though.

File: core/ir/x86/instr.c [hunk 7]
```diff
@@ -980,7 +980,8 @@ instr_may_write_zmm_or_opmask_register(instr_t *instr)
         opnd_t dst = instr_get_dst(instr, i);
         if (opnd_is_reg(dst)) {
             if (reg_is_strictly_zmm(opnd_get_reg(dst)) ||
-                reg_is_opmask(opnd_get_reg(dst)))
+                reg_is_opmask(opnd_get_reg(dst))
```
Comment (abhinav92003) [inline core/ir/x86/instr.c]: I see this condition repeated in #7512. Would it make sense to add it to a new reg_is_avx512 function?

File: core/arch/interp.c (hunk 1 above)
Comment (derekbruening) [reply core/arch/interp.c:1]: Done.

File: core/ir/x86/instr.c (hunk 6 above)
Comment (derekbruening) [reply core/ir/x86/instr.c]: Actually they are. 32-bit mode cannot access {x,y,z}16..31: in fact 32-bit can only access 0..7.
I think it would have been simpler to have this API function available in all modes and just always return false in 32-bit, but there are several routines grouped with it under the ifdef and that seems a bigger change out of scope here, so we have to do the IF_X64.

File: core/ir/opnd_shared.c (hunk 5 above)
Comment (derekbruening) [reply core/ir/opnd_shared.c:2541]: If you look a few lines above this comment is on the prior function and it makes sense there (these are the lower halves of %esp, %ebp, etc.) and it was blindly copied to this function which has no relation to GPR registers so the comment does not belong here.  Fairly related to this PR b/c I'm dealing w/ avx512 extended checks; could maybe separate out but does not seem worth the effort IMHO.

File: core/ir/decode.h (hunk 3 above)
Comment (derekbruening) [reply core/ir/decode.h]: Yes we want the flag to not be set by full decode.  Let me try to reword the comments.  The flag is too broad and includes non-AVX-512 so it is *not* the first choice; we only use it when we don't have operand info.

Comment (derekbruening) [reply core/ir/decode.h]: I rewrote to this:

/* Generic prefix used only by decode_cti() and used as a rough method
 * to detect AVX-512 in build_bb_ilist, but it's too broad.
 * Full decode does *not* set this prefix and instead we use precise
 * operand checks for AVX-512 detection when we have operand info.

File: core/arch/interp.c (hunk 2 above)
Comment (derekbruening) [reply core/arch/interp.c]: Rewrote to be up above the conditions and to say:

                    /* Check operands for precise AVX-512 detection; if we don't have
                     * full decode with operands, we fall back on checking the
                     * PREFIX_EVEX flag which is only set by decode_cti() and is
                     * too broad but the best we have there.
                     */

Also added `(!bb->full_decode &&` to the PREFIX_EVEX check just to make it very clear.

File: core/ir/instr.h (hunk 4 above)
Comment (derekbruening) [reply core/ir/instr.h]: Deleted this sentence.

File: core/ir/decode.h (hunk 3 above)
Comment (derekbruening) [reply core/ir/decode.h]: Added the other function to the comment:

/* Generic prefix used only by decode_cti() and used as a rough method to detect AVX-512
 * in instr_may_write_avx512_register() and build_bb_ilist(), but it's too broad.  Full
 * decode does *not* set this prefix and instead we use precise operand checks for
 * AVX-512 detection when we have operand info.
 */

File: core/ir/x86/instr.c (hunk 7 above)
Comment (derekbruening) [reply core/ir/x86/instr.c]: Done.  Will put this PR in first and then use it in #7512.

File: core/ir/x86/instr.c (hunk 6 above)
Comment (abhinav92003) [reply core/ir/x86/instr.c]: > Actually they are. 32-bit mode cannot access {x,y,z}16..31: in fact 32-bit can only access 0..7.

You mean xmm16 etc are 64-bit only in the hardware. Yes.

What I meant was that the `DR_REG_XMM16` constant doesn't seem 64-bit only. (not suggesting that we make it so here, just curious).

File: core/ir/decode.h (hunk 3 above)
Comment (abhinav92003) [reply core/ir/decode.h]: Ack.

File: core/ir/x86/instr.c (hunk 6 above)
Comment (derekbruening) [reply core/ir/x86/instr.c]: Right, the current API headers are a bit inconsistent: they try to not have too many ifdefs, so constants or other things not relevant to all platforms are generally not ifdefed, but the headers still have ifdefs in some cases where they don't seem necessary.  Could be made more consistent; for Doxygen, and cross-arch, removing ifdefs where it's easy would be the best step.
