### PR TITLE
i#3911: Change 0 and 0LL into NULL for variable length arguments of syscall().

### LINKED ISSUE #3911: pselect6 with NULL {sigmask*,masksize} struct for 6th + 7th args does not work?
This program does not seem to run correctly under DynamioRIO:
```
#include <sys/select.h>
#include <sys/syscall.h>
#include <unistd.h>

int main()
{
  fd_set fds;
  struct timespec ts;

  FD_ZERO(&fds);
  ts.tv_sec = 2;
  ts.tv_nsec = 0;
  return syscall(SYS_pselect6, 0, 0, 0, &fds, &ts, 0);
}
```

I think it's because the pselect6 code in `pre_system_call` does not check for the sigmask parameter being NULL.

### PR DESCRIPTION
**Pull request by hgreving2304**
Fixes a 64-bit bug that led to a non-zero pointer on some systems and a subsequent test
failure. Using NULL works for both 32-bit and 64-bit.

Additionally:
* Adds missing implicit registers to clobber list of syscall inline asm.
* Adds yet another version for pselect6, in inline asm. The test is semantically redundant
to the existing NULL pointer test, and would only expose unexpected changes in glibc's
syscall() implementation. Added for completeness.
* Casts every parameter passed to variadic function syscall() into their safe type according
to their function definiton.
* Fixes all types passed in asm volatile statements as well.
* Makes all parameters named in asm volatile statements.

Fixes #3911

### CODE REVIEW

**Comment by derekbruening** [comment]
> Fixes i#3911

s/i//

**Comment by derekbruening** [comment]
> Additionally,

Incomplete sentence.

File: suite/tests/linux/syscall_pwait.cpp [hunk 1]
```diff
@@ -197,7 +197,8 @@ main(int argc, char *argv[])
     auto psyscall_epoll_pwait = [test_set](bool nullsigmask) -> int {
         int epoll_fd = epoll_create1(EPOLL_CLOEXEC);
         struct epoll_event events;
-        return epoll_pwait(epoll_fd, &events, 24, -1, nullsigmask ? NULL : &test_set);
+        return epoll_pwait(epoll_fd, &events, IF_X64_ELSE(24LL, 24L),
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.cpp]: The man page says this is "int maxevents" so this looks like a bad change, with the original correct.

File: suite/tests/linux/syscall_pwait.cpp [hunk 2]
```diff
@@ -197,7 +197,8 @@ main(int argc, char *argv[])
...
+                           IF_X64_ELSE(-1LL, -1L), nullsigmask ? NULL : &test_set);
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.cpp]: This also looks incorrect: this is an int, not a long and not a long long.

File: suite/tests/linux/syscall_pwait.cpp [hunk 3]
```diff
@@ -278,31 +280,31 @@ main(int argc, char *argv[])
...
+            "mov $1, %0\n\t"
+            "no_syscall_error%=:\n\t"
+            "mov $0, %1\n\t"
+            "cmp %%rbx, %%r8\n\t"
+            "je no_mask_error%=\n\t"
+            "mov $1, %1\n\t"
+            "no_mask_error%=:\n"
+            /* early-clobber outputs */
+            : "=&r"(syscall_error), "=&r"(mask_error)
+            : "rm"((int64_t)SYS_epoll_pwait), "rm"((int64_t)epoll_fd), "rm"(&events),
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.cpp]: I think it would be better to write to the %e version of the register and avoid a cast and confusion.

**Comment by hgreving2304** [comment]
> > Fixes i#3911
> 
> s/i//

Fixed.

**Comment by hgreving2304** [comment]
> > Additionally,
> 
> Incomplete sentence.

Changed into list format.

File: suite/tests/linux/syscall_pwait.cpp [hunk 4]
```diff
@@ -278,31 +280,31 @@ main(int argc, char *argv[])
...
+            "jl no_syscall_error%=\n\t"
+            "mov $1, %0\n\t"
+            "no_syscall_error%=:\n\t"
+            "mov $0, %1\n\t"
+            "cmp %%rbx, %%r8\n\t"
+            "je no_mask_error%=\n\t"
+            "mov $1, %1\n\t"
+            "no_mask_error%=:\n"
+            /* early-clobber outputs */
+            : "=&r"(syscall_error), "=&r"(mask_error)
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.cpp]: Please rewrite this using named parameters.  This will make it easier to read so we don't have to manually figure out which number is which parameter.  See suite/tests/linux/rseq.c for examples.

File: suite/tests/linux/syscall_pwait.cpp [hunk 5]
```diff
@@ -433,7 +437,7 @@ main(int argc, char *argv[])
         } data;
         data.sigmask = NULL;
         data.ss_len = 0;
-        return syscall(SYS_pselect6, 0, 0, 0, &fds, &ts, &data);
+        return syscall(SYS_pselect6, NULL, NULL, NULL, &fds, &ts, &data);
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.cpp]: I understand making the 2nd and 3rd NULL b/c they're pointers, but the first is an integer, so 0 is better.  See the comment above: is this b/c you're writing into the %r instead of %e register??

File: suite/tests/linux/syscall_pwait.cpp (hunk 1 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.cpp]: You're right, plus the non variadic argument functions know their types anyway. Reverted this and the next. I went through all the syscall() instances in the test again and now cast into their exact types.

File: suite/tests/linux/syscall_pwait.cpp (hunk 2 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.cpp]: Same as above.

File: suite/tests/linux/syscall_pwait.cpp (hunk 3 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.cpp]: Done for all parameters in the test to inline asm that are just 'int', except one occurrence that ran out of 32-bit registers that is still casting into int64_t.

File: suite/tests/linux/syscall_pwait.cpp (hunk 4 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.cpp]: Done for all asm volatiles.

File: suite/tests/linux/syscall_pwait.cpp (hunk 5 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.cpp]: Fixed. I went through every single parameter in the test and am now casting into their correct types according to their function declaration. Even NULL might actually not be 100% safe, thought the compiler might conservatively assume that NULL may be a LL pointer (but could be an int). Only the pointers are being passed a casted NULL now, and the rest is passing literals. This should be ultra-safe now.

Comment (derekbruening) [reply suite/tests/linux/syscall_pwait.cpp]: You made this a C++ test, so `nullptr` should resolve worries about the size of `NULL`.

**Comment by derekbruening** [comment]
> Additionally,

This still looks like a dangling incomplete start of a sentence: use a colon or something, not a comma, to make it clear it is referring to the list on the next line.

File: suite/tests/linux/syscall_pwait.cpp [hunk 6]
```diff
@@ -278,31 +280,32 @@ main(int argc, char *argv[])
...
+            "mov $1, %[syscall_error]\n\t"
+            "no_syscall_error%=:\n\t"
+            "mov $0, %[mask_error]\n\t"
+            "cmp %%rbx, %%r8\n\t"
+            "je no_mask_error%=\n\t"
+            "mov $1, %[mask_error]\n\t"
+            "no_mask_error%=:\n"
+            /* early-clobber outputs */
+            : [syscall_error] "=&r"(syscall_error), [mask_error] "=&r"(mask_error)
+            : [sys_num] "rm"((long)SYS_epoll_pwait), [epfd] "rm"(epoll_fd),
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.cpp]: Repeating prior request: remove the long cast and write to %eax.

File: suite/tests/linux/syscall_pwait.cpp [hunk 7]
```diff
@@ -242,7 +242,8 @@ main(int argc, char *argv[])
 
     data_t data_wrong = { &test_set, 0 };
 
-    if (syscall(SYS_pselect6, 0, NULL, NULL, NULL, NULL, &data_wrong) == 0) {
+    if (syscall(SYS_pselect6, 0, (fd_set *)NULL, (fd_set *)NULL, (fd_set *)NULL,
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.cpp]: See other comment: it seems like these casts are not necessary if using `nullptr`.

File: suite/tests/linux/syscall_pwait.cpp (hunk 6 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.cpp]: I did see your prior request and I explicitly changed the 'int' into writing to 32-bit registers (even though the test works fine without it). This 'long' here was intentional because syscall() does take it as long, it is not needed here indeed. 'long' doesn't guarantee 64-bit AFAIK by the way so it wouldn't resolve a operand error of moving it to a 64-bit register in inline asm. The test should be safe now either way, I've removed it and write the 'int' to 32-bit reg now.

File: suite/tests/linux/syscall_pwait.cpp (hunk 7 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.cpp]: I didn't want to change even more. 'nullptr' gets rid of the casts, so: sure. Done.

**Comment by hgreving2304** [comment]
(Google-verified)

**Comment by derekbruening** [comment]
Don't forget to adjust the title/description which talk about NULL
