### PR TITLE
i#5297: Relax a64 jmp-to-label encoding failures

### LINKED ISSUE #5297: AArch64 assert aarch64/decode.c:189 false + "failed to encode" warnings calling instr_get_arith_flags() on a jump-to-instr
Running a drbbdup test on a64 for #4134 hits:

```
<Internal Error: Failed to encode instruction: 'b      @0x0000fffdb402bfc0[8byte]'
>
<Internal Error: Failed to encode instruction: 'b      @0x0000fffdb402bfc0[8byte]'
>
<Application /home/derek/dr/build/suite/tests/bin/simple_app (3256451).  Internal Error: DynamoRIO debug check failure: /home/derek/dr/src/core/ir/aarch64/decode.c:189 false
```
A callstack for the "Failed to encode":
```
<Internal Error: Failed to encode instruction: 'b      @0x0000fffdb402bfc0[8byte]'
>
<press enter to continue>
^C
Program received signal SIGINT, Interrupt.
dynamorio_syscall () at /home/derek/dr/src/core/drlibc/drlibc_aarch64.asm:66
66	#define FUNCNAME dr_fpu_exception_init
(gdb) bt
#0  dynamorio_syscall () at /home/derek/dr/src/core/drlibc/drlibc_aarch64.asm:66
#1  0x00000000713bef50 in read_syscall (fd=0, buf=0xfffdb4026c47, nbytes=1) at /home/derek/dr/src/core/drlibc/drlibc_unix.c:293
#2  0x00000000713bf0dc in os_read (f=0, buf=0xfffdb4026c47, count=1) at /home/derek/dr/src/core/drlibc/drlibc_unix.c:370
#3  0x00000000710c8fec in d_r_notify (priority=SYSLOG_ERROR, internal=true, synch=true, substitution_num=0, prefix=0x7142f280 "SYSLOG_ERROR", 
    fmt=0x7142f248 "Internal Error: Failed to encode instruction: '%s'\n") at /home/derek/dr/src/core/utils.c:1921
#4  0x0000000071231ac8 in instr_encode_arch (dcontext=0xfffdb4002080, instr=0xfffdb402be78, 
    copy_pc=0xffffb4064858 '\253' <repeats 64 times>, "\274\274\274\274\274\274\274\274", '\315' <repeats 127 times>, <incomplete sequence \315>..., final_pc=0xffffb4064858 '\253' <repeats 64 times>, "\274\274\274\274\274\274\274\274", '\315' <repeats 127 times>, <incomplete sequence \315>..., 
    check_reachable=true, has_instr_opnds=0xfffdb4027687, assert_reachable=false) at /home/derek/dr/src/core/ir/aarch64/encode.c:250
#5  0x0000000071231744 in instr_encode_check_reachability (dcontext=0xfffdb4002080, instr=0xfffdb402be78, 
    pc=0xffffb4064858 '\253' <repeats 64 times>, "\274\274\274\274\274\274\274\274", '\315' <repeats 127 times>, <incomplete sequence \315>..., 
    has_instr_opnds=0xfffdb4027687) at /home/derek/dr/src/core/ir/encode_shared.c:125
#6  0x00000000712211ac in private_instr_encode (dcontext=0xfffdb4002080, instr=0xfffdb402be78, always_cache=true)
    at /home/derek/dr/src/core/ir/instr_shared.c:362
#7  0x000000007122271c in instr_get_eflags (instr=0xfffdb402be78, flags=DR_QUERY_INCLUDE_COND_SRCS)
    at /home/derek/dr/src/core/ir/instr_shared.c:891
#8  0x00000000712228bc in instr_get_arith_flags (instr=0xfffdb402be78, flags=DR_QUERY_INCLUDE_COND_SRCS)
    at /home/derek/dr/src/core/ir/instr_shared.c:932
#9  0x0000ffffb3fe9ca0 in drreg_event_bb_analysis (drcontext=0xfffdb4002080, tag=0xfffff7fccb40, bb=0xfffdb402bbe0, for_trace=0 '\000', 
    translating=0 '\000', user_data=0xffffb4064840) at /home/derek/dr/src/ext/drreg/drreg.c:405
#10 0x0000ffffb40097fc in drmgr_bb_event_do_instrum_phases (drcontext=0xfffdb4002080, tag=0xfffff7fccb40, bb=0xfffdb402bbe0, for_trace=0 '\000', 
    translating=0 '\000', pt=0xffffb3fc1460, local_info=0xfffdb4027948, pair_data=0xffffb4064838, quintet_data=0xffffb4064850)
    at /home/derek/dr/src/ext/drmgr/drmgr.c:957
#11 0x0000ffffb400a428 in drmgr_bb_event (drcontext=0xfffdb4002080, tag=0xfffff7fccb40, bb=0xfffdb402bbe0, for_trace=0 '\000', 
    translating=0 '\000') at /home/derek/dr/src/ext/drmgr/drmgr.c:1195
#12 0x00000000711e0cd4 in instrument_basic_block (dcontext=0xfffdb4002080, tag=0xfffff7fccb40 "\377C\025\321\375{", bb=0xfffdb402bbe0, 
    for_trace=false, translating=false, emitflags=0xfffdb4028b24) at /home/derek/dr/src/core/lib/instrument.c:1680
#13 0x0000000071335808 in client_process_bb (dcontext=0xfffdb4002080, bb=0xfffdb4028dd0) at /home/derek/dr/src/core/arch/interp.c:2742
#14 0x000000007133a1fc in build_bb_ilist (dcontext=0xfffdb4002080, bb=0xfffdb4028dd0) at /home/derek/dr/src/core/arch/interp.c:4105
#15 0x000000007133e6ac in build_basic_block_fragment (dcontext=0xfffdb4002080, start=0xfffff7fccb40 "\377C\025\321\375{", initial_flags=0, 
    link=true, visible=true, for_trace=false, unmangled_ilist=0x0) at /home/derek/dr/src/core/arch/interp.c:5096
#16 0x00000000710aa9c4 in d_r_dispatch (dcontext=0xfffdb4002080) at /home/derek/dr/src/core/dispatch.c:210
```

Looks like aarch64 instr_encode_arch() isn't honoring
assert_reachable=false: those are the warnings, I assume for instr operands
w/o having note values yet.

The assert:
```
#5  0x00000000710c34e4 in d_r_internal_error (file=0x7142dec8 "/home/derek/dr/src/core/ir/aarch64/decode.c", line=189, expr=0x7142df40 "false")
    at /home/derek/dr/src/core/utils.c:179
#6  0x0000000071231490 in opcode_to_encoding_info (opc=26, isa_mode=DR_ISA_ARM_A64) at /home/derek/dr/src/core/ir/aarch64/decode.c:189
#7  0x0000000071221220 in private_instr_encode (dcontext=0xfffdb4002080, instr=0xfffdb402be78, always_cache=true)
    at /home/derek/dr/src/core/ir/instr_shared.c:367
#8  0x000000007122271c in instr_get_eflags (instr=0xfffdb402be78, flags=DR_QUERY_INCLUDE_COND_SRCS)
    at /home/derek/dr/src/core/ir/instr_shared.c:891
#9  0x00000000712228bc in instr_get_arith_flags (instr=0xfffdb402be78, flags=DR_QUERY_INCLUDE_COND_SRCS)
    at /home/derek/dr/src/core/ir/instr_shared.c:932
#10 0x0000ffffb3fe9ca0 in drreg_event_bb_analysis (drcontext=0xfffdb4002080, tag=0xfffff7fccb40, bb=0xfffdb402bbe0, for_trace=0 '\000', 
    translating=0 '\000', user_data=0xffffb4064840) at /home/derek/dr/src/ext/drreg/drreg.c:405
#11 0x0000ffffb40097fc in drmgr_bb_event_do_instrum_phases (drcontext=0xfffdb4002080, tag=0xfffff7fccb40, bb=0xfffdb402bbe0, for_trace=0 '\000', 
    translating=0 '\000', pt=0xffffb3fc1460, local_info=0xfffdb4027948, pair_data=0xffffb4064838, quintet_data=0xffffb4064850)
    at /home/derek/dr/src/ext/drmgr/drmgr.c:957
#12 0x0000ffffb400a428 in drmgr_bb_event (drcontext=0xfffdb4002080, tag=0xfffff7fccb40, bb=0xfffdb402bbe0, for_trace=0 '\000', 
    translating=0 '\000') at /home/derek/dr/src/ext/drmgr/drmgr.c:1195
#13 0x00000000711e0cd4 in instrument_basic_block (dcontext=0xfffdb4002080, tag=0xfffff7fccb40 "\377C\025\321\375{", bb=0xfffdb402bbe0, 
    for_trace=false, translating=false, emitflags=0xfffdb4028b24) at /home/derek/dr/src/core/lib/instrument.c:1680
#14 0x0000000071335808 in client_process_bb (dcontext=0xfffdb4002080, bb=0xfffdb4028dd0) at /home/derek/dr/src/core/arch/interp.c:2742
#15 0x000000007133a1fc in build_bb_ilist (dcontext=0xfffdb4002080, bb=0xfffdb4028dd0) at /home/derek/dr/src/core/arch/interp.c:4105
#16 0x000000007133e6ac in build_basic_block_fragment (dcontext=0xfffdb4002080, start=0xfffff7fccb40 "\377C\025\321\375{", initial_flags=0, 
    link=true, visible=true, for_trace=false, unmangled_ilist=0x0) at /home/derek/dr/src/core/arch/interp.c:5096
#17 0x00000000710aa9c4 in d_r_dispatch (dcontext=0xfffdb4002080) at /home/derek/dr/src/core/dispatch.c:210
```

So the encoding failure then tries to call opcode_to_encoding_info() which is not supported on a64.

### PR DESCRIPTION
**Pull request by derekbruening**
Removes a requirement for an aligned target when encoding without
checking reachability, to allow a branch to a label whose note is set
to a small integer during instrumentation.

Removes a debug warning about an encoding failure for
!assert_reachable for the same reason: a branch to a label with a
small note value.

Adds a regression test case to api.ir.  Confirmed that it fails
without these fixes.

Fixes #5297

### CODE REVIEW

**Comment by derekbruening** [comment]
@AssadHashmi ping

File: core/ir/aarch64/encode.c [hunk 1]
```diff
@@ -248,12 +248,17 @@ instr_encode_arch(dcontext_t *dcontext, instr_t *instr, byte *copy_pc, byte *fin
...
+                 * branches to labels during instrumentation (i#5297).
+                 */
+                if (assert_reachable) {
+                    char disas_instr[MAX_INSTR_DIS_SZ];
+                    instr_disassemble_to_buffer(dcontext, instr, disas_instr,
+                                                MAX_INSTR_DIS_SZ);
+                    SYSLOG_INTERNAL_ERROR("Internal Error: Failed to encode instruction:"
+                                          " '%s'\n",
+                                          disas_instr);
+                }
```
Comment (abhinav92003) [inline core/ir/aarch64/encode.c:261]: Can the encoding failure be due to something other than reachability problems here? In that case we probably don't want to ignore the failure right?

File: core/ir/aarch64/codec.c [hunk 2]
```diff
@@ -226,8 +226,11 @@ encode_pc_off(OUT uint *poff, int bits, byte *pc, instr_t *instr, opnd_t opnd,
         *poff = off >> 2 & (range - 1);
         return true;
     }
-    /* If !di->check_reachable we still require correct alignment. */
```
Comment (abhinav92003) [inline core/ir/aarch64/codec.c:229]: Besides the label instr case, does this comment still hold true?

File: core/ir/aarch64/codec.c [hunk 3]
```diff
@@ -226,8 +226,11 @@ encode_pc_off(OUT uint *poff, int bits, byte *pc, instr_t *instr, opnd_t opnd,
...
-    if (!di->check_reachable && ALIGNED(off, 4)) {
+    /* If !di->check_reachable we do not require correct alignment as there is
+     * a common use case of a label instruction operand whose note value holds
```
Comment (abhinav92003) [inline core/ir/aarch64/codec.c:230]: The note field should be interpreted as a pc-relative offset only for non-label instructions right? So, how about skipping the alignment check if `instr_is_label(instr)`?

File: core/ir/aarch64/encode.c (hunk 1 above)
Comment (derekbruening) [reply core/ir/aarch64/encode.c:261]: The assert_reachable flag tells us whether to make noise or keep silent, so we do want to ignore if it is not set.  We should trust the caller to set it properly.

Comment (abhinav92003) [reply core/ir/aarch64/encode.c:261]: The caller might set `assert_reachable=true` to silence reachability errors, but still want to get notified of other encoding failures.

File: core/ir/aarch64/codec.c (hunk 2 above)
Comment (derekbruening) [reply core/ir/aarch64/codec.c:229]: The code no longer checks for alignment for `!check_reachable` so no the comment should not be there as it would not match the code.

Or do you mean, should the code change?  I would argue no: `!check_reachable` means we should not care about the target at all, in my book.  It is set prior to the final encoding when various pieces are not in place to know whether the target is valid.

File: core/ir/aarch64/codec.c (hunk 3 above)
Comment (derekbruening) [reply core/ir/aarch64/codec.c:230]: No, the note field holds the offset from the start of the instruction list for all instructions, including and especially labels as they are often targets of jumps and thus we need to know where they live.

Maybe what you mean is to keep the alignment check for `opnd.kind == PC_kind`?  That seems reasonable.  Done.

File: core/ir/aarch64/encode.c (hunk 1 above)
Comment (derekbruening) [reply core/ir/aarch64/encode.c:261]: Not sure what you are proposing to be done: if this SYSLOG is printed even when `assert_reachable` is false, we're going to have tons of spurious output (see the issue: every single jump to a label, which for bbdup or memtrace is multiple per block, will print this out).  We don't want that.

Comment (derekbruening) [reply core/ir/aarch64/encode.c:261]: > we probably don't want to ignore the failure right?

The encoding still fails.  There is just no SYSLOG.  The caller can decide what to do.

**Comment by derekbruening** [comment]
This is needed to make progress on drbbdup #4134.  Since it is still not merged I will probably go ahead with a drbbdup PR that includes it or branches off it.

File: core/ir/aarch64/codec.c (hunk 2 above)
Comment (abhinav92003) [reply core/ir/aarch64/codec.c:229]: > Or do you mean, should the code change?

Yeah, I was just trying to understand why the comment says we still require correct alignment even if `!di->check_reachable`.

> I would argue no: !check_reachable means we should not care about the target at all, in my book.

Okay.

File: core/ir/aarch64/encode.c (hunk 1 above)
Comment (abhinav92003) [reply core/ir/aarch64/encode.c:261]: > Not sure what you are proposing to be done

I assume `assert_reachable` is intended to silence only reachability errors, but not other errors.

If so, it seems ideal if we can find the cause of the encoding failing, and SYSLOG only if `failure_was_not_due_to_reachability || assert_reachable`. This way, the user can still see logs for other errors, even if they have silenced reachability errors.

Not sure how hard it is to find the encoding failure reason. So, LGTM.

**Review by abhinav92003 — APPROVED** [review]

File: core/ir/aarch64/encode.c (hunk 1 above)
Comment (derekbruening) [reply core/ir/aarch64/encode.c:261]: Agreed, if it were simple, to have the failure reason here: but I think it would take work to try and propagate the reason from inside deeper encoding call chains.  32-bit arm has an attempt at propagating some things; I think the other arches are harder to figure out for misc encoding errors.
