### PR TITLE
i#2663 ~raw2trace_t segfault: Initialize modhandle

### LINKED ISSUE #2663: Segfault in ~raw2trace_t when modfule file is not parsed correctly
`raw2trace_t.modhandle` is only initialized in `raw2trace_t::read_and_map_modules` when `drmodtrack_offline_read` returns successfully, otherwise it is left untouched. In the scenario where `drmodtrack_offline_read` returns an error, the destructor of `raw2trace_t` calls `raw2trace_t::unmap_modules` which calls `drmodtrack_offline_exit`, passing the uninitialized `modhandle` pointer to it. This causes a segfault when `drmodtrack_offline_exit` tries to dereference the pointer.

I have a simple fix for this, just submitting an issue for tracking purposes.

### PR DESCRIPTION
**Pull request by Carrotman42**
Initialize the modhandle field to NULL, and don't call
drmodtrack_offline_exit when the modhandle is NULL. This prevents a
segfault during the destructor of raw2trace_t when the module file is
missing or invalid.

Fixes #2663

### CODE REVIEW

File: clients/drcachesim/tracer/raw2trace.cpp [hunk 1]
```diff
@@ -133,8 +133,12 @@ raw2trace_t::read_and_map_modules(const char *module_map)
 std::string
 raw2trace_t::unmap_modules(void)
 {
-    if (drmodtrack_offline_exit(modhandle) != DRCOVLIB_SUCCESS)
-        return "Failed to clean up module table data";
+    // drmodtrack_offline_exit requires the parameter to be non-null, but we
+    // may not have even initialized the modhandle yet
```
Comment (derekbruening) [inline clients/drcachesim/tracer/raw2trace.cpp]: style nit: punctuation (ending .)

Comment (Carrotman42) [reply clients/drcachesim/tracer/raw2trace.cpp]: Done
