### PR TITLE
i#5336: Add missing pcprofile whereami category

### LINKED ISSUE #5336: ASSERT "unknown whereAmI 6" core/unix/pcprofile.c:563
This has happened twice in the master-merge tests:

https://github.com/DynamoRIO/dynamorio/issues/1807#issuecomment-999296015
`prof_pcs|common.decode`
```
ERROR: unknown whereAmI 6
<Application /home/runner/work/dynamorio/dynamorio/build_debug-internal-64/suite/tests/bin/common.decode (41356). Internal Error: DynamoRIO debug check failure: /home/runner/work/dynamorio/dynamorio/core/unix/pcprofile.c:563 false
```
https://github.com/DynamoRIO/dynamorio/runs/4602849193

Happened again: https://github.com/DynamoRIO/dynamorio/runs/4986838918

I believe this should be easy to fix.

### PR DESCRIPTION
**Pull request by derekbruening**
The pcprofile printing code was missing DR_WHERE_TRAMPOLINE, leading
to an assert.

I was not able to reproduce the assert locally so the new case is
technically not tested.

Fixes #5336

### CODE REVIEW

File: core/unix/pcprofile.c [hunk 1]
```diff
@@ -548,10 +548,12 @@ pcprofile_results(thread_pc_info_t *info)
                     print_file(info->file, " dispatch\n");
                 } else if (e->whereami == DR_WHERE_MONITOR) {
                     print_file(info->file, " monitor\n");
-                } else if (e->whereami == DR_WHERE_SIGNAL_HANDLER) {
-                    print_file(info->file, " signal handler\n");
                 } else if (e->whereami == DR_WHERE_SYSCALL_HANDLER) {
                     print_file(info->file, " syscall handler\n");
+                } else if (e->whereami == DR_WHERE_SIGNAL_HANDLER) {
+                    print_file(info->file, " signal handler\n");
```
Comment (abhinav92003) [inline core/unix/pcprofile.c:554]: I see that the order between `DR_WHERE_SYSCALL_HANDLER` and `DR_WHERE_SIGNAL_HANDLER` has changed too. Is that intended?

**Review by abhinav92003 — APPROVED** [review]

File: core/unix/pcprofile.c (hunk 1 above)
Comment (derekbruening) [reply core/unix/pcprofile.c:554]: Yes, I made it match the enum order, which makes it easier to see whether anything is missing.

Comment (derekbruening) [reply core/unix/pcprofile.c:554]: If this were the only dispatch I would use a case and the compiler could tell us if we missed something, but two of the cases are large and handled separately so I abandoned that plan.  Plus I think that only works if we have no default case.
