### PR TITLE
i#6303: Avoid duplicate encoding entry on chunk-split branch pair

### LINKED ISSUE #6303: Tests failing with "Encoding size 2 != instr size 1": drcacheoff.invariant_checker, drcachesim.opcode_mix
Happened on x86-64 here:
https://github.com/DynamoRIO/dynamorio/actions/runs/6113660426/job/16593592056?pr=6302
```
390: CMake Error at /home/runner/work/dynamorio/dynamorio/suite/tests/runmulti.cmake:111 (message):
390:   *** postcmd failed (Subprocess aborted): Encoding size 2 != instr size 1
390: 
390:   drcachesim:
390:   /home/runner/work/dynamorio/dynamorio/clients/drcachesim/reader/reader.cpp:203:
390:   virtual bool dynamorio::drmemtrace::reader_t::process_input_entry():
390:   Assertion `false' failed.
390: 
390:   ***
390: 
390: Call Stack (most recent call first):
390:   /home/runner/work/dynamorio/dynamorio/suite/tests/runmulti.cmake:123 (process_cmdline)
390: 
390: 
389/471 Test #390: code_api|tool.drcacheoff.invariant_checker .......................***Failed    2.08 sec
```

### PR DESCRIPTION
**Pull request by derekbruening**
Fixes a case where a branch followed by an indirect branch with a chunk split in the middle results in an extra encoding entry after the indirect branch target marker.  This extra entry is accumulated in the reader and results in a fatal error.

Adds a unit test.  Confirmed the fix on the
drcacheoff.invariant_checker test as well where it was failing reliably on one machine.

Fixes #6303

### CODE REVIEW

File: clients/drcachesim/tracer/raw2trace.cpp [hunk 1]
```diff
@@ -3100,8 +3100,13 @@ raw2trace_t::write(raw2trace_thread_data_t *tdata, const trace_entry_t *start,
             }
```
Comment (abhinav92003) [inline clients/drcachesim/tracer/raw2trace.cpp:3100]: For L3082: It'd be useful to add a comment above that reminds the reader that prev_was_encoding is to avoid a duplicate encoding being emitted after an actual encoding entry, specifically for the case *after we open a new chunk* (because record_encoding_emitted will still return `true` since we just cleared that cache after opening a new chunk)

(or possibly a better worded summary)

File: clients/drcachesim/tests/raw2trace_unit_tests.cpp [hunk 2]
```diff
@@ -771,26 +771,43 @@ test_chunk_encodings(void *drcontext)
...
     instr_t *move1 =
         XINST_CREATE_move(drcontext, opnd_create_reg(REG1), opnd_create_reg(REG2));
     instr_t *move2 =
         XINST_CREATE_move(drcontext, opnd_create_reg(REG1), opnd_create_reg(REG2));
-    instr_t *jmp2 = XINST_CREATE_jump(drcontext, opnd_create_instr(move2));
-    instr_t *jmp1 = XINST_CREATE_jump(drcontext, opnd_create_instr(jmp2));
+    instr_t *jmp_move2 = XINST_CREATE_jump(drcontext, opnd_create_instr(move2));
+    instr_t *jmp_jmp = XINST_CREATE_jump(drcontext, opnd_create_instr(jmp_move2));
+    instr_t *nop_start = XINST_CREATE_nop(drcontext);
+    instr_t *jcc =
```
[the remark this answers is not in the document]
Comment (derekbruening) [reply clients/drcachesim/tests/raw2trace_unit_tests.cpp:783]: It doesn't matter where the jcc goes as it's not taken, but to make it consistent with the others here I renamed it.

File: clients/drcachesim/tests/raw2trace_unit_tests.cpp [hunk 3]
```diff
@@ -801,11 +818,16 @@ test_chunk_encodings(void *drcontext)
     raw.push_back(make_timestamp());
     raw.push_back(make_core());
     raw.push_back(make_block(offs_move1, 2));
-    raw.push_back(make_block(offs_jmp2, 1));
+    raw.push_back(make_block(offs_jmp_move2, 1));
     raw.push_back(make_block(offs_move2, 1));
     // Repeat the jmp,jmp to test re-emitting encodings in new chunks.
```
[the remark this answers is not in the document]
Comment (derekbruening) [reply clients/drcachesim/tests/raw2trace_unit_tests.cpp:823]: No it is correct: the move1 block has 2 instrs, move1 and then jmp_jmp which targets jmp_move2.

File: clients/drcachesim/tracer/raw2trace.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (derekbruening) [reply clients/drcachesim/tracer/raw2trace.cpp:3100]: Done.

File: clients/drcachesim/tracer/raw2trace.cpp [hunk 4]
```diff
@@ -3100,8 +3100,13 @@ raw2trace_t::write(raw2trace_thread_data_t *tdata, const trace_entry_t *start,
...
             if (it->type == TRACE_TYPE_ENCODING)
                 prev_was_encoding = true;
-            else
-                prev_was_encoding = false;
+            else {
+                // Do not clear across an indirect branch target, to avoid
+                // a duplicate encoding on the other side.
```
[the remark this answers is not in the document]
Comment (derekbruening) [reply clients/drcachesim/tracer/raw2trace.cpp:3105]: Yes; reworded.

File: clients/drcachesim/tracer/raw2trace.cpp (hunk 1 above)
Comment (derekbruening) [reply clients/drcachesim/tracer/raw2trace.cpp:3100]: Hmm: your questions are making me realize that record_encoding_emitted is never called for these delayed encodings (it was called pre-chunk but was cleared) -- it seems like what we want is to call that, and get rid of prev_was_encoding.  I just added a 2nd ret to the unit test and indeed we (incorrectly) emit another encoding there!

Comment (abhinav92003) [reply clients/drcachesim/tracer/raw2trace.cpp:3100]: > your questions are making me realize that record_encoding_emitted is never called for these delayed encodings (it was called pre-chunk but was cleared) 

Wait why?

By delayed encoding, you mean an encoding that we deliberately repeat after opening a new chunk (L3091), right? But control would enter that if-block only after calling record_encoding_emitted.

Comment (derekbruening) [reply clients/drcachesim/tracer/raw2trace.cpp:3100]: That if-block is only for instructions and it short-circuits if prev_was_encoding.  But we don't have the hash key: so I think we have to wait for the instr and if prev_was_encoding add to the hash there.

Comment (abhinav92003) [reply clients/drcachesim/tracer/raw2trace.cpp:3100]: > That if-block is only for instructions

Right, but that's fine because we want to emit the delayed encoding only when we see an actual instruction for it.

> it short-circuits if prev_was_encoding

Right, but for delayed encodings, by definition, we don't have a new encoding just before that instruction (we had an encoding before a previous dynamic instance of that instruction).

Comment (derekbruening) [reply clients/drcachesim/tracer/raw2trace.cpp:3111]: > Right, but for delayed encodings, by definition, we don't have a new encoding just before that instruction (we had an encoding before a previous dynamic instance of that instruction).

This *is* the previous dynamic instance: the delayed branch.

I've put in the updated test and new code if you'd like to take a look.

Comment (derekbruening) [reply clients/drcachesim/tracer/raw2trace.cpp:3111]: Going to go ahead with this.
