### PR TITLE
i#7796 doxygen: Fix unresolved link requests

### LINKED ISSUE #7796: Doxygen failures with Doxygen 1.15+
All Windows CI workflows seem to be failing with various Doxygen errors: https://gist.github.com/abhinav92003/5afdf69873b9c9263f90007722a1cb80.

This is affecting multiple PRs: atleast #7795, #7794, #7792.

Example failing Windows workflow:
https://github.com/DynamoRIO/dynamorio/actions/runs/21594900090/job/62224539774?pr=7792

### PR DESCRIPTION
**Pull request by edeiana**
Fixes warnings (treated as errors):
```
warning: explicit link request to
'func_trace_t::TRACE_FUNC_ID_SYSCALL_BASE'
could not be resolved
```

By fully qualifying `func_trace_t`.

Related issue in the doxygen repo:
https://github.com/doxygen/doxygen/issues/10713

Fixes #7796

### CODE REVIEW

File: clients/drcachesim/common/trace_entry.h [hunk 1]
```diff
@@ -356,7 +356,7 @@ typedef enum {
      * This marker is also used to record parameter values for certain system calls such
      * as for #OFFLINE_FILE_TYPE_BLOCKING_SYSCALLS or -record_syscall.  These use
      * large identifiers equal to
-     * #func_trace_t::TRACE_FUNC_ID_SYSCALL_BASE plus the system
+     * #dynamorio::drmemtrace::func_trace_t::TRACE_FUNC_ID_SYSCALL_BASE plus the system
```
Comment (derekbruening) [inline clients/drcachesim/common/trace_entry.h:359]: (Ah right, we have hit this before...but this did not occur to me as the problem here.)

File: clients/drcachesim/common/trace_entry.h [hunk 2]
```diff
@@ -356,7 +356,7 @@ typedef enum {
      * This marker is also used to record parameter values for certain system calls such
```
Comment (derekbruening) [inline clients/drcachesim/common/trace_entry.h:356]: > Issue #7796

This finishes it off, right? So s/Issue/Fixes/

Comment (edeiana) [reply clients/drcachesim/common/trace_entry.h:356]: Ah, right. Done.
