### PR TITLE
i#3674: Add stack alignment to test calling "vfprintf".

### LINKED ISSUE #3674: Test common.decode x64 fails on Ubuntu 18.
The expected output seems to be different:

13: Testing nops
13: Done with nops
13: Testing SSE3
13: Bad instruction, instance 1
13: Testing 3D-Now
13: Bad instruction, instance 2
13: Testing far call/jmp
13: Bad instruction, instance 3
13: Bad instruction, instance 4
13: Bad instruction, instance 5
13: Bad instruction, instance 6
13: Access violation, instance 7
13: Access violation, instance 8
13: Testing rip-rel ind branch
13: Access violation, instance 9
13: Bad instruction, instance 10
13: All done

The "Access violation, instance 9" is unexpected.

### PR DESCRIPTION
**Pull request by hgreving2304**
An Ubuntu 18 system's libc, even with older gcc versions 4.8 (we did not try
< 4.5), decided to callee-save a xmm register on the stack. This patch aligns
the stack in the function in the test that is calling vfprintf. This problem generally
affects all functions that we are hand-coding in asm and calling from a test.
Absent a complete review of all hand-coded functions in the code base, this
fixes this one only single case where a test failure was observed.

Fixes #3674

### CODE REVIEW

File: suite/tests/common/decode.c [hunk 1]
```diff
@@ -708,9 +708,15 @@ DECL_EXTERN(func_ptr)
 #define FUNCNAME test_rip_rel_ind
         DECLARE_FUNC_SEH(FUNCNAME)
 GLOBAL_LABEL(FUNCNAME:)
+        sub      REG_XSP, FRAME_ALIGNMENT - ARG_SZ  /* Maintain alignment. Some systemn's
```
Comment (derekbruening) [inline suite/tests/common/decode.c]: spelling: system

File: suite/tests/common/decode.c [hunk 2]
```diff
@@ -708,9 +708,15 @@ DECL_EXTERN(func_ptr)
...
+                                                    * libc may decide to callee-save xmm
```
Comment (derekbruening) [inline suite/tests/common/decode.c]: style: line up the `*`'s

File: suite/tests/common/decode.c (hunk 1 above)
Comment (derekbruening) [inline suite/tests/common/decode.c]: This makes an illegal Windows prologue without an SEH64 directive.  Probably we should have an asm_defines macro for this to make it easy.  The directive would be `.allocstack <size>` I believe.

Comment (hgreving2304) [reply suite/tests/common/decode.c]: Fixed.

File: suite/tests/common/decode.c (hunk 2 above)
Comment (hgreving2304) [reply suite/tests/common/decode.c]: Fixed.

File: suite/tests/common/decode.c (hunk 1 above)
Comment (hgreving2304) [reply suite/tests/common/decode.c]: Does '.allocstack' add to the instruction for the Windows compiler, or it's instead of the instruction? There's barely any allocstack directive in the code base right now, how come?
git grep allocstack
core/arch/asm_defines.asm:#  define PUSH_NONCALLEE_SEH(reg) push reg @N@ .allocstack 8

Comment (derekbruening) [reply suite/tests/common/decode.c]: It augments: it is not an instrution on its own.  It's not needed in leaf functions which do not touch the stack pointer so most of our asm code doesn't need it.  Most of our prologues just use PUSH_SEH.

Comment (hgreving2304) [reply suite/tests/common/decode.c]: Ok. PTAL.

File: core/arch/asm_defines.asm [hunk 3]
```diff
@@ -196,11 +198,15 @@ ASSUME fs:_DATA @N@\
 #  define PUSH_SEH(reg) push reg @N@ .pushreg reg
 /* Push a volatile register or an immed in prolog: */
 #  define PUSH_NONCALLEE_SEH(reg) push reg @N@ .allocstack 8
+# define ADD_STACK_ALIGNMENT sub REG_XSP, FRAME_ALIGMMENT - ARG_SZ @N@ .allocstack 16
```
Comment (derekbruening) [inline core/arch/asm_defines.asm]: This is adjusting by 8 bytes so it should be `.allocstack 8`, not 16.

File: core/arch/asm_defines.asm [hunk 4]
```diff
@@ -196,11 +198,15 @@ ASSUME fs:_DATA @N@\
...
+# define RESTORE_STACK_ALIGNMENT add REG_XSP, FRAME_ALIGMMENT - ARG_SZ @N@ .allocstack 16
```
Comment (derekbruening) [inline core/arch/asm_defines.asm]: The epilogue has no directives, just a strict order (add rsp, then pops, then ret).

File: core/arch/asm_defines.asm (hunk 3 above)
Comment (hgreving2304) [reply core/arch/asm_defines.asm]: I'm completely blind there not knowing the Windows compiler. This doesn't really make sense though does it, you mean you need to tell the Windows compiler how many static bytes to adjust? The computation is dynamic. Happy to believe you that allocstack 8 is correct, unless you want me to research what it means.

Comment (derekbruening) [reply core/arch/asm_defines.asm]: These directives go into a special section of the binary and are used for frame unwinding at runtime for exception handling.  I have a pointer to this page which has some details: http://msdn2.microsoft.com/en-us/library/tawsa7cb.aspx

The reason allocstack would be 8 is b/c that's how much you're adjusting the stack pointer by, right?  That's what the unwinder cares about.

File: core/arch/asm_defines.asm (hunk 4 above)
Comment (hgreving2304) [reply core/arch/asm_defines.asm]: Removed .allocstack.

File: core/arch/asm_defines.asm (hunk 3 above)
Comment (hgreving2304) [reply core/arch/asm_defines.asm]: I shouldn't have said "dynamic", it's static in this case. I was wondering how the compiler is using the directive, e.g. if the adjustment *is* dynamic. In any case, set to "8".

File: core/arch/asm_defines.asm [hunk 5]
```diff
@@ -134,6 +134,8 @@
 # define DECLARE_FUNC_SEH(symbol) DECLARE_FUNC(symbol)
 # define PUSH_SEH(reg) push reg
 # define PUSH_NONCALLEE_SEH(reg) push reg
+# define ADD_STACK_ALIGNMENT sub REG_XSP, FRAME_ALIGNMENT - ARG_SZ
```
Comment (derekbruening) [inline core/arch/asm_defines.asm]: Seems cleanest to move the #define of FRAME_ALIGNMENT, which is currently down on line 531, up above this use.  The comment there seems stale: there is no define in arch_exports.h.  The only other one I see is in x86.asm: but couldn't it get it from here?  If so that x86.asm comment should be moved here.

Comment (hgreving2304) [reply core/arch/asm_defines.asm]: Done.

**Comment by AssadHashmi** [comment]
@hgreving2304 does clicking on 'Details' for the 'AArch64 Precommit' check take you to the Jenkins server pages to look at what failed?

**Comment by hgreving2304** [comment]
@AssadHashmi, it doesn't. Is it possible to make this work?

**Comment by derekbruening** [comment]
> @hgreving2304 does clicking on 'Details' for the 'AArch64 Precommit' check take you to the Jenkins server pages to look at what failed? 

Clicking on Details always used to go straight to the Jenkins pages for me, but when I just tried it here, it takes me to a Jenkins login page which I have never seen before.

**Comment by AssadHashmi** [comment]
> @AssadHashmi, it doesn't. Is it possible to make this work?

What type of error do you get? A Jenkins login screen, an authentication error or a HTTP 404-like error? Or something else?

**Comment by AssadHashmi** [comment]
@derekbruening @hgreving2304 please try the 'Details' link now.

**Comment by derekbruening** [comment]
It now goes to the Jenkins page with all the info, just like it did before for me.

**Comment by hgreving2304** [comment]
@AssadHashmi, the login page is gone, it's a page with "Build #298" now. Though I am not sure where to find the test results. Thanks for the reference above, this looks like a flaky test.

**Comment by hgreving2304** [comment]
run arm tests

**Comment by AssadHashmi** [comment]
> @AssadHashmi, the login page is gone, it's a page with "Build #298" now.

I've found the 'Console Output' link on the left to be the most useful view.

**Comment by hgreving2304** [comment]
I found the info. Yes, it is as before now.

**Comment by hgreving2304** [comment]
run arm tests

**Comment by hgreving2304** [comment]
Looks like some flaky tests failed before. If there's a history of the earlier build available, could the ARM guys check whether issues had been filed about these tests?
