### PR TITLE
i#7725: Correct slight negative times in drmemtraces

### LINKED ISSUE #7725: Negative elapsed time across some drmemtrace timestamps
drmemtrace has an invariant check "Timestamp does not increase monotonically".
We've seen it fail a few times like this:

```
     6034639     4065585: W0.T3500618 ifetch       3 byte(s) @ 0x000055a4c7922791 4c 89 f6             mov    %r14, %rsi
     6034640     4065585: W0.T3500618 <marker: timestamp 13408459038349822>
     6034641     4065585: W0.T3500618 <marker: W0.T3500618 on core 4194>
     6034642     4065585: W0.T3500618 <marker: timestamp 13408459038349821>
     6034643     4065585: W0.T3500618 <marker: W0.T3500618 on core 4194>
     6034644     4065586: W0.T3500618 ifetch       5 byte(s) @ 0x000055a4c7922794 e8 87 fc ff ff       call   $0x000055a4c7922420
```

We've seen through other evidence that the kernel's own timers sometimes go backward, so we believe this is coming from the kernel and is not in any way a drmemtrace bug.

The proposal is to have raw2trace just tweak such a timestamp that is only negative within a threhsold, when back to back like this.

### PR DESCRIPTION
**Pull request by derekbruening**
Adds correction of a negative time of 1us, which we observe coming from Linux kernel timestamps.

Adds a stat to track the count of such corrections.

Adds a unit test.

Tested on a larger trace with a real negative timestamp. Before:
```
     6034640     4065585: W0.T3500618 <marker: timestamp 13408459038349822>
     6034641     4065585: W0.T3500618 <marker: W0.T3500618 on core 4194>
     6034642     4065585: W0.T3500618 <marker: timestamp 13408459038349821>
     6034643     4065585: W0.T3500618 <marker: W0.T3500618 on core 4194>
```
After:
```
     6034640     4065585: W0.T3500618 <marker: timestamp 13408459038349822>
     6034641     4065585: W0.T3500618 <marker: W0.T3500618 on core 4194>
     6034642     4065585: W0.T3500618 <marker: timestamp 13408459038349822>
     6034643     4065585: W0.T3500618 <marker: W0.T3500618 on core 4194>
```

Fixes #7725

### CODE REVIEW

File: clients/drcachesim/tracer/raw2trace.cpp [hunk 1]
```diff
@@ -3346,6 +3367,7 @@ raw2trace_t::write(raw2trace_thread_data_t *tdata, const trace_entry_t *start,
                     prev_was_encoding = false;
             }
             if (it->type == TRACE_TYPE_MARKER) {
+                // NOCHECK 2ndary processing
```
Comment (abhinav92003) [inline clients/drcachesim/tracer/raw2trace.cpp]: Anything else to be done for this NOCHECK? I guess this was an alternate control point for fixing the timestamp, but process_marker works better?

Comment (derekbruening) [reply clients/drcachesim/tracer/raw2trace.cpp]: Ah yes. This is too late for the stats like earliest and latest. Removing the comment.
