### PR TITLE
i#4777: Fix uninitialized drmodtrack offset on Windows

### LINKED ISSUE #4777: drmodtrack offset field has uninitialized values on Windows
For #2939 an offset field was added to drmodtrack in PR #2940 (and PR #2973).  However, it is ifdef-ed out for Windows in some places but not in others.  Now, I'm adding a new field for #4474, and drmodtrack-test is failing with uninit bogus printed offset values differing bet online and offline.  Not sure how it passed before: probably just got lucky and the uninit values matched.

It's too late to ifdef it out of the interface so maybe the best solution is to set it to 0 on Windows.

### PR DESCRIPTION
**Pull request by derekbruening**
PR #2940 and #2973 added an offset field to drmodtrack for #2939, but
they ifdef-ed the field in some places but not others, resulting in
uninitialized output.  Since it's already locked into the interface,
we always set it to 0 here and include it in internal structures to
fix the problem.

Tested on drmodtrack-test where the fields were manually confirmed to
no longer contain bogus values, and where the test doesn't fail when
i#4474 adds a new field that shifts the test buffer to avoid the
happens-to-match scenario that masked this bug in that test before.

Issue: #2939, #4474, #4777
Fixes #4777

### CODE REVIEW

**Comment by derekbruening** [comment]
snehasish is out today so asking sapostolakis

File: ext/drcovlib/modules.c [hunk 1]
```diff
@@ -459,10 +459,9 @@ module_table_entry_print(module_entry_t *entry, char *buf, size_t size)
 #endif
     read_entry.path = full_path;
     read_entry.custom = entry->custom;
-#ifndef WINDOWS
-    // For unices we record the physical offset from the backing file.
+    // For unices we record the physical offset from the backing file
+    // (always 0 on Windows).
```
Comment (sapostolakis) [inline ext/drcovlib/modules.c:463]: nit: maybe use /* */  instead for the comment.

**Review by sapostolakis — APPROVED** [review]

File: ext/drcovlib/modules.c (hunk 1 above)
Comment (derekbruening) [reply ext/drcovlib/modules.c:463]: That's from snehasish's original code but it is a C file so sure I could tweak it to better match the style.
