### PR TITLE
i#2126: int2d mismanagement

### LINKED ISSUE #2126: APP CRASH (antiRE_auto_failonly.exe) DynamoRIO debug check failure: core\translate.c:817
With version 6.2.0-2 of DynamoRio
The latest build does not solve the problem

On Windows 7, with a 32 bit application, antiRE_auto_failonly.exe from Daniel Plohmann and Christopher Kannen : it is another tool to test reverse engineering tools such as dynamorio
[file](https://simorfo.com/files/antiRE_auto_failonly.exe)

I run it with (no client)
C:\rio\bin32\drrun.exe -- antiRE_auto_failonly.exe

With flags -debug -msgbox_mask 0xf, I got the information message "non-syscall, non-int2b 0x2d @ 0x004027b5 from 0x00402798"

The expected output is some lines ending with "All tests finished. Successful Tests : X. Failed Tests : Y"
Instead we get an application crash.

Interruption 2d seems to be mishandled.
Looking at http://reverseengineering.stackexchange.com/questions/1541/int-2d-anti-forensic-method, I found that there is a off-by-one as seen in the [log file](https://simorfo.com/files/log.0.1504.html)
```
ASYNCH intercepted exception in thread 1504 at pc 0x18c015b4
	cxt pc is different: 0x18c015b3
```

The following patch fixes this problem (but it is rather ugly)
```
diff --git a/dynamorio/core/win32/callback.c b/dynamorio/core/win32/callback.c
index 01e5191..6608ae5 100644
--- a/dynamorio/core/win32/callback.c
+++ b/dynamorio/core/win32/callback.c
@@ -5571,6 +5571,15 @@ intercept_exception(app_state_at_intercept_t *state)
              */
             mutex_lock(&thread_initexit_lock);
             if (cxt->CXT_XIP != (ptr_uint_t)pExcptRec->ExceptionAddress) {
+                app_pc translated_pc;
+                if (cxt->CXT_XIP+1 == (ptr_uint_t)pExcptRec->ExceptionAddress) {
+                    translated_pc =
+                    recreate_app_pc(dcontext, (cache_pc) cxt->CXT_XIP, f) + 1;
+                }
+                else {
+                    translated_pc =
+                    recreate_app_pc(dcontext, pExcptRec->ExceptionAddress, f);
+                }
                 /* sometimes this happens, certainly cxt can be changed by exception
                  * handlers, but not clear why kernel changes it before getting here.
                  * I saw it pointing to next instr while ExceptionAddress was faulting
@@ -5578,8 +5587,6 @@ intercept_exception(app_state_at_intercept_t *state)
                  * exceptionaddress first since cxt is the one we want for real, we
                  * just want pc for exceptionaddress.
                  */
-                app_pc translated_pc =
-                    recreate_app_pc(dcontext, pExcptRec->ExceptionAddress, f);
                 ASSERT(translated_pc != NULL);
                 LOG(THREAD, LOG_ASYNCH, 2, "Translated ExceptionAddress "
                     PFX" to "PFX"\n",
```

### PR DESCRIPTION
**Pull request by Simorfo**
During the interception of an exception, we check that the
ExceptionAddress might be equal to the value of EIP + 1.

Fixes #2126

### CODE REVIEW

File: core/win32/callback.c [hunk 1]
```diff
@@ -5577,8 +5577,19 @@ intercept_exception(app_state_at_intercept_t *state)
...
                  */
-                app_pc translated_pc =
+                app_pc translated_pc;
+                if (pExcptRec->ExceptionCode == EXCEPTION_BREAKPOINT &&
+                    cxt->CXT_XIP+1 == (ptr_uint_t)pExcptRec->ExceptionAddress) {
+                    /* i#2126 : In case of an int 2d, the exception address is
+                     * increased by 1 and we make the same.
+                     */
+                    translated_pc =
+                    recreate_app_pc(dcontext, (cache_pc) cxt->CXT_XIP, f) + 1;
```
Comment (derekbruening) [inline core/win32/callback.c]: Should be indented 4 more

File: core/win32/callback.c [hunk 2]
```diff
@@ -5577,8 +5577,19 @@ intercept_exception(app_state_at_intercept_t *state)
...
+                }
+                else {
+                    translated_pc =
                     recreate_app_pc(dcontext, pExcptRec->ExceptionAddress, f);
```
Comment (derekbruening) [inline core/win32/callback.c]: Should be indented 4 more

File: suite/tests/security-common/except-int2d.c [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+#include "asm_defines.asm"
+START_FILE
+
+/* int foo()
+ *   Generates int 2d interruptions and should return 2.
+ */
+#define FUNCNAME foo
+DECLARE_FUNC(FUNCNAME)
+GLOBAL_LABEL(FUNCNAME:)
+XOR eax, eax
```
Comment (derekbruening) [inline suite/tests/security-common/except-int2d.c]: Here and below:
See https://github.com/DynamoRIO/dynamorio/wiki/Code-Style:
"In .asm files, place opcodes on column 8 and start operands on column 17."

Also, best to follow the style of the other assembly: lower-case opcodes (so we can distinguish from asm_defines macros)

File: suite/tests/security-common/except-int2d.c [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+INT 2dh
```
Comment (derekbruening) [inline suite/tests/security-common/except-int2d.c]: suggest: HEX(2d) is the asm_defines way (cross-platform); below too

File: suite/tests/CMakeLists.txt [hunk 5]
```diff
@@ -3136,6 +3136,7 @@ if (X64 AND NOT AARCH64) # FIXME i#1569: get working on AArch64
 endif (X64 AND NOT AARCH64)
 
 tobuild("security-common.TestAllocWE" security-common/TestAllocWE.c)
+tobuild(security-common.except-int2d security-common/except-int2d.c)
```
Comment (derekbruening) [inline suite/tests/CMakeLists.txt]: Along the same lines, this should be Windows-only and x86-only.  That's most easily done by adding it inside an existing conditional: next to other security-win32 tests.

File: suite/tests/CMakeLists.txt [hunk 6]
```diff
@@ -2948,6 +2948,7 @@ else (UNIX)
     append_link_flags(security-win32.except-execution "/dynamicbase:no")
 
     tobuild(security-win32.except-guard security-win32/except-guard.c)
+    tobuild(security-win32.except-int2d security-win32/except-int2d.c)
```
Comment (derekbruening) [inline suite/tests/CMakeLists.txt]: So here it will not be tested on 64-bit -- was that the intention?  If it works for 64-bit let's get it out of this NOT X64 block.

Comment (Simorfo) [inline suite/tests/CMakeLists.txt]: I guess it should work for 64 bit as well.
Let us try.

Comment (Simorfo) [inline suite/tests/CMakeLists.txt]: And should we do it for security-win32.except-guard as well ?

Comment (derekbruening) [inline suite/tests/CMakeLists.txt]: If the -guard test works, sure (cleanest as separate CL but ok either way) -- if it does I guess we just didn't test all of these on x64?  I was assuming they all had problems on x64.

File: suite/tests/security-win32/except-int2d.c [hunk 7]
```diff
@@ -0,0 +1,97 @@
...
+
+/* int foo()
+ *   Generates int 2d interruptions and should return 2.
+ */
+#define FUNCNAME foo
+DECLARE_FUNC(FUNCNAME)
+GLOBAL_LABEL(FUNCNAME:)
+        xor      eax, eax
+        int      HEX(2d)
+        mov      EAX, 1
```
Comment (derekbruening) [inline suite/tests/security-win32/except-int2d.c]: nit: s/EAX/eax/

File: suite/tests/security-win32/except-int2d.c [hunk 8]
```diff
@@ -0,0 +1,97 @@
...
+        /* int 2d might behave differently with eax equal to 1. */
+        int      HEX(2d)
+        /* This jump ends the basic block right after the int. */
+        jmp      @OneMore
+        ret
+@OneMore:
+        /* We increment eax to check that we got in the right branch. */
+        inc EAX
```
Comment (derekbruening) [inline suite/tests/security-win32/except-int2d.c]: nit: s/EAX/eax/

File: suite/tests/security-win32/except-int2d.c [hunk 9]
```diff
@@ -0,0 +1,97 @@
...
+#define FUNCNAME foo
+DECLARE_FUNC(FUNCNAME)
+GLOBAL_LABEL(FUNCNAME:)
+        xor      eax, eax
+        int      HEX(2d)
+        mov      EAX, 1
+        /* int 2d might behave differently with eax equal to 1. */
+        int      HEX(2d)
+        /* This jump ends the basic block right after the int. */
+        jmp      @OneMore
```
Comment (derekbruening) [inline suite/tests/security-win32/except-int2d.c]: What does the @ mean to masm?  Have not seen it, not used in other asm files.

File: suite/tests/CMakeLists.txt (hunk 6 above)
Comment (Simorfo) [inline suite/tests/CMakeLists.txt]: I did not test it on 64 bit but it should work the same.
What is a separate "CL" ? Did you mean a separate pull request ?

Comment (derekbruening) [inline suite/tests/CMakeLists.txt]: Yes, CL == ChangeList == nomenclature in some review systems for patch sent for review.

AppVeyor should test it for us on 64-bit.

File: suite/tests/security-win32/except-int2d.c (hunk 9 above)
Comment (Simorfo) [inline suite/tests/security-win32/except-int2d.c]: Inspired by antiRE source code, which was how I found this issue. I do not know what it means.

**Comment by derekbruening** [comment]
Looks like 64-bit needs debugging:
```
code_api|security-win32.except-int2d =>  Application C:\projects\dynamorio\build\build_debug-internal-64\suite\tests\bin\security-win32.except-int2d.exe (3528).  Internal Error: DynamoRIO debug check failure: C:\projects\dynamorio\core\translate.c:817 false 
```

File: suite/tests/security-win32/except-int2d.c (hunk 9 above)
Comment (derekbruening) [inline suite/tests/security-win32/except-int2d.c]: suggest/optional: if you're making more changes anyway (for 64-bit) -- maybe best to use our style of names (i.e., lowercase and underscores) for the label name and just remove the @'s?

**Comment by Simorfo** [comment]
Can you provide me the logs for the 64 bit test ?
It is the error that should be corrected by this patch.

File: suite/tests/CMakeLists.txt (hunk 6 above)
Comment (Simorfo) [inline suite/tests/CMakeLists.txt]: I think I should submit this new pull request once this one is merged

**Comment by derekbruening** [comment]
On Mon, Feb 27, 2017 at 3:48 AM, Simorfo <notifications@github.com> wrote:

> Can you provide me the logs for the 64 bit test ?
> It is the error that should be corrected by this patch.
>
From the Appveyor failure that I quoted?  There's no simple access to any
logs there: you'd have to do a custom run and figure out how to get build
artifacts out.

**Comment by derekbruening** [comment]
> I think I am understanding it thanks to this guide

Maybe you could summarize in the issue tracker?  Parts of it don't make sense to me.  I did not read what you just linked to, but your earlier link (in tracker maybe?) seemed incorrect: e.g., it talked about EXCEPTION_BREAKPOINT only being sent when a debugger is attached.

> Depending on the value of eax (and other factors) when we get an int 2d at address EIP=X, the kernel can either resume at EIP=X+2 or EIP=X+3 (after dispatching an exception or not), and dynamorio assumes the kernel will resume only at EIP=X+2.

I don't follow this.  The kernel sets CONTEXT.Eip before invoking the exception dispatcher, and unless an SEH handler changes it, that's where control will resume via NtContinue.  No assumptions on what the kernel will do seem to be necessary: we can see exactly what the kernel will do because we see the CONTEXT.Eip value passed to the dispatcher and then passed to NtContinue.

If the only weirdness is what the kernel sets as ExceptionAddress, and if nobody ever takes ExceptionAddress and changes CONTEXT.Eip to match it, what does it matter what ExceptionAddress is set to?  It's just informational to user mode.  Your test's SEH handler just says EXCEPTION_CONTINUE_EXECUTION, which ends up leaving CONTEXT.Eip unchanged and ignoring ExceptionAddress, right?

From the link in the tracker I assumed that the only issue was that a debugger sometimes takes ExceptionAddress and directly goes there, instead of going to CONTEXT.Eip.  Is there more to it than that?

**Comment by derekbruening** [comment]
It seems to me that the only problem DR is going to hit is trying to translate a weird ExceptionAddress that points into the middle of an instruction, just because DR's translation code assumes all requests will be at instruction boundaries.  Is that what the x64 failure was, instead of being +1 it was +2 or +3?  I'm still not seeing any other issue here.  So long as we translate correctly, we shouldn't need any other special handling: we'll go execute whatever app PC the SEH handler wants to go to.  Right?

**Comment by Simorfo** [comment]
For me this is a different problem.
I propose that we close this issue and open a new one.
Tell me what you think.

Here are some logs to explain it.
Control seems to resume without running NtContinue (and without my SEH handler) at an unexpected address.

```
dispatch: target = 0x000000013fba11d4

after instrumentation:
TAG  0x000000013fba11d4
 +0    L3                      b8 01 00 00 00       mov    $0x00000001 -> %eax
 +5    L3                      cd 2d                int    $0x2d
 +7    L3                      eb 01                jmp    $0x000000013fba11de
END 0x000000013fba11d4

bb ilist after mangling:
TAG  0x000000013fba11d4
 +0    L3                      b8 01 00 00 00       mov    $0x00000001 -> %eax
 +5    L3                      cd 2d                int    $0x2d
 +7    L4 @0x00000000bfde8858  e9 f9 2e ed 7f       jmp    $0x000000013fba11de
END 0x000000013fba11d4

Entry into F3082(0x000000013fba11d4).0x00000000bfeb8474 (shared)
	[security-win32.except-int2d.exe]
fcache_enter = 0x00000000bfc63000, target = 0x00000000bfeb8474
ASYNCH intercepted exception in thread 2512 at pc 0x00000000bfeb847d
	exception code = 0x00000000c0000005, ExceptionFlags=0x0000000000000000
	record=0x0000000000000000, params=2
	PC 0x00000000bfeb847d tried to write address 0x000000006b972f83

ERROR: recreate_app : looking for 0x00000000bfeb847d in frag @ 0x00000000bfeb8474 (tag 0x000000013fba11d4)
```

I gather that the following is happening on the real code (EIP, instruction, result)
- 11d4 | mov eax 1 | ok
- 11d9 | int 2d | goes to kernel, and coming back to 11dc instead of 11db
- 11dc | add ebx, eax | mixing jmp 11de and ret : eb 01 and c3
- 11de | inc eax | ok, resumed normal flow
with dynamorio
- 11d4 | mov eax 1 | ok
- 11d9 | int 2d | goes to kernel, and coming back to 11dc instead of 11db
- 11dc | stc | ok so far
- 11dd | writing instruction | exception generated from an unexpected address

**Comment by derekbruening** [comment]
(It would be easier to have the interp: sequence with app addresses and the loglevel 4 code cache addresses, rather than the two instrlist views, to have the actual addresses in front of us.)

So the key thing that you're saying is, there is not any user-visible exception (viz., EXCEPTION_BREAKPOINT) raised on the int 2d in your case.  All of my comments assumed that: NtContinue is how user mode resumes after an exception.  I based that on what I see running your (modified) test, built 32-bit and run on my win7x64 machine.  I passed 0 through 5 in and I got an exception each time:

```
        xor eax, eax
        int 2dh
        mov eax, 1
        /* int 2d might behave differently with eax equal to 1. */
        int 2dh
        /* The purpose of this jump is to end the basic block right after the int. */
        jmp @OneMore
        ret
        @OneMore:
        /* We increment eax to be able to check that we got in the right branch. */
        inc eax
        int 2dh
        /* We test with a one byte opcode following the int. */
        nop
        int 2dh
        nop
        nop
        nop
        mov eax, 2
        int 2dh
        nop
        nop
        nop
        mov eax, 3
        int 2dh
        nop
        nop
        nop
        mov eax, 4
        int 2dh
        nop
        nop
        nop
        mov eax, 5
        int 2dh
        nop
        nop
        nop
        ret
```

```
% suite/tests/bin/security-win32.except-int2d.exe
start of test, count = 0
breakpoint exception
breakpoint exception
breakpoint exception
breakpoint exception
breakpoint exception
breakpoint exception
breakpoint exception
breakpoint exception
end of test, count = 13
```

How are you not getting an exception when I get one every time?  What else does it depend on besides eax?  OS version?

**Comment by Simorfo** [comment]
Indeed, there is not any user-visible exception raised on the second int 2d.
I do not know why the behavior is different for you.
I bet it depends on OS version and configuration.

So, what should we do ?

**Comment by derekbruening** [comment]
Your example is 64-bit.  If I build 64-bit, instead of 8 EXCEPTION_BREAKPOINTs I only get 4 -- so is it that for 32-bit, an exception is raised **every time** on int 2d, but for 64-bit it varies based on eax?

```
% suite/tests/bin/security-win32.except-int2d.exe
start of test, count = 0
breakpoint exception
breakpoint exception
breakpoint exception
breakpoint exception
end of test, count = 9
```

It seems like we have to treat int 2d as a control transfer instruction for 64-bit.  So you have the rules for exactly where it goes?  Is it based only on eax?  So if we can find the eax statically we can treat it as a direct branch, but if the eax set is not visible in the current block we may have to treat it as an indirect branch.

**Comment by derekbruening** [comment]
I filed #2250 on handling the cases where int 2d does **not** raise an exception.

So #2126 only covers the cases where it **does** raise an exception.  But it seems like this patch here is incomplete as it fails to handle 64-bit cases (where I guess the ExceptionAddress is off by more than 1), right?  We still saw the assert there.

**Comment by derekbruening** [comment]
> I think that the patch for #2126 is complete (Continuous integration is green). The ExceptionAddress may  be off only by one even in 64 bit. The fail was the one described in #2250

I checked the assert I can repro for x64 even with this patch: yes, I agree, it is after control goes off into badness.
