### PR TITLE
i#6611: Fix pthread lock hang

### LINKED ISSUE #6611: HANG in elfutils libdw in looking up line numbers with drsyms
Noticed this in Dr. Memory where with the update to use elfutils libdw, release build seem to hang when looking up line numbers:

```
(gdb) bt
#0  0x00007fffe3c15ad0 in ?? ()
#1  0x00007fffe3e3a088 in Dwarf_Abbrev_Hash_find (htab=htab@entry=0x7ffde464b8f0, hval=hval@entry=1)
    at /home/runner/work/drmemory/drmemory/dynamorio/third_party/elfutils/lib/dynamicsizehash_concurrent.c:475
#2  0x00007fffe3e3c35e in __libdw_getabbrev (dbg=0x7ffde3dd5050, cu=cu@entry=0x7ffde464b8a8, offset=0, lengthp=lengthp@entry=0x7ffde3c9c610, result=result@entry=0x0)
    at /home/runner/work/drmemory/drmemory/dynamorio/third_party/elfutils/libdw/dwarf_getabbrev.c:86
#3  0x00007fffe3e3bb54 in __libdw_findabbrev (cu=0x7ffde464b8a8, code=5) at /home/runner/work/drmemory/drmemory/dynamorio/third_party/elfutils/libdw/dwarf_tag.c:56
#4  0x00007fffe3e3a8aa in __libdw_dieabbrev (readp=<synthetic pointer>, die=0x7ffde3c9c830)
    at /home/runner/work/drmemory/drmemory/dynamorio/third_party/elfutils/libdw/libdwP.h:762
#5  __libdw_find_attr (die=die@entry=0x7ffde3c9c830, search_name=search_name@entry=16, codep=codep@entry=0x7ffde3c9c6d0, formp=formp@entry=0x7ffde3c9c6d4)
    at /home/runner/work/drmemory/drmemory/dynamorio/third_party/elfutils/libdw/dwarf_child.c:49
#6  0x00007fffe3e3a22f in dwarf_attr (die=die@entry=0x7ffde3c9c830, search_name=search_name@entry=16, result=result@entry=0x7ffde3c9c6d0)
    at /home/runner/work/drmemory/drmemory/dynamorio/third_party/elfutils/libdw/dwarf_attr.c:45
#7  0x00007fffe3e397f4 in dwarf_getsrclines (cudie=0x7ffde3c9c830, lines=0x7ffde3c9c758, nlines=0x7ffde3c9c750)
    at /home/runner/work/drmemory/drmemory/build_drmemory-debug-64/dynamorio/ext/drsyms/dwarf_getsrclines.c:1243
#8  0x00007fffe3df62fa in get_lines_from_cu (mod=0x7fffe41230d8, cu_die=0x7ffde3c9c830, lines_out=0x7ffde3c9c7a8)
    at /home/runner/work/drmemory/drmemory/dynamorio/ext/drsyms/drsyms_dw.c:236
#9  0x00007fffe3df63dd in search_addr2line_in_cu (mod=0x7fffe41230d8, pc=4464, cu_die=0x7ffde3c9c830, sym_info=0x7ffde3c9cc60)
    at /home/runner/work/drmemory/drmemory/dynamorio/ext/drsyms/drsyms_dw.c:262
#10 0x00007fffe3df61c4 in drsym_dwarf_search_addr2line (mod_in=0x7fffe41230d8, pc=4464, sym_info=0x7ffde3c9cc60)
    at /home/runner/work/drmemory/drmemory/dynamorio/ext/drsyms/drsyms_dw.c:199
#11 0x00007fffe3df1d6f in drsym_unix_lookup_address (mod_in=0x7fffe3fcdda0, modoffs=4464, out=0x7ffde3c9cc60, flags=1)
    at /home/runner/work/drmemory/drmemory/dynamorio/ext/drsyms/drsyms_unix_common.c:683
#12 0x00007fffe3df03aa in drsym_lookup_address_local (modpath=0x7fffe4017510 "dr/test/drmem-user", modoffs=4464, out=0x7ffde3c9cc60, 
    flags=1) at /home/runner/work/drmemory/drmemory/dynamorio/ext/drsyms/drsyms_unix_frontend.c:153
#13 0x00007fffe3df058d in drsym_lookup_address (modpath=0x7fffe4017510 "dr/test/drmem-user", modoffs=4464, out=0x7ffde3c9cc60, flags=1)
    at /home/runner/work/drmemory/drmemory/dynamorio/ext/drsyms/drsyms_unix_frontend.c:244
#14 0x00007fffe3cddb97 in lookup_func_and_line (frame=0x7fffe41130d0, name_info=0x7fffe40174b8, modoffs=4464)
    at /home/runner/work/drmemory/drmemory/common/callstack.c:548
#15 0x00007fffe3cf5ced in packed_frame_to_symbolized (pcs=0x7fffe4161440, frame=0x7fffe41130d0, idx=0) at /home/runner/work/drmemory/drmemory/common/callstack.c:2303
#16 0x00007fffe3cf6ae9 in packed_callstack_to_symbolized (pcs=0x7fffe4161440, scs=0x7ffde3c9ce60) at /home/runner/work/drmemory/drmemory/common/callstack.c:2347
#17 0x00007fffe3d2d53d in report_error (etp=0x7ffde3c9d1c0, mc=0x7ffde3c9ddb0, pcs=0x0) at /home/runner/work/drmemory/drmemory/drmemory/report.c:2797
#18 0x00007fffe3d38ae4 in report_unaddressable_access (loc=0x7ffde3c9db00, addr=0x7ffff3c00330 "", sz=4, access_type=2, container_start=0x7ffff3c00330 "", 
    container_end=0x7ffff3c00334 "", mc=0x7ffde3c9ddb0) at /home/runner/work/drmemory/drmemory/drmemory/report.c:3092
#19 0x00007fffe3c5089b in handle_mem_ref_internal (flags=9, loc=0x7ffde3c9db00, addr=0x7ffff3c00330 "", sz=4, mc=0x7ffde3c9ddb0, opnum=0, comb=0x7ffde3c9db40)
    at /home/runner/work/drmemory/drmemory/drmemory/slowpath.c:1741
#20 0x00007fffe3c515d5 in check_mem_opnd (opc=56, flags=9, loc=0x7ffde3c9db00, opnd=..., sz=4, mc=0x7ffde3c9ddb0, opnum=0, comb=0x7ffde3c9db40)
    at /home/runner/work/drmemory/drmemory/drmemory/slowpath.c:1815
#21 0x00007fffe3c46460 in slow_path_with_mc (drcontext=0x7ffde3c84080, pc=0x7ffff3bfb170 <incomplete sequence \307>, 
    decode_pc=0x7ffff3bfb170 <incomplete sequence \307>, mc=0x7ffde3c9ddb0) at /home/runner/work/drmemory/drmemory/drmemory/slowpath.c:878
#22 0x00007fffe3c47043 in slow_path (pc=0x7ffff3bfb170 <incomplete sequence \307>, decode_pc=0x7ffff3bfb170 <incomplete sequence \307>)
    at /home/runner/work/drmemory/drmemory/drmemory/slowpath.c:952
```

Let it run w/ breakpoints in drsyms_dw.c -- never returns out of libdw.
```
(gdb) bt
#0  resize_worker (htab=htab@entry=0x7ffde464b8f0) at /home/runner/work/drmemory/drmemory/dynamorio/third_party/elfutils/lib/dynamicsizehash_concurrent.c:306
#1  0x00007fffe3e3a080 in Dwarf_Abbrev_Hash_find (htab=htab@entry=0x7ffde464b8f0, hval=hval@entry=1)
    at /home/runner/work/drmemory/drmemory/dynamorio/third_party/elfutils/lib/dynamicsizehash_concurrent.c:476
#2  0x00007fffe3e3c35e in __libdw_getabbrev (dbg=0x7ffde3dd5050, cu=cu@entry=0x7ffde464b8a8, offset=0, lengthp=lengthp@entry=0x7ffde3c9c610, result=result@entry=0x0)
    at /home/runner/work/drmemory/drmemory/dynamorio/third_party/elfutils/libdw/dwarf_getabbrev.c:86
```

Seems to be stuck here inside Dwarf_Abbrev_Hash_find at
third_party/elfutils/lib/dynamicsizehash_concurrent.c:476:
```
  while (pthread_rwlock_tryrdlock(&htab->resize_rwl) != 0)
    resize_worker(htab);
```
htab is maybe not initialized properly?
```
(gdb) p htab
$6 = (Dwarf_Abbrev_Hash *) 0x7ffde464b8f0
(gdb) p *htab
$2 = {
  size = 41,
  old_size = 7308831422233340207,
  filled = 0,
  table = 0x7ffde47b8050,
  old_table = 0x64756c636e692f72,
  resizing_state = 0,
  next_init_block = 0,
  num_initialized_blocks = 0,
  next_move_block = 0,
  num_moved_blocks = 0,
  resize_rwl = {
    __data = {
      __readers = 11,
      __writers = 0,
      __wrphase_futex = 0,
      __writers_futex = 0,
      __pad3 = 0,
      __pad4 = 0,
      __cur_writer = 0,
      __shared = 0,
      __rwelision = 0 '\000',
      __pad1 = "\000\000\000\000\000\000",
      __pad2 = 0,
      __flags = 0
    },
    __size = "\v", '\000' <repeats 54 times>,
    __align = 11
  }
}
```

### PR DESCRIPTION
**Pull request by derekbruening**
Fixes a hang on glibc 2.37 by initializing the tid pthread TLS field. Its offset is located by decoding an exported function known to reference it in a new routine privload_set_pthread_tls_fields().

Only x86 is supported with this fix as no aarch64 machine with the required glibc is available for developing and testing the decode fix.

Tested on a glibc 2.37 machine where without this fix the client.drcallstack test hangs in release build.

Also tested on a Dr. Memory 2.6.19737 build pointing at a release build DR with this fix and confirmed it fixes the hang there.

Fixes #6611

### CODE REVIEW

File: core/unix/loader_linux.c [hunk 1]
```diff
@@ -283,7 +284,98 @@ privload_mod_tls_init(privmod_t *mod)
...
+        return;
+    LOG(GLOBAL, LOG_LOADER, 2, "%s: decoding %s to find tid offset\n", __FUNCTION__,
+        PTHREAD_TID_FUNC_NAME);
+    app_pc pc = (app_pc)tid_using_func;
+    instr_t instr;
+    dcontext_t *dcontext = get_thread_private_dcontext();
+    if (dcontext == NULL)
+        dcontext = GLOBAL_DCONTEXT;
+    instr_init(dcontext, &instr);
+#    define MAX_INSTRS_TO_DECODE 64
```
Comment (abhinav92003) [inline core/unix/loader_linux.c:311]: Add justification comment for why 64 is a good limit.

File: core/unix/loader_linux.c [hunk 2]
```diff
@@ -283,7 +284,98 @@ privload_mod_tls_init(privmod_t *mod)
...
+        /* TODO i#6611: We have to decode something like this to come up with
+         * privlib_tls_base - 0x700 + 208 but we need a 2.37+ machine to test on:
+         *     13dec:       d53bd042        mrs     x2, tpidr_el0
+         *     13df0:       52800000        mov     w0, #0x0
+         *     13df4:       d11c0042        sub     x2, x2, #0x700
+         *     13df8:       b940d042        ldr     w2, [x2, #208]
+         */
+        break;
+#    else
+        /* XXX i#6611: Not supported. */
```
Comment (abhinav92003) [inline core/unix/loader_linux.c:347]: We would presumably need to add this on RISC-V at some point right? s/supported/supported yet/?

File: core/unix/loader_linux.c [hunk 3]
```diff
@@ -283,7 +284,98 @@ privload_mod_tls_init(privmod_t *mod)
...
+        PTHREAD_TID_FUNC_NAME);
+    app_pc pc = (app_pc)tid_using_func;
+    instr_t instr;
+    dcontext_t *dcontext = get_thread_private_dcontext();
+    if (dcontext == NULL)
+        dcontext = GLOBAL_DCONTEXT;
+    instr_init(dcontext, &instr);
+#    define MAX_INSTRS_TO_DECODE 64
+    int instr_count = 0;
+    long *tid_slot = NULL;
```
Comment (abhinav92003) [inline core/unix/loader_linux.c:313]: This could be loop-local.

File: core/unix/loader_linux.c [hunk 4]
```diff
@@ -283,7 +284,98 @@ privload_mod_tls_init(privmod_t *mod)
...
+         *   8ac2d:       00
+         */
+        if (instr_get_opcode(&instr) == OP_mov_ld &&
+            opnd_is_far_base_disp(instr_get_src(&instr, 0)) &&
+            opnd_get_segment(instr_get_src(&instr, 0)) == LIB_SEG_TLS) {
+            int offs = opnd_get_disp(instr_get_src(&instr, 0));
+            tid_slot = (long *)(priv_tls_base + offs);
+        }
+#    elif defined(AARCH64)
+        /* TODO i#6611: We have to decode something like this to come up with
```
Comment (abhinav92003) [inline core/unix/loader_linux.c:338]: Maybe print a SYSLOG_INTERNAL_WARNING to make it easier to debug the crash when it does show up on AArch64/others?

**Review by abhinav92003 — APPROVED** [review]

File: core/unix/loader_linux.c (hunk 1 above)
Comment (derekbruening) [reply core/unix/loader_linux.c:311]: Done.

File: core/unix/loader_linux.c (hunk 2 above)
Comment (derekbruening) [reply core/unix/loader_linux.c:347]: Yes.  Done.

File: core/unix/loader_linux.c (hunk 3 above)
Comment (derekbruening) [reply core/unix/loader_linux.c:313]: Done.

File: core/unix/loader_linux.c (hunk 4 above)
Comment (derekbruening) [reply core/unix/loader_linux.c:338]: I *think* this is limited to glibc 2.37+, and that version is identified over in another file, so I put a warning there for non-x86.  Tested by temporarily making it print for x86.

File: core/unix/loader_linux.c [hunk 5]
```diff
@@ -283,7 +284,104 @@ privload_mod_tls_init(privmod_t *mod)
...
+                    SYSLOG_INTERNAL_WARNING("%s: failed to write tid to slot %p\n",
+                                            __FUNCTION__, tid_slot);
+                }
+            }
+            break;
+        }
+        instr_reset(dcontext, &instr);
+        ++instr_count;
+    }
+    instr_free(dcontext, &instr);
```
Comment (abhinav92003) [inline core/unix/loader_linux.c:380]: We should probably show a warning or something if we exit the loop after MAX_INSTRS_TO_DECODE. Because that's something unexpected.
