### PR TITLE
i#7858: Workaround std::regex_search crash in core_sharded_test

### LINKED ISSUE #7858: tool.drcachesim.core_sharded segfault
`tool.drcachesim.core_sharded` has started failing recently. There doesn't seem to be a recent DR change that might've triggered this. The cause is a stack overflow in std::regex:

```
#571 0x00005555555c896c in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::__cxx11::regex_traits<char>, true>::_M_dfs (this=0x7fffffffc720, 
    __match_mode=std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::__cxx11::regex_traits<char>, true>::_Match_mode::_Prefix, __i=84) at /usr/include/c++/15/bits/regex_executor.tcc:518
#572 0x00005555555d1239 in std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::__cxx11::regex_traits<char>, true>::_M_rep_once_more (this=0x7fffffffc720, 
    __match_mode=std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::__cxx11::regex_traits<char>, true>::_Match_mode::_Prefix, __i=92) at /usr/include/c++/15/bits/regex_executor.tcc:185
```

This is currently blocking PRs (#7857). The x86-64 failure seems flaky as it went away on a retry, but the aarch64 one is persisting.

### PR DESCRIPTION
**Pull request by abhinav92003**
core_sharded_test invokes std::regex_search over the analyzer output after sharding into 11 cores. This invocation has started crashing with a stack overflow recently, without any inciting change in DR itself. To workaround, we reduce the string to regex search over by extracting stats only for the relevant core (or total stats).

Fixes: #7858

### CODE REVIEW

**Comment by abhinav92003** [comment]
Scatter gather tests are failing on x86-32 because of a different reason: #7678.

File: clients/drcachesim/tests/core_sharded_test.cpp [hunk 1]
```diff
@@ -185,13 +185,32 @@ Core [0-9] counts:
             dir.c_str(), "-cores",        "11",    "-cpu_schedule_file", cpu_file.c_str()
         };
         std::string output = run_analyzer(sizeof(args) / sizeof(args[0]), args);
-        assert(std::regex_search(output, std::regex(R"DELIM(Basic counts tool results:
+        // We're sharding into 11 cores which creates an output string which is
+        // apparently too large for our std::regex_search below (i#7858), so we try to
+        // reduce the haystack by extracting only the relevant stats from the full
+        // output.
+        // The last line in the total stats or stats for any core.
+        constexpr char kLastStats[] = " encodings\n";
```
Comment (derekbruening) [inline clients/drcachesim/tests/core_sharded_test.cpp]: This seems too fragile as we could easily add more output lines. Safer to look for "^Thread" for the start of the next thread stats, right? That seems much less likely to change.

Or, just look for "total threads" which is the final line we want to find. That seems best, most robust, and simplest.

File: clients/drcachesim/tests/core_sharded_test.cpp [hunk 2]
```diff
@@ -185,13 +185,32 @@ Core [0-9] counts:
             dir.c_str(), "-cores",        "11",    "-cpu_schedule_file", cpu_file.c_str()
         };
         std::string output = run_analyzer(sizeof(args) / sizeof(args[0]), args);
-        assert(std::regex_search(output, std::regex(R"DELIM(Basic counts tool results:
+        // We're sharding into 11 cores which creates an output string which is
+        // apparently too large for our std::regex_search below (i#7858), so we try to
```
Comment (derekbruening) [inline clients/drcachesim/tests/core_sharded_test.cpp:189]: This is really surprising: these are only 24 lines each; these things should be able to handle thousands of lines, not just 200.

What does a callstack of the overflow look like? That may give hints as to what is really going on.

It may well be worth filing a bug on this, if one is not filed already: this really seems like a mistake in some recent regex library change if it can't scale at all.

A quick search shows this is not uncommon due to recursive DFS: only RE2 and Boost seem to implement things scalably.

**Review by derekbruening — APPROVED** [review]

File: clients/drcachesim/tests/core_sharded_test.cpp (hunk 1 above)
Comment (abhinav92003) [reply clients/drcachesim/tests/core_sharded_test.cpp]: Done.

Comment (abhinav92003) [reply clients/drcachesim/tests/core_sharded_test.cpp]: Used " threads\n" because no "total" in each core's stats.

File: clients/drcachesim/tests/core_sharded_test.cpp (hunk 2 above)
Comment (abhinav92003) [reply clients/drcachesim/tests/core_sharded_test.cpp:189]: #7858 shows part of the callstack. Frames of that sort just repeat.

> A quick search shows this is not uncommon due to recursive DFS: only RE2 and Boost seem to implement things scalably.

I found some discussions too, like https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86164 which links to some other, but I got the impression from the latest update that it should've been resolved now? Was that also what you found?

Comment (abhinav92003) [reply clients/drcachesim/tests/core_sharded_test.cpp:189]: Going ahead with submitting this PR; we can discuss this thread separately offline.
