### PR TITLE
i#7552: Fix a race condition in attach-memory-dump-syscall-test.

### LINKED ISSUE #7552: client.attach-memory-dump-syscall-test failed: missing "syscall" output
client.attach-memory-dump-syscall-test failed on a master merge x64:

https://github.com/DynamoRIO/dynamorio/actions/runs/16328307412/job/46124109179

```
test 477
        Start 477: code_api|client.attach-memory-dump-syscall-test

477: Test command: /opt/hostedtoolcache/cmake/3.19.7/x64/cmake-3.19.7-Linux-x86_64/bin/cmake "-D" "toolbindir=/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/bin64" "-D" "precmd=rm@/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/suite/tests/attach_syscall_record_file.*" "-D" "cmd=/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/bin64/run_in_bg@-out@/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/suite/tests/client.attach-memory-dump-syscall-test-out@/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/bin64/drrun@-no_inject@--@/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/suite/tests/bin/linux.syscall_records_attach@-v@-attach" "-D" "postcmd=/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/bin64/drsyscall_record_viewer@/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/suite/tests/attach_syscall_record_file.*" "-D" "postcmd2=" "-D" "postcmd3=" "-D" "postcmd4=" "-D" "out=/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/suite/tests/client.attach-memory-dump-syscall-test-out" "-D" "nudge=<attach>@-quiet@-debug@-stderr_mask@0xC@-dumpcore_mask@0@-code_api@-c@/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/suite/tests/bin/libclient.attach-memory-dump-syscall-test.dll.so" "-D" "clear=" "-D" "pidfile=" "-P" "/home/runner/work/dynamorio/dynamorio/suite/tests/runall.cmake"
477: Test timeout computed to be: 90
477: Running postcmd |/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/bin64/drsyscall_record_viewer;/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/suite/tests/attach_syscall_record_file.30990|
477: Hello World!
477: thread init
477: nudge delivered 1
477: done<unable to determine lib path for cross-arch execve>
477: 
474/545 Test #477: code_api|client.attach-memory-dump-syscall-test ....................***Failed  Required regular expression not found. Regex=[^.*thread init
.*nudge delivered 1
.*done.*
.*syscall.*
$
]  0.48 sec
```

### PR DESCRIPTION
**Pull request by ivankyluk**
There is a race condition between the post-command to read the syscall record file and the DR client in attach-memory-dump-syscall-test.dll.c writing to the file. The post-command is triggered by writing "done" to  STDOUT or STDERR. This race is resolved by having the DR client write the done only after it has finished writing to the syscall record file within its exit event handler.

Removing print("done") from the signal_handler in syscall-records-attach.c introduces another race condition.
A race exists between the application making syscalls and a SIGTERM that is sent after the attach event. This could potentially cause the test to fail if no syscalls are recorded before the signal is sent. The solution is to explicitly perform a write syscall in the code, guaranteeing that at least one syscall  is recorded for the test.

Tested:
Without the changes, "ctest --repeat-until-fail 100 -R attach-memory-dump-syscall-test" usually fails before hitting 100 tests. 

With the changes, multiple runs of "ctest --repeat-until-fail 1000 -R attach-memory-dump-syscall-test " have 0 failures.

Fixes #7552

### CODE REVIEW

File: suite/runsuite_wrapper.pl [hunk 1]
```diff
@@ -512,7 +512,6 @@
             %ignore_failures_64 = (
```
Comment (derekbruening) [inline suite/runsuite_wrapper.pl:512]: Please describe how this was tested in the PR description with numbers: something like you ran 100x and it failed 20x before and 0x with the fix.

Comment (ivankyluk) [reply suite/runsuite_wrapper.pl:512]: Done.
