### PR TITLE
i#1312 AVX-512 support: Suppress incomplete AVX-512 support on non-UNIX and 32-bit.

### LINKED ISSUE #3949: AVX-512 handling breaks DynamoRIO execution on Windows with full AVX-512 support
**Describe the bug**
Execution of any application under DynamoRIO is impossible in the following scenario:

- Windows 
- Full AVX-512 Support (i.e. `avx512_enabled` is set to true in proc.c)
https://github.com/DynamoRIO/dynamorio/blob/cf1ec32e9b89c1d8a28e0f355b8338d4c05c0f14/core/arch/x86/proc.c#L437

*Note*: This behavior appears with and w/o client and is deterministic.

**To Reproduce**
1. Take Windows machine with AVX-512 (full) support (No VM), check flag `avx512_enabled = true` in `proc.c`.
2. Execute any Program like `notepad.exe`
3.1 In release builds, DR immediately exits
3.2 In debug builds, assertion fires: `rip-relative reference out of 32-bit reach`

**Access Violation, as reported by WinDBG**
```
(3aa8.3a44): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
dynamorio!encode_cti+0x3b [inlined in dynamorio!instr_encode_arch+0x102]:
00000000`7107e042 8803            mov     byte ptr [rbx],al ds:00000000`00000000=??
0:000> kb
 # RetAddr           : Args to Child                                                           : Call Site
00 (Inline Function) : --------`-------- --------`-------- --------`-------- --------`-------- : dynamorio!encode_cti+0x3b [c:\users\felix\source\repos\dynamorio\core\arch\x86\encode.c @ 2598] 
01 00000000`7107b13a : 00000000`00000000 00000000`71070c00 00000237`69b0e780 00000000`00000000 : dynamorio!instr_encode_arch+0x102 [c:\users\felix\source\repos\dynamorio\core\arch\x86\encode.c @ 2785] 
02 (Inline Function) : --------`-------- --------`-------- --------`-------- --------`-------- : dynamorio!instr_encode_to_copy+0x16 [c:\users\felix\source\repos\dynamorio\core\arch\encode_shared.c @ 132] 
03 00000000`710b0a51 : 00000000`00000000 00000237`69b0e780 00000000`00000000 00000000`00000002 : dynamorio!instr_encode+0x1a [c:\users\felix\source\repos\dynamorio\core\arch\encode_shared.c @ 140] 
04 00000000`710b1eaa : 00000000`00000007 00000237`69b35b30 00000000`710b32e0 00000000`00000000 : dynamorio!emit_intercept_code+0x1eb1 [c:\users\felix\source\repos\dynamorio\core\win32\callback.c @ 1328] 
05 00000000`710adaf9 : 00000000`7118427f 00000237`69ac1a01 00000000`710b32e0 00000000`00000000 : dynamorio!intercept_call+0x26a [c:\users\felix\source\repos\dynamorio\core\win32\callback.c @ 1743] 
06 00000000`7100594a : 00000000`7118c4b8 00000000`00000218 00000000`00000000 00000000`00000000 : dynamorio!callback_interception_init_finish+0x59 [c:\users\felix\source\repos\dynamorio\core\win32\callback.c @ 7747] 
07 00000000`7109b40c : 000000a1`0510f700 00000000`00000000 00000000`00000000 00000237`67ea0031 : dynamorio!dynamorio_app_init+0x23a [c:\users\felix\source\repos\dynamorio\core\dynamo.c @ 692] 
08 00000000`710d28e0 : 00007ff9`1c1d9770 00000000`710d28d0 00000000`00000000 00000000`00000000 : dynamorio!auto_setup+0x1c [c:\users\felix\source\repos\dynamorio\core\arch\x86_code.c @ 169] 
09 00007ff9`1c1d9770 : 00000000`710d28d0 00000000`00000000 00000000`00000000 00000000`00000000 : dynamorio!dynamo_auto_start+0x10 [C:\Users\felix\CMakeBuilds\1ac36d74-80db-f93a-9dba-3c80b8e1e38c\build\x64-Release\core\x86.asm_core.s @ 1599] 
0a 00000000`710d28d0 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!GetProcAddressStub
0b 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : dynamorio!dynamo_auto_start [C:\Users\felix\CMakeBuilds\1ac36d74-80db-f93a-9dba-3c80b8e1e38c\build\x64-Release\core\x86.asm_core.s @ 1591] 
```

**Debug Output with loglevel 3**

[log.0.2376.html.txt](https://github.com/DynamoRIO/dynamorio/files/3862852/log.0.2376.html.txt)

**Versions**
- All versions newer than (including) cronbuild-7.91.18109
- Prior Versions are not affected
- When manually disabling AVX512 support by setting `avx512_enabled = false ` (in `proc.c`). Dynamorio is executed correctly

cc @TomSie, @jones718

### PR DESCRIPTION
**Pull request by hgreving2304**
As pointed out in cf1ec32e9b89c1d8a28e0f3, AVX-512 context management by DynamoRIO is not
fully supported or is untested on non-UNIX as well as on 32-bit builds. Yet processor
detection and certain AVX-512 functionality was enabled on those builds when running on
machines with AVX-512 support enabled by the OS. This was causing problems (xref #3949).
For now, this patch completely disables all AVX-512 features on unsupported and untested
builds.

Fixes #3949
Issue: #1312

### CODE REVIEW

**Comment by derekbruening** [comment]
> As pointed out in cf1ec32, AVX-512 context management by DynamoRIO is not
> fully supported or untested on non-UNIX as well as on 32-bit builds.

?  You mean s/untested/tested/ I assume.

**Comment by derekbruening** [comment]
I thought you were able to repro the init-time issues and we'd fix them, making it likely that it would work, which with the existing warning seems reasonable.

**Comment by hgreving2304** [comment]
> I thought you were able to repro the init-time issues and we'd fix them, making it likely that it would work, which with the existing warning seems reasonable.

There are other known things missing on Windows and 32-bit or at least are untested. I wasn't planning to fully support and test Windows this week, considering that this is a pretty bad break (Windows completely broken when running on an AVX-512 machine) I thought it is imperative to fix quickly. WDYT?

**Comment by hgreving2304** [comment]
> > As pointed out in [cf1ec32](https://github.com/DynamoRIO/dynamorio/commit/cf1ec32e9b89c1d8a28e0f355b8338d4c05c0f14), AVX-512 context management by DynamoRIO is not
> > fully supported or untested on non-UNIX as well as on 32-bit builds.
> 
> ? You mean s/untested/tested/ I assume.

Fixed.

File: core/arch/x86/proc.c [hunk 1]
```diff
@@ -427,17 +427,27 @@ proc_init_arch(void)
...
         if (proc_has_feature(FEATURE_AVX512F)) {
             if (TESTALL(XCR0_HI16_ZMM | XCR0_ZMM_HI256 | XCR0_OPMASK, bv_low)) {
-                /* XXX i#1312: It had been unclear whether the kernel uses CR0 bits to
-                 * disable AVX-512 for its own lazy context switching optimization. If it
-                 * did, then our lazy context switch would interfere with the kernel's and
-                 * more support would be needed. We have concluded that the Linux kernel
-                 * does not do its own lazy context switch optimization for AVX-512 at
-                 * this time.
+#if !defined(UNIX) || !defined(X64)
+                /* FIXME i#1312: AVX-512 is not fully supported or untested on all
```
Comment (derekbruening) [inline core/arch/x86/proc.c]: Same problem!

File: core/arch/x86/proc.c [hunk 2]
```diff
@@ -427,17 +427,27 @@ proc_init_arch(void)
...
+                 * non-UNIX builds and in 32-bit yet. A SYSLOG_INTERNAL_ERROR_ONCE is
+                 * issued on Windows and by any 32-bit build if AVX-512 code is
+                 * encountered. Setting DynamoRIO to a state that partially supports
+                 * AVX-512 is causing problems, xref i#3949. We therefore completely
+                 * disable AVX-512 support in these builds.
```
Comment (derekbruening) [inline core/arch/x86/proc.c]: "for now" or sthg

File: core/arch/arch.h [hunk 3]
```diff
@@ -256,7 +256,7 @@ static inline void
 d_r_set_avx512_code_in_use(bool in_use, app_pc pc)
```
Comment (derekbruening) [inline core/arch/arch.h]: > This patch completely disables all AVX-512 features on unsupported and untested builds.

"for now" or sthg.

File: core/arch/x86/proc.c (hunk 1 above)
Comment (hgreving2304) [reply core/arch/x86/proc.c]: Fixed.

File: core/arch/x86/proc.c (hunk 2 above)
Comment (hgreving2304) [reply core/arch/x86/proc.c]: Done.

File: core/arch/arch.h (hunk 3 above)
Comment (hgreving2304) [reply core/arch/arch.h]: Done.
