### PR TITLE
i#3327: recognize DR core mangling spill to non-natural spill position.

### LINKED ISSUE #3327: Translating state not restoring register after observing async signal in mangle epilogue
xref #3307 . 

This is similar and related to bug referenced above:

loop_inc == 1

[..]
       mov      REG_XCX, HEX(0)
       mov      LOOP_COUNT_REG_ASM, 1
       add      LOOP_COUNT_REG_ASM, PTRSZ SYMREF(loop_inc)
       // mangle epilogue of add instruction
       mov      LOOP_COUNT_REG_ASM, 2
       sub      LOOP_TEST_REG_ASM, 1
       cmp      LOOP_TEST_REG_ASM, 0

As stated in #3307 , if an asynch interrupt hit in mangling epilogue of add instruction as indicated above, DR currently incorrectly xl8 the PC to an already executed app instruction. This mainly affects rip-rel mangling. In test above, if LOOP_COUNT_REG_ASM != rax, DR will present LOOP_COUNT_REG_ASM to be 2, but set PC to the 'add' instruction. DR will use rax to mangle the abs rip-rel address into internal slot 0.

I now discovered that if LOOP_COUNT_REG_ASM == rax, there is another, different bug: In this case, DR will use another register to mangle abs rip-rel address, e.g. rbx or rcx.  In this case, when the same asynch interrupt hits, DR will not recognize the restore of rcx from slot 0 as DR's own restore, because rcx doesn't match DR's natural spill slot (slot 0 is rax, see instr_is_DR_reg_spill_or_restore). In example above, xl8 rcx will be incorrect.

Another issue to mention is that when xl8 an instruction of mangled epilogue of rip-rel add (load), the reason why it is not marked as unsupported_mangle is that add is recognized as "instr_is_trace_cmp" in "translate_walk_track", which seems rather coincidental.

I can provide a test case along w/ work related to #3307 (TBD). This potentially affects more than just the rip-rel mangling case.

### PR DESCRIPTION
**Pull request by hgreving2304**
Allow for non-natural spill position when recognizing spill/restore if part of mangling. Dependent on the app instruction's register usage, mangling is able to spill different registers than it is naturally assumed.

Adds a subtest to client.mangle_suspend to expose i#3327.

Fixes #3327

### CODE REVIEW

File: core/arch/instr_shared.c [hunk 1]
```diff
@@ -3333,7 +3333,14 @@ instr_is_reg_spill_or_restore_ex(void *drcontext, instr_t *instr, bool DR_only,
...
     if (instr_check_tls_spill_restore(instr, spill, reg, &check_disp)) {
         int offs = reg_spill_tls_offs(*reg);
-        if (!DR_only || (offs != -1 && check_disp == os_tls_offset((ushort)offs))) {
+        if (!DR_only ||
+            (offs != -1 &&
+             /* Mangling may choose to spill registers to a not natural tls offset,
+              * e.g. rip-rel mangling will, if rax is used by the instruction. We
+              * allow for this here and still recognize the DR spill.
+              */
+             (instr_is_our_mangling(instr) ||
```
Comment (derekbruening) [inline core/arch/instr_shared.c]: This only works for a mangled instruction list: i.e., only during bb building (after a client's events) or bb recreation (also after a client's events).   Thus this call will never return true for a client.    Plus, this is-spill function is used for more than instrlists: some callers use it when decoding raw instructions, such as drreg and also I think DR may use it that way when it decodes from the cache in some cases?  So this does not seem a complete solution.

File: core/translate.c [hunk 2]
```diff
@@ -82,7 +82,7 @@ typedef struct _translate_walk_t {
     /* PR 263407: Track registers spilled since the last cti, for
      * restoring indirect branch and rip-rel spills
      */
-    bool reg_spilled[REG_SPILL_NUM];
+    uint reg_spilled[REG_SPILL_NUM];
```
Comment (derekbruening) [inline core/translate.c]: Explain in the comment above what this uint encodes

File: core/translate.c [hunk 3]
```diff
@@ -107,6 +107,8 @@ translate_walk_init(translate_walk_t *walk, byte *start_cache, byte *end_cache,
     walk->mc = mc;
     walk->start_cache = start_cache;
     walk->end_cache = end_cache;
+    for (int r = 0; r < REG_SPILL_NUM; r++)
+        walk->reg_spilled[r] = UINT_MAX;
```
Comment (derekbruening) [inline core/translate.c]: A comment above and perhaps here too would help to understand what UINT_MAX is supposed to mean

File: core/translate.c [hunk 4]
```diff
@@ -330,12 +334,16 @@ translate_walk_track(dcontext_t *tdcontext, instr_t *inst, translate_walk_t *wal
...
-                       (!spill && walk->reg_spilled[r]));
+            if (spill || walk->reg_spilled[r] != UINT_MAX) {
+                /* Ensure restores and spills are properly paired up, but we do
+                 * allow for redundant spills.
+                 */
+                ASSERT(spill || (!spill && walk->reg_spilled[r] != UINT_MAX));
                 ASSERT(spill || walk->reg_tls[r] == spill_tls);
-                walk->reg_spilled[r] = spill;
+                if (spill)
+                    walk->reg_spilled[r] = offs;
```
Comment (derekbruening) [inline core/translate.c]: I see here that this holds an offset: how about renaming it to reg_spill_offs?  IMHO that will make all the new code using it clearer and easier to read.

File: suite/tests/client-interface/mangle_suspend.c [hunk 5]
```diff
@@ -60,22 +63,28 @@ suspend_thread_routine(void *arg)
...
      * does the suspend and subsequent check for correctness.
      */
+    int suspend_val = *(int *)arg;
     while (!test_ready) {
         /* Empty. */
     }
-    struct timespec sleeptime;
-    sleeptime.tv_sec = 0;
-    /* Pick an uneven number to maximize the number of suspend calls w/o
-     * running into limitations in DR.
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.c]: What limitations?  Is there some bug somewhere to xref?

File: suite/tests/client-interface/mangle_suspend.c [hunk 6]
```diff
@@ -60,22 +63,28 @@ suspend_thread_routine(void *arg)
...
-                     : "i"(SUSPEND_VAL_C)
-                     : "rdx");
-        nanosleep(&sleeptime, NULL);
+        if (suspend_val == SUSPEND_VAL_TEST_1_C) {
+            asm volatile("mov %0, %%rdx\n\t"
+                         "mov %0, %%rdx\n"
+                         :
+                         : "i"(SUSPEND_VAL_TEST_1_C)
+                         : "rdx");
+        } else {
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.c]: I think it would be cleaner to have two separate functions rather than one with split behavior.

File: suite/tests/client-interface/mangle_suspend.dll.c [hunk 7]
```diff
@@ -101,17 +98,17 @@ suspend_func()
         if (!dr_get_mcontext(drcontexts[0], &mc))
             CHECK(false, "dr_get_mcontext failed!");
         /* Check xip such that we only perform the check if we are in the loop
-         * body of the test, in order to avoid races. The magic values 7 and 24
+         * body of the test, in order to avoid races. The magic values 16 and 42
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.dll.c]: Please include a comment in the test about updating here when changing its code.

File: suite/tests/client-interface/mangle_suspend.dll.c [hunk 8]
```diff
@@ -129,6 +126,51 @@ suspend_func()
...
+    uint num_suspended;
+    if (dr_suspend_all_other_threads(&drcontexts, &num_suspended, NULL)) {
+        if (num_suspended != 1)
+            CHECK(false, "num_suspended unexpected!");
+        dr_mcontext_t mc = { sizeof(mc), DR_MC_INTEGER | DR_MC_CONTROL };
+        if (!dr_get_mcontext(drcontexts[0], &mc))
+            CHECK(false, "dr_get_mcontext failed!");
+        /* Check xip such that we only perform the check if we are in the loop
+         * body of the test, in order to avoid races. The magic values 16 and 42
+         * are byte counts to compute the bounds of the asm loop in the test.
```
Comment (derekbruening) [inline suite/tests/client-interface/mangle_suspend.dll.c]: Please include a comment in the test about updating here when changing its code.

File: core/translate.c (hunk 2 above)
Comment (hgreving2304) [reply core/translate.c]: Done.

File: core/translate.c (hunk 4 above)
Comment (hgreving2304) [reply core/translate.c]: Done.

File: core/translate.c (hunk 3 above)
Comment (hgreving2304) [reply core/translate.c]: Added comment.

File: suite/tests/client-interface/mangle_suspend.c (hunk 5 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.c]: Just filed i#3332.

File: suite/tests/client-interface/mangle_suspend.dll.c (hunk 7 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.dll.c]: Done.

File: suite/tests/client-interface/mangle_suspend.dll.c (hunk 8 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.dll.c]: Done.

File: suite/tests/client-interface/mangle_suspend.c (hunk 6 above)
Comment (hgreving2304) [reply suite/tests/client-interface/mangle_suspend.c]: Done.

File: core/arch/instr_shared.c (hunk 1 above)
Comment (hgreving2304) [reply core/arch/instr_shared.c]: >> This only works for a mangled instruction list:
But that was the purpose. Only DR's mangling (I think only rip-rel) can add such a spill. Are there other cases (maybe I should add DR_only &&) where we want to recognize such a spill as well?

Comment (derekbruening) [reply core/arch/instr_shared.c]: Won't drreg do the wrong thing if it doesn't recognize this as a DR spill?  Similarly for other cases: though I just looked at decode_fragment() and it only uses instr_is_tls_xcx_spill().

Comment (hgreving2304) [reply core/arch/instr_shared.c]: That's true. I think we can test for TLS_REG0/1/2/3_SLOT, see patch.
