### PR TITLE
i#7676: Refactor aarchxx private TLS to match the actual layout

### LINKED ISSUE #7676: aarchxx privload TLS has layout wrong
The aarchxx private library TLS setup has the wrong layout and seems to do the wrong thing: it puts the TCB at the end of the allocation when it should be at the very start, before the thread pointer.

Xref #7670 where I'm trying to use the privload TLS in a client thread: I had to change the privload code to make it work. Not sure how private libraries have been working on aarchxx all this time. It looks like the RISCV layout and should follow that code.

I'm going to udpate the parts I need for #7670 but likely will not have time to fix all pieces so filing this issue.

### PR DESCRIPTION
**Pull request by derekbruening**
The aarchxx private library TLS was laid out like x86 with the app/library TLS before the TCB, but in actuality it needs to look more like RISC-V with the TCB before the app/library TLS.

Re-orders and updates the offset from the thread pointer.
Updates the ELF_R_TLS_DESC relocation and other places where the direction is specified.
Updates the static client thread TLS page to use 2 pages so the thread pointer can point to the middle, allowing for a negative offset.

Leaves some space for future pthread struct increases.
Adds decoding of pthread_mutex_consistent() to set the pthread tid field for platforms different than the 2.38 default.

Keeps 32-bit arm with the checked-in pthread layout, as that came from aarch32.
Removes the TCB padding to correctly work with the new ordering.

Issue: #1569, #7670, #7676
Fixes #7676

### CODE REVIEW

File: core/unix/loader_linux.c [hunk 1]
```diff
@@ -142,8 +147,10 @@ static size_t client_tls_size = 2 * 4096;
  *    0xf779e5bc:  mov    %eax,0x8(%edx)
  *    0xf779e5bf:  movb   $0x0,%gs:0x4fe
  */
-/* On A32, the pthread is put before tcbhead instead tcbhead being part of pthread */
-static size_t tcb_size_estimate = IF_X64_ELSE(0x1000, 0x500);
+/* On AArchXX and RISCV, the pthread struct is put before tcbhead instead of tcbhead
+ * being part of the pthread struct.
+ */
+static size_t tcb_size_estimate = IF_X64_ELSE(0x1000, 0x800);
```
Comment (abhinav92003) [inline core/unix/loader_linux.c]: Re the s/0x500/0x800/

Is this related to "Removes the TCB padding to correctly work with the new ordering."?

File: core/unix/loader_linux.c [hunk 2]
```diff
@@ -181,20 +186,33 @@ typedef struct _tcb_head_t {
 
 #ifdef X86
 #    define TLS_PRE_TCB_SIZE 0
-#elif defined(AARCHXX)
-/* XXX i#1569: This may be wrong for AArch64! */
```
Comment (abhinav92003) [inline core/unix/loader_linux.c:185]: So the comment was correct? Maybe xref to #1569 also in the PR description?

File: core/unix/loader_linux.c [hunk 3]
```diff
@@ -454,42 +487,47 @@ privload_tls_init(void *app_tp)
     /* GDB reads some pthread members (e.g., pid, tid), so we must make sure
      * the size and member locations match to avoid gdb crash.
      */
-    ASSERT(TLS_PRE_TCB_SIZE == LIBC_PTHREAD_SIZE);
+    ASSERT(TLS_PRE_TCB_SIZE >= LIBC_PTHREAD_SIZE);
     ASSERT(LIBC_PTHREAD_TID_OFFSET == offsetof(dr_pthread_t, tid));
 #endif
     LOG(GLOBAL, LOG_LOADER, 2, "%s: allocated %d at " PFX "\n", __FUNCTION__,
         client_tls_alloc_size, dr_tp);
 #ifdef RISCV64
```
Comment (abhinav92003) [inline core/unix/loader_linux.c]: Can do ifndef X86 instead of duplicating for AARCHXX.

File: core/unix/loader_linux.c [hunk 4]
```diff
@@ -528,6 +570,8 @@ privload_tls_exit(void *dr_tp)
         return;
 #ifdef RISCV64
```
Comment (abhinav92003) [inline core/unix/loader_linux.c]: Same here.

**Review by abhinav92003 — APPROVED** [review]

File: core/unix/loader_linux.c (hunk 2 above)
Comment (derekbruening) [reply core/unix/loader_linux.c:185]: Right, it was correct.  OK, added #1569.  Note that it is the very general port-to-aarch64 issue. Although looking at the bottom of #1569 I see a ref to the related #7569: which I had forgotten all about. This should subsume that.

File: core/unix/loader_linux.c (hunk 4 above)
Comment (derekbruening) [reply core/unix/loader_linux.c]: Done.

File: core/unix/loader_linux.c (hunk 3 above)
Comment (derekbruening) [reply core/unix/loader_linux.c]: Done.
