### PR TITLE
i#2387 assert in drcov: fixed a bug in drcov for module reload

### LINKED ISSUE #2387: ASSERT(ext/drcovlib/modules.c:321: (0) (fail to find the module to be unloaded))
Running drcachesim with -offline on test client.annotation-concurrency, an assert is seeing.
```
20:40|zhaoqin@zhaoqin:~/Workspace/DynamoRIO/builds/build_x64_dbg.git
> time ./bin64/drrun -msgbox_mask 0x0 -t drcachesim -offline -- ./suite/tests/bin/client.annotation-concurrency libclient.annotation-concurrency.appdll.so A 4
<Starting application /home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/suite/tests/bin/client.annotation-concurrency (30324)>
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/bin64/../clients/lib64/debug/libdrmemtrace.so' 0x00000000720097f0
add-symbol-file '/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/lib64/debug/libdynamorio.so' 0x000055a14a6c8b80
add-symbol-file '/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/ext/lib64/debug/libdrutil.so' 0x0000000075001680
add-symbol-file '/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/ext/lib64/debug/libdrmgr.so' 0x00000000730029f0
add-symbol-file '/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/ext/lib64/debug/libdrcovlib.so' 0x0000000073801dd0
add-symbol-file '/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/ext/lib64/debug/libdrx.so' 0x0000000077003100
add-symbol-file '/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/ext/lib64/debug/libdrreg.so' 0x0000000078002900
add-symbol-file '/usr/lib/x86_64-linux-gnu/libstdc++.so.6' 0x00007f1938893620
add-symbol-file '/lib/x86_64-linux-gnu/libm.so.6' 0x00007f1938536610
add-symbol-file '/lib/x86_64-linux-gnu/libc.so.6' 0x00007f1938187520
add-symbol-file '/lib64/ld-linux-x86-64.so.2' 0x00007f1937f42ae0
add-symbol-file '/lib/x86_64-linux-gnu/libgcc_s.so.1' 0x00007f1937d2dab0
>
<Initial options = -no_dynamic_options -client_lib '/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/bin64/../clients/lib64/debug/libdrmemtrace.so;0;-offline' -code_api -stack_size 56K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<(1+x) Handling our fault in a TRY at 0x000055a14a95a7ae>

    -------------------------------------------------------------------
     Performance for solving AX=B Linear Equation using Jacobi method
     Running on DynamoRIO
     Client version (null)
    ...................................................................

     Matrix Size :  1024
     Threads     :  4


     Started iteration 1 of the computation...
<get_memory_info mismatch! (can happen if os combines entries in /proc/pid/maps)
	os says: 0x00007f19352f9000-0x00007f1935b0a000 prot=0x00000003
	cache says: 0x00007f1935309000-0x00007f1935b0a000 prot=0x00000003
>

     Finished computing current solution distance in mode 0.
     Mode changed to 0.

     Started iteration 2 of the computation...
ASSERT FAILURE: /home/zhaoqin/Workspace/DynamoRIO/dynamorio.git/ext/drcovlib/modules.c:321: (0) (fail to find the module to be unloaded)

real	0m1.868s
user	0m1.680s
sys	0m0.452s
```
It can run online simulation correctly.
```
> time ./bin64/drrun -msgbox_mask 0x0 -t drcachesim -ipc_name drtestpipe1 -- ./suite/tests/bin/client.annotation-concurrency libclient.annotation-concurrency.appdll.so A 4
<Starting application /home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/suite/tests/bin/client.annotation-concurrency (31242)>
...
    -------------------------------------------------------------------
     Performance for solving AX=B Linear Equation using Jacobi method
     Running on DynamoRIO
     Client version (null)
    ...................................................................

     Matrix Size :  1024
     Threads     :  4


     Started iteration 1 of the computation...

     Finished computing current solution distance in mode 0.
     Mode changed to 0.

     Started iteration 2 of the computation...

     Finished computing current solution distance in mode 0.
     Mode changed to 0.

     Started iteration 3 of the computation...

     Finished computing current solution distance in mode 0.
     Mode changed to 0.

     Started iteration 4 of the computation...

     Finished computing current solution distance in mode 0.
     Mode changed to 0.

     Started iteration 5 of the computation...

     Finished computing current solution distance in mode 0.
     Mode changed to 0.

     Started iteration 6 of the computation...

     Finished computing current solution distance in mode 0.
     Mode changed to 0.

     Started iteration 7 of the computation...

     Finished computing current solution distance in mode 0.
     Mode changed to 0.

     Started iteration 8 of the computation...

     Finished computing current solution distance in mode 0.
     Mode changed to 0.

     Started iteration 9 of the computation...

     Finished computing current solution distance in mode 0.
     Mode changed to 0.

     Started iteration 10 of the computation...

     Finished computing current solution distance in mode 0.
     Mode changed to 0.


     The Jacobi Method For AX=B .........DONE
     Total Number Of iterations   :  10
    ...................................................................
<Stopping application /home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/suite/tests/bin/client.annotation-concurrency (31242)>
---- <application exited with code 0> ----
Cache simulation results:
Core #0 (11 thread(s))
  L1I stats:
    Hits:                       77,256,498
    Misses:                          6,329
    Miss rate:                        0.01%
  L1D stats:
    Hits:                       38,395,531
    Misses:                        231,562
    Miss rate:                        0.60%
Core #1 (10 thread(s))
  L1I stats:
    Hits:                       39,957,846
    Misses:                            112
    Miss rate:                        0.00%
  L1D stats:
    Hits:                       18,833,941
    Misses:                         85,001
    Miss rate:                        0.45%
Core #2 (10 thread(s))
  L1I stats:
    Hits:                       39,471,431
    Misses:                            113
    Miss rate:                        0.00%
  L1D stats:
    Hits:                       18,606,694
    Misses:                         85,184
    Miss rate:                        0.46%
Core #3 (10 thread(s))
  L1I stats:
    Hits:                       40,091,435
    Misses:                            115
    Miss rate:                        0.00%
  L1D stats:
    Hits:                       19,095,450
    Misses:                         85,025
    Miss rate:                        0.44%
LL stats:
    Hits:                          355,134
    Misses:                        138,307
    Local miss rate:                 28.03%
    Child hits:                291,708,826
    Total miss rate:                  0.05%

real	0m31.092s
user	0m36.780s
sys	0m3.408s

```

### PR DESCRIPTION
**Pull request by zhaoqin**
This CL fixed a bug in drcov handling module reload.
Because there could be more than one submodules of a module, we should iterate
the whole module table to update all submodules when a module is reloaded.

Fixes #2387

### CODE REVIEW

**Comment by zhaoqin** [comment]
Test to be added after i2006 PR commit, since the CL may conflict.

File: ext/drcovlib/modules.c [hunk 1]
```diff
@@ -174,11 +176,12 @@ event_module_load(void *drcontext, const module_data_t *data, bool loaded)
                 }
             }
 #endif
-            break;
+            /* We may just see a sub module, so we cannot stop here. We need iterate
+             * all entries to update all sub modules of the reloaded module.
```
Comment (derekbruening) [inline ext/drcovlib/modules.c]: I don't understand: "We may just see a sub module": you mean if the app does a custom mmap of just one segment of an ELF file, and then goes and executes from that segment to trigger the module load event?  But why would that require further iteration?  All non-contiguous entries are guaranteed to be in the vector immediately following the initial entry.  Why would we need to iterate further?

Comment (zhaoqin) [inline ext/drcovlib/modules.c]: The bug actually happens like below:
1. a module with multiple sub-modules is loaded, the module self and all sub-modules are added into module_table.
2. the module is unloaded, the module and all its sub-modules are marked as unloaded
3. the module is loaded at the same place (where the bug happens)
    the first entry we found match is actually a sub-module, and there are more sub-modules located before this submodule need update, but the code only updated all module/sub-modules after.
We could fixed the bug by forward scan in the outer loop, so we will see the module first before any submodule.
I will see if there is a better fix so we can reuse the code of handling the non-contiguous module reload.

Comment (derekbruening) [inline ext/drcovlib/modules.c]: The first segment entry should match as all segments share the same module_data_t pointer.  Why didn't the first one match?

**Comment by zhaoqin** [comment]
Updated commit message.

i#2387 assert in drcov: fixed a bug in drcov for module reload

This CL fixed a bug in drcov handling module reload.
Because a module could have multiple sub-modules, we should find the
containing module and update all its sub-modules on reload.

Fixes #2387

File: ext/drcovlib/modules.c (hunk 1 above)
Comment (zhaoqin) [inline ext/drcovlib/modules.c]: Because the loop is backward.

File: ext/drcovlib/modules.c [hunk 2]
```diff
@@ -141,6 +141,8 @@ event_module_load(void *drcontext, const module_data_t *data, bool loaded)
         entry = drvector_get_entry(&module_table.vector, i);
         mod   = entry->data;
         if (entry->unload &&
+            /* only check the main (containing) module */
```
Comment (derekbruening) [inline ext/drcovlib/modules.c]: Please add a note that this is needed b/c the loop is backward

File: ext/drcovlib/modules.c [hunk 3]
```diff
@@ -297,7 +299,8 @@ event_module_unload(void *drcontext, const module_data_t *data)
     for (i = module_table.vector.entries - 1; i >= 0; i--) {
         entry = drvector_get_entry(&module_table.vector, i);
         ASSERT(entry != NULL, "fail to get module entry");
-        if (pc_is_in_module(entry, data->start))
+        /* only check the main (containing) module */
```
Comment (derekbruening) [inline ext/drcovlib/modules.c]: Please add a note that this is needed b/c the loop is backward

File: ext/drcovlib/modules.c [hunk 4]
```diff
@@ -234,7 +236,7 @@ static inline void
 lookup_helper_set_fields(module_entry_t *entry, OUT uint *mod_index, OUT app_pc *mod_base)
 {
     if (mod_index != NULL)
-        *mod_index = entry->id;
+        *mod_index = entry->containing_id; /* Yes, the main (containing) module. */
```
Comment (derekbruening) [inline ext/drcovlib/modules.c]: I don't think this is what we want: drmodtrack treats the segments as separate entries and exposes that to the user.  The user expects the resulting index to actual contain the queried PC, which is not true with this change.  What is your reason for wanting to change this?

File: ext/drcovlib/modules.c (hunk 2 above)
Comment (zhaoqin) [inline ext/drcovlib/modules.c]: done

File: ext/drcovlib/modules.c (hunk 4 above)
Comment (zhaoqin) [inline ext/drcovlib/modules.c]: removed.
I want to return the consistent result.
Currently, it could return either the segment or the containing module.

File: ext/drcovlib/modules.c (hunk 3 above)
Comment (zhaoqin) [inline ext/drcovlib/modules.c]: done

File: ext/drcovlib/modules.c (hunk 4 above)
Comment (derekbruening) [inline ext/drcovlib/modules.c]: In terms of the bounds they are all segments: no entry has the whole bounds, so in that sense it is consistent.  The "containing" module entry is simply the first segment.

File: ext/drcovlib/modules.c [hunk 5]
```diff
@@ -234,7 +238,7 @@ static inline void
 lookup_helper_set_fields(module_entry_t *entry, OUT uint *mod_index, OUT app_pc *mod_base)
 {
     if (mod_index != NULL)
-        *mod_index = entry->id;
+        *mod_index = entry->id; /* We expose the segment. */
```
Comment (derekbruening) [inline ext/drcovlib/modules.c]: It has to be exposed: some users will not work properly otherwise.  I think you were not aware of what is exposed: see drmodtrack_info_t's docs.

**Comment by zhaoqin** [comment]
should I update the comment?

**Comment by derekbruening** [comment]
Doesn't matter, just seems a little odd.

**Comment by zhaoqin** [comment]
sorry, saw you message after merge

**Comment by fhahn** [comment]
Looks like this is a stale branch, I'll delete it
