### PR TITLE
i#6712: Add record_scheduler_t support for replay-as-traced

### LINKED ISSUE #6712: Add drmemtrace replay-as-traced support to record_scheduler_t
Trying to use record_filter running as-traced on a smallish app based on the threadsig sample fails:
```
Encoding size 9 != instr size 3 for PC 0x7ffa29f26ba9
```

```
[scheduler] next_record[6]: from 2 @1710797586236606: type=10 size=2 addr=0x7ffa2b0582fc
[scheduler] next_record[6]: from 2 @1710797586236631: type=47 size=6 addr=0x12c840f
[scheduler] next_record[6]: waiting because timestamp 13355270234506704 is ahead of output 0
[scheduler] next_record[6]: replay segment in=2 (@909) type=0 start=876 end=909
next_record[7]: from 2 @1710797586238158: next_record[3]: from 4 @1710797586238082: [scheduler] [record_filter] next_record[6]: advancing to input 3 instr #0
next_record[6]: replay segment in=3 (@0) type=0 start=0 end=-1
next_record[6]: from 3 @1710797586237492: type=25 size=0 addr=0x6
next_record[0]: from 1 @1710797586238563: next_record[6]: from 3 @1710797586238516: type=28 size=2 addr=0x2f728c2a350003
next_record[6]: from 3 @1710797586238712: type=28 size=9 addr=0xe40
[scheduler] next_record[6]: from 3 @1710797586238981: type=22 size=4 addr=0x41194
[scheduler] next_record[6]: from 3 @1710797586239016: type=24 size=4 addr=0x4115c
[scheduler] next_record[6]: from 3 @1710797586239212: type=28 size=10 addr=0x40
[scheduler] [scheduler] next_record[6]: from 3 @1710797586239336: type=28 size=20 addr=0x989680
[record_filter] [scheduler] next_record[6]: from 3 @1710797586239495: type=28 size=18 addr=0x1000
[scheduler] next_record[6]: from 3 @1710797586239827: [record_filter] type=28 size=2 addr=0x2f728c2a3505d0
[scheduler] next_record[3]: from 4 @1710797586239853: next_record[6]: from 3 @1710797586239920: type=28 size=3 addr=0x7
[scheduler] next_record[6]: from 3 @1710797586240088: type=47 size=3 addr=0xc08548
[scheduler] next_record[6]: from 3 @1710797586240206: type=10 size=3 addr=0x7ffa29f26ba9
```

It's the segment endpoint: have to stop before the encoding.
This would also affect skips, incl for ROI.
Better to change record_file_reader to ++ the instr count at the encoding
instead of the instr?

### PR DESCRIPTION
**Pull request by derekbruening**
Adds record_scheduler_t (for the record_filter tool) support for
replaying as-traced.  The key change here is having record_reader_t's
instruction ordinal, record_scheduler_t's output stream instruction
ordinal, and record_scheduler_t's switch boundaries all consider the
first in any sequence of encoding records or
TRACE_MARKER_TYPE_BRANCH_TARGET markers to start an instruction
instead of waiting for the instruction record.  (Previously the
scheduler switch point did consider encodings, but not branch targets,
and the ordinals only considered instructions.)

Moving the boundary back avoids splitting encodings from instructions
when operating at instrution boundaries in the scheduler (encountered
during replay, but this would also affect skipping for scheduler
regions of interest).

Adds tests of all 3 boundary types to the record_scheduler_t unit
test.

Adds a test of record_filter on the checked-in threadsig trace in
as-traced replay mode.

Fixes #6712

### CODE REVIEW

File: clients/drcachesim/reader/record_file_reader.h [hunk 1]
```diff
@@ -149,7 +149,13 @@ class record_reader_t : public std::iterator<std::input_iterator_tag, trace_entr
         UNUSED(res);
```
Comment (abhinav92003) [inline clients/drcachesim/reader/record_file_reader.h:149]: In the PR description: s/instrution/instruction/

File: clients/drcachesim/reader/record_file_reader.h [hunk 2]
```diff
@@ -177,6 +183,10 @@ class record_reader_t : public std::iterator<std::input_iterator_tag, trace_entr
                     break;
                 }
             }
+            if (cur_entry_.type == TRACE_TYPE_ENCODING)
+                prev_record_was_encoding_ = true;
```
Comment (abhinav92003) [inline clients/drcachesim/reader/record_file_reader.h:187]: nit: prev_record_was_encoding_ = (cur_entry_.type == TRACE_TYPE_ENCODING)

File: clients/drcachesim/tests/record_filter_as_traced.templatex [hunk 3]
```diff
@@ -0,0 +1,6 @@
+Output .* entries from .* entries.
+Schedule stats tool results:
+.*
+Core #0 schedule: .*
+Core #1 schedule: .*
+Core #2 schedule: .*
```
Comment (abhinav92003) [inline clients/drcachesim/tests/record_filter_as_traced.templatex:6]: There should be 7 cores right? Maybe check for all?

File: clients/drcachesim/reader/record_file_reader.h (hunk 1 above)
Comment (abhinav92003) [inline clients/drcachesim/reader/record_file_reader.h:149]: > The key change here is having record_reader_t increment the instruction ordinal on an encoding record instead of an instruction record.

This should be documented in  get_instruction_ordinal in scheduler.h.

**Review by abhinav92003 — APPROVED** [review]

File: clients/drcachesim/reader/record_file_reader.h [hunk 4]
```diff
@@ -149,7 +149,13 @@ class record_reader_t : public std::iterator<std::input_iterator_tag, trace_entr
         UNUSED(res);
         if (!eof_) {
             ++cur_ref_count_;
-            if (type_is_instr(static_cast<trace_type_t>(cur_entry_.type)))
+            // We increment the instr count at the encoding as that avoids multiple
```
Comment (derekbruening) [inline clients/drcachesim/reader/record_file_reader.h:152]: In a larger app I tracked down a further problem that looks like it should modify this PR rather than being separate, as the ordinals in the current PR here are wrong and it seems best to not merge this as is: we have to account for TRACE_MARKER_TYPE_BRANCH_TARGET which appears between the encoding and the instruction records.  Do we have an existing unit test for record_reader?  Not sure how to make a test of this: will see if it fits in any existing unit test framework.

File: clients/drcachesim/reader/record_file_reader.h (hunk 1 above)
Comment (derekbruening) [reply clients/drcachesim/reader/record_file_reader.h:149]: Done.

File: clients/drcachesim/reader/record_file_reader.h (hunk 2 above)
Comment (derekbruening) [reply clients/drcachesim/reader/record_file_reader.h:187]: Done (or the equivalent with a new helper function for branch target markers too).

File: clients/drcachesim/tests/record_filter_as_traced.templatex (hunk 3 above)
Comment (derekbruening) [reply clients/drcachesim/tests/record_filter_as_traced.templatex:6]: Done.

File: clients/drcachesim/reader/record_file_reader.h (hunk 1 above)
Comment (derekbruening) [reply clients/drcachesim/reader/record_file_reader.h:149]: Done.

Comment (derekbruening) [reply clients/drcachesim/reader/record_file_reader.h:149]: Also fixed the scheduler output stream counting.

File: clients/drcachesim/reader/record_file_reader.h (hunk 4 above)
Comment (derekbruening) [reply clients/drcachesim/reader/record_file_reader.h:152]: Done, for record_reader_t and scheduler output stream and scheduler switches, with tests added.

File: clients/drcachesim/reader/record_file_reader.h [hunk 5]
```diff
@@ -283,7 +289,10 @@ class record_reader_t : public std::iterator<std::input_iterator_tag, trace_entr
     uint64_t cur_instr_count_ = 0;
     uint64_t last_timestamp_ = 0;
     uint64_t first_timestamp_ = 0;
-    bool prev_record_was_encoding_ = false;
+    // Whether the prior record was a record that immediately precedes
+    // an instrution or another record of this type: an encoding or
```
Comment (abhinav92003) [inline clients/drcachesim/reader/record_file_reader.h:293]: s/instrution/instruction/

File: clients/drcachesim/scheduler/scheduler.cpp [hunk 6]
```diff
@@ -447,6 +437,25 @@ scheduler_tmpl_t<trace_entry_t, record_reader_t>::record_type_is_marker(
...
+    trace_entry_t record, trace_entry_t prev_record)
+{
+    trace_marker_type_t marker_type;
+    uintptr_t marker_value;
+    // The branch target marker sits between any encodings and the instr.
+    bool is_target_marker = record_type_is_marker(record, marker_type, marker_value) &&
+        marker_type == TRACE_MARKER_TYPE_BRANCH_TARGET;
+    // Don't advance past encodings or target markers and split them from their
+    // associated instr.
+    return (record_type_is_instr(record) || record_type_is_encoding(record) ||
```
Comment (abhinav92003) [inline clients/drcachesim/scheduler/scheduler.cpp:452]: Could we reuse record_is_pre_instr from record_file_reader.h here?

**Review by abhinav92003 — APPROVED** [review]

File: clients/drcachesim/reader/record_file_reader.h (hunk 5 above)
Comment (derekbruening) [reply clients/drcachesim/reader/record_file_reader.h:293]: Done.

File: clients/drcachesim/scheduler/scheduler.cpp (hunk 6 above)
Comment (derekbruening) [reply clients/drcachesim/scheduler/scheduler.cpp:452]: If we make that a static class function.  Done.
