### PR TITLE
i#5455 path-ignore-directory: Do not try to execute directories

### LINKED ISSUE #5455: USAGE ERROR when a directory named like an executable is present in the PATH variable [Minor bug]
**Describe the bug**
When there is a directory named like an executable in one of the locations the PATH variable points to, normally it is ignored and a real executable is searched instead.
For example if there is a directory called `vim` in a user defined PATH directory (like `~/.bin`) it is ignored and the real vim application will be run.
DynamoRIO does not handle this case and will try to run the directory resulting in an error message like this:
`./drrun -- vim`
`<Application /home/derek/.bin/vim (543) DynamoRIO usage error : Failed to read app ELF headers.  Check path and architecture.>`

This can be confusing because just typing `vim` without `./drrun` does work in this case.

**To Reproduce**
1. Have a directory named like an executable in one of the PATH variables
2. Run `./drrun -- [name of the executable/directory]`

Please also answer these questions:
 - What happens when you run without any client?
 Same
 - What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)?
 Same

**Expected behavior**
DynamoRIO should ignore directories and traverse through the other possible locations in the PATH variable.

**Versions**
 - What version of DynamoRIO are you using?
6e88738383e78c0be9c3dda373e43f311425b862
 - Does the latest build from https://github.com/DynamoRIO/dynamorio/releases solve the problem?
 No
- What operating system version are you running on? 
Manjaro Linux and Debian 11
- Is your application 32-bit or 64-bit?
64 bit

Additional context
This does also happen with non-executable files in `PATH`

### PR DESCRIPTION
**Pull request by derchr**
I changed the required access mode to `DRFRONT_EXEC` to ciruumvent trying to execute files that aren't executable.
A new check in `drfront_searchenv()` is introduced to determine if the path in option is in fact a directory and should not be executed.

In this implementiation we are in the akward situation of calling `stat()` twice (first time in `drfront_access()` and then in `drfront_searchenv()`). An alternative approach would be to add a new variant for `drfront_access_mode_t` called `DRFRONT_ISDIR`. Though `ISDIR` isn't really an access mode.

So what would the preferable method be?

```
Fixes a bug where DynamoRIO tries to execute a directory or a file that
is not marked as executable when it is present in a directory contained
in the PATH environment variable.

Fixes #5455
```

### CODE REVIEW

File: libutil/dr_frontend_unix.c [hunk 1]
```diff
@@ -166,15 +168,18 @@ drfront_searchenv(const char *fname, const char *env_var, OUT char *full_path,
...
+            status_check = drfront_access(realpath_buf, DRFRONT_EXEC, &access_ret);
             if (status_check != DRFRONT_SUCCESS) {
                 *ret = false;
                 return status_check;
             } else if (access_ret == true) {
-                *ret = true;
-                snprintf(full_path, full_path_size, "%s", realpath_buf);
-                full_path[full_path_size - 1] = '\0';
-                return DRFRONT_SUCCESS;
+                r = stat(realpath_buf, &st);
```
Comment (derekbruening) [inline libutil/dr_frontend_unix.c:176]: > In this implementiation we are in the akward situation of calling stat() twice (first time in drfront_access() and then in drfront_searchenv()). An alternative approach would be to add a new variant for drfront_access_mode_t called DRFRONT_ISDIR. Though ISDIR isn't really an access mode.
> 
> So what would the preferable method be?

Hmm, adding `DRFRONT_ISDIR = 0x08` or something could break existing code that wants to include directories: it would have to be negated `DRFRONT_NOTDIR = 0x08` so the unset behavior is the legacy behavior: and then it would be less useful b/c it couldn't be used to find a directory, only to exclude them...so maybe `drfront_access_ex` is better which looks at `DRFRONT_ISDIR` while `drfront_access` ignores it.  Hmm.  I could also live with the extra `stat`.  How about just a `XXX` comment here about possibly avoiding the extra `stat` by either the `DRFRONT_NOTDIR` or the  `DRFRONT_ISDIR` plus `drfront_access_ex`.

File: libutil/dr_frontend_unix.c [hunk 2]
```diff
@@ -166,15 +168,18 @@ drfront_searchenv(const char *fname, const char *env_var, OUT char *full_path,
...
+                if (r != -1 && !S_ISDIR(st.st_mode)) {
+                    *ret = true;
+                    snprintf(full_path, full_path_size, "%s", realpath_buf);
+                    full_path[full_path_size - 1] = '\0';
+                    return DRFRONT_SUCCESS;
+                }
```
Comment (derekbruening) [inline libutil/dr_frontend_unix.c:182]: Could we include a test in suite/tests/libutil/frontend_test.c?  It already creates a dir: could add that to PATH with setenv and then test whether it shows up in searchenv?

File: libutil/dr_frontend_unix.c (hunk 1 above)
Comment (derchr) [reply libutil/dr_frontend_unix.c:179]: I added a comment.

File: libutil/dr_frontend_unix.c (hunk 2 above)
Comment (derchr) [reply libutil/dr_frontend_unix.c:185]: I added a test case that tests this. It's a bit convoluted though because the current directory is handled differently.
I'm not sure if it could be written in a bit more elegant way.

**Comment by derekbruening** [comment]
> derchr force-pushed the i5455-path-ignore-directory branch from a9105cf to 27b7b35 Compare4 hours ago

Please don't force-push: it ruins the history.  Now the reviewer can't see just the new changes.  We put warnings against force-pushing on several docs pages (https://dynamorio.org/page_contributing.html, https://dynamorio.org/page_code_reviews.html).  The squash-and-merge will clean up all commits at the end.

File: libutil/dr_frontend_unix.c (hunk 2 above)
Comment (derekbruening) [reply libutil/dr_frontend_unix.c:185]: Looks reasonable.

File: suite/tests/libutil/frontend_test.c [hunk 3]
```diff
@@ -53,11 +58,22 @@ main()
         return -1;
     }
 
-    res = drfront_remove_dir("test_dir");
+    path = getenv("PATH");
+    strncpy(path_buf, "test_dir:", 9);
+    strncat(path_buf, path, 512 - 10);
```
Comment (derekbruening) [inline suite/tests/libutil/frontend_test.c:63]: nit: Better to use `sizeof(path_buf)` instead of repeating the 512 so they'll stay in sync; even better to use our BUFFER_SIZE_ELEMENTS macro, but that may not be available w/ the current headers here.

**Review by derekbruening — APPROVED** [review]

File: suite/tests/libutil/frontend_test.c (hunk 3 above)
Comment (derekbruening) [reply suite/tests/libutil/frontend_test.c]: Well I tried to tweak this and get the test to run on Windows but there are still Windows and Mac issues and I have no more time.

**Comment by derekbruening** [comment]
OK got it green and merged.

**Comment by derchr** [comment]
Thank you for merging and taking your time.
