### PR TITLE
i#3812: Preserve AVX state on sigreturn

### LINKED ISSUE #3812: ymmh values zeroed on signal return
The app's ymmh values are being zeroed out somewhere between handle_sigreturn and post-sigreturn dispatch.  In a proprietary app I am observing this with custom diagnostics:

```
signal interruption sigcontext:
	xmm1=0x3f7fe40e3f7fe40e3f7fe40e3f7fe40e3f7fe40e3f7fe40e3f7fe40e3f7fe40e
mcontext pre-delivery:
	zmm1=0x3f7fe40e3f7fe40e3f7fe40e3f7fe40e3f7fe40e3f7fe40e3f7fe40e3f7fe40e0000000000000000000000000000000000000000000000000000000000000000
about to sigreturn to this sigcontext:
	xmm1=0x3f7fe40e3f7fe40e3f7fe40e3f7fe40e3f7fe40e3f7fe40e3f7fe40e3f7fe40e
resuming 0x000000004b818f40 post-sigreturn:
	zmm1=0x3f7fe40e3f7fe40e3f7fe40e3f7fe40e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

It leads to a crash.

Augmenting api.state_detach to test ymmh (unfortunately I bailed on that when first writing it) we see the same problem on detach:

```
$ ctest -V -R detach_state
293: Test timeout computed to be: 1500
293: ERROR: detach changed ymmh0.hi from 0x1122334455667788 to 0x0
293: ERROR: detach changed ymmh0.lo from 0x11223344556677 to 0x0
293: ERROR: detach changed ymmh0.hi from 0x1122334455667788 to 0x0
293: ERROR: detach changed ymmh0.lo from 0x11223344556677 to 0x0
293: all done
1/1 Test #293: code_api|api.detach_state ........***Failed  Required regular expression not found.Regex=[^all done
```

### PR DESCRIPTION
**Pull request by derekbruening**
Fixes a bug where the trailing magic word was missing from the signal
frame, causing the kernel to zero out rather than restore AVX+ state.
We copy the whole extended state at once now, rather than piecemeal,
with checks for both magic words.

Fixes os_forge_exception() to properly set the fpstate magic words and
sizes.

Disables the 32-bit xsave in save_xmm(), which causes failures on
recent processors, in order to better test the changes here for
32-bit.  A complete fix is still needed there but that is i#3256.

Updates comments to clarify the confusing extended_size vs xstate_size
and magic word locations for 64-bit and 32-bit.

Augments the linux.sigcontext test to test that SIMD state is
preserved across sigreturn.

Augments the api.detach_state test to test that ymmh, zmm, and opmask
state is preserved across detach.

Issue: #3812, #3256
Fixes #3812

### CODE REVIEW

**Comment by hgreving2304** [comment]
The currently 32-bit disabled tests in linux.sigcontext, is it possible to enable them now?

**Comment by derekbruening** [comment]
> The currently 32-bit disabled tests in linux.sigcontext, is it possible to enable them now?

linux.sigcontext is already enabled in 32-bit mode today.  Did you mean something else?

File: suite/tests/api/detach_state.c [hunk 1]
```diff
@@ -408,7 +408,94 @@ START_FILE
...
+        lea      rsp, [rsp - NUM_SIMD_REGS*SIMD_REG_SIZE] @N@ \
+        vmovdqu  [rsp +  0*SIMD_REG_SIZE], ymm0 @N@ \
+        vmovdqu  [rsp +  1*SIMD_REG_SIZE], ymm1 @N@ \
+        vmovdqu  [rsp +  2*SIMD_REG_SIZE], ymm2 @N@ \
+        vmovdqu  [rsp +  3*SIMD_REG_SIZE], ymm3 @N@ \
+        vmovdqu  [rsp +  4*SIMD_REG_SIZE], ymm4 @N@ \
+        vmovdqu  [rsp +  5*SIMD_REG_SIZE], ymm5 @N@ \
+        vmovdqu  [rsp +  6*SIMD_REG_SIZE], ymm6 @N@ \
+        vmovdqu  [rsp +  7*SIMD_REG_SIZE], ymm7 @N@ \
+        vmovdqu  [rsp +  8*SIMD_REG_SIZE], ymm8 @N@ \
```
Comment (hgreving2304) [inline suite/tests/api/detach_state.c]: Same as above.

File: suite/tests/api/detach_state.c [hunk 2]
```diff
@@ -408,7 +408,94 @@ START_FILE
...
+                       NUM_OPMASK_REGS*OPMASK_REG_SIZE] @N@     \
+        vmovups  [rsp +  0*SIMD_REG_SIZE], zmm0 @N@ \
+        vmovups  [rsp +  1*SIMD_REG_SIZE], zmm1 @N@ \
+        vmovups  [rsp +  2*SIMD_REG_SIZE], zmm2 @N@ \
+        vmovups  [rsp +  3*SIMD_REG_SIZE], zmm3 @N@ \
+        vmovups  [rsp +  4*SIMD_REG_SIZE], zmm4 @N@ \
+        vmovups  [rsp +  5*SIMD_REG_SIZE], zmm5 @N@ \
+        vmovups  [rsp +  6*SIMD_REG_SIZE], zmm6 @N@ \
+        vmovups  [rsp +  7*SIMD_REG_SIZE], zmm7 @N@ \
+        vmovups  [rsp +  8*SIMD_REG_SIZE], zmm8 @N@ \
```
Comment (hgreving2304) [inline suite/tests/api/detach_state.c]: ifdef X64 missing?

File: suite/tests/api/detach_state.c [hunk 3]
```diff
@@ -408,7 +408,94 @@ START_FILE
...
+        lea      rsp, [rsp - NUM_SIMD_REGS*SIMD_REG_SIZE] @N@ \
+        movups   [rsp +  0*SIMD_REG_SIZE], xmm0 @N@ \
+        movups   [rsp +  1*SIMD_REG_SIZE], xmm1 @N@ \
+        movups   [rsp +  2*SIMD_REG_SIZE], xmm2 @N@ \
+        movups   [rsp +  3*SIMD_REG_SIZE], xmm3 @N@ \
+        movups   [rsp +  4*SIMD_REG_SIZE], xmm4 @N@ \
+        movups   [rsp +  5*SIMD_REG_SIZE], xmm5 @N@ \
+        movups   [rsp +  6*SIMD_REG_SIZE], xmm6 @N@ \
+        movups   [rsp +  7*SIMD_REG_SIZE], xmm7 @N@ \
+        movups   [rsp +  8*SIMD_REG_SIZE], xmm8 @N@ \
```
Comment (hgreving2304) [inline suite/tests/api/detach_state.c]: Ditto

File: suite/tests/api/detach_state.c [hunk 4]
```diff
@@ -462,22 +583,106 @@ DECL_EXTERN(safe_stack)
...
+#    define Z7 ZMMH0_3_BASE()
+        SET_ZMM_IMMED(0, Z0, Z1, Z2, Z3, Z4, Z5, Z6, Z7)
+        SET_ZMM_IMMED(1, Z0, Z1, Z2, Z3, Z4, Z5, Z6, Z7)
+        SET_ZMM_IMMED(2, Z0, Z1, Z2, Z3, Z4, Z5, Z6, Z7)
+        SET_ZMM_IMMED(3, Z0, Z1, Z2, Z3, Z4, Z5, Z6, Z7)
+        SET_ZMM_IMMED(4, Z0, Z1, Z2, Z3, Z4, Z5, Z6, Z7)
+        SET_ZMM_IMMED(5, Z0, Z1, Z2, Z3, Z4, Z5, Z6, Z7)
+        SET_ZMM_IMMED(6, Z0, Z1, Z2, Z3, Z4, Z5, Z6, Z7)
+        SET_ZMM_IMMED(7, Z0, Z1, Z2, Z3, Z4, Z5, Z6, Z7)
+        SET_ZMM_IMMED(8, Z0, Z1, Z2, Z3, Z4, Z5, Z6, Z7)
```
Comment (hgreving2304) [inline suite/tests/api/detach_state.c]: Ditto. (offline: apparently the test is not enabled for 32-bit, maybe comment instead).

File: core/unix/signal.c [hunk 5]
```diff
@@ -6414,6 +6411,20 @@ os_forge_exception(app_pc target_pc, dr_exception_type_t type)
 #if defined(LINUX) && defined(X86)
     /* We use a TLS buffer to avoid too much stack space here. */
     sc->fpstate = (kernel_fpstate_t *)get_xstate_buffer(dcontext);
+    sc->fpstate->sw_reserved.extended_size = signal_frame_extra_size(false);
+    if (YMM_ENABLED()) {
+        sc->fpstate->sw_reserved.magic1 = FP_XSTATE_MAGIC1;
```
Comment (hgreving2304) [inline core/unix/signal.c]: Not sure. Apparently this causes a failure of test linux.bad-signal-stack, where the app's altstack is read-only. The test wants a SIGSEGV delivered. Does this somehow cause us to write into this memory before and we crash? But didn't we do that before already?

**Comment by hgreving2304** [comment]
> > The currently 32-bit disabled tests in linux.sigcontext, is it possible to enable them now?
> 
> linux.sigcontext is already enabled in 32-bit mode today. Did you mean something else?

For the AVX512F parts of the test, there are some ifdef X64 that excludes 32-bit, it doesn't print and test the state.

File: core/unix/signal.c [hunk 6]
```diff
@@ -3057,40 +3057,31 @@ fixup_rtframe_pointers(dcontext_t *dcontext, int sig, sigframe_rt_t *f_old,
...
-        if (YMM_ENABLED()) {
-            kernel_xstate_t *xstate_new = (kernel_xstate_t *)tgt;
-            kernel_xstate_t *xstate_old =
-                (kernel_xstate_t *)f_old->uc.uc_mcontext.fpstate;
-            memcpy(&xstate_new->xstate_hdr, &xstate_old->xstate_hdr,
-                   sizeof(xstate_new->xstate_hdr));
-            memcpy(&xstate_new->ymmh, &xstate_old->ymmh, sizeof(xstate_new->ymmh));
-        }
-#    ifdef X64
-        if (ZMM_ENABLED()) {
```
[the remark this answers is not in the document]
Comment (derekbruening) [reply core/unix/signal.c]: Yes.

**Comment by derekbruening** [comment]
Will add to commit message: "Tested the modified tests on a machine with AVX-512 enabled."

**Comment by derekbruening** [comment]
> For the AVX512F parts of the test, there are some ifdef X64 that excludes 32-bit, it doesn't print and test the state.

I think that has to wait for #3256.

File: core/unix/signal.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (derekbruening) [reply core/unix/signal.c]: See top-level note: will add to commit msg.

File: core/unix/signal.c [hunk 7]
```diff
@@ -6414,6 +6411,20 @@ os_forge_exception(app_pc target_pc, dr_exception_type_t type)
 #if defined(LINUX) && defined(X86)
     /* We use a TLS buffer to avoid too much stack space here. */
     sc->fpstate = (kernel_fpstate_t *)get_xstate_buffer(dcontext);
+    sc->fpstate->sw_reserved.extended_size = signal_frame_extra_size(false);
+    if (YMM_ENABLED()) {
```
[the remark this answers is not in the document]
Comment (derekbruening) [reply core/unix/signal.c]: Done.

File: core/unix/signal_linux_x86.c [hunk 8]
```diff
@@ -225,12 +225,24 @@ save_xmm(dcontext_t *dcontext, sigframe_rt_t *frame)
                      : "m"(xstate)
                      : "eax", "edx", "rcx", "memory");
 #else
+#    if DISABLED_ISSUE_3256
+        /* FIXME i#3256: DR's kernel_fpstate_t includes the fsave 0x70 bytes at the
```
[the remark this answers is not in the document]
Comment (derekbruening) [reply core/unix/signal_linux_x86.c]: Done.

File: core/unix/signal_linux_x86.c [hunk 9]
```diff
@@ -225,12 +225,24 @@ save_xmm(dcontext_t *dcontext, sigframe_rt_t *frame)
...
+         * top.  We need to skip them to reach the xsave area at the _fxsr_env field.
+         * However, that requires aligning that instead of the kernel_fpstate_t start
+         * itself in sigpending_t and the frame we make on the app stack.  An
+         * alternative here is to copy into a temp buffer but that seems wasteful.
+         * For now we skip the xsave, which seems safer than clobbering the wrong
```
[the remark this answers is not in the document]
Comment (derekbruening) [reply core/unix/signal_linux_x86.c]: Too much extra work for this same PR.

File: suite/tests/CMakeLists.txt [hunk 10]
```diff
@@ -2613,6 +2620,8 @@ endif ()
       # XXX i#1312: we do not yet support AVX-512 Windows context switching.
       tobuild_ci(client.avx512ctx client-interface/avx512ctx.c "" "" "")
       set_target_properties(client.avx512ctx PROPERTIES COMPILE_FLAGS "${CFLAGS_AVX512}")
+      append_property_string(TARGET client.avx512ctx.dll COMPILE_FLAGS
```
[the remark this answers is not in the document]
Comment (derekbruening) [reply suite/tests/CMakeLists.txt]: This is only needed for including the shared header: was not needed before.

File: suite/tests/api/detach_state.c [hunk 11]
```diff
@@ -237,39 +239,55 @@ check_xmm_value(const char *name, ptr_uint_t value, ptr_uint_t expect)
...
-    check_gpr_value("xmm14.hi", *(xsp + 45), MAKE_HEX_C(XMM14_HIGH_BASE()));
-    check_gpr_value("xmm14.lo", *(xsp + 44), MAKE_HEX_C(XMM14_LOW_BASE()));
-    check_gpr_value("xmm15.hi", *(xsp + 47), MAKE_HEX_C(XMM15_HIGH_BASE()));
-    check_gpr_value("xmm15.lo", *(xsp + 46), MAKE_HEX_C(XMM15_LOW_BASE()));
+#        define NUM_GPRS 16
+#        define SIMD_SZ_IN_PTRS (SIMD_REG_SIZE / sizeof(ptr_uint_t))
+#        ifdef __AVX512F__
+    for (i = 0; i < NUM_SIMD_REGS; i++) {
+        check_simd_value("xmm", i, "lo", *(xsp + NUM_GPRS + i * SIMD_SZ_IN_PTRS + 0),
+                         MAKE_HEX_C(XMM0_LOW_BASE()) << i);
```
[the remark this answers is not in the document]
Comment (derekbruening) [reply suite/tests/api/detach_state.c]: It is not the value for all: it is the value for number 0.  The value for the others is the value for 0 shifted to the left.

File: suite/tests/api/detach_state.c (hunk 2 above)
Comment (derekbruening) [reply suite/tests/api/detach_state.c]: All of this code is inside ifdef X64 up above.  Some should be shared when 32-bit support is added, but for now that's not there.

File: suite/tests/api/detach_state.c (hunk 1 above)
Comment (derekbruening) [reply suite/tests/api/detach_state.c]: Same response: ifdef X64 is at line 374.

File: suite/tests/api/detach_state.c (hunk 3 above)
Comment (derekbruening) [reply suite/tests/api/detach_state.c]: Same response.

Comment (derekbruening) [reply suite/tests/api/detach_state.c]: (You can see all this code is using "rsp" too, so it's not just these extra registers that would fail for 32-bit.)

File: suite/tests/api/detach_state.c (hunk 4 above)
Comment (derekbruening) [reply suite/tests/api/detach_state.c]: This one is not inside ifdef X64.  Added.

File: core/unix/signal.c (hunk 5 above)
Comment (derekbruening) [reply core/unix/signal.c]: The bug fix is to memset the thing to 0 first (this is a heap-allocated synthetic xstate).  It seems to be having non-zero values in the reserved1 field of kernel_xsave_hdr_t that causes the crash: it seems to cause the kernel to change the %gs base.  Kind of strange, but good to not have uninitialized values in there.

Comment (derekbruening) [reply core/unix/signal.c]: (Will put a comment by the memset.)

**Comment by derekbruening** [comment]
PTAL

File: suite/tests/api/detach_state.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (hgreving2304) [reply suite/tests/api/detach_state.c]: Ok.

File: suite/tests/api/detach_state.c (hunk 1 above)
Comment (hgreving2304) [reply suite/tests/api/detach_state.c]: Ok.

**Comment by hgreving2304** [comment]
> > For the AVX512F parts of the test, there are some ifdef X64 that excludes 32-bit, it doesn't print and test the state.
> 
> I think that has to wait for #3256.

Ok.
