### PR TITLE
i#297: Fix client thread synch issues and api.static_sideline test

### LINKED ISSUE #297: sideline thread has no chance to clean up
_From [derek.br...@gmail.com](https://code.google.com/u/117968039472581148324/) on April 23, 2010 14:49:38_

In debug build DR synchs + terminates our sideline thread prior to calling
our exit event so we have no chance to clean up its memory.  DR then
asserts about leaks if the sideline thread had thread-local memory.  DR
either needs to call the client exit event even sooner, before the
synchall, or should add support for a sideline exit routine.

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=297_

### PR DESCRIPTION
**Pull request by derekbruening**
Gets the api.static_sideline test working again and removes its _FLAKY status:

+ Moves the test's wait to the post-attach event b/c client threads wait for dr_app_start.

+ Passes in the dcontext to thread exit in cleanup_and_terminate to work around the #3535 TLS ignoring so client threads can exit on their own: but for x86 only uses it for client threads, to preserve the #3535 detach race fix.

+ Augments the safe-spot condition for a client thread to be unsafe if dcontext->is_exiting is set, to avoid killing a thread that has incremented exiting_thread_count (is_exiting is set right before doing that) and is waiting on the thread_initexit_lock to exit. This causes the synchall loop to retry and drop the lock, letting the client threads exit reliably. This solves the static-DR issue of not being able to distinguish the client from DR.

The test is disabled for AArch64 due to #7670.

Tested:
```
$ ctest --repeat-until-fail 500 -R static_sideline
100% tests passed, 0 tests failed out of 1
```

Fixes #297

### CODE REVIEW

**Comment by derekbruening** [comment]
api.detach_state failed again on aarch64: #7576

File: core/synch.c [hunk 1]
```diff
@@ -1376,7 +1376,16 @@ synch_with_all_threads(thread_synch_state_t desired_synch_state,
...
             if (synch_array[i] != SYNCH_WITH_ALL_SYNCHED && threads[i]->id != my_id) {
-                if (!finished_non_client_threads &&
+                if ((!finished_non_client_threads
+#ifdef STATIC_LIBRARY
+                     /* Give client threads who may be in dynamo_thread_exit waiting
+                      * on thread_initexit_lock a chance to exit.  For static DR we
+                      * can't tell whether we suspended safely b/c is_in_client_lib()
+                      * is true for the whole app!
+                      */
+                     || (int)loop_count < num_threads
```
Comment (edeiana) [inline core/synch.c]: Did I understand this correctly: this is an heuristic that gives more "time" to client threads to exit through more iterations of the while-loop at line 1302, so that when we get the list of threads with `get_list_of_threads(&threads, &num_threads);` at line 1316 there is no client thread anymore, hence avoiding setting `all_synched = false;`?
If so, it would be helpful to highlight that this could still "fail" even if the chances are low.
But then, should we really remove the `_FLAKY` status from `api.static_sideline`?

Or is it always guaranteed to work? If so, why?

Comment (derekbruening) [reply core/synch.c]: For the static_sideline 1st test with app synch controlling some of the timing, the sideline threads very reliably line up at the lock, and 1 iteration each lets them continue.  But you are right it is theoretically possible that one won't be scheduled; not sure we can easily reproduce that but it is possible.

If we could better identify a safe spot that would help.  The proximate issue is the exiting thread count: dcontext->is_exiting is set before that and maybe it can be used to avoid killing an exiting thread.  Or: we document that we don't support clients that don't join with their threads at exit time and we provide a join method that kills the client thread explicitly, to avoid all these races.

Comment (edeiana) [reply core/synch.c]: > we document that we don't support clients that don't join with their threads at exit time and we provide a join method that kills the client thread explicitly, to avoid all these races.

I think this is the best option until we can identify a better safe spot.
Though we should still leave this heuristic in place, since it works reliably IMO; just in case there are clients out there that don't want to use our new join method that will explicitly kill the client thread.

Comment (derekbruening) [reply core/synch.c]: I filed #7673 on client join and added some XXX comments.

I also changed the "loop_count < num_threads" to instead make dcontext->is_exiting make a client thread "unsafe": which is a more robust method of avoiding the original problem.
