### PR TITLE
i#2494 ARM encoder: Fix bug in roll-back of reglists.

### LINKED ISSUE #2494: ARM encoder incorrectly handles VTBL/VTBX reglist in some cases
(This is split off from #2465.)

Example error message from log (`-checklevel 1`):
```
ERROR: from app:  ffb6 69a8  vtbl.8 %d22 %d23 %d24 -> %d6
vs from encoding: ffb6 6aa8  vtbl.8 %d22 %d23 %d24 %d24 -> %d6
```

It appears from this and other examples that the encoder gets confused when the second source operand (a single register) looks like a continuation of the reglist operand, which is the first source operand. In the case above, the encoder seems to eat d22-d24, then later realise that it needs d24 for the second source operand, but fails to remove d24 from the register list. A search for "greed" in arm/encode.c reveals what the strategy is supposed to be, but apparently it does not work in this case.

(Might other instructions be affected by the same bug?)

### PR DESCRIPTION
**Pull request by egrimley**
Roll-back of greedy reglists was permitted even when the reglist was
required to have min_num == max_num. This prevented the encoding of
an instruction such as "VTBL.8 d0, {d2-d3}, d4", because it was
tried with TYPE_L_VAx3 (list of length 3) before it was tried with
TYPE_L_VAx2 (list of length 2). The attempt to use TYPE_L_VAx3 would
incorrectly succeed because of the unrestricted roll-back.

The solution used here is to set a field reglist_min_num in the
decode_info_t and disallow roll-back beyond that minimum length.

Fixes #2494

Change-Id: Id1c22723f7862abc2cf24c0bbab4254b32232b33

### CODE REVIEW

**Comment by fhahn** [comment]
Would it be possible to add a simple test case for that, e.g. to dis-armA32?

**Comment by egrimley** [comment]
You can add the example from the log message to the disT32 test like this:
```
printf "\xb2\xff\x04\x09" >> suite/tests/api/dis-armT32-randtest.raw
echo "+0xcdb2   ffb2 0904  vtbl.8 %d2 %d3 %d4 -> %d0" >> suite/tests/api/dis-armT32.expect
```

However, that test does not detect the bug. Apparently it does not test the encoder, unlike dis-a64, which tests encoder, decoder and disassembler. That would be another thing for #1686.

File: core/arch/arm/encode.c [hunk 1]
```diff
@@ -1098,7 +1100,8 @@ encode_opnd_ok(decode_info_t *di, byte optype, opnd_size_t size_temp, instr_t *i
     /* Roll back greedy reglist if necessary */
     if (di->reglist_stop > 0 && optype_is_reg(optype) &&
         (!di->reglist_simd || !optype_is_gpr(optype)) &&
-        di->reglist_stop - 1 > di->reglist_start && di->reglist_stop == opnum) {
+        di->reglist_stop - di->reglist_start > di->reglist_min_num &&
```
Comment (derekbruening) [inline core/arch/arm/encode.c]: For no minimum, previously we required stop-1>start == stop-start>1, but now you're requiring stop-start>0.  We don't support an empty list in our encoder, so >1 seems right.  Maybe that means reglist_min_num (and the min_num param) should be 1 instead of 0 everywhere?

Comment (egrimley) [inline core/arch/arm/encode.c]: Yes, I noticed that discrepancy. But perhaps we should allow an empty register list in some cases. Here's what the disassembler says about an LDM with an empty register list:
```
	e8900000 	ldm	r0, {}	; <UNPREDICTABLE>
```
So the encoding is perhaps valid, in a sense. It's just very unclear what the instruction would do if we executed it.

Comment (derekbruening) [inline core/arch/arm/encode.c]: IIRC an empty register list violates an invariant relied on in the tables.  There's a comment about it: something about making some templates indistinguishable.

Comment (egrimley) [inline core/arch/arm/encode.c]: In that case it would be better to require stop - start > min && stop - start > 1.

Comment (derekbruening) [inline core/arch/arm/encode.c]: Either 1 here or passing 1 as the min in other places sounds fine to me.
