### PR TITLE
i#7315: Avoid ID_AA64MMFR2_EL1 under QEMU to avoid fatal SIGILL

### LINKED ISSUE #7315: CRASH aarch64 under QEMU at proc_init `mrs x0, ID_AA64MMFR2_EL1`
On Ubuntu22 (where we have to migrate: #7270), every aarch64 test run under QEMU hits a SIGILL from the final MRS instruction in proc_init: `mrs x0, ID_AA64MMFR2_EL1`.

This shows up as:
```
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
```

DR only intercepts SIGSEGV and SIGBUS during init time.  I'd like to intercept SIGILL and put these MRS instructions in a try-except: but it's tricky since we use SIGILL for nudges and suspending later on.  I may try to add an init-time-only try-except handling.

This is blocking us from moving to Ubuntu22 on Github Actions as mandated: #7270.

### PR DESCRIPTION
**Pull request by derekbruening**
Under QEMU, proc_init()'s MRS of ID_AA64MMFR2_EL1 causes a fatal SIGILL.
We avoid it when under QEMU.
(Note that this did not fail on Ubuntu20's QEMU, only on Ubuntu22, but we
avoid under any QEMU for now to unblock progress.)

We'd prefer to use TRY_EXCEPT_ALLOW_NO_DCONTEXT, but proc_init() is
called prior to init-time signal handling being set up: and we'd need
to add SIGILL to the ones caught at init time, which complicates later
uses of SIGILL for NUDGESIG_SIGNUM and suspend_signum (and on x86
XSTATE_QUERY_SIG): so we'd want SIGILL to only work for try-except at
init time. That is all a little too involved to implement right now so we're
putting in this disabling to unblock Ubuntu22 progress for #7270.
Long-term we probably want to put in the try-except, so we'll leave
#7315 open.

Tested on a local Ubuntu22 x86 machine with aarch64 cross-compilation
where every test failed before this fix and nearly all pass now (the
others fail for other reasons masked by this SIGILL before).

Issue: #7270, #7315

### CODE REVIEW

**Comment by derekbruening** [comment]
See my check of ubuntu22 on the GA CI VM which failed but with a handful of tests as opposed to all of them.  It matches my local results except it also has unit_tests failing; plus there's a #6260 ignore which I think we can remove:

https://github.com/DynamoRIO/dynamorio/actions/runs/13623080513/job/38075729778?pr=7316
```
aarch64-debug-internal: 89 tests passed, **** 5 tests failed, but ignoring 2 for i#6260: ****
	unit_tests 
	code_api|linux.signal_racesys 
	code_api|client.exception 
	(ignore: i#6260) 	code_api|client.drx_buf-test 
	(ignore: i#6260) 	code_api|client.drreg-test 
```

Reverting those temporary changes in order to commit this back on ubuntu20.

File: core/arch/aarch64/proc.c [hunk 1]
```diff
@@ -111,11 +111,25 @@ read_feature_regs(uint64 isa_features[])
...
+         * XXX i#7315: We'd prefer to use TRY_EXCEPT_ALLOW_NO_DCONTEXT here and
+         * remove this xarch_root check, but proc_init() is called prior to
+         * init-time signal handling being set up: and we'd need to add SIGILL
+         * to the ones caught at init time, which complicates later uses of
+         * SIGILL for NUDGESIG_SIGNUM and suspend_signum (and on x86
+         * XSTATE_QUERY_SIG): so we'd want SIGILL to only work for try-except
+         * at init time. This is all a little too involved to implement right now.
+         */
+        LOG(GLOBAL, LOG_TOP | LOG_ASYNCH, 1,
+            "Skipping MRS of ID_AA64ISAR2_EL1 under QEMU\n");
```
Comment (abhinav92003) [inline core/arch/aarch64/proc.c:125]: s/ID_AA64ISAR2_EL1/ID_AA64MMFR2_EL1/

(as noted by @pm215 on #7315).

File: core/arch/aarch64/proc.c [hunk 2]
```diff
@@ -111,11 +111,25 @@ read_feature_regs(uint64 isa_features[])
...
+    } else {
+        asm(".inst 0xd5380740\n" /* mrs x0, ID_AA64MMFR2_EL1 */
```
Comment (abhinav92003) [inline core/arch/aarch64/proc.c:127]: LGTM to proceed with this PR, but I'm curious about https://github.com/DynamoRIO/dynamorio/issues/7315#issuecomment-2694661674.

**Review by abhinav92003 — APPROVED** [review]

File: core/arch/aarch64/proc.c (hunk 1 above)
Comment (derekbruening) [reply core/arch/aarch64/proc.c:125]: Emacs auto-completed to the wrong one.  Fixed.
