### PR TITLE
i#3336: increase determinism of linux.syscall_pwait test.

### LINKED ISSUE #3336: linux.syscall_pwait failing on Android.
Test output was 

handlers for signals: 10, 12
signal blocked: 10
Testing epoll_pwait
signal received: 12
signal received: 10
Testing pselect
signal received: 12
Testing ppoll
signal received: 12
Testing epoll_pwait failure
Testing pselect failure
Testing ppoll failure

Seems that the SIGUSR1 signals were not received.

http://dynamorio.org/CDash/testDetails.php?test=584315&build=40410

### PR DESCRIPTION
**Pull request by hgreving2304**
Stabilize linux.syscall_pwait test that currently (sporadically-) fails on Android.

Checks for pending signals in emulation of p* versions of system calls and aborts call if necessary.

Changes linux.syscall_pwait to using pthreads and cond_vars.

Adds subtest to check signal in "pending" state as well as signals arriving during system call execution.

Fixes #3336, #3344

### CODE REVIEW

File: suite/tests/linux/syscall_pwait.c [hunk 1]
```diff
@@ -109,6 +117,7 @@ main(int argc, char *argv[])
     sigdelset(&test_set, SIGUSR1);
     sigdelset(&test_set, SIGUSR2);
 
+    *ready_to_listen = false;
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.c]: Are you assuming the fork syscall is a barrier on arm to ensure this write is visible to the child before it hits its while loop?  Could you point at documentation for that?  Maybe an explicit barrier should be added.  Or switch to sysv ipc or sthg.  Ditto below.

File: suite/tests/linux/syscall_pwait.c [hunk 2]
```diff
@@ -73,6 +75,9 @@ kick_off_child_signals()
     if (pid < 0) {
         perror("fork error");
     } else if (pid == 0) {
+        while (!*ready_to_listen) {
+            /* Empty. */
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: Done.

File: suite/tests/linux/syscall_pwait.c (hunk 1 above)
Comment (derekbruening) [reply suite/tests/linux/syscall_pwait.c]: Yes, weak memory ordering, and yes 1 followed by 0 can happen.  Why do you say "I don't think this applies here"?  Because of the fork system call being a barrier?  Please be explicit.  I think any un-synchronized thread-shared store in code run on ARM needs a comment explaining why it is safe.  We need to be careful here: we can't be fast and loose with un-synchronized memory stores in cross-platform code.  We need to get the x86 strong ordering model out of our heads.  It has burned us in the past.  See #2502 where we still have outstanding bugs.

Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: But by the time *ready_to_listen = false (causality), the second process doesn't exist yet. According to fork, at the time of creation, both memory spaces have the same contents at the moment of the fork (in the program). The kernel must insert barriers there for ARM. So the "false" value is guaranteed. I can insert extra barriers but I strongly think this isn't necessary. Agree?

Comment (derekbruening) [reply suite/tests/linux/syscall_pwait.c]: A race detection tool will call this a data race.  The stores setting ready_to_listen to true rely on the blocking syscall as a sort of barrier, but there are no comments about that.  There are subtle issues here and I don't think we should be using lock-free communication where it's not hard to use safer synchronized communication (i.e., this isn't a perf-critical part of core DR; it's not assembly code: it's high-level code in a test).  We have suite/tests/condvar.h for safe thread communication; sthg similar should be used for process communication.  Or, the test could be tweaked to use threads, pthread_kill, and the existing condvar.h condition variables.  Most other projects have style/content guidelines that strongly discourage any kind of hand-rolled synch such as lock-free communication where at all possible.  I know that existing DR code is not always a paragon of best high-level practices but we should try to improve for better ARM support and cleaner code.

Looking at the test more closely: it seems inherently racy for SIGUSR2.  SIGUSR2 is not blocked up front, so it will be delivered immediately.  So if the child sends it before the parent executes its blocking syscall, the signal will go through and the parent will subsequently block.  The SIGUSR1 will interrupt it, but the parent will loop and block again and hang forever because the child does not send any further signals.  Right?  And the changes here don't eliminate that race: they just narrow the window for SIGUSR2 coming through too early.  Right?  Unless I'm missing something, then, I don't see how this PR fixes the race?  I think the only fix is to block SIGUSR2 up front as well.  Or else change the child to keep sending signals in a loop until both syscalls are interrupted.

Looking at the #3336 test output: could you explain your theory as to what is happening?  How is SIGUSR1 not being delivered at all?  The problem I see, described above, is that the test might hang.

Looking at the code for handle_pre_extended_syscall_sigmasks(): it fails to call check_signals_pending() so it won't deliver a pending signal like handle_sigprocmask() will.  Is this why SIGUSR1 is not being delivered?  That call should be added.

File: suite/tests/linux/syscall_pwait.c [hunk 3]
```diff
@@ -117,6 +126,7 @@ main(int argc, char *argv[])
 
     print("Testing epoll_pwait\n");
 
+    *ready_to_listen = true;
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.c]: Along the same lines: the compiler could move this store potentially below the loop (see  https://github.com/DynamoRIO/dynamorio/blob/master/core/unix/signal.c#L5864 where the compiler was moving a store to the other side of a loop) and we'd have a hang with the child never sending its signals.

Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: That is definitely true (the second part 'inherently racy' I agree). The fork-part I think is ok, but I am going to put in a few barriers now (not to mix up compiler and HW barriers here, the kernel has macros for both). barrier(), wmb(). I wonder if _Android_ supports the same macros?

Comment (derekbruening) [reply suite/tests/linux/syscall_pwait.c]: First, if you could explain what is being fixed by this PR's "ready_to_listen"?  As I mentioned earlier I don't understand how it's fully fixing a race?  Second, if it is a full fix, I would again vote for higher-level abstractions (e.g., threads and condvar.h) instead of raw stores and barriers, for the reasons listed above: don't roll your own synch if there's an alternative.

Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: It just narrows the window of the race that can happen that the child is sending the signals before the parent is waiting for them. Maybe we (I) should just wait and re-write the test in a more deterministic way (barriers or as you mentioned w/ threads, if possible)

Comment (derekbruening) [reply suite/tests/linux/syscall_pwait.c]: If my analysis above is correct, it is not possible to avoid the race using any user-mode synchronization.  The only way is to block SIGUSR2.  However, I do not see how the Android test produced the output that it did: it seems it should hang if it fails.  Repeating an earlier question: do you have a theory for how it produced that output?

Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: >> do you have a theory for how it produced that output?
I don't, in particular, I can't reproduce on Android. Is it a sporadic failure or does it always fail on Android? If always, maybe bionic implements this such that even though epoll_pwait unblocks USR1, the signal handler isn't called?

Comment (derekbruening) [reply suite/tests/linux/syscall_pwait.c]: The missing check_signals_pending() I mentioned above is my theory as to why the signal handler wouldn't be called -- but I don't see why it would be android-specific and I think it would be called later anyway?  I would have to review the signal code: maybe not: maybe there is some non-determinism there.

> Is it a sporadic failure or does it always fail on Android?
The CDash history on the CDash site should answer that.

Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: Ok, so I just re-factored, without re-writing everything using threads, but adding proper barriers and  sending the (both blocked-) signals "one-by-one". This should be deterministic/safe. It actually exposes the missing check_signals_pending() perfectly because now, the test ensures the signals are fully "pending" and when running under DR, we never call the signal handler. Is there an open bug? We can use this as a test.

Comment (derekbruening) [reply suite/tests/linux/syscall_pwait.c]: Could consider #3336 as the bug b/c it's the only theory for the missing handler calls.

**Comment by hgreving2304** [comment]
PTAL.
The pending signals seem like they don't get delivered in AArch64. I'd be interested in if they do get delivered when not running under DR. I don't have an explanation why. I can/would add XXX comments to the test mentioning this.

File: suite/tests/linux/syscall_pwait.c [hunk 4]
```diff
@@ -64,24 +93,52 @@ signal_handler(int sig, siginfo_t *siginfo, void *context)
...
+kick_off_child_usr1()
 {
-    /* waste some time */
-    nanosleep(&sleeptime, NULL);
+    int pid = fork();
+    if (pid < 0) {
+        perror("fork error");
+    } else if (pid == 0) {
+        kill(getppid(), SIGUSR1);
+        *ready_to_listen = true;
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.c]: How do you know this store won't be moved above the kill()?  Again, it seems best to use higher-level abstractions: rolling your own synch makes it just too easy to make errors and makes it harder to read and understand the code with its extra complexity.

File: suite/tests/linux/syscall_pwait.c [hunk 5]
```diff
@@ -49,13 +49,42 @@
...
+#    define wmb() dsb(st)
+#else
+#    define dsb(opt) asm volatile("dsb " #    opt : : : "memory")
+/* Hardware (-and compiler) read/write memory barrier */
+#    define mb() dsb(sy)
+/* Hardware (-and compiler) read memory barrier */
+#    define rmb() dsb(sy)
+/* Hardware (-and compiler) write memory barrier */
+#    define wmb() dsb(sy)
+#endif
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.c]: I thought we had agreed to use higher-level abstractions and not roll our own synchronization?

File: suite/tests/linux/syscall_pwait.c [hunk 6]
```diff
@@ -93,38 +150,43 @@ main(int argc, char *argv[])
...
+                           MAP_SHARED | MAP_ANONYMOUS, -1, 0);
+
     sleeptime.tv_sec = 0;
     sleeptime.tv_nsec = 500 * 1000 * 1000;
 
     intercept_signal(SIGUSR1, (handler_3_t)signal_handler, true);
     intercept_signal(SIGUSR2, (handler_3_t)signal_handler, true);
     print("handlers for signals: %d, %d\n", SIGUSR1, SIGUSR2);
     sigemptyset(&new_set);
+    sigaddset(&new_set, SIGUSR2);
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.c]: I think this one line was the only thing that needed to change in the test: without any synch it would have worked, though it is nicer to be deterministic and ensure we test pending signals.

File: core/unix/signal_linux.c [hunk 7]
```diff
@@ -349,6 +349,13 @@ signalfd_thread_exit(dcontext_t *dcontext, thread_sig_info_t *info)
     TABLE_RWLOCK(sigfd_table, write, unlock);
 }
 
+bool
+is_repeat_handle_pre_extended_syscall_sigmasks(dcontext_t *dcontext)
+{
+    thread_sig_info_t *info = (thread_sig_info_t *)dcontext->signal_field;
+    return info->pre_syscall_app_sigprocmask_valid;
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/signal_linux.c]: We def couldn't handle a 'nested' epoll_pwait right now.

[the remark this answers is not in the document]
Comment (derekbruening) [reply core/unix/signal_linux.c]: But does the kernel handle that?  As mentioned I would not expect the kernel to bother with a stack of state: it would either stash the state it needs in the signal frame, or just say this isn't supported.

[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/signal_linux.c]: I don't know, focus'sing on simpler things right now, e.g. pthread version doesn't work w/ DR. I can add a XXX comment mentioning this. I suggest to say we do not support "if" kernel does.

File: core/unix/os.c [hunk 8]
```diff
@@ -7434,12 +7434,22 @@ pre_system_call(dcontext_t *dcontext)
...
+        kernel_sigset_t *sigmask;
+        /* If there had been pending signals upon first pre_system_call and this is a
+         * repeat, then we don't want to read the already modified app's sigmask, but
+         * read the saved original version instead.
+         */
+        if (!is_repeat_handle_pre_extended_syscall_sigmasks(dcontext)) {
+            sigmask = (kernel_sigset_t *)sys_param(dcontext, 3);
+            dcontext->sys_param3 = (reg_t)sigmask;
+        } else {
+            sigmask = (kernel_sigset_t *)dcontext->sys_param3;
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/os.c]: I addressed this by restoring the app's parameter.

File: core/unix/signal_linux.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/signal_linux.c]: Added XXX comment.

File: suite/tests/linux/syscall_pwait.c (hunk 6 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: Right, but now we found the pending signal issue which was a real bug.. so it's ok.

File: suite/tests/linux/syscall_pwait.c (hunk 1 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: Updated patch checks for pending signals. One complication was that we are changing the signal mask in pre_system_call. In sigreturn handler we re-set the app's emulated signal mask to the one in the signal frame. I have added code such that we are restoring the correct signal mask that we had previously saved in the "pre" part of a system call. This is already tested in syscall_pwait by the "sigmask mismatch" checks.

File: suite/tests/linux/syscall_pwait.c (hunk 3 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: i#3336 now considered "pending signal" bug. See above, patch updated.

File: suite/tests/linux/syscall_pwait.c (hunk 4 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: The compiler wouldn't move a store across a system call but we have talked about this already (adhere to Google standard). In any case, the test has been changed to using pthreads and cond vars.

File: suite/tests/linux/syscall_pwait.c (hunk 5 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: Ditto above.

**Comment by hgreving2304** [comment]
PTAL!

File: core/unix/signal.c [hunk 9]
```diff
@@ -6015,8 +6019,16 @@ handle_sigreturn(dcontext_t *dcontext, void *ucxt_param, int style)
...
          */
 
-        /* Discard blocked signals, re-set from prev mask stored in frame. */
-        set_blocked(dcontext, SIGMASK_FROM_UCXT(ucxt), true /*absolute*/);
+        if (info->pre_syscall_app_sigprocmask_valid) {
+            /* Discard blocked signals, re-set from original sigmask we have changed
+             * in pre_system_call of extended p* version of a system call.
+             */
+            set_blocked(dcontext, &info->pre_syscall_app_sigprocmask, true /*absolute*/);
+            info->pre_syscall_app_sigprocmask_valid = false;
```
Comment (derekbruening) [inline core/unix/signal.c]: I don't follow the high-level reason for doing this: the comment does not seem to contain enough context as to the assumptions and goal here.

The app does not have to invoke sigreturn out of a handler: it can and does use longjmp (hopefully siglongjmp).  DR should not rely on coming here to reset any state.

Xref my comments above in pre-syscall about restoring the mask: are you saying the mask restore needs to be delayed?  Please explain that in the pre-syscall comments.  If it's about getting the mask right for the handler, we may need to restore this p* syscall state right after setting up the handler's signal frame and to-restore mask inside the frame.

File: core/unix/signal_linux.c [hunk 10]
```diff
@@ -363,15 +363,24 @@ handle_pre_extended_syscall_sigmasks(dcontext_t *dcontext, kernel_sigset_t *sigm
      */
     if (sizemask != sizeof(kernel_sigset_t))
         return false;
+    /* XXX: we do not support any kind of nesting of p* variants of system calls, e.g.
```
Comment (derekbruening) [inline core/unix/signal_linux.c]: Issue number

File: suite/tests/linux/syscall_pwait.c [hunk 11]
```diff
@@ -49,40 +49,73 @@
...
 } data_t;
 
+typedef struct {
+    pthread_t main_thread;
+    bool delay;
+} args_t;
+
 static struct timespec sleeptime;
+static void *ready_to_listen;
+static args_t a;
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.c]: Use a more descriptive name: `args` or sthg.

File: suite/tests/linux/syscall_pwait.c [hunk 12]
```diff
@@ -93,119 +126,141 @@ main(int argc, char *argv[])
...
+                0, /* Set padding to 0 so we can use memcmp */
+            };
+            /* delay == false sends the signal before the system call is executed such
+             * that the signal is in pending state once we start the call.
+             * delay == true adds a delay before sending the signal such that the signal
+             * arrives while we are in the system call, but there is no check to verifiy
+             * whether it arrived "late enough".
+             */
+            bool delay = i == 0 ? false : true;
+            kick_off_child_signal(count, main_thread, !delay);
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.c]: It is confusing to negate the bool here when you completely control the construction of it: could we rename it to "immediate" or sthg and avoid the negation.

File: suite/tests/linux/syscall_pwait.c [hunk 13]
```diff
@@ -93,119 +126,141 @@ main(int argc, char *argv[])
...
-    sleeptime.tv_sec = 0;
-    sleeptime.tv_nsec = 500 * 1000 * 1000;
+    sleeptime.tv_sec = 1;
+    sleeptime.tv_nsec = 0;
 
     intercept_signal(SIGUSR1, (handler_3_t)signal_handler, true);
     intercept_signal(SIGUSR2, (handler_3_t)signal_handler, true);
     print("handlers for signals: %d, %d\n", SIGUSR1, SIGUSR2);
     sigemptyset(&new_set);
+    sigaddset(&new_set, SIGUSR2);
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.c]: A comment would help explain why it is important to block both.

File: suite/tests/linux/syscall_pwait.c (hunk 11 above)
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.c]: I do not see any reason for this to be a global variable?

File: suite/tests/linux/syscall_pwait.c [hunk 14]
```diff
@@ -49,40 +49,73 @@
...
         nanosleep(&sleeptime, NULL);
-        kill(getppid(), SIGUSR2);
+    }
+    pthread_kill(a.main_thread, SIGUSR1);
+    signal_cond_var(ready_to_listen);
+    return THREAD_FUNC_RETURN_ZERO;
+}
+
+THREAD_FUNC_RETURN_TYPE
+kick_off_child_usr2(void *arg)
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.c]: Since you're passing a multi-field parameter anyway, I would merge these into one function and pass in the signal.

File: suite/tests/linux/syscall_pwait.c [hunk 15]
```diff
@@ -93,119 +126,141 @@ main(int argc, char *argv[])
...
+            }
+            sigset_t post_syscall_set = {
+                0, /* Set padding to 0 so we can use memcmp */
+            };
+            pthread_sigmask(SIG_SETMASK, NULL, &post_syscall_set);
+            if (memcmp(&pre_syscall_set, &post_syscall_set, sizeof(pre_syscall_set)) !=
+                0) {
+                print("sigmask mismatch");
+                exit(1);
+            }
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.c]: It would be nice to share the code and avoid duplicating all of this: passing in a lambda (if this is renamed to .cpp; or a function pointer) for the p* syscall wrapper should make it relatively easy, right?

File: suite/tests/linux/syscall_pwait.c [hunk 16]
```diff
@@ -49,40 +49,73 @@
...
     sigset_t *sigmask;
     size_t sizemask;
 } data_t;
 
+typedef struct {
+    pthread_t main_thread;
+    bool delay;
+} args_t;
+
 static struct timespec sleeptime;
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.c]: Optional suggestion: Making a `sleep_briefly()` or sthg function would mean this could be a local var instead of global.

File: suite/tests/linux/syscall_pwait.c [hunk 17]
```diff
@@ -49,40 +49,73 @@
...
+        create_thread(kick_off_child_usr1, &a);
+    } else if (count == 2) {
+        create_thread(kick_off_child_usr2, &a);
+    }
+    if (!delay) {
+        /* This makes sure that the signal is pending
+         * in the kernel after return of this call.
+         */
+        wait_cond_var(ready_to_listen);
+    }
```
Comment (derekbruening) [inline suite/tests/linux/syscall_pwait.c]: Missing join_thread(), so there are resource leaks here (zombie threads).  If you want to *not* wait for the child for the delay case maybe you want to create a single, permanent thread up front, and have a shared args struct plus synch to tell it what to do?  Or else join after the syscall.

File: core/unix/os.c [hunk 18]
```diff
@@ -7434,21 +7434,34 @@ pre_system_call(dcontext_t *dcontext)
...
-        /* The original app's sigmask parameter is now NULL effectively making the syscall
-         * a non p* version, and the mask's semantics are emulated by DR instead.
-         */
+        kernel_sigset_t *sigmask;
+        sigmask = (kernel_sigset_t *)sys_param(dcontext, 3);
         dcontext->sys_param3 = (reg_t)sigmask;
+        /* The original app's sigmask parameter is now NULL effectively making the
+         * syscall a non p* version, and the mask's semantics are emulated by DR
+         * instead.
+         */
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/os.c]: Ok.

File: core/unix/os.c [hunk 19]
```diff
@@ -7434,21 +7434,34 @@ pre_system_call(dcontext_t *dcontext)
...
              */
             set_failure_return_val(dcontext, EINVAL);
             DODEBUG({ dcontext->expect_last_syscall_to_fail = true; });
             execute_syscall = false;
         }
+        if (sig_pending) {
+            /* If there had been pending signals, we revert re-writing the app's
+             * parameter, but we leave the modified signal mask.
+             */
+            set_syscall_param(dcontext, 3, dcontext->sys_param4);
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/os.c]: Thanks! The reason it passed is that there was a second bug in syscall_pwait.c kick_off_child_signal w/ delay == true, so the pending signal path was never taken for the mask parameter test.

File: core/unix/os.c [hunk 20]
```diff
@@ -7467,34 +7480,58 @@ pre_system_call(dcontext_t *dcontext)
...
+            execute_syscall = false;
         }
         break;
     }
     case SYS_epoll_pwait: {
-        kernel_sigset_t *sigmask = (kernel_sigset_t *)sys_param(dcontext, 4);
+        kernel_sigset_t *sigmask;
         size_t sizemask = (size_t)sys_param(dcontext, 5);
         /* Refer to comments in SYS_ppoll above. */
+        sigmask = (kernel_sigset_t *)sys_param(dcontext, 4);
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/os.c]: Ok.

File: core/unix/os.c [hunk 21]
```diff
@@ -7434,21 +7434,34 @@ pre_system_call(dcontext_t *dcontext)
...
             /* In old kernels with sizeof(kernel_sigset_t) != sizemask, we're forcing
              * failure. We're already violating app transparency in other places in DR.
              */
             set_failure_return_val(dcontext, EINVAL);
             DODEBUG({ dcontext->expect_last_syscall_to_fail = true; });
             execute_syscall = false;
         }
+        if (sig_pending) {
+            /* If there had been pending signals, we revert re-writing the app's
+             * parameter, but we leave the modified signal mask.
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/os.c]: If we do this, we won't receive the pending signals. We want the modified emulated app mask to be "active" when we receive pending signals.

File: core/unix/signal.c (hunk 9 above)
Comment (hgreving2304) [reply core/unix/signal.c]: > The app does not have to invoke sigreturn out of a handler
I agree to that. It turned out to be difficult to find the right place where to restore the mask we had modified pre_syscall. The dispatcher doesn't call post_syscall if pre_syscall returned EINTR error (which is convenient so the syscall doesn't get executed).
> re you saying the mask restore needs to be delayed
Yes, if we restore too early, we won't receive pending signals.
> If it's about getting the mask right for the handler, we may need to restore this p* syscall state right after setting up the handler's signal frame and to-restore mask inside the frame.
Where are you suggesting that should happen?

File: core/unix/os.c (hunk 21 above)
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/os.c]: Cont' discussion below.

File: suite/tests/linux/syscall_pwait.c (hunk 11 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: I can't make it local in kick_off_child_signal because the child thread may be reading the pointer after its lifetime is over.

File: suite/tests/linux/syscall_pwait.c (hunk 14 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: Done.

File: suite/tests/linux/syscall_pwait.c (hunk 17 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: Done.

File: core/unix/signal_linux.c (hunk 10 above)
Comment (hgreving2304) [reply core/unix/signal_linux.c]: i#3344.

File: suite/tests/linux/syscall_pwait.c (hunk 12 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: Done.

File: suite/tests/linux/syscall_pwait.c (hunk 13 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: Done.

File: suite/tests/linux/syscall_pwait.c (hunk 15 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: Since this came up several times already => done.

File: suite/tests/linux/syscall_pwait.c (hunk 16 above)
Comment (hgreving2304) [reply suite/tests/linux/syscall_pwait.c]: Ack

File: core/unix/signal.c (hunk 9 above)
Comment (hgreving2304) [reply core/unix/signal.c]: Done. Mask is not restored when setting up app's signal frame.

File: core/unix/signal.c [hunk 22]
```diff
@@ -6017,6 +6039,7 @@ handle_sigreturn(dcontext_t *dcontext, void *ucxt_param, int style)
 
         /* Discard blocked signals, re-set from prev mask stored in frame. */
         set_blocked(dcontext, SIGMASK_FROM_UCXT(ucxt), true /*absolute*/);
+
```
Comment (hgreving2304) [inline core/unix/signal.c]: I will remove this line change before merge.

Comment (hgreving2304) [reply core/unix/signal.c]: Done.

File: core/unix/signal.c [hunk 23]
```diff
@@ -6043,16 +6066,24 @@ handle_sigreturn(dcontext_t *dcontext, void *ucxt_param, int style)
...
         ASSERT(sig > 0 && sig <= MAX_SIGNUM && !IS_RT_FOR_APP(info, sig));
         sc = get_sigcontext_from_app_frame(info, sig, (void *)frame);
-        /* discard blocked signals, re-set from prev mask stored in frame */
-        prevset.sig[0] = frame->IF_X86_ELSE(sc.oldmask, uc.uc_mcontext.oldmask);
-        if (_NSIG_WORDS > 1) {
-            memcpy(&prevset.sig[1], &frame->IF_X86_ELSE(extramask, uc.sigset_ex),
-                   sizeof(prevset.sig[1]));
-        }
+        if (info->pre_syscall_app_sigprocmask_valid) {
+            /* Discard blocked signals, re-set from original sigmask we have changed
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/signal.c]: I had missed the non-rt path. Done.

File: core/unix/signal_linux.c [hunk 24]
```diff
@@ -363,15 +363,24 @@ handle_pre_extended_syscall_sigmasks(dcontext_t *dcontext, kernel_sigset_t *sigm
      */
     if (sizemask != sizeof(kernel_sigset_t))
         return false;
+    /* XXX i#3344: we do not support any kind of nesting of p* variants of system calls,
+     * e.g. by executing another one in a signal handler, should the kernel support this.
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/signal_linux.c]: I was unsure whether this will work. We copy the modified pre-syscall mask to the app's frame. App executes another p* syscall. Frame has previous mask, process starts over again. So I think you're right and this should work (if even the kernel supports it natively). Removing comment, I will close i#3344 once merged.

[the remark this answers is not in the document]
Comment (derekbruening) [reply core/unix/signal_linux.c]: > I will close i#3344 once merged

Just put "Fixes #3344" here.  At least put "Issue: #3344".

File: suite/tests/CMakeLists.txt [hunk 25]
```diff
@@ -447,7 +447,7 @@ function (set_cflags source)
   endif ()
   if ("${source}" MATCHES ".cpp$")
     # Our C files need -std=gnu99, but that's an invalid flag for C++.
-    string(REGEX REPLACE "-std=gnu99" "" cflags "${cflags}")
+    string(REGEX REPLACE "-std=gnu99" "-std=c++11" cflags "${cflags}")
```
[the remark this answers is not in the document]
Comment (hgreving2304) [reply suite/tests/CMakeLists.txt]: Comment added

File: core/unix/signal_linux.c (hunk 24 above)
[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/signal_linux.c]: Ok

File: core/unix/signal.c [hunk 26]
```diff
@@ -3223,8 +3237,16 @@ copy_frame_to_stack(dcontext_t *dcontext, int sig, sigframe_rt_t *frame, byte *s
...
 #        endif
 #    endif /* X86 */
-        /* Store the prior mask, for restoring in sigreturn. */
-        convert_rt_mask_to_nonrt(f_new, &info->app_sigblocked);
+        if (info->pre_syscall_app_sigprocmask_valid) {
+            /* Store the prior mask that had been saved pre-syscall, for restoring in
+             * sigreturn.
+             */
+            convert_rt_mask_to_nonrt(f_new, &info->pre_syscall_app_sigprocmask);
+            info->pre_syscall_app_sigprocmask_valid = false;
```
[the remark this answers is not in the document]
Comment (derekbruening) [reply core/unix/signal.c]: ?  No, the local prevents having any conditional in the two rt and non-rt cases: they would be the same as TOT but using the local instead of &info->app_sigblocked.

[the remark this answers is not in the document]
Comment (hgreving2304) [reply core/unix/signal.c]: Done.

**Comment by hgreving2304** [comment]
s/Simply/Simplify/

**Comment by hgreving2304** [comment]
run armtests

File: core/unix/signal.c [hunk 27]
```diff
@@ -3158,6 +3162,14 @@ copy_frame_to_stack(dcontext_t *dcontext, int sig, sigframe_rt_t *frame, byte *s
         ASSERT_NOT_REACHED();
     }
 
+    kernel_sigset_t *pre_syscall_app_sigprocmask = NULL;
```
Comment (derekbruening) [inline core/unix/signal.c]: The variable name seems odd for the common case of just delivering a signal: there's no syscall involved there.  Something like "mask_to_restore, or continuation_mask, or something seems clearer.

File: core/unix/signal.c [hunk 28]
```diff
@@ -3179,8 +3191,11 @@ copy_frame_to_stack(dcontext_t *dcontext, int sig, sigframe_rt_t *frame, byte *s
             &f_new->uc.uc_stack, info->app_sigstack.ss_sp);
         f_new->uc.uc_stack = info->app_sigstack;
 #endif
-        /* Store the prior mask, for restoring in sigreturn. */
-        memcpy(&f_new->uc.uc_sigmask, &info->app_sigblocked,
+
+        /* Store the prior app's mask or the mask that had been saved pre-syscall, for
```
Comment (derekbruening) [inline core/unix/signal.c]: nit: Aren't they both prior masks?

File: core/unix/signal.c [hunk 29]
```diff
@@ -6043,7 +6060,6 @@ handle_sigreturn(dcontext_t *dcontext, void *ucxt_param, int style)
 #    endif
         ASSERT(sig > 0 && sig <= MAX_SIGNUM && !IS_RT_FOR_APP(info, sig));
         sc = get_sigcontext_from_app_frame(info, sig, (void *)frame);
-        /* discard blocked signals, re-set from prev mask stored in frame */
```
Comment (derekbruening) [inline core/unix/signal.c]: Comment was lost?

File: core/unix/signal_linux.c [hunk 30]
```diff
@@ -363,15 +363,22 @@ handle_pre_extended_syscall_sigmasks(dcontext_t *dcontext, kernel_sigset_t *sigm
      */
     if (sizemask != sizeof(kernel_sigset_t))
         return false;
+    /* Fixes #3344. */
```
Comment (derekbruening) [inline core/unix/signal_linux.c]: Is this trying to trigger the issue tracker?  It needs to be in the commit message.  When I said "here" in the prior review comment I meant in this PR/commit as opposed to manually closing the issue separately after merging.

File: core/unix/signal.c (hunk 27 above)
Comment (hgreving2304) [reply core/unix/signal.c]: Done.

File: core/unix/signal.c (hunk 28 above)
Comment (hgreving2304) [reply core/unix/signal.c]: Comment modified

File: core/unix/signal.c (hunk 29 above)
Comment (hgreving2304) [reply core/unix/signal.c]: Re-added.

File: core/unix/signal_linux.c (hunk 30 above)
Comment (hgreving2304) [reply core/unix/signal_linux.c]: Ok, I was surprised you wanted to add this here. Added to commit message instead.
