### PR TITLE
i#3567: Restore check for 8-bit register enum size.

### LINKED ISSUE #3567: reg_id_t width check broken by OPSZ_NA=0
I noticed that 053f6b6ad69dce472b47b4cade62d192cb4cbb1c PR #3497 broke this check:
```
     * The reg_id_t type is now wider, but for x86 we ensure our values
     * all fit via an assert in d_r_arch_init().
```
That PR set OPSZ_NA to 0, which broke the check, which I believe is this:
```C
    IF_X86(ASSERT(CHECK_TRUNCATE_TYPE_byte(OPSZ_LAST)));
```

### PR DESCRIPTION
**Pull request by hgreving2304**
Certain DR_REG_ enums are used as type opnd_size_t in x86. This patch restores an
assertion to ensure these enums fit into a byte. The affected DR_REG_ enums are
available in combination with a type and template_optype_is_reg is used to identify them.

Fixes #3567

### CODE REVIEW

File: core/arch/arch.c [hunk 1]
```diff
@@ -650,6 +650,11 @@ d_r_arch_init(void)
 {
```
Comment (derekbruening) [inline core/arch/arch.c]: > Certain DR_REG_ enums are used as type opnd_size_t in x86'.

Superfluous `'`

File: core/arch/arch.c [hunk 2]
```diff
@@ -650,6 +650,11 @@ d_r_arch_init(void)
...
     ASSERT(sizeof(opnd_t) == EXPECTED_SIZEOF_OPND);
     IF_X86(ASSERT(CHECK_TRUNCATE_TYPE_byte(OPSZ_LAST)));
+    /* This ensures that DR_REG_ enums that may be used as opnd_size_t fit its size.
+     * Only DR_REG_ enums covered by types listed in template_optype_is_reg can fall
+     * into this category.
+     */
+    IF_X86(ASSERT(CHECK_TRUNCATE_TYPE_byte(DR_REG_INVALID)));
```
Comment (derekbruening) [inline core/arch/arch.c]: I would say, add a new enum `DR_REG_MAX_AS_OPSZ = DR_REG_CR15` so we have a clear indicator in the enum.

File: core/arch/arch.c (hunk 1 above)
Comment (hgreving2304) [reply core/arch/arch.c]: Done.

File: core/arch/arch.c (hunk 2 above)
Comment (hgreving2304) [reply core/arch/arch.c]: Done.

File: core/arch/opnd.h [hunk 3]
```diff
@@ -300,6 +300,7 @@ enum {
     DR_REG_CR13,
     DR_REG_CR14,
     DR_REG_CR15,
+    DR_REG_MAX_AS_OPSZ = DR_REG_CR15,
```
Comment (derekbruening) [inline core/arch/opnd.h]: A comment may be necessary esp since you did not immediately parse the name so it may be unclear to other readers.

File: core/arch/opnd.h [hunk 4]
```diff
@@ -300,6 +300,7 @@ enum {
...
     DR_REG_INVALID, /**< Sentinel value indicating an invalid register. */
```
Comment (derekbruening) [inline core/arch/opnd.h]: (I suppose there's no simple way to ensure larger DR_REG values are not used in the decode tables.)

File: core/arch/opnd.h (hunk 3 above)
Comment (hgreving2304) [reply core/arch/opnd.h]: Done.

File: core/arch/opnd.h (hunk 4 above)
Comment (hgreving2304) [reply core/arch/opnd.h]: Indeed. The comment mentions it.
