### PR TITLE
i#3756: Fix copying signal magic1 value.

### LINKED ISSUE #3756: Fail to propagate magic1 field in signal frame (linux.sigcontext).
Looks to me like we're failing to propagate the magic1 field if the extended context is valid. The test for this is already been written (linux.sigcontext), but the AVX part is not enabled by default. When tweaking the test, it looks like we're good propagating the state, but we're not setting the magic1 field, which the test already checks. The same might apply to magic2, I'm not sure if that gets copied already or needs to be written separately.

To be clear, the issue is only exposed when editing the test and make sure it's compiled with and include AVX state.

### PR DESCRIPTION
**Pull request by hgreving2304**
Fixes copying the current state when delivering pending signals by preserving the original
magic1 value of the signal's fpstate.

Re-factor AVX detection in test linux.sigcontext and add support to actually test the AVX
state on supported machines.

Adds new <test>_runavx and <test>_runavx512 variables to the cmake suite similar to
_runcmp, in order to propagate the __AVX__ and __AVX512F__ defines to the template
parsers which are usually automatically defined by the compiler.

Updates a comment w.r.t. alignment of a stack variable we're declaring.

Fixes #3756

### CODE REVIEW

**Comment by hgreving2304** [comment]
Have a failure only reproducible on Travis, do not review until "PTAL"

**Comment by hgreving2304** [comment]
> Have a failure only reproducible on Travis, do not review until "PTAL"

The reason was a latent bug in the test asserting for the wrong size. Fixed.

**Comment by hgreving2304** [comment]
PTAL.

File: suite/tests/linux/sigcontext.c [hunk 1]
```diff
@@ -96,10 +96,9 @@ signal_handler(int sig, siginfo_t *siginfo, ucontext_t *ucxt)
              */
             kernel_xstate_t *xstate = (kernel_xstate_t *)ucxt->uc_mcontext.fpregs;
             if (xstate->fpstate.sw_reserved.magic1 == FP_XSTATE_MAGIC1) {
-                assert(xstate->fpstate.sw_reserved.xstate_size >= sizeof(*xstate));
-                /* we can't print b/c not all processors have avx */
+                assert(xstate->fpstate.sw_reserved.extended_size >= sizeof(*xstate));
```
Comment (derekbruening) [inline suite/tests/linux/sigcontext.c]: But extended_size includes the x87 state, doesn't it?  The original seems what we want.

File: suite/tests/CMakeLists.txt [hunk 2]
```diff
@@ -1031,6 +1031,11 @@ function(template2expect outexpect template runops key)
     # so currently this is unused.
     set(rundefs "${rundefs} -DCYGWIN")
   endif ()
+  if (DEFINED ${key}_runavx512)
+    set(rundefs "${rundefs} -D__AVX__ -D__AVX512F__")
+  elseif (DEFINED ${key}_runavx)
+    set(rundefs "${rundefs} -D__AVX__")
```
Comment (derekbruening) [inline suite/tests/CMakeLists.txt]: These are only for template files, but I don't see any template file uses here?  Is this for future use?

File: core/unix/signal_linux_x86.c [hunk 3]
```diff
@@ -179,7 +179,8 @@ convert_fxsave_to_fpstate(kernel_fpstate_t *fpstate, struct i387_fxsave_struct *
     fpstate->status = fxsave->swd;
     fpstate->magic = X86_FXSR_MAGIC;
 
-    memcpy(&fpstate->_fxsr_env[0], fxsave, sizeof(struct i387_fxsave_struct));
+    memcpy(&fpstate->_fxsr_env[0], fxsave,
+           sizeof(struct i387_fxsave_struct) - sizeof(fpstate->sw_reserved));
```
Comment (derekbruening) [inline core/unix/signal_linux_x86.c]: offsetof seems more robust: will handle appended fields.  Ditto below.

File: suite/tests/linux/sigcontext.c (hunk 1 above)
Comment (hgreving2304) [reply suite/tests/linux/sigcontext.c]: It's my understanding that the size is extended_size if magic1 == FP_XSTATE_MAGIC1. i.e. the legacy region that can be used for x87 + extensions. From the kernel sources:

```
[..]
If sw_reserved.magic1 == FP_XSTATE_MAGIC1 then there's a
 * sw_reserved.extended_size bytes large extended context area present.
[..]
```

This matched my observation, where with AVX (not even AVX-512 yet), xstate_size is < sizeof(xstate).

File: suite/tests/CMakeLists.txt (hunk 2 above)
Comment (hgreving2304) [reply suite/tests/CMakeLists.txt]: See suite/tests/linux/sigcontext.template as part of this PR. The AVX512F flag is not used yet.

File: core/unix/signal_linux_x86.c (hunk 3 above)
Comment (hgreving2304) [reply core/unix/signal_linux_x86.c]: I should be able to use xmm_space's offset.

Comment (hgreving2304) [reply core/unix/signal_linux_x86.c]: Ok. Changed to using offsetof(struct i387_fxsave_struct, xmm_space).
We can use the entire sizeof(i387_fsave_struct) for the fnsave case.

Comment (hgreving2304) [reply core/unix/signal_linux_x86.c]: It appears that newer kernel sources have clarified extended_size, and it seems to depict the extended xstate area's size as discussed offline:

```
* If sw_reserved.magic1 == FP_XSTATE_MAGIC1 then there's a
 * sw_reserved.extended_size bytes large extended context area present. (The
 * last 32-bit word of this extended area (at the
 * fpstate+extended_size-FP_XSTATE_MAGIC2_SIZE address) is set to
 * FP_XSTATE_MAGIC2 so that you can sanity check your size calculations.)
 *
 * This extended area typically grows with newer CPUs that have larger and
 * larger XSAVE areas.
```

I suggest updating our sigcontext.h file.

File: suite/tests/linux/sigcontext.c (hunk 1 above)
Comment (hgreving2304) [reply suite/tests/linux/sigcontext.c]: It appears that newer kernel sources have clarified extended_size, and it seems to depict the extended xstate area's size as discussed offline:

```
* If sw_reserved.magic1 == FP_XSTATE_MAGIC1 then there's a
 * sw_reserved.extended_size bytes large extended context area present. (The
 * last 32-bit word of this extended area (at the
 * fpstate+extended_size-FP_XSTATE_MAGIC2_SIZE address) is set to
 * FP_XSTATE_MAGIC2 so that you can sanity check your size calculations.)
 *
 * This extended area typically grows with newer CPUs that have larger and
 * larger XSAVE areas.
```

I suggest updating our sigcontext.h file.

File: core/unix/signal_linux_x86.c (hunk 3 above)
Comment (hgreving2304) [reply core/unix/signal_linux_x86.c]: Done.

File: suite/tests/linux/sigcontext.c (hunk 1 above)
Comment (hgreving2304) [reply suite/tests/linux/sigcontext.c]: Historically have we copied this file, and if so, from which version?

Comment (derekbruening) [reply suite/tests/linux/sigcontext.c]: OK.  Maybe augment the comment in our sigcontext.h to remind future-us?

File: suite/tests/CMakeLists.txt (hunk 2 above)
Comment (derekbruening) [reply suite/tests/CMakeLists.txt]: My bad, missed that.

File: suite/tests/linux/sigcontext.c (hunk 1 above)
Comment (hgreving2304) [reply suite/tests/linux/sigcontext.c]: Resolving, have not updated the header file yet. Separately?

Comment (hgreving2304) [reply suite/tests/linux/sigcontext.c]: > OK. Maybe augment the comment in our sigcontext.h to remind future-us?

Done (pulled in the kernel version of the comment).
