### PR TITLE
i#7376: Fix schedule_stats crash at verbose 4

### LINKED ISSUE #7376: CRASH schedule_stats tool at verbose 4
Running the scheduler_stats drmemtrace tool at verbose 4 crashes when it hits an idle sequence: it tries to de-reference the input stream, which is null for idle.

### PR DESCRIPTION
**Pull request by derekbruening**
Fixes a crash in the drmemtrace schedule_stats tool at verbose 4 where it tries to get the input stream on an idle sequence.

Tested on the new threadsig checked-in trace.  Unfortunately the unit tests mock the stream interfaces and so can't reproduce this, and the top-level at verbose 4 with a big enough trace to hit idle is too slow for a good regression test.

Fixes #7376

### CODE REVIEW

File: clients/drcachesim/tools/schedule_stats.cpp [hunk 1]
```diff
@@ -271,10 +271,16 @@ schedule_stats_t::parallel_shard_memref(void *shard_data, const memref_t &memref
...
              << std::setw(9)
-             << shard->stream->get_input_interface()->get_instruction_ordinal()
+             // The interface is null when we see idle records.
+             << (shard->stream->get_input_interface() == nullptr
+                     ? -1
+                     : shard->stream->get_input_interface()->get_record_ordinal())
+             << " refs, " << std::setw(9)
+             << (shard->stream->get_input_interface() == nullptr
+                     ? -1
+                     : shard->stream->get_input_interface()->get_instruction_ordinal())
```
Comment (edeiana) [inline clients/drcachesim/tools/schedule_stats.cpp:283]: nit: maybe we should save `shard->stream->get_input_interface()` to a local variable and use that in this case and the three other places above.
Unrelated, but `input_id` at L268 looks like it's used only in "verbose mode", maybe it should be scoped inside this if.

**Review by edeiana — APPROVED** [review]

File: clients/drcachesim/tools/schedule_stats.cpp (hunk 1 above)
Comment (derekbruening) [reply clients/drcachesim/tools/schedule_stats.cpp:283]: Done on the local var.  input_id is actually used further down below in this function.

Comment (edeiana) [reply clients/drcachesim/tools/schedule_stats.cpp]: Ah, you're right, I didn't "expand" down enough.
