### PR TITLE
i#7643: Simplify icache sync on AArch64: act on IC IVAU immediately.

### LINKED ISSUE #7643: AArch64 handling of self-modifying program is not thread-safe
The problem has been seen with a real application but can be demonstrated with the following program (DEBUG build with `-fake_ctr_dic` where required, e.g. Graviton3 and Graviton4):
```
#include <pthread.h>
#include <unistd.h>

void *work(void *arg)
{
    for (;;)
        __clear_cache((void *)64, (void *)65);
}

int main()
{
    pthread_t t1, t2;
    pthread_create(&t1, 0, work, 0);
    pthread_create(&t2, 0, work, 0);
    for (;;)
        sleep(10);
    return 0;
}
```

`Internal Error: DynamoRIO debug check failure: /.../dynamorio/core/fragment.c:6440 base != NULL || size != 0`

### PR DESCRIPTION
**Pull request by egrimley-arm**
Instead of accumulating IC IVAU addresses in a global struct and only acting on them when an ISB is seen, act on each IC IVAU immediately and in the same thread. This may be slower in some cases as there may be multiple calls to flush_fragments_synch_unlink_priv instead of a single call but it avoids an inter-thread issue.

Fixes #7643

### CODE REVIEW

File: core/arch/aarchxx/mangle.c
Comment (derekbruening) [inline core/arch/aarchxx/mangle.c:3021]: This can be a single store of x0.

Comment (derekbruening) [inline core/arch/aarchxx/mangle.c:3027]: This would put pc into x0 and then store x0.

Comment (derekbruening) [inline core/arch/aarchxx/mangle.c:3032]: This would be a single store of xt/x0.

Comment (derekbruening) [inline core/arch/aarchxx/mangle.c:3045]: Dest here would be x0.

Comment (derekbruening) [inline core/arch/aarchxx/mangle.c]: This can be a plain indirect branch.

Comment (derekbruening) [inline core/arch/aarchxx/mangle.c]: This should be removed, with a comment "Does not return."

Comment (derekbruening) [inline core/arch/aarchxx/mangle.c:3047]: Hmm, do we need to pass the TLS base to the asm routine? Is this to support dynamic choice of dr_reg_stolen: so we don't hardcode x28 into the asm routine?  Is this what other aarch64 asm routines do?  If it has to pass it in: I guess this routine does need to save 2 regs up front. But the changes below should still be done: it will be confusing to readers to see BLR with code after it when it doesn't return.

File: core/arch/aarch64/aarch64.asm [hunk 1]
```diff
@@ -627,197 +626,55 @@ GLOBAL_LABEL(tlsdesc_resolver:)
...
 /* This function is called from the fragment cache when the original code had
- * IC IVAU, Xt. Typically it just records which cache lines have been invalidated
- * and sets icache_op_struct.flag. However, if non-contiguous cache lines have
- * been invalidated we branch to fcache_return instead of returning.
- * When we enter here:
+ * IC IVAU, Xt. When we enter here:
  *
  * X0 contains the pointer to spill_state_t.
- * X30 contains the return address in the fragment cache.
+ * X30 contains the return address in the fragment cache (no longer required).
```
Comment (derekbruening) [inline core/arch/aarch64/aarch64.asm]: Please update the mangle code to use a plain indirect branch instead of branch and link and then remove this comment. Otherwise it will be confusing to look at the mangle code and wonder why it does a branch and link with code after it. Someone is going to think there is an error.

File: core/arch/aarchxx/mangle.c
Comment (derekbruening) [reply core/arch/aarchxx/mangle.c:3021]: Update: maybe we do still need 2 registers.

Comment (derekbruening) [reply core/arch/aarchxx/mangle.c:3027]: Update: maybe this would stay if we need 2 registers.

Comment (derekbruening) [reply core/arch/aarchxx/mangle.c:3032]: Update: maybe this would stay if we need 2 registers.

Comment (derekbruening) [reply core/arch/aarchxx/mangle.c:3045]: Update: maybe this would stay if we need 2 registers.

Comment (egrimley-arm) [reply core/arch/aarchxx/mangle.c:3047]: Yes, it's to support a dynamic choice of `dr_reg_stolen`. Changing the stolen register from its default value isn't CI-tested, but I've tested it occasionally by hand and it still works. (But see #7540 about the CLI, and it seems that some of the CI tests fail when the default is changed because of limitations of the test which are probably intentional; there's a `DR_ASSERT(stolen == DR_REG_X28)` in one case.)

File: core/arch/aarch64/aarch64.asm (hunk 1 above)
Comment (egrimley-arm) [reply core/arch/aarch64/aarch64.asm]: Done.

File: core/arch/aarchxx/mangle.c
Comment (egrimley-arm) [reply core/arch/aarchxx/mangle.c]: Done.

Comment (egrimley-arm) [reply core/arch/aarchxx/mangle.c]: Done.

Comment (egrimley-arm) [reply core/arch/aarchxx/mangle.c:3021]: Yes, it's the old problem that when you arrive somewhere with a register branch on RISC one of your registers unavoidably but uselessly contains the address of where you've just arrived.
